# This file is intended to be shared between the Archipelago Client/World and the Game sdkmod.
# I don't expect to be able to have one source of truth distributed to both, so just keep the two files in sync.

level_name_to_id = {
    # 2 through 30
    "Level " + str(i) : i for i in range(2, 31)
}

gear_kind_to_id = {
    # Gear [100 - 199]
    "Common Shield":                    100,
    "Uncommon Shield":                  101,
    "Rare Shield":                      102,
    "VeryRare Shield":                  103,
    # "E-Tech Shield":                    104,
    "Legendary Shield":                 105,
    "Seraph Shield":                    106,
    "Rainbow Shield":                   107,
    # "Pearlescent Shield":               108,
    "Unique Shield":                    109,

    "Common GrenadeMod":                110,
    "Uncommon GrenadeMod":              111,
    "Rare GrenadeMod":                  112,
    "VeryRare GrenadeMod":              113,
    # "E-Tech GrenadeMod":                114,
    "Legendary GrenadeMod":             115,
    "Seraph GrenadeMod":                116,
    "Rainbow GrenadeMod":               117,
    # "Pearlescent GrenadeMod":           118,
    "Unique GrenadeMod":                119,

    "Common ClassMod":                  120,
    "Uncommon ClassMod":                121,
    "Rare ClassMod":                    122,
    "VeryRare ClassMod":                123,
    # "E-Tech ClassMod":                  124,
    "Legendary ClassMod":               125,
    # "Seraph ClassMod":                  126,
    # "Rainbow ClassMod":                 127,
    # "Pearlescent ClassMod":             128,
    # "Unique ClassMod":                  129,

    "Common Relic":                     130,
    "Uncommon Relic":                   131,
    "Rare Relic":                       132,
    "VeryRare Relic":                   133,
    "E-Tech Relic":                     134,
    # "Legendary Relic":                  135,
    "Seraph Relic":                     136,
    "Rainbow Relic":                    137,
    # "Pearlescent Relic":                138,
    "Unique Relic":                     139,

    "Common Pistol":                    140,
    "Uncommon Pistol":                  141,
    "Rare Pistol":                      142,
    "VeryRare Pistol":                  143,
    "E-Tech Pistol":                    144,
    "Legendary Pistol":                 145,
    "Seraph Pistol":                    146,
    # "Rainbow Pistol":                   147,
    "Pearlescent Pistol":               148,
    "Unique Pistol":                    149,

    "Common Shotgun":                   150,
    "Uncommon Shotgun":                 151,
    "Rare Shotgun":                     152,
    "VeryRare Shotgun":                 153,
    "E-Tech Shotgun":                   154,
    "Legendary Shotgun":                155,
    "Seraph Shotgun":                   156,
    "Rainbow Shotgun":                  157,
    "Pearlescent Shotgun":              158,
    "Unique Shotgun":                   159,

    "Common SMG":                       160,
    "Uncommon SMG":                     161,
    "Rare SMG":                         162,
    "VeryRare SMG":                     163,
    "E-Tech SMG":                       164,
    "Legendary SMG":                    165,
    "Seraph SMG":                       166,
    "Rainbow SMG":                      167,
    "Pearlescent SMG":                  168,
    "Unique SMG":                       169,

    "Common SniperRifle":               170,
    "Uncommon SniperRifle":             171,
    "Rare SniperRifle":                 172,
    "VeryRare SniperRifle":             173,
    "E-Tech SniperRifle":               174,
    "Legendary SniperRifle":            175,
    "Seraph SniperRifle":               176,
    "Rainbow SniperRifle":              177,
    "Pearlescent SniperRifle":          178,
    "Unique SniperRifle":               179,

    "Common AssaultRifle":              180,
    "Uncommon AssaultRifle":            181,
    "Rare AssaultRifle":                182,
    "VeryRare AssaultRifle":            183,
    "E-Tech AssaultRifle":              184,
    "Legendary AssaultRifle":           185,
    "Seraph AssaultRifle":              186,
    "Rainbow AssaultRifle":             187,
    "Pearlescent AssaultRifle":         188,
    "Unique AssaultRifle":              189,

    "Common RocketLauncher":            190,
    "Uncommon RocketLauncher":          191,
    "Rare RocketLauncher":              192,
    "VeryRare RocketLauncher":          193,
    "E-Tech RocketLauncher":            194,
    "Legendary RocketLauncher":         195,
    "Seraph RocketLauncher":            196,
    "Rainbow RocketLauncher":           197,
    "Pearlescent RocketLauncher":       198,
    "Unique RocketLauncher":            199,
}

quest_name_to_id = {
    # Quest [200 - 486]
    "Sanctuary: The Road to Sanctuary":                                  200,
    "Sanctuary: Plan B":                                                 201,
    "Frostburn: Hunting the Firehawk":                                   202,
    "EndOfTheLine: A Train to Catch":                                       203,
    "Fridge: Rising Action":                                          204,
    "Highlands: Bright Lights, Flying City":                             205,
    "Badlands: Data Mining":                                            206,
    "Lynchwood: Breaking the Bank":                                      207,
    "Eridium Blight: Kill Yourself":                                          208,
    "Boneyard: This Just In":                                           209,
    "WindshearWaste: My First Gun":                                           210,
    "HolySpirits: Clan War: Wakey Wakey":                                  211,
    "SouthernShelf: Handsome Jack Here!":                                    212,
    "SouthernShelf: This Town Ain't Big Enough":                             213,
    "SouthernShelf: Shielded Favors":                                        214,
    "SouthernShelfBay: Symbiosis":                                              215,
    "Thousand Cuts: Defend Slab Tower":                                      216,
    "Highlands: Best Mother's Day Ever":                                 217,
    "Fridge: Note for Self-Person":                                   218,
    "Opportunity: The Bane":                                               219,
    "Dust: The Good, the Bad, and the Mordecai":                    220,
    "Sawtooth Cauldron: The Lost Treasure":                                      221,
    "Highlands: Arms Dealing":                                           222,
    "Lynchwood: 3:10 to Kaboom":                                         223,
    "Eridium Blight: Customer Service":                                       224,
    "ThreeHornsValley: Neither Rain nor Sleet nor Skags":                       225,
    "SouthernShelf: Blindsided":                                             226,
    "SouthernShelf: Cleaning up the Berg":                                   227,
    "SouthernShelf: Best Minion Ever":                                       228,
    "Ramparts: A Dam Fine Rescue":                                      229,
    "WildlifePreserve: Wildlife Preservation":                                  230,
    "Thousand Cuts: The Once and Future Slab":                               231,
    "Opportunity: The Man Who Would Be Jack":                              232,
    "Control Core Angel: Where Angels Fear to Tread":                             233,
    "Control Core Angel: Where Angels Fear to Tread (Part 2)":                    234,
    "Sawtooth Cauldron: Toil and Trouble":                                       235,
    "WarriorVault: The Talon of God":                                       236,
    "Southpaw: Assassinate the Assassins":                              237,
    "SouthernShelf: Bad Hair Day":                                           238,
    "Control Core Angel: Bearer of Bad News":                                     239,
    "Sanctuary: BFFs":                                                   240,
    "Frostburn Canyon: Cult Following: Eternal Flame":                          241,
    "Frostburn Canyon: Cult Following: Lighting the Match":                     242,
    "Frostburn Canyon: Cult Following: The Enkindling":                         243,
    "Sanctuary: Claptrap's Secret Stash":                                244,
    "Tundra Express: You Are Cordially Invited: Party Prep":                  245,
    "EndOfTheLine: The Ice Man Cometh":                                     246,
    "ThreeHornsDivide: In Memoriam":                                            247,
    "Tundra Express: Mighty Morphin'":                                        248,
    "Tundra Express: Mine, All Mine":                                         249,
    "Caustic Caverns: Minecart Mischief":                                      250,
    "Sanctuary: The Name Game":                                          251,
    "Tundra Express: No Hard Feelings":                                       252,
    "ThreeHornsValley: No Vacancy":                                             253,
    "Caustic Caverns: Perfectly Peaceful":                                     254,
    "Sanctuary: Rock, Paper, Genocide: Slag Weapons!":                   255,
    "Sanctuary: Rock, Paper, Genocide: Fire Weapons!":                   256,
    "Sanctuary: Do No Harm":                                             257,
    "Tundra Express: The Pretty Good Train Robbery":                          258,
    "Sanctuary: Won't Get Fooled Again":                                 259,
    "Eridium Blight: A Real Boy: Face Time":                                  260,
    "Eridium Blight: A Real Boy: Clothes Make the Man":                       261,
    "Sanctuary: Claptrap's Birthday Bash!":                              262,
    "Dust: Clan War: Zafords vs. Hodunks":                          263,
    "WildlifePreserve: Animal Rights":                                          264,
    "Opportunity: Hell Hath No Fury":                                      265,
    "Opportunity: Home Movies":                                            266,
    "Opportunity: Statuesque":                                             267,
    "Lynchwood: Showdown":                                               268,
    "HolySpirits: Clan War: End of the Rainbow":                           269,
    "Dust: Clan War: Starting the War":                             270,
    "Highlands: The Overlooked: Medicine Man":                           271,
    "Highlands: The Overlooked: Shields Up":                             272,
    "Highlands The Overlooked: This Is Only a Test":                    273,
    "Thousand Cuts: Poetic License":                                         274,
    "Dust: Clan War: First Place":                                  275,
    "CausticCaverns: Safe and Sound":                                         276,
    "Lynchwood: Animal Rescue: Shelter":                                 277,
    "Highlands: Slap-Happy":                                             278,
    "Highlands: Stalker of Stalkers":                                    279,
    "Terramorphous Peak: You. Will. Die. (Seriously.)":                           280,
    "Dust: Clan War: Trailer Trashing":                             281,
    "Opportunity: Written by the Victor":                                  282,
    "Sawtooth Cauldron: Capture the Flags":                                      283,
    "Sawtooth Cauldron: The Chosen One":                                         284,
    "Fridge: The Cold Shoulder":                                      285,
    "Eridium Blight: To Grandmother's House We Go":                           286,
    "Sawtooth Cauldron: The Great Escape":                                       287,
    "Lynchwood: Hungry Like the Skag":                                   288,
    "Thousand Cuts: Hyperion Contract #873":                                 289,
    "ThreeHornsValley: Medical Mystery":                                        290,
    "ThreeHornsValley: Medical Mystery: X-Com-municate":                        291,
    "Ramparts: Out of Body Experience":                                 292,
    "Ore Chasm: Hyperion Slaughter: Round 1":                            293,
    "Ore Chasm: Hyperion Slaughter: Round 2":                            294,
    "Ore Chasm: Hyperion Slaughter: Round 3":                            295,
    "Ore Chasm: Hyperion Slaughter: Round 4":                            296,
    "Ore Chasm: Hyperion Slaughter: Round 5":                            297,
    "Fridge: Swallowed Whole":                                        298,
    "Dust: Too Close For Missiles":                                 299,
    "Badlands: Uncle Teddy":                                            300,
    "Badlands: Get to Know Jack":                                       301,
    "Tundra Express: You Are Cordially Invited: Tea Party":                   302,
    "Tundra Express: You Are Cordially Invited: RSVP":                        303,
    "Sanctuary: Rock, Paper, Genocide: Corrosive Weapons!":              304,
    "Sanctuary: Rock, Paper, Genocide: Shock Weapons!":                  305,
    "Lynchwood: Animal Rescue: Medicine":                                306,
    "BloodshotStronghold: Splinter Group":                                         307,
    "Thousand Cuts: Shoot This Guy in the Face":                             308,
    "Fink's Slaughterhouse: Bandit Slaughter: Round 1":                              309,
    "Fink's Slaughterhouse: Bandit Slaughter: Round 2":                              310,
    "Fink's Slaughterhouse: Bandit Slaughter: Round 3":                              311,
    "Fink's Slaughterhouse: Bandit Slaughter: Round 4":                              312,
    "Fink's Slaughterhouse: Bandit Slaughter: Round 5":                              313,
    "CreatureSlaughter: Creature Slaughter: Round 1":                            314,
    "CreatureSlaughter: Creature Slaughter: Round 2":                            315,
    "CreatureSlaughter: Creature Slaughter: Round 3":                            316,
    "CreatureSlaughter: Creature Slaughter: Round 4":                            317,
    "CreatureSlaughter: Creature Slaughter: Round 5":                            318,
    "Sawtooth Cauldron: Monster Mash (Part 1)":                                  319,
    "Sawtooth Cauldron: Monster Mash (Part 2)":                                  320,
    "Boneyard: Monster Mash (Part 3)":                                  321,
    "Highlands: Torture Chairs":                                         322,
    "WildlifePreserve: Doctor's Orders":                                        323,
    "Dust: Rakkaholics Anonymous":                                  324,
    "Highlands: Hidden Journals":                                        325,
    "Dust: Positive Self Image":                                    326,
    "Frostburn Canyon: Cult Following: False Idols":                            327,
    "HolySpirits: Clan War: Reach the Dead Drop":                          328,
    "Eridium Blight: A Real Boy: Human":                                      329,
    "Lynchwood: Demon Hunter":                                           330,
    "Thousand Cuts: Rocko's Modern Strife":                                  331,
    "Lynchwood: Animal Rescue: Food":                                    332,
    "MercenaryDay: Get Frosty":                                             333,
    "GlutGulch: The Hunger Pangs":                                       334,
    "MercenaryDay: Special Delivery":                                       335,
    "GlutGulch: Grandma Flexington's Story":                             336,
    "GlutGulch: Grandma Flexington's Story: Raid Difficulty":            337,
    "FFSIntroSanctuary: The Dawn of New Pandora":                                338,
    "DahlAbandon: Winging It":                                             339,
    "DahlAbandon: Spore Chores":                                           340,
    "TheBurrows: A Hard Place":                                           341,
    "HeliosFallen: Shooting The Moon":                                      342,
    "Mt.Scarab: The Cost of Progress":                                   343,
    "FFSBossFight: Paradise Found":                                         344,
    "Mt.Scarab: Claptocurrency":                                         345,
    "HeliosFallen: BFFFs":                                                  346,
    "DahlAbandon: Hypocritical Oath":                                      347,
    "HeliosFallen: Cadeuceus":                                              348,
    "FFSBossFight: My Brittle Pony":                                        349,
    "DahlAbandon: The Oddest Couple":                                      350,
    "WrithingDeep: A Most Cacophonous Lure":                                351,
    "HeliosFallen: Sirentology":                                            352,
    "DahlAbandon: Space Cowboy":                                           353,
    "DahlAbandon: The Vaughnguard":                                        354,
    "HeliosFallen: The Hunt is Vaughn":                                     355,
    "FFSBossFight: Chief Executive Overlord":                               356,
    "Mt.Scarab: Echoes of the Past":                                     357,
    "Flamerock Refuge: A Role-Playing Game":                                    358,
    "MinesOfAvarice: Dwarven Allies":                                         359,
    "Agony: The Amulet":                                             360,
    "MinesOfAvarice: The Claptrap's Apprentice":                              361,
    "MinesOfAvarice: The Beard Makes The Man":                                362,
    "MinesOfAvarice: My Kingdom for a Wand":                                  363,
    "Immortal Woods: Critical Fail":                                          364,
    "Lair of Infinite Agony: My Dead Brother":                                        365,
    "Immortal Woods: Lost Souls":                                             366,
    "TheForest: Ell in Shining Armor":                                   367,
    "Flamerock Refuge: Fake Geek Guy":                                          368,
    "Flamerock Refuge: Feed Butt Stallion":                                     369,
    "Hatred's Shadow: Loot Ninja":                                             370,
    "Immortal Woods: MMORPGFPS":                                              371,
    "Flamerock Refuge: Pet Butt Stallion":                                      372,
    "Immortal Woods: Denial, Anger, Initiative":                              373,
    "Hatred's Shadow: A Game of Games":                                        374,
    "Lair of Infinite Agony: Post-Crumpocalyptic":                                    375,
    "Winged Storm: Raiders of the Last Boss":                               376,
    "Flamerock Refuge: Roll Insight":                                           377,
    "The Forest: Tree Hugger":                                            378,
    "Hatred's Shadow: Winter is a Bloody Business":                            379,
    "Murderlin's Temple: Magic Slaughter: Round 1":                               380,
    "Murderlin's Temple: Magic Slaughter: Round 2":                               381,
    "Murderlin's Temple: Magic Slaughter: Round 3":                               382,
    "Murderlin's Temple: Magic Slaughter: Round 4":                               383,
    "Murderlin's Temple: Magic Slaughter: Round 5":                               384,
    "Murderlin's Temple: Magic Slaughter: Badass Round":                          385,
    "Murderlin's Temple: The Magic of Childhood":                                 386,
    "Murderlin's Temple: Find Murderlin's Temple":                                387,
    "Unassuming Docks: The Sword in The Stoner":                                388,
    "Hallowed Hollow: The Bloody Harvest":                                     389,
    "Hallowed Hollow: Trick or Treat":                                         390,
    "Badass Crater: Highway To Hell":                                        391,
    "Torgue Arena: Tier 2 Battle: Appetite for Destruction":                392,
    "Torgue Arena: Tier 3 Battle: Appetite for Destruction":                393,
    "Torgue Arena: Tier 3 Rematch: Appetite for Destruction":               394,
    "Pyro Pete's Bar: Tier 2 Battle: Bar Room Blitz":                          395,
    "Pyro Pete's Bar: Tier 3 Battle: Bar Room Blitz":                          396,
    "Pyro Pete's Bar: Battle: Bar Room Blitz":                                 397,
    "Pyro Pete's Bar: Tier 3 Rematch: Bar Room Blitz":                         398,
    "Badass Crater: Tier 2 Battle: The Death Race":                          399,
    "Badass Crater: Tier 3 Battle: The Death Race":                          400,
    "Badass Crater: Battle: The Death Race":                                 401,
    "Badass Crater: Tier 3 Rematch: The Death Race":                         402,
    "Forge: Tier 2 Battle: Twelve O' Clock High":                    403,
    "Forge: Tier 3 Battle: Twelve O' Clock High":                    404,
    "Forge: Battle: Twelve O' Clock High":                           405,
    "Forge: Tier 3 Rematch: Twelve O' Clock High":                   406,
    "Beatdown: Mother-Lover":                                           407,
    "Beatdown: Number One Fan":                                         408,
    "Forge: Commercial Appeal":                                      409,
    "Forge: My Husband the Skag":                                    410,
    "Forge: Say That To My Face":                                    411,
    "Torgue Arena: Welcome To The Jungle":                                  412,
    "Torgue Arena: Battle: Appetite for Destruction":                       413,
    "Pyro Pete's Bar: Burn, Baby, Burn":                                       414,
    "Pyro Pete's Bar: Chop Suey":                                              415,
    "BadassBar: A Montage":                                              416,
    "Southern Raceway: Get Your Motor Running":                                 417,
    "Torgue Arena Ring: Eat Cookies and Crap Thunder":                           418,
    "Forge: Knockin' on Heaven's Door":                              419,
    "Forge: Breaking and Entering":                                  420,
    "Forge: Kickstart My Heart":                                     421,
    "Torgue Arena: Long Way To The Top":                                    422,
    "Southern Raceway: Gas Guzzlers":                                           423,
    "Southern Raceway: Matter Of Taste":                                        424,
    "Southern Raceway: Monster Hunter":                                         425,
    "Southern Raceway: Interview with a Vault Hunter":                          426,
    "BadassBar: Walking the Dog":                                        427,
    "Pyro Pete's Bar: Pete the Invincible":                                    428,
    "Beatdown: Totally Recall":                                         429,
    "Southern RacewayEverybody Wants to be Wanted":                           430,
    "DigistructInner: A History of Simulated Violence":                        431,
    "DigiPeakInner: More History of Simulated Violence":                     432,
    "DigiPeak: Dr. T and the Vault Hunters":                            433,
    "WamBamIsland: Fun, Sun, and Guns":                                     434,
    "RotgutDistillery: A Match Made on Pandora":                                435,
    "WamBamIsland: Victims of Vault Hunters":                               436,
    "RotgutDistillery: Learning to Love":                                       437,
    "Oasis: A Warm Welcome":                                         438,
    "Wurmwater: Message in a Bottle 2":                                  439,
    "HaytorsFolly: Message in a Bottle 3":                                  440,
    "Rustyards: Message in a Bottle 4":                                  441,
    "MagnysLighthouseMessage In A Bottle 5":                                  442,
    "Oasis: My Life For A Sandskiff":                                443,
    "Wurmwater: A Study in Scarlett":                                    444,
    "Hayters: Two Easy Pieces":                                        445,
    "Rustyards: The Hermit":                                             446,
    "Rustyards: Crazy About You":                                        447,
    "Washburne: Whoops":                                                 448,
    "Magnys Lighthouse: Let There Be Light":                                     449,
    "LeviathansLair: X Marks The Spot":                                       450,
    "Oasis: Burying the Past":                                       451,
    "Rustyards: Just Desserts for Desert Deserters":                     452,
    "LeviathansLair: Treasure of the Sands":                                  453,
    "Oasis: Fire Water":                                             454,
    "Washburne: Freedom of Speech":                                      455,
    "Washburne: I Know It When I See It":                                456,
    "Washburne: Faster Than the Speed of Love":                          457,
    "Wurmwater: Smells Like Victory":                                    458,
    "Oasis: Wingman":                                                459,
    "Oasis: Giving Jocko A Leg Up":                                  460,
    "Washburne: Don't Copy That Floppy":                                 461,
    "Oasis: Message in a Bottle 1":                                  462,
    "Washburne: Hyperius the Invincible":                                463,
    "Hayters: Master Gee the Invincible":                              464,
    "Wurmwater: Ye Scurvy Dogs":                                         465,
    "Wurmwater: Declaration Against Independents":                       466,
    "Hayters: Grendel":                                                467,
    "Oasis: Man's Best Friend":                                      468,
    "Rustyards: Catch-A-Ride, and Also Tetanus":                         469,
    "HuntersGrotto: Savage Lands":                                           470,
    "HuntersGrotto: Professor Nakayama, I Presume?":                         471,
    "HuntersGrotto: A-Hunting We Will Go":                                   472,
    "Terminus: The Fall of Nakayama":                                   473,
    "HuntersGrotto: An Acquired Taste":                                      474,
    "CandlerakksCrag: Big Feet":                                               475,
    "HuntersGroto: Still Just a Borok in a Cage":                           476,
    "ArdortonStation: The Rakk Dahlia Murder":                                 477,
    "HuntersGrotto: Egg on Your Face":                                       478,
    "ArdortonStation: Follow The Glow":                                        479,
    "ScyllasGrove: Nakayama-rama":                                          480,
    "CandlerakksCrag: Now You See It":                                         481,
    "ScyllasGrove: Ol' Pukey":                                              482,
    "HuntersGrotto: Palling Around":                                         483,
    "HuntersGrotto: I Like My Monsters Rare":                                484,
    "ScyllasGrove: Urine, You're Out":                                      485,
    "CandlerakksCrag: Voracidous the Invincible":                              486,
}

loc_name_to_id = {
    # Enemies [500 - 558]
    "Enemy WindshearWaste: Knuckle Dragger":           500,
    "Enemy SouthernShelfBay: Midgemong":               501,
    "Enemy SouthernShelf: Boom":                       502,
    "Enemy SouthernShelf: Bewm":                       503,
    "Enemy SouthernShelf: Captain Flynt":              504,
    "Enemy ThreeHornsDivide: Savage Lee":              505,
    "Enemy ThreeHornsDivide: Boll":                    506,
    "Enemy ThreeHornsValley: Doc Mercy":               507,
    "Enemy SouthpawSteam&Power: Assassin Oney":        508,
    "Enemy SouthpawSteam&Power: Assassin Wot":         509,
    "Enemy SouthpawSteam&Power: Assassin Reeth":       510,
    "Enemy SouthpawSteam&Power: Assassin Rouf":        511,
    "Enemy FrostburnCanyon: Scorch":                   512,
    "Enemy ThreeHornsValley: Incinerator Clayton":     513,
    "Enemy Dust: Gettle":                              514,
    "Enemy Dust: Mobley":                              515,
    "Enemy Dust: Black Queen":                         516,
    "Enemy ThreeHornsValley: Bad Maw":                 517,
    "Enemy BloodshotStronghold: Mad Mike":             518,
    "Enemy BloodshotRamparts: W4R-D3N":                519,
    "Enemy Frostburn Canyon: Spycho":                   520,
    "Enemy Dust: McNally":                             521,
    "Enemy Dust: Mick/Tector":                         522,
    # "Enemy Dust: Mick/Tector":                       522,
    "Enemy BloodshotStronghold: Dan":                  523,
    "Enemy BloodshotStronghold: Lee":                  524,
    "Enemy BloodshotStronghold: Mick":                 525,
    "Enemy BloodshotStronghold: Ralph":                526,
    "Enemy BloodshotStronghold: Flinter":              527,
    "Enemy TundraExpress: MadameVonBartlesby":         528,
    "Enemy TundraExpress: Prospector Zeke":            529,
    "Enemy EndOfTheLine: Wilhelm":                     530,
    "Enemy Fridge: LaneyWhite":                        531,
    "Enemy Fridge: Rakkman":                           532,
    "Enemy Fridge: SmashHead":                         533,
    "Enemy Fridge: Sinkhole":                          534,
    "Enemy Highlands: OldSlappy":                      535,
    "Enemy Highlands: GluttonousThresher":             536,
    "Enemy Highlands: Henry":                          537,
    "Enemy CausticCaverns: Blue":                      538,
    "Enemy CausticCaverns: BadassCreeper":             539,
    "Enemy WildlifePreserve: Tumbaa":                  540,
    "Enemy WildlifePreserve: Pimon":                   541,
    "Enemy WildlifePreserve: SonOfMothrakk":           542,
    # "Bloodwing":                                     543,
    "Enemy ThousandCuts: GOD-liath":                   544,
    "Enemy Lynchwood: DukinosMom":                     545,
    "Enemy Lynchwood: MadDog":                         546,
    "Enemy Lynchwood: SheriffNisha":                   547,
    "Enemy Lynchwood: DeputyWinger":                   548,
    "Enemy Opportunity: ForemanJasper":                549,
    "Enemy Opportunity: JackBodyDouble":               550,
    "Enemy Bunker: BNK-3R":                            551,
    "Enemy EridiumBlight: KingMong":                   552,
    "Enemy EridiumBlight: DonkeyMong":                 553,
    "Enemy SawtoothCauldron: Mortar":                  554,
    "Enemy AridNexusBoneyard: HunterHellquist":        555,
    "Enemy AridNexusBadlands: BoneHead":               556,
    "Enemy AridNexusBadlands: Saturn":                 557,
    "Enemy VaultOfTheWarrior: Warrior":                558,
    # Headhunter Enemies [1100 - 1135]
    "Enemy HallowedHollow: Sully the Blacksmith":                   1100,
    "Enemy HallowedHollow: Pumpkin Kingpin":                        1101,
    "Enemy HallowedHollow: Cryptkeeper Clark":                      1102,
    "Enemy GluttonyGulch: Chef Gouda Ramsay":                       1103,
    "Enemy GluttonyGulch: The Rat in the Hat":                      1104,
    "Enemy GluttonyGulch: Chef Brulee":                             1105,
    "Enemy GluttonyGulch: Chef Bork Bork":                          1106,
    "Enemy GluttonyGulch: Wattle Gobbler":                          1107,
    "Enemy GluttonyGulch: Glasspool, Tribute of Wurmwater":         1108,
    "Enemy GluttonyGulch: William, Tribute of Wurmwater":           1109,
    "Enemy GluttonyGulch: Axel, Tribute of Opportunity":            1110,
    "Enemy GluttonyGulch: Rose, Tribute of Opportunity":            1111,
    "Enemy GluttonyGulch: Strip, Tribute of Southern Shelf":        1112,
    "Enemy GluttonyGulch: Flay, Tribute of Southern Shelf":         1113,
    "Enemy GluttonyGulch: Bailly, Tribute of Sawtooth Cauldron":    1114,
    "Enemy GluttonyGulch: Moretus, Tribute of Sawtooth Cauldron":   1115,
    "Enemy GluttonyGulch: Cynder, Tribute of Frostburn":            1116,
    "Enemy GluttonyGulch: Fuse, Tribute of Frostburn":              1117,
    "Enemy GluttonyGulch: Annie, Tribute of Lunchwood":             1118,
    "Enemy GluttonyGulch: Garret, Tribute of Lynchwood":            1119,
    "Enemy GluttonyGulch: Fiona, Tribute of Sanctuary":             1120,
    "Enemy GluttonyGulch: Max, Tribute of Sanctuary":               1121,
    "Enemy MercenaryDay: Tinder Snowflake":                         1122,
    "Enemy RotgutDistillery: Colin Zaford":                         1123,
    "Enemy RotgutDistillery: Bridget Hodunk":                       1124,
    "Enemy RotgutDistillery: BLNG Loader":                          1125,
    "Enemy RotgutDistillery: Stella":                               1126,
    "Enemy RotgutDistillery: Ed":                                   1127,
    "Enemy RotgutDistillery: Innuendobot 5000":                     1128,
    "Enemy RotgutDistillery: Sigmand":                              1129,
    "Enemy RotgutDistillery: Ikaroa":                               1130,
    "Enemy RotgutDistillery: Moby":                                 1131,
    "Enemy RotgutDistillery: Fire Crak'n":                          1132,
    "Enemy RotgutDistillery: Rue, the Love Thresher":               1133,
    "Enemy WamBamIsland: Son of Crawmerax":                         1134,
    "Enemy WamBamIsland: Sparky Flynt":                             1135,

    "Enemy Hallowed Hollow: Sully the Blacksmith":                  1558,
    "Enemy Hallowed Hollow: Pumpkin Kingpin":                       1099,
    "Enemy Hallowed Hollow: Cryptkeeper Clark":                     1100,
    "Enemy GlutGulch: Chef Gouda Ramsay":                      1101,
    "Enemy GlutGulch: The Rat in the Hat":                     1102,
    "Enemy GlutGulch: Chef Brulee":                            1103,
    "Enemy GlutGulch: Chef Bork Bork":                         1104,
    "Enemy GlutGulch: Wattle Gobbler":                         1105,
    "Enemy GlutGulch: Glasspool, Tribute of Wurmwater":        1106,
    "Enemy GlutGulch: William, Tribute of Wurmwater":          1107,
    "Enemy GlutGulch: Axel, Tribute of Opportunity":           1108,
    "Enemy Gluttony Gulch: Rose, Tribute of Opportunity":           1109,
    "Enemy Gluttony Gulch: Strip, Tribute of Southern Shelf":       1110,
    "Enemy Gluttony Gulch: Flay, Tribute of Southern Shelf":        1111,
    "Enemy Gluttony Gulch: Bailly, Tribute of Sawtooth Cauldron":   1112,
    "Enemy Gluttony Gulch: Moretus, Tribute of Sawtooth Cauldron":  1113,
    "Enemy Gluttony Gulch: Cynder, Tribute of Frostburn":           1114,
    "Enemy Gluttony Gulch: Fuse, Tribute of Frostburn":             1115,
    "Enemy Gluttony Gulch: Annie, Tribute of Lunchwood":            1116,
    "Enemy Gluttony Gulch: Garret, Tribute of Lynchwood":           1117,
    "Enemy Gluttony Gulch: Fiona, Tribute of Sanctuary":            1118,
    "Enemy Gluttony Gulch: Max, Tribute of Sanctuary":              1119,
    "Enemy Marcus's Mercenary Shop: Tinder Snowflake":              1120,
    "Enemy Rotgut Distillery: Colin Zaford":                        1121,
    "Enemy Rotgut Distillery: Bridget Hodunk":                      1122,
    "Enemy Rotgut Distillery: BLNG Loader":                         1123,
    "Enemy Rotgut Distillery: Stella":                              1124,
    "Enemy Rotgut Distillery: Ed":                                  1125,
    "Enemy Rotgut Distillery: Innuendobot 5000":                    1126,
    "Enemy Rotgut Distillery: Sigmand":                             1127,
    "Enemy Rotgut Distillery: Ikaroa":                              1128,
    "Enemy Rotgut Distillery: Moby":                                1129,
    "Enemy Rotgut Distillery: Fire Crak'n":                         1130,
    "Enemy Rotgut Distillery: Rue, the Love Thresher":              1131,
    "Enemy Wam Bam Island: Son of Crawmerax":                       1132,
    "Enemy Wam Bam Island: Sparky Flynt":                           1133,
    "Enemy Oasis: No Beard": 1134,
    "Enemy Oasis: Tinkles": 1135,
    "Enemy Hayter's Folly: Grendel": 1136,
    "Enemy Hayter's Folly: Sandman": 1137,
    "Enemy Hayter's Folly: Big Sleep": 1138,
    "Enemy Oasis: Benny the Booster": 1139,
    "Enemy Hayter's Folly: Deckhand": 1140,
    "Enemy The Rustyards: Toothless Terry": 1141,
    "Enemy Washburne Refinery: P3RV-E": 1142,
    "Enemy Washburne Refinery: H3RL-E": 1143,
    "Enemy Magnys Lighthouse: DJ Tanner": 1144,
    "Enemy Magnys Lighthouse: Mr. Bubbles": 1145,
    "Enemy Magnys Lighthouse: Lt. Hoffman": 1146,
    "Enemy Magnys Lighthouse: Lt. White": 1147,
    "Enemy Leviathan's Lair: Roscoe": 1148,
    "Enemy Leviathan's Lair: The Leviathan": 1149,
    "Enemy Washburne Refinery: Hyperius": 1150,
    "Enemy Hayter's Folly: Master Gee": 1151,

    "Enemy PyroPete'sBar: Pyro Pete": 1152,
    "Enemy Beatdown: Sully the Stabber": 1153,
    "Enemy Beatdown: Hamhock": 1154,
    "Enemy Southern Raceway: Buff Gamer": 1156,
    "Enemy Southern Raceway: Game Critic": 1157,
    "Enemy Southern Raceway: Motor Mama": 1158,
    "Enemy The Forge: Anonymous Troll": 1159,
    "Enemy The Forge: Uriah": 1160,
    "Enemy The Forge: Piston's Blimp": 1161,
    "Enemy Torgue Arena: Badassasaurus": 1162,
    "Enemy Torgue Arena: Piston": 1163,
    "Enemy Pyro Pete's Bar: Pyro Pete the Invincible": 1164,

    "Enemy Hunter's Grotto: Arizona":       1165,
    "Enemy Scyllas Grove: Thermitage":      1166,
    "Enemy Scyllas Grove: Rakkanoth":       1167,
    "Enemy Ardorton Station: Dribbles:":    1168,
    "Enemy Ardorton Station: Woundspike":   1169,
    "Enemy Hunters Grotto: The Bulwark":    1170,
    "Enemy Candlerakks Crag: Rouge":        1171,
    "Enemy Candlerakks Crag: Bloodtail":    1172,
    "Enemy Terminus: Jackenstein":          1173,
    "Enemy Terminus: Dr. Nakayama":         1174,
    "Enemy Hunter's Grotto: Bulstoss":      1175,

    "Enemy HolySprits: Bagman":                 1176,

    "Enemy Unassuming Docks: Mr. Boney Pants Guy": 1177,
    "Enemy Unassuming Docks: Unmotivated Golem": 1178,
    "Enemy Flamerock Refuge: Sir Reginald von Bartlesby": 1179,
    "Enemy The Forest: Spiderpants": 1180,
    "Enemy The Forest: Arguk the Butcher": 1181,
    "Enemy The Forest: Warlord Glug": 1182,
    "Enemy Immortal Woods: -=n00bkiller=-": 1183,
    "Enemy Immortal Woods: 420_E-Sports_Masta": 1184,
    "Enemy Immortal Woods: [720NoScope]Headshotz": 1185,
    "Enemy Immortal Woods: xxDatVaultHuntrxx": 1186,
    "Enemy Immortal Woods: King Aliah": 1187,
    "Enemy Immortal Woods: King Crono": 1188,
    "Enemy Immortal Woods: King Seth": 1189,
    "Enemy Immortal Woods: King Nazar": 1190,
    "Enemy Mines of Avarice: Maxibillion": 1191,
    "Enemy Mines of Avarice: Magical Orc": 1192,
    "Enemy Mines of Avarice: Magical Spider": 1193,
    "Enemy Mines of Avarice: Greedtooth": 1194,
    "Enemy Hatred's Shadow: Canine": 1195,
    "Enemy Hatred's Shadow: Molehill": 1196,
    "Enemy Hatred's Shadow: Sir Boil": 1197,
    "Enemy Hatred's Shadow: Sir Mash": 1198,
    "Enemy Hatred's Shadow: Sir Stew": 1199,
    "Enemy Hatred's Shadow: Handsome Dragon": 1200,
    "Enemy Lair of Infinite Agony: Sorcerer's Daughter": 1201,
    "Enemy Dragon Keep: Handsome Sorcerer": 1202,
    "Enemy Winged Storm: Incinerator": 1203,
    "Enemy Winged Storm: Healianth": 1204,
    "Enemy Winged Storm: Brood": 1205,
    "Enemy Winged Storm: Boost": 1206,
    "Enemy Mines of Avarice: Warlord Turge": 1207,
    "Enemy Murderlin's Temple: Warlord Slog": 1208,

    "Enemy The Burrows: Ghost": 1209,
    "Enemy Dahl Abandon: The Dark Web": 1210,
    "Enemy Helios Fallen: Uranus Bot": 1211,
    "Enemy The Burrows: Lt. Angvar": 1212,
    "Enemy Dahl Abandon: Lt. Bolson": 1213,
    "Enemy Helios Fallen: Lt. Tetra": 1214,
    "Enemy Mt Scarab: Lt. Hoffman": 1215,
    "Enemy Mt Scarab: Cassius": 1216,
    "Enemy Paradise Sanctum: Hector": 1217,

    #rest of the raids
    "Enemy Hunters Grotto: Dexiduous the Invincible":        1218,   #"Dexiduous the Invincible"
    "Enemy CandlerakksCrag: Chief Ngwatu": 1219,#"Chief Ngwatu"
    "Enemy CandlerakksCrag: Voracidous the Invincible":        1220, #"Voracidous the Invincible"
    "Enemy Writhing Deep: Haderax the Invincible":    1221, #"Haderax the Invincible" maybe??

    #new enemies
    "Enemy Lair of Infinite Agony: Edgar/Simon": 1223,   #"Edgar"
    "Enemy Fridge: Bloody":    1225,
    "Enemy Fridge: Crabby":    1226,
    "Enemy Fridge: Creepy":    1227,
    "Enemy Fridge: Dirty":     1228,
    "Enemy Fridge: Greedy":    1229,
    "Enemy Fridge: Sleazy":    1230,
    "Enemy Fridge: Tipsy":     1231,
    "Enemy Fridge: Shorty":    1232,

    # Vault Symbols (601-751)
    "Symbol Sanctuary: Rooftop":                             601,
    "Symbol Sanctuary: Moxxi's Corner":                      602,
    "Symbol Sanctuary: Trash Corner":                        603,
    "Symbol Sanctuary: Tire Corner":                         604,
    "Symbol Sanctuary: Parkour Door":                        605,
    "Symbol EridiumBlight: Hellsfont Crate":                 606,
    "Symbol EridiumBlight: Stairs Door":                     607,
    "Symbol EridiumBlight: Refund Building":                 608,
    "Symbol Fink's: Column":                                 609,
    "Symbol Bunker: Backside":                               610,
    "Symbol WarriorVault: Elevator Bottom":                  611,
    "Symbol SouthernShelfBay: Blackburn Cove Corner":        612,
    "Symbol SouthernShelfBay: Ice Flows Shipwreck":          613,
    "Symbol Sawtooth: Refinery Container":                   614,
    "Symbol Sawtooth: Elevator":                             615,
    "Symbol CreatureSlaughter: Crate Ceiling":               616,
    "Symbol HerosPass: Strut":                               617,
    "Symbol HerosPass: Spawn":                               618,
    "Symbol Fridge: Secret Stash":                           619,
    "Symbol Fridge: Sheetmetal Roof":                        620,
    "Symbol ThreeHornsValley: Slums Wall":                   621,
    "Symbol ThreeHornsValley: Frostsprings Wall":            622,
    "Symbol ThreeHornsValley: Frostsprings Shack":           623,
    "Symbol AridNexusBoneyard: Pipe":                        624,
    "Symbol AridNexusBoneyard: Safety":                      625,
    "Symbol WindshearWaste: Claptrap's Closet":              626,
    "Symbol ThousandCuts: Buzzard Factory":                  627,
    "Symbol ThousandCuts: No Man's Land Shack":              628,
    "Symbol Lynchwood: Gunslinger Roof":                     629,
    "Symbol Lynchwood: Main Street":                         630,
    "Symbol Highlands: Highlands Tower":                     631,
    "Symbol FriendshipGulag: Gulag Container":               632,
    "Symbol Opportunity: Construction Site":                 633,
    "Symbol Opportunity: Office Bridge":                     634,
    "Symbol ThreeHornsDivide: Drydocks Corner":               635,
    "Symbol ThreeHornsDivide: Billboard":                     636,
    "Symbol ThreeHornsDivide: Windbreak Wall":                637,
    "Symbol Dust: Speedway Wall":                            638,
    "Symbol Dust: Buzzard Pad":                              639,
    "Symbol Dust: Moonshiner Lid":                           640,
    "Symbol CausticCaverns: Gravestone Feature":             641,
    "Symbol CausticCaverns: Bloody Ladder":                  642,
    "Symbol Bloodshot: Pizza Intercom":                      643,
    "Symbol Bloodshot: Switch Room":                         644,
    "Symbol BloodshotRamparts: Ramp":                        645,
    "Symbol Frostburn: Blisterpus Cave":                     646,
    "Symbol Frostburn: Ashmouth Pit":                        647,
    "Symbol TorgueArenaRing: Arena Wall":                    648,
    "Symbol TorgueArenaRing: Arena Ladder":                  649,
    "Symbol Beatdown: Underpass":                            650,
    "Symbol Beatdown: School Bus":                           651,
    "Symbol Forge: Smack Talker":                            652,
    "Symbol Forge: Lava":                                    653,
    "Symbol Forge: Housing":                                 654,
    "Symbol SouthernRaceway: Zer0 Poster":                   655,
    "Symbol SouthernRaceway: Maya Poster":                   656,
    "Symbol BadassCrater: Badass Highway":                   657,
    "Symbol BadassCrater: Beatdown Door":                    658,
    "Symbol BadassCrater: Billboard Lower":                  659,
    "Symbol BadassCrater: Billboard Upper":                  660,
    "Symbol HolySpirits: Bathroom":                          661,
    "Symbol HaytorsFolly: Hot Springs Crate":                662,
    "Symbol HaytorsFolly: Grendel Exit":                     663,
    "Symbol Oasis: Kronus":                                  664,
    "Symbol Oasis: Lair Exit":                               665,
    "Symbol Oasis: Lionel Docks":                            666,
    "Symbol Oasis: Coral Island":                            667,
    "Symbol WashburneRefinery: P3RV-E Lair":                 668,
    "Symbol WashburneRefinery: Forge Array":                 669,
    "Symbol Wurmwater: Rustyard Corridor":                   670,
    "Symbol Wurmwater: Scarlett's Ship":                     671,
    "Symbol Wurmwater: The Dish":                            672,
    "Symbol Rustyards: Maroonie's Clipper":                  673,
    "Symbol Rustyards: Rustyards Fence":                     674,
    "Symbol MagnysLighthouse: House":                        675,
    "Symbol MagnysLighthouse: Lighthouse":                   676,
    "Symbol LeviathansLair: Lair":                           677,
    "Symbol WildlifePreserve: Dockyard Roof":                678,
    "Symbol WildlifePreserve: Broken Boulevard":             679,
    "Symbol OreChasm: Elevator":                             680,
    "Symbol CandlerakksCragg: Elite Crossing House":         681,
    "Symbol CandlerakksCragg: Near Voracidous":              682,
    "Symbol CandlerakksCragg: Rouge's Lair":                 683,
    "Symbol Terminus: Terminus":                             684,
    "Symbol ArdortonStation: Woundspike's Lair":             685,
    "Symbol ArdortonStation: Psycho Surgery":                686,
    "Symbol ArdortonStation: Ardo Farm":                     687,
    "Symbol ArdortonStation: Dribble's Lair":                688,
    "Symbol ScyllasGrove: Low Gut Rut Wall":                 689,
    "Symbol ScyllasGrove: Urine Wall":                       690,
    "Symbol ScyllasGrove: Upper Village":                    691,
    "Symbol ScyllasGrove: Lower Village":                    692,
    "Symbol SanctuaryHole: Staircase Wall":                  693,
    "Symbol SouthernShelf: Flynt's Ship":                    694,
    "Symbol SouthernShelf: Safehouse":                       695,
    "Symbol Southpaw: Parkour":                              696,
    "Symbol Southpaw: Engine":                               697,
    "Symbol Southpaw: Ladder":                               698,
    "Symbol TerramorphousPeak: Dropdown":                    699,
    "Symbol TerramorphousPeak: Elevator":                    700,
    "Symbol EndOfTheLine: Wilhelm Wall":                     701,
    "Symbol TundraExpress: Fork Shack":                      702,
    "Symbol TundraExpress: Facility Roof":                   703,
    "Symbol Backburner: Zed's":                              704,
    "Symbol Backburner: Entrance":                           705,
    "Symbol HatredsShadow: Sir Boil":                        706,
    "Symbol HatredsShadow: Nefarious Elevator":              707,
    "Symbol HatredsShadow: Sir Mash":                        708,
    "Symbol DragonKeep: Sacrifice Staircase":                709,
    "Symbol Forest: Blood Tree Camp":                        710,
    "Symbol Forest: Glenn's Cottage":                        711,
    "Symbol ImmortalWoods: Fields of the Fallen":            712,
    "Symbol ImmortalWoods: Sacred Ruins Upper":              713,
    "Symbol ImmortalWoods: Sacred Ruins Lower":              714,
    "Symbol UnassumingDocks: Temple Shoreline":              715,
    "Symbol UnassumingDocks: Forlorn Ruins":                 716,
    "Symbol UnassumingDocks: Hamlet Building":               717,
    "Symbol WingedStorm: The Winged Storm":                  718,
    "Symbol LairOfInfiniteAgony: Platform Corridor":         719,
    "Symbol LairOfInfiniteAgony: Hall of the Dead":          720,
    "Symbol LairOfInfiniteAgony: Wailer Drop":               721,
    "Symbol HeliosFallen: Moonshot Complaint Dept":          722,
    "Symbol HeliosFallen: The Freightway":                   723,
    "Symbol HeliosFallen: Hellion Hole":                     724,
    "Symbol HeliosFallen: Munitions Loading":                725,
    "Symbol HeliosFallen: Fire Control Alpha":               726,
    "Symbol HeliosFallen: The Hold":                         727,
    "Symbol MinesOfAvarice: Ingot Processing":               728,
    "Symbol MinesOfAvarice: Cube Room":                      729,
    "Symbol MinesOfAvarice: Greedtooth's Lair":              730,
    "Symbol DahlAbandon: Simon's Perch Climb":               731,
    "Symbol DahlAbandon: Ride's End":                        732,
    "Symbol DahlAbandon: Redclaw Rise Cliff":                733,
    "Symbol DahlAbandon: The Veiny Shaft":                   734,
    "Symbol DahlAbandon: Simon's Perch Container":           735,
    "Symbol MtScarab: Test Candidate Detention":             736,
    "Symbol MtScarab: 02 Staircase":                         737,
    "Symbol MtScarab: Experimentation Room":                 738,
    "Symbol HuntersGrotto: Arizona's Lair":                  739,
    "Symbol HuntersGrotto: Grotto Lodge":                    740,
    "Symbol HuntersGrotto: Grotto Start":                    741,
    "Symbol HuntersGrotto: Dahl Door":                       742,
    "Symbol WrithingDeep: Elevator Room":                    743,
    "Symbol WrithingDeep: Southern Top":                     744,
    "Symbol WrithingDeep: Northern Top":                     745,
    "Symbol Burrows: Hyperion's Grave":                      746,
    "Symbol Burrows: Burrows Cliff":                         747,
    "Symbol MurderlinsTemple: The Nursery":                  748,
    "Symbol MurderlinsTemple: Below Murderlin":              749,
    "Symbol FlamerockRefuge: Outskirts":                     750,
    "Symbol FlamerockRefuge: Parkour":                       751,

    # Vending Machines [800 - 1098]
    "Vending Sanctuary Crimson Base: Guns":                    800,
    "Vending Sanctuary Crimson Base: Ammo Dump":               801,
    "Vending Sanctuary Zed's: Ammo Dump":                      802,
    "Vending Sanctuary Zed's: Zed's Meds 1":                   803,
    "Vending Sanctuary Zed's: Zed's Meds 2":                   804,
    "Vending Sanctuary Marcus's: Zed's Meds":                  805,
    "Vending Sanctuary Marcus's: Ammo Dump":                   806,
    "Vending Sanctuary Marcus's: Marcus":                      807,
    "Vending FriendshipGulag: Zed's Meds":                     808,
    "Vending FriendshipGulag: Ammo Dump":                      809,
    "Vending Dust Ellie's: Zed's Meds":                        810,
    "Vending Dust Ellie's: Ammo Dump":                         811,
    "Vending SouthernShelf Hammerlock's: Guns":                812,
    "Vending SouthernShelf Liar's: Ammo Dump":                 813,
    "Vending SouthernShelf Liar's: Zed's Meds":                814,
    "Vending SouthernShelf Safehouse: Zed's Meds":             815,
    "Vending SouthernShelf Dragon: Zed's Meds":                816,
    "Vending SouthernShelf Dragon: Ammo Dump":                 817,
    "Vending SouthernShelfBay Spawn: Ammo Dump":               818,
    "Vending SouthernShelfBay Spawn: Zed's Meds":              819,
    "Vending SouthernShelfBay Cove: Guns":                     820,
    "Vending SouthernShelfBay Cove: Ammo Dump":                821,
    "Vending SouthernShelfBay Cove: Zed's Meds":               822,
    "Vending ThreeHornsDivide Jump: Ammo Dump":                823,
    "Vending ThreeHornsDivide Jump: Zed's Meds":               824,
    "Vending ThreeHornsDivide Crossroads: Guns":               825,
    "Vending ThreeHornsDivide Crossroads: Ammo Dump":          826,
    "Vending ThreeHornsDivide Crossroads: Zed's Meds":         827,
    "Vending ThreeHornsValley Motel: Guns":                    828,
    "Vending ThreeHornsValley Motel: Ammo Dump":               829,
    "Vending ThreeHornsValley Motel: Zed's Meds":              830,
    "Vending Southpaw: Ammo Dump":                             831,
    "Vending Southpaw: Zed's Meds":                            832,
    "Vending Frostburn Spawn: Ammo Dump":                      833,
    "Vending Frostburn Spawn: Zed's Meds":                     834,
    "Vending Frostburn Firehawk: Ammo Dump":                   835,
    "Vending Frostburn Firehawk: Zed's Meds":                  836,
    "Vending Stronghold: Ammo Dump":                           837,
    "Vending Stronghold: Zed's Meds":                          838,
    "Vending Ramparts: Ammo Dump":                             839,
    "Vending Ramparts: Zed's Meds":                            840,
    "Vending Tundra Spawn: Ammo Dump":                         841,
    "Vending Tundra Spawn: Zed's Meds":                        842,
    "Vending Tundra Farm: Guns":                               843,
    "Vending Tundra Tina: Ammo Dump":                          844,
    "Vending EndOfTheLine: Ammo Dump":                         845,
    "Vending EndOfTheLine: Zed's Meds":                        846,
    "Vending Fridge Spawn: Ammo Dump":                         847,
    "Vending Fridge Spawn: Zed's Meds":                        848,
    "Vending Fridge Elevator: Ammo Dump":                      849,
    "Vending Fridge Elevator: Zed's Meds":                     850,
    "Vending Fink's: Guns":                                    851,
    "Vending Fink's: Ammo Dump":                               852,
    "Vending Fink's: Zed's Meds":                              853,
    "Vending Outwash: Ammo Dump":                              854,
    "Vending Outwash: Zed's Meds":                             855,
    "Vending Highlands Bridge: Ammo Dump":                     856,
    "Vending Highlands Bridge: Zed's Meds":                    857,
    "Vending Highlands Overlook: Guns":                        858,
    "Vending Highlands Overlook: Ammo Dump":                   859,
    # "Vending Highlands Overlook: Zed's Meds":                860,
    # "Vending Extraction Plant: Zed's Meds":                  861,
    # "Vending Hyperion Bridge: Zed's Meds":                   862,
    "Vending HolySpirits: Guns":                               863,
    "Vending HolySpirits: Ammo Dump":                          864,
    "Vending HolySpirits: Zed's Meds":                         865,
    "Vending Dust Speedway: Ammo Dump":                        866,
    "Vending Dust Speedway: Zed's Meds":                       867,
    "Vending Dust Steve: Ammo Dump":                           868,
    "Vending Dust Steve: Zed's Meds":                          869,
    "Vending SanctuaryHole: Ammo Dump":                        870,
    "Vending SanctuaryHole: Zed's Meds":                       871,
    "Vending Caverns Spawn: Ammo Dump":                        872,
    "Vending Caverns Spawn: Zed's Meds":                       873,
    "Vending Caverns Shortcut: Guns":                          874,
    "Vending Preserve Spawn: Ammo Dump":                       875,
    "Vending Preserve Spawn: Zed's Meds":                      876,
    "Vending Preserve Halfway: Ammo Dump":                     877,
    "Vending Preserve Halfway: Zed's Meds":                    878,
    "Vending Creature: Ammo Dump":                             879,
    "Vending Creature: Zed's Meds":                            880,
    "Vending Thousand: Ammo Dump":                             881,
    "Vending Thousand: Zed's Meds":                            882,
    "Vending Lynchwood Spawn: Ammo Dump":                      883,
    "Vending Lynchwood Spawn: Zed's Meds":                     884,
    "Vending Lynchwood Gunslinger: Guns":                      885,
    "Vending Opportunity Spawn: Guns":                         886,
    "Vending Opportunity Spawn: Ammo Dump":                    887,
    "Vending Opportunity Spawn: Zed's Meds":                   888,
    "Vending Opportunity Office: Ammo Dump":                   889,
    "Vending Opportunity Office: Zed's Meds":                  890,
    "Vending Opportunity Square: Ammo Dump":                   891,
    "Vending Opportunity Square: Zed's Meds":                  892,
    "Vending Opportunity Residential: Guns":                   893,
    "Vending Opportunity Residential: Ammo Dump":              894,
    "Vending Bunker: Ammo Dump":                               895,
    "Vending Bunker: Zed's Meds":                              896,
    "Vending Blight Spawn: Ammo Dump":                         897,
    "Vending Blight Spawn: Zed's Meds":                        898,
    "Vending Blight Extraction: Ammo Dump":                    899,
    "Vending Blight Extraction: Zed's Meds":                   900,
    "Vending Blight Refinery: Guns":                           901,
    "Vending Blight Refinery: Ammo Dump":                      902,
    "Vending Blight Refinery: Zed's Meds":                     903,
    "Vending OreChasm: Guns":                                  904,
    "Vending OreChasm: Ammo Dump":                             905,
    "Vending OreChasm: Zed's Meds":                            906,
    "Vending Sawtooth Spawn: Ammo Dump":                       907,
    "Vending Sawtooth Spawn: Zed's Meds":                      908,
    "Vending Sawtooth Elevator: Ammo Dump":                    909,
    "Vending Boneyard Spawn: Ammo Dump":                       910,
    "Vending Boneyard Spawn: Zed's Meds":                      911,
    "Vending Badlands Fyrestone: Ammo Dump":                   912,
    "Vending Badlands Fyrestone: Zed's Meds":                  913,
    "Vending Badlands Baha: Guns":                             914,
    "Vending HerosPass Spawn: Ammo Dump":                      915,
    "Vending HerosPass Spawn: Zed's Meds":                     916,
    "Vending Warrior: Ammo Dump":                              917,
    "Vending Warrior: Zed's Meds":                             918,
    "Vending Terramorphous: Guns":                             919,
    "Vending Terramorphous: Ammo Dump":                        920,
    "Vending Terramorphous: Zed's Meds":                       921,
    # "Vending Oasis Town: Seraph Vendor":                     922,
    "Vending Oasis Town: Guns":                                923,
    "Vending Oasis Town: Ammo Dump":                           924,
    "Vending Oasis Town: Zed's Meds":                          925,
    "Vending Wurmwater Oasis Door: Ammo Dump":                 926,
    "Vending Wurmwater Oasis Door: Zed's Meds":                927,
    "Vending Wurmwater Canyon: Guns":                          928,
    "Vending Wurmwater Canyon: Ammo Dump":                     929,
    "Vending Wurmwater Fen: Ammo Dump":                        930,
    "Vending Wurmwater Ship: Guns":                            931,
    "Vending Wurmwater Ship: Ammo Dump":                       932,
    "Vending Wurmwater Ship: Zed's Meds":                      933,
    "Vending Wurmwater Rustyard: Guns":                        934,
    "Vending Hayters Spawn: Guns":                             935,
    "Vending Hayters Spawn: Ammo Dump":                        936,
    "Vending Hayters Spawn: Zed's Meds":                       937,
    "Vending Hayters Gee: Ammo Dump":                          938,
    "Vending Hayters Gee: Zed's Meds":                         939,
    "Vending Rustyards Spawn: Ammo Dump":                      940,
    "Vending Rustyards Spawn: Zed's Meds":                     941,
    "Vending Washburne Spawn: Ammo Dump":                      942,
    "Vending Washburne Spawn: Zed's Meds":                     943,
    "Vending Washburne Hyperius: Ammo Dump":                   944,
    "Vending Washburne Hyperius: Zed's Meds":                  945,
    "Vending Magnys Spawn: Ammo Dump":                         946,
    "Vending Magnys Spawn: Zed's Meds":                        947,
    "Vending Leviathan Body: Ammo Dump":                       948,
    "Vending Leviathan Body: Zed's Meds":                      949,
    "Vending Leviathan Lair: Ammo Dump":                       950,
    "Vending Leviathan Lair: Zed's Meds":                      951,
    "Vending Crater Spawn: Ammo Dump":                         952,
    "Vending Crater Spawn: Zed's Meds":                        953,
    # "Vending Crater Town: Seraph Vendor":                    954,
    "Vending Crater Town: Ammo Dump":                          955,
    "Vending Crater Town: Zed's Meds":                         956,
    "Vending Crater Forge: Torgue Vendor":                     957,
    "Vending Crater Forge: Ammo Dump":                         958,
    "Vending Crater Forge: Zed's Meds":                        959,
    "Vending Arena Inner: Torgue Vendor":                      960,
    "Vending Arena Inner: Ammo Dump":                          961,
    "Vending Arena Inner: Zed's Meds":                         962,
    "Vending Beatdown Spawn: Torgue Vendor":                   963,
    "Vending Beatdown Spawn: Ammo Dump":                       964,
    "Vending Beatdown Spawn: Zed's Meds":                      965,
    "Vending Beatdown Underpass: Torgue Vendor":               966,
    "Vending Beatdown Underpass: Ammo Dump":                   967,
    "Vending Beatdown Underpass: Zed's Meds":                  968,
    "Vending Pete's: Torgue Vendor":                           969,
    "Vending Pete's: Ammo Dump":                               970,
    "Vending Pete's: Zed's Meds":                              971,
    "Vending BadassBar: Torgue Vendor":                        972,
    "Vending BadassBar: Ammo Dump":                            973,
    "Vending BadassBar: Zed's Meds":                           974,
    "Vending Raceway: Torgue Vendor":                          975,
    "Vending Raceway: Ammo Dump":                              976,
    "Vending Raceway: Zed's Meds":                             977,
    "Vending Forge Spawn: Torgue Vendor":                      978,
    "Vending Forge Spawn: Ammo Dump":                          979,
    "Vending Forge Spawn: Zed's Meds":                         980,
    "Vending Forge Flyboy: Ammo Dump":                         981,
    "Vending Forge Flyboy: Zed's Meds":                        982,
    # "Vending Grotto Lodge: Seraph Vendor":                   983,
    "Vending Grotto Lodge: Guns":                              984,
    "Vending Grotto Lodge: Ammo Dump":                         985,
    "Vending Grotto Lodge: Zed's Meds":                        986,
    "Vending Scylla's Entrance: Guns":                         987,
    "Vending Scylla's Entrance: Ammo Dump":                    988,
    "Vending Scylla's Entrance: Zed's Meds":                   989,
    "Vending Scylla's Pukey: Zed's Meds":                      990,
    "Vending Ardorton Entrance: Ammo Dump":                    991,
    "Vending Ardorton Entrance: Zed's Meds":                   992,
    "Vending Ardorton Exit: Ammo Dump":                        993,
    "Vending Ardorton Exit: Zed's Meds":                       994,
    "Vending Crag Spawn: Ammo Dump":                           995,
    "Vending Crag Spawn: Zed's Meds":                          996,
    "Vending Crag Voracidous: Ammo Dump":                      997,
    "Vending Crag Voracidous: Zed's Meds":                     998,
    "Vending Terminus Entrance: Ammo Dump":                    999,
    "Vending Terminus Entrance: Zed's Meds":                  1000,
    # "Vending Flamerock Refuge: Seraph Vendor":              1001,
    "Vending Flamerock Refuge: Guns/Cannons":                 1002,
    "Vending Flamerock Refuge: Ammo Dump/Missiles":           1003,
    "Vending Flamerock Refuge: Zed's Apothecary":             1004,
    "Vending Forest Spawn: Ammo Dump/Missiles":               1005,
    "Vending Forest Spawn: Zed's Apothecary":                 1006,
    "Vending Immortal Spawn: Ammo Dump/Missiles":             1007,
    "Vending Immortal Spawn: Zed's Apothecary":               1008,
    "Vending Immortal Vitality Grove: Ammo Dump/Missiles":    1009,
    "Vending Immortal Vitality Grove: Zed's Apothecary":      1010,
    "Vending Avarice Spawn: Ammo Dump/Missiles":              1011,
    "Vending Avarice Spawn: Zed's Apothecary":                1012,
    "Vending Avarice Greedtooth: Ammo Dump/Missiles":         1013,
    "Vending Avarice Greedtooth: Zed's Apothecary":           1014,
    "Vending Shadow Spawn: Ammo Dump/Missiles":               1015,
    "Vending Shadow Spawn: Zed's Apothecary":                 1016,
    "Vending Handsome Bridge: Guns/Cannons":                  1017,
    "Vending Handsome Bridge: Ammo Dump/Missiles":            1018,
    "Vending Handsome Bridge: Zed's Apothecary":              1019,
    "Vending Agony Spawn: Ammo Dump/Missiles":                1020,
    "Vending Agony Spawn: Zed's Apothecary":                  1021,
    "Vending Agony Daughter: Ammo Dump/Missiles":             1022,
    "Vending Agony Daughter: Zed's Apothecary":               1023,
    # "Vending Agony Hall of the Dead: Mr. Miz":              1024,
    "Vending DragonKeep: Ammo Dump/Missiles":                 1025,
    "Vending DragonKeep: Zed's Apothecary":                   1026,
    "Vending WingedStorm: Guns/Cannons":                      1027,
    "Vending WingedStorm: Ammo Dump/Missiles":                1028,
    "Vending WingedStorm: Zed's Apothecary":                  1029,
    "Vending Murderlin's Temple: Guns/Cannons":               1030,
    "Vending Murderlin's Temple: Ammo Dump/Missiles":         1031,
    "Vending Murderlin's Temple: Zed's Apothecary":           1032,
    "Vending HallowedHollow Entrance: Ammo Dump":             1033,
    "Vending HallowedHollow Entrance: Zed's Meds":            1034,
    "Vending HallowedHollow Kingpin Approach: Zed's Meds":    1035,
    "Vending HallowedHollow Kingpin Approach: Ammo Dump":     1036,
    "Vending GlutGulch Entrance: Guns":                       1037,
    "Vending GlutGulch Entrance: Ammo Dump":                  1038,
    "Vending GlutGulch Entrance: Zed's Meds":                 1039,
    "Vending GlutGulch Kitchen: Ammo Dump":                   1040,
    "Vending GlutGulch Stabber Jabber: Guns":                 1041,
    "Vending GlutGulch Tribute Station: Guns":                1042,
    "Vending GlutGulch Tribute Station: Zed's Meds":          1043,
    "Vending GlutGulch Tribute Station: Ammo Dump":           1044,
    "Vending MercenaryDay Entrance: Guns":                    1045,
    "Vending MercenaryDay Entrance: Ammo Dump":               1046,
    "Vending MercenaryDay Entrance: Zed's Meds":              1047,
    "Vending MercenaryDay Tinder Arena: Zed's Meds":          1048,
    "Vending MercenaryDay Tinder Arena: Ammo Dump":           1049,
    "Vending Distillery Entrance: Zed's Meds":                1050,
    "Vending Distillery Entrance: Ammo Dump":                 1051,
    "Vending Distillery Pot of Gold: Ammo Dump":              1052,
    "Vending Distillery Wedding Venue: Zed's Meds":           1053,
    "Vending Distillery Wedding Venue: Ammo Dump":            1054,
    "Vending WamBam Entrance: Ammo Dump":                     1055,
    "Vending WamBam Entrance: Zed's Meds":                    1056,
    "Vending WamBam Water Wheel: Zed's Meds":                 1057,
    "Vending WamBam Water Wheel: Ammo Dump":                  1058,
    "Vending WamBam Son's Arena: Ammo Dump":                  1059,
    "Vending WamBam Son's Arena: Zed's Meds":                 1060,
    "Vending Backburner Entrance: Ammo Dump":                 1061,
    "Vending Backburner Entrance: Zed's Meds":                1062,
    "Vending Backburner Vaughn's HQ: Guns":                   1063,
    "Vending Backburner Vaughn's HQ: Ammo Dump":              1064,
    "Vending Backburner Vaughn's HQ: Zed's Meds":             1065,
    "Vending Backburner Marcus: Guns":                        1066,
    "Vending Backburner Marcus: Ammo Dump":                   1067,
    "Vending DahlAbandon Entrance: Ammo dump":                1068,
    "Vending DahlAbandon Entrance: Zed's Meds":               1069,
    "Vending DahlAbandon Mine Door: Ammo Dump":               1070,
    "Vending DahlAbandon Mine Door: Zed's Meds":              1071,
    "Vending Burrows Entrance: Ammo Dump":                    1072,
    "Vending Burrows Entrance: Zed's Meds":                   1073,
    "Vending HeliosFallen Entrance: Ammo Dump":               1074,
    "Vending HeliosFallen Entrance: Zed's Meds":              1075,
    "Vending HeliosFallen Munitions Loading: Ammo Dump":      1076,
    "Vending HeliosFallen Munitions Loading: Zed's Meds":     1077,
    "Vending HeliosFallen The Arsenal: Ammo Dump":            1078,
    "Vending HeliosFallen The Arsenal: Zed's Meds":           1079,
    "Vending Mt.Scarab Entrance: Ammo Dump":                  1080,
    "Vending Mt.Scarab Entrance: Zed's Meds":                 1081,
    "Vending Mt.Scarab Observation Deck: Ammo Dump":          1082,
    "Vending Mt.Scarab Observation Deck: Zed's Meds":         1083,
    # "Vending Paradise Sanctum Entrance: Ammo Dump":         1084,
    # "Vending Paradise Sanctum Entrance: Zed's Meds":        1085,
    # "Vending Paradise Sanctum Marcus Munitions: Guns":      1086,
    # "Vending Paradise Sanctum Marcus Munitions: Zed's Meds":  1087,
    # "Vending Paradise Sanctum Hector: Ammo Dump":           1088,
    # "Vending Paradise Sanctum Hector: Zed's Meds":          1089,
    "Vending WrithingDeep: Ammo Dump":                        1090,
    "Vending WrithingDeep: Zed's Meds":                       1091,
    "Vending Digistruct Spawn: Guns":                         1092,
    "Vending Digistruct Spawn: Ammo Dump":                    1093,
    "Vending Digistruct Spawn: Zed's Meds":                   1094,
    "Vending DigistructInner Butcher Base: Ammo Dump":        1095,
    # "Vending DigistructInner Area of Anguish: Ammo Dump":   1096,
    # "Vending DigistructInner Area of Anguish: Zed's Meds":  1097,
    # "Vending DigistructInner Tower of Torment: Ammo Dump":  1098,
    "Vending Dust: Dahlwell: Zed's Meds":       1314,
    "Vending Dust: Dahlwell: Ammo Dump":        1315,

    # Generic Mobs [1300 - 1313]
    "Generic: Skag":              1300,
    "Generic: Rakk":              1301,
    "Generic: Bullymong":         1302,
    "Generic: Psycho":            1303,
    "Generic: Rat":               1304,
    "Generic: Spiderant":         1305,
    "Generic: Varkid":            1306,
    "Generic: Goliath":           1307,
    "Generic: Marauder":          1308,
    "Generic: Stalker":           1309,
    "Generic: Midget":            1310,
    "Generic: Nomad":             1311,
    "Generic: Thresher":          1312,
    "Generic: Badass":            1313,
}


item_name_to_id = {
    "3 Skill Points":                     1,
    "Progressive Money Cap":              2,
    "Weapon Slot":                        3,
    "$100":                               4,
    "10 Eridium":                         5,

    "Progressive Jump":                   6,
    "Melee":                              7,
    "Crouch":                             8,
    "Sprint":                             9,
    "Gear Leveler":                      10,
    "Vehicle Fire":                      11,

    # Map Areas [501 - 580]
    # "Travel: Windshear Waste":                   501,
    "Travel: Arid Nexus Boneyard":                 502,
    "Travel: The Holy Spirits":                    503,
    "Travel: Southpaw Steam & Power":              504,
    "Travel: Sanctuary Hole":                      505,
    "Travel: Hero's Pass":                         506,
    "Travel: Bloodshot Stronghold":                507,
    "Travel: Three Horns Valley":                  508,
    "Travel: Sanctuary":                           509,
    "Travel: Thousand Cuts":                       510,
    "Travel: End of the Line":                     511,
    "Travel: Wildlife Exploitation Preserve":      512,
    "Travel: Terramorphous Peak":                  513,
    "Travel: Tundra Express":                      514,
    "Travel: The Fridge":                          515,
    "Travel: Fink's Slaughterhouse":               516,
    "Travel: Southern Shelf Bay":                  517,
    "Travel: Frostburn Canyon":                    518,
    "Travel: Three Horns Divide":                  519,
    "Travel: Highlands":                           520,
    "Travel: Natural Selection Annex":             521,
    "Travel: The Dust":                            522,
    "Travel: Friendship Gulag":                    523,
    "Travel: Opportunity":                         524,
    "Travel: Bloodshot Ramparts":                  525,
    "Travel: Arid Nexus Badlands":                 526,
    "Travel: Southern Shelf":                      527,
    "Travel: Highlands Outwash":                   528,
    "Travel: Caustic Caverns":                     529,
    "Travel: Lynchwood":                           530,
    "Travel: Sawtooth Cauldron":                   531,
    "Travel: Ore Chasm":                           532,
    "Travel: The Bunker":                          533,
    "Travel: Control Core Angel":                  534,
    "Travel: Vault of the Warrior":                535,
    "Travel: Eridium Blight":                      536,
    "Travel: Gluttony Gulch":                      537,
    "Travel: Marcus's Mercenary Shop":             538,
    "Travel: Helios Fallen":                       539,
    "Travel: FFS Boss Fight":                      540,
    "Travel: The Backburner":                      541,
    "Travel: FFS Intro Sanctuary":                 542,
    "Travel: Dahl Abandon":                        543,
    "Travel: Mt. Scarab Research Center":          544,
    "Travel: The Burrows":                         545,
    "Travel: Writhing Deep":                       546,
    "Travel: The Forest":                          547,
    "Travel: Immortal Woods":                      548,
    "Travel: Dragon Keep":                         549,
    "Travel: Unassuming Docks":                    550,
    "Travel: Flamerock Refuge":                    551,
    "Travel: Hatred's Shadow":                     552,
    "Travel: Lair of Infinite Agony":              553,
    "Travel: Murderlin's Temple":                  554,
    "Travel: Mines of Avarice":                    555,
    "Travel: The Winged Storm":                    556,
    "Travel: Hallowed Hollow":                     557,
    "Travel: Torgue Arena Ring":                   558,
    "Travel: Torgue Arena":                        559,
    "Travel: The Beatdown":                        560,
    "Travel: The Forge":                           561,
    "Travel: Badass Crater":                       562,
    "Travel: Southern Raceway":                    563,
    "Travel: Pyro Pete's Bar":                     564,
    "Travel: Baddass Crater Bar":                  565,
    "Travel: Digistruct Peak":                     566,
    "Travel: Wam Bam Island":                      567,
    "Travel: Rotgut Distillery":                   568,
    "Travel: The Leviathan's Lair":                569,
    "Travel: Washburne Refinery":                  570,
    "Travel: Wurmwater":                           571,
    "Travel: Magnys Lighthouse":                   572,
    "Travel: The Rustyards":                       573,
    "Travel: Haytor's Folly":                      574,
    "Travel: Oasis":                               575,
    "Travel: Ardorton Station":                    576,
    "Travel: Hunter's Grotto":                     577,
    "Travel: Candlerakk's Cragg":                  578,
    "Travel: Terminus":                            579,
    "Travel: Scylla's Grove":                      580,

    # Traps [600 - 605]
    "Trap Spawn: Saturn":                     600,
    "Trap Spawn: Black Queen":                601,
    "Trap Spawn: Assassins":                  602,
    "Trap Spawn: Dukino's Mom":               603,
    "Trap Spawn: Doc Mercy":                  604,
    "Trap Spawn: Creeper":                    605,
}

# stitch dictionaries together

loc_name_to_id.update(gear_kind_to_id)
loc_name_to_id.update(level_name_to_id)
loc_name_to_id.update({"Quest " + k : v for k, v in quest_name_to_id.items()})

item_name_to_id.update(gear_kind_to_id)
item_name_to_id.update({"Reward " + k : v for k, v in quest_name_to_id.items()})

loc_id_to_name = {id: name for name, id in loc_name_to_id.items()}
item_id_to_name = {id: name for name, id in item_name_to_id.items()}
