# This file is intended to be shared between the Archipelago Client/World and the Game sdkmod.
# I don't expect to be able to have one source of truth distributed to both, so just keep the two files in sync.

level_name_to_id = {
    # 2 through 30
    "Level " + str(i) : i for i in range(2, 31)
}

gear_kind_to_id = {
    # Gear
    "Common Shield":                    100,
    "Uncommon Shield":                  101,
    "Rare Shield":                      102,
    "VeryRare Shield":                  103,
    # "E-Tech Shield":                    104,
    "Legendary Shield":                 105,
    # "Seraph Shield":                    106,
    # "Rainbow Shield":                   107,
    # "Pearlescent Shield":               108,
    # "Unique Shield":                    109,

    "Common GrenadeMod":                110,
    "Uncommon GrenadeMod":              111,
    "Rare GrenadeMod":                  112,
    "VeryRare GrenadeMod":              113,
    # "E-Tech GrenadeMod":                114,
    "Legendary GrenadeMod":             115,
    # "Seraph GrenadeMod":                116,
    # "Rainbow GrenadeMod":               117,
    # "Pearlescent GrenadeMod":           118,
    # "Unique GrenadeMod":                119,

    "Common ClassMod":                  120,
    "Uncommon ClassMod":                121,
    "Rare ClassMod":                    122,
    "VeryRare ClassMod":                123,
    # "E-Tech ClassMod":                  124,
    "Legendary ClassMod":               125,
    # "Seraph ClassMod":                  126,
    # "Rainbow ClassMod":                 127,
    # "Pearlescent ClassMod":             128,
    # "Unique ClassMod":                  129,

    "Common Relic":                     130,
    "Uncommon Relic":                   131,
    "Rare Relic":                       132,
    "VeryRare Relic":                   133,
    # "E-Tech Relic":                     134,
    # "Legendary Relic":                  135,
    # "Seraph Relic":                     136,
    # "Rainbow Relic":                    137,
    # "Pearlescent Relic":                138,
    # "Unique Relic":                     139,

    "Common Pistol":                    140,
    "Uncommon Pistol":                  141,
    "Rare Pistol":                      142,
    "VeryRare Pistol":                  143,
    "E-Tech Pistol":                    144,
    "Legendary Pistol":                 145,
    # "Seraph Pistol":                    146,
    # "Rainbow Pistol":                   147,
    # "Pearlescent Pistol":               148,
    "Unique Pistol":                    149,

    "Common Shotgun":                   150,
    "Uncommon Shotgun":                 151,
    "Rare Shotgun":                     152,
    "VeryRare Shotgun":                 153,
    "E-Tech Shotgun":                   154,
    "Legendary Shotgun":                155,
    # "Seraph Shotgun":                   156,
    # "Rainbow Shotgun":                  157,
    # "Pearlescent Shotgun":              158,
    "Unique Shotgun":                   159,

    "Common SMG":                       160,
    "Uncommon SMG":                     161,
    "Rare SMG":                         162,
    "VeryRare SMG":                     163,
    "E-Tech SMG":                       164,
    "Legendary SMG":                    165,
    # "Seraph SMG":                       166,
    # "Rainbow SMG":                      167,
    # "Pearlescent SMG":                  168,
    "Unique SMG":                       169,

    "Common SniperRifle":               170,
    "Uncommon SniperRifle":             171,
    "Rare SniperRifle":                 172,
    "VeryRare SniperRifle":             173,
    "E-Tech SniperRifle":               174,
    "Legendary SniperRifle":            175,
    # "Seraph SniperRifle":               176,
    # "Rainbow SniperRifle":              177,
    # "Pearlescent SniperRifle":          178,
    "Unique SniperRifle":               179,

    "Common AssaultRifle":              180,
    "Uncommon AssaultRifle":            181,
    "Rare AssaultRifle":                182,
    "VeryRare AssaultRifle":            183,
    "E-Tech AssaultRifle":              184,
    "Legendary AssaultRifle":           185,
    # "Seraph AssaultRifle":              186,
    # "Rainbow AssaultRifle":             187,
    # "Pearlescent AssaultRifle":         188,
    "Unique AssaultRifle":              189,

    "Common RocketLauncher":            190,
    "Uncommon RocketLauncher":          191,
    "Rare RocketLauncher":              192,
    "VeryRare RocketLauncher":          193,
    "E-Tech RocketLauncher":            194,
    "Legendary RocketLauncher":         195,
    # "Seraph RocketLauncher":            196,
    # "Rainbow RocketLauncher":           197,
    # "Pearlescent RocketLauncher":       198,
    "Unique RocketLauncher":            199,
}

loc_name_to_id = {

    # Enemies
    "Enemy WindshearWaste: Knuckle Dragger":           301,
    "Enemy SouthernShelfBay: Midgemong":               302,
    "Enemy SouthernShelf: Boom Bewm":                  303,
    "Enemy SouthernShelf: Captain Flynt":              304,
    "Enemy ThreeHornsDivide: Savage Lee":              305,
    "Enemy ThreeHornsDivide: Boll":                    306,
    "Enemy ThreeHornsValley: Doc Mercy":               307,
    "Enemy SouthpawSteam&Power: Assassin Oney":        308,
    "Enemy SouthpawSteam&Power: Assassin Wot":         309,
    "Enemy SouthpawSteam&Power: Assassin Reeth":       310,
    "Enemy SouthpawSteam&Power: Assassin Rouf":        311,
    "Enemy ThreeHornsValley: Scorch":                  312,
    "Enemy ThreeHornsValley: Incinerator Clayton":     313,
    "Enemy Dust: Gettle":                              314,
    "Enemy Dust: Mobley":                              315,
    "Enemy Dust: Black Queen":                         316,
    "Enemy ThreeHornsValley: Bad Maw":                 317,
    "Enemy BloodshotStronghold: Mad Mike":             318,
    "Enemy BloodshotRamparts: W4R-D3N":                319,
    "Enemy FrostburnCanyon: Spycho":                   320,
    "Enemy Dust: McNally":                             321,
    "Enemy Dust: Mick/Tector":                         322,
    # "Enemy Dust: Mick/Tector":                         322,
    "Enemy BloodshotStronghold: Dan":                  323,
    "Enemy BloodshotStronghold: Lee":                  324,
    "Enemy BloodshotStronghold: Mick":                 325,
    "Enemy BloodshotStronghold: Ralph":                326,
    "Enemy BloodshotStronghold: Flinter":              327,
    "Enemy TundraExpress: MadameVonBartlesby":         328,
    "Enemy EndOfTheLine: Wilhelm":                     329,
    "Enemy Fridge: LaneyWhite":                        330,
    "Enemy Fridge: Rakkman":                           331,
    "Enemy Fridge: SmashHead":                         332,
    "Enemy Fridge: Sinkhole":                          333,
    "Enemy Highlands: OldSlappy":                      334,
    "Enemy Highlands: GluttonousThresher":             335,
    "Enemy Highlands: Henry":                          336,
    "Enemy CausticCaverns: Blue":                      337,
    "Enemy CausticCaverns: BadassCreeper":             338,
    "Enemy WildlifePreserve: Tumbaa":                  339,
    "Enemy WildlifePreserve: Pimon":                   340,
    "Enemy WildlifePreserve: SonOfMothrakk":           341,
    # "Bloodwing":                         342,
    "Enemy ThousandCuts: GOD-liath":                    343,
    "Enemy Lynchwood: DukinosMom":                     344,
    "Enemy Lynchwood: MadDog":                         345,
    "Enemy Lynchwood: SheriffNisha":                   346,
    "Enemy Lynchwood: DeputyWinger":                   347,
    "Enemy Opportunity: ForemanJasper":                348,
    "Enemy Opportunity: JackBodyDouble":               349,
    # "BNK-3R":                            350,
    "Enemy EridiumBlight: KingMong":                   351,
    "Enemy EridiumBlight: DonkeyMong":                 352,
    "Enemy SawtoothCauldron: Mortar":                  353,
    "Enemy AridNexusBoneyard: HunterHellquist":        354,
    "Enemy AridNexusBadlands: BoneHead":               355,
    "Enemy AridNexusBadlands: Saturn":                 356,
    # "Warrior":                           357,

    # Vault Symbols
    "Symbol Sanctuary: Rooftop":                             501,
    "Symbol Sanctuary: Moxxi's Corner":                      502,
    "Symbol Sanctuary: Trash Corner":                        503,
    "Symbol Sanctuary: Tire Corner":                         504,
    "Symbol Sanctuary: Parkour Door":                        505,
    "Symbol EridiumBlight: Hellsfont Crate":                 506,
    "Symbol EridiumBlight: Stairs Door":                     507,
    "Symbol EridiumBlight: Refund Building":                 508,
    "Symbol Fink's: Column":                                 509,
    "Symbol Bunker: Backside":                               510,
    "Symbol WarriorVault: Elevator Bottom":                  511,
    "Symbol SouthernShelfBay: Blackburn Cove Corner":        512,
    "Symbol SouthernShelfBay: Ice Flows Shipwreck":          513,
    "Symbol Sawtooth: Refinery Container":                   514,
    "Symbol Sawtooth: Elevator":                             515,
    "Symbol CreatureSlaughter: Crate Ceiling":               516,
    "Symbol HerosPass: Strut":                               517,
    "Symbol HerosPass: Spawn":                               518,
    "Symbol Fridge: Secret Stash":                           519,
    "Symbol Fridge: Sheetmetal Roof":                        520,
    "Symbol ThreeHornsValley: Slums Wall":                   521,
    "Symbol ThreeHornsValley: Frostsprings Wall":            522,
    "Symbol ThreeHornsValley: Frostsprings Shack":           523,
    "Symbol AridNexusBoneyard: Pipe":                        524,
    "Symbol AridNexusBoneyard: Safety":                      525,
    "Symbol WindshearWaste: Claptrap's Closet":              526,
    "Symbol ThousandCuts: Buzzard Factory":                  527,
    "Symbol ThousandCuts: No Man's Land Shack":              528,
    "Symbol Lynchwood: Gunslinger Roof":                     529,
    "Symbol Lynchwood: Main Street":                         530,
    "Symbol Highlands: Highlands Tower":                     531,
    "Symbol FriendshipGulag: Gulag Container":               532,
    "Symbol Opportunity: Construction Site":                 533,
    "Symbol Opportunity: Office Bridge":                     534,
    "Symbol ThreeHornsDivide Drydocks Corner":               535,
    "Symbol ThreeHornsDivide Billboard":                     536,
    "Symbol ThreeHornsDivide Windbreak Wall":                537,
    "Symbol Dust: Speedway Wall":                            538,
    "Symbol Dust: Buzzard Pad":                              539,
    "Symbol Dust: Moonshiner Lid":                           540,
    "Symbol CausticCaverns: Gravestone Feature":             541,
    "Symbol CausticCaverns: Bloody Ladder":                  542,
    "Symbol Bloodshot: Pizza Intercom":                      543,
    "Symbol Bloodshot: Switch Room":                         544,
    "Symbol BloodshotRamparts: Ramp":                        545,
    "Symbol Frostburn: Blisterpus Cave":                     546,
    "Symbol Frostburn: Ashmouth Pit":                        547,
    "Symbol TorgueArenaRing: Arena Wall":                    548,
    "Symbol TorgueArenaRing: Arena Ladder":                  549,
    "Symbol Beatdown: Underpass":                            550,
    "Symbol Beatdown: School Bus":                           551,
    "Symbol Forge: Smack Talker":                            552,
    "Symbol Forge: Lava":                                    553,
    "Symbol Forge: Housing":                                 554,
    "Symbol SouthernRaceway: Zer0 Poster":                   555,
    "Symbol SouthernRaceway: Maya Poster":                   556,
    "Symbol BadassCrater: Badass Highway":                   557,
    "Symbol BadassCrater: Beatdown Door":                    558,
    "Symbol BadassCrater: Billboard Lower":                  559,
    "Symbol BadassCrater: Billboard Upper":                  560,
    "Symbol HolySpirits: Bathroom":                          561,
    "Symbol HaytorsFolly: Hot Springs Crate":                562,
    "Symbol HaytorsFolly: Grendel Exit":                     563,
    "Symbol Oasis: Kronus":                                  564,
    "Symbol Oasis: Lair Exit":                               565,
    "Symbol Oasis: Lionel Docks":                            566,
    "Symbol Oasis: Coral Island":                            567,
    "Symbol WashburneRefinery: P3RV-E Lair":                  568,
    "Symbol WashburneRefinery: Forge Array":                  569,
    "Symbol Wurmwater: Rustyard Corridor":                   570,
    "Symbol Wurmwater: Scarlett's Ship":                     571,
    "Symbol Wurmwater: The Dish":                            572,
    "Symbol Rustyards: Maroonie's Clipper":                  573,
    "Symbol Rustyards: Rustyards Fence":                     574,
    "Symbol MagnysLighthouse: House":                        575,
    "Symbol MagnysLighthouse: Lighthouse":                   576,
    "Symbol LeviathansLair: Lair":                           577,
    "Symbol WildlifePreserve: Dockyard Roof":                578,
    "Symbol WildlifePreserve: Broken Boulevard":             579,
    "Symbol OreChasm: Elevator":                             580,
    "Symbol CandlerakksCragg: Elite Crossing House":         581,
    "Symbol CandlerakksCragg: Near Voracidous":              582,
    "Symbol CandlerakksCragg: Rouge's Lair":                 583,
    "Symbol Terminus: Terminus":                             584,
    "Symbol ArdortonStation: Woundspike's Lair":              585,
    "Symbol ArdortonStation: Psycho Surgery":                 586,
    "Symbol ArdortonStation: Ardo Farm":                      587,
    "Symbol ArdortonStation: Dribble's Lair":                 588,
    "Symbol ScyllasGrove: Low Gut Rut Wall":                 589,
    "Symbol ScyllasGrove: Urine Wall":                       590,
    "Symbol ScyllasGrove: Upper Village":                    591,
    "Symbol ScyllasGrove: Lower Village":                    592,
    "Symbol SanctuaryHole: Staircase Wall":                  593,
    "Symbol SouthernShelf: Flynt's Ship":                    594,
    "Symbol SouthernShelf: Safehouse":                       595,
    "Symbol Southpaw: Parkour":                              596,
    "Symbol Southpaw: Engine":                               597,
    "Symbol Southpaw: Ladder":                               598,
    "Symbol TerramorphousPeak: Dropdown":                    599,
    "Symbol TerramorphousPeak: Elevator":                    600,
    "Symbol EndOfTheLine: Wilhelm Wall":                     601,
    "Symbol TundraExpress: Fork Shack":                      602,
    "Symbol TundraExpress: Facility Roof":                   603,
    "Symbol Backburner: Zed's":                              604,
    "Symbol Backburner: Entrance":                           605,
    "Symbol HatredsShadow: Sir Boil":                        606,
    "Symbol HatredsShadow: Nefarious Elevator":              607,
    "Symbol HatredsShadow: Sir Mash":                        608,
    "Symbol DragonKeep: Sacrifice Staircase":                609,
    "Symbol Forest: Blood Tree Camp":                        610,
    "Symbol Forest: Glenn's Cottage":                        611,
    "Symbol ImmortalWoods: Fields of the Fallen":            612,
    "Symbol ImmortalWoods: Sacred Ruins Upper":              613,
    "Symbol ImmortalWoods: Sacred Ruins Lower":              614,
    "Symbol UnassumingDocks: Temple Shoreline":              615,
    "Symbol UnassumingDocks: Forlorn Ruins":                 616,
    "Symbol UnassumingDocks: Hamlet Building":               617,
    "Symbol WingedStorm: The Winged Storm":                  618,
    "Symbol LairOfInfiniteAgony: Platform Corridor":         619,
    "Symbol LairOfInfiniteAgony: Hall of the Dead":          620,
    "Symbol LairOfInfiniteAgony: Wailer Drop":               621,
    "Symbol HeliosFallen: Moonshot Complaint Dept":          622,
    "Symbol HeliosFallen: The Freightway":                   623,
    "Symbol HeliosFallen: Hellion Hole":                     624,
    "Symbol HeliosFallen: Munitions Loading":                625,
    "Symbol HeliosFallen: Fire Control Alpha":               626,
    "Symbol HeliosFallen: The Hold":                         627,
    "Symbol MinesOfAvarice: Ingot Processing":               628,
    "Symbol MinesOfAvarice: Cube Room":                      629,
    "Symbol MinesOfAvarice: Greedtooth's Lair":              630,
    "Symbol DahlAbandon: Simon's Perch Climb":               631,
    "Symbol DahlAbandon: Ride's End":                        632,
    "Symbol DahlAbandon: Redclaw Rise Cliff":                633,
    "Symbol DahlAbandon: The Veiny Shaft":                   634,
    "Symbol DahlAbandon: Simon's Perch Container":           635,
    "Symbol MtScarab: Test Candidate Detention":             636,
    "Symbol MtScarab: 02 Staircase":                         637,
    "Symbol MtScarab: Experimentation Room":                 638,
    "Symbol HuntersGrotto: Arizona's Lair":                  639,
    "Symbol HuntersGrotto: Grotto Lodge":                    640,
    "Symbol HuntersGrotto: Grotto Start":                    641,
    "Symbol HuntersGrotto: Dahl Door":                       642,
    "Symbol WrithingDeep: Elevator Room":                    643,
    "Symbol WrithingDeep: Southern Top":                     644,
    "Symbol WrithingDeep: Northern Top":                     645,
    "Symbol Burrows: Hyperion's Grave":                      646,
    "Symbol Burrows: Burrows Cliff":                         647,
    "Symbol MurderlinsTemple: The Nursery":                  648,
    "Symbol MurderlinsTemple: Below Murderlin":              649,
    "Symbol FlamerockRefuge: Outskirts":                     650,
    "Symbol FlamerockRefuge: Parkour":                       651,

    # Vending Machines
    "Vending Sanctuary Crimson Base: Guns":                    700,
    "Vending Sanctuary Crimson Base: Ammo Dump":               701,
    "Vending Sanctuary Zed's: Ammo Dump":                      702,
    "Vending Sanctuary Zed's: Zed's Meds 1":                   703,
    "Vending Sanctuary Zed's: Zed's Meds 2":                   704,
    "Vending Sanctuary Marcus's: Zed's Meds":                  705,
    "Vending Sanctuary Marcus's: Ammo Dump":                   706,
    "Vending Sanctuary Marcus's: Marcus":                      707,
    "Vending FriendshipGulag: Zed's Meds":                     708,
    "Vending FriendshipGulag: Ammo Dump":                      709,
    "Vending Dust Ellie's: Zed's Meds":                        710,
    "Vending Dust Ellie's: Ammo Dump":                         711,
    "Vending SouthernShelf Hammerlock's: Guns":                712,
    "Vending SouthernShelf Liar's: Ammo Dump":                 713,
    "Vending SouthernShelf Liar's: Zed's Meds":                714,
    "Vending SouthernShelf Safehouse: Zed's Meds":             715,
    "Vending SouthernShelf Dragon: Zed's Meds":                716,
    "Vending SouthernShelf Dragon: Ammo Dump":                 717,
    "Vending SouthernShelfBay Spawn: Ammo Dump":               718,
    "Vending SouthernShelfBay Spawn: Zed's Meds":              719,
    "Vending SouthernShelfBay Cove: Guns":                     720,
    "Vending SouthernShelfBay Cove: Ammo Dump":                721,
    "Vending SouthernShelfBay Cove: Zed's Meds":               722,
    "Vending ThreeHornsDivide Jump: Ammo Dump":                723,
    "Vending ThreeHornsDivide Jump: Zed's Meds":               724,
    "Vending ThreeHornsDivide Crossroads: Guns":               725,
    "Vending ThreeHornsDivide Crossroads: Ammo Dump":          726,
    "Vending ThreeHornsDivide Crossroads: Zed's Meds":         727,
    "Vending ThreeHornsValley Motel: Guns":                    728,
    "Vending ThreeHornsValley Motel: Ammo Dump":               729,
    "Vending ThreeHornsValley Motel: Zed's Meds":              730,
    "Vending Southpaw: Ammo Dump":                             731,
    "Vending Southpaw: Zed's Meds":                            732,
    "Vending Frostburn Spawn: Ammo Dump":                      733,
    "Vending Frostburn Spawn: Zed's Meds":                     734,
    "Vending Frostburn Firehawk: Ammo Dump":                   735,
    "Vending Frostburn Firehawk: Zed's Meds":                  736,
    "Vending Stronghold: Ammo Dump":                           737,
    "Vending Stronghold: Zed's Meds":                          738,
    "Vending Ramparts: Ammo Dump":                             739,
    "Vending Ramparts: Zed's Meds":                            740,
    "Vending Tundra Spawn: Ammo Dump":                         741,
    "Vending Tundra Spawn: Zed's Meds":                        742,
    "Vending Tundra Farm: Guns":                               743,
    "Vending Tundra Tina: Ammo Dump":                          744,
    "Vending EndOfTheLine: Ammo Dump":                         745,
    "Vending EndOfTheLine: Zed's Meds":                        746,
    "Vending Fridge Spawn: Ammo Dump":                         747,
    "Vending Fridge Spawn: Zed's Meds":                        748,
    "Vending Fridge Elevator: Ammo Dump":                      749,
    "Vending Fridge Elevator: Zed's Meds":                     750,
    "Vending Fink's: Guns":                                    751,
    "Vending Fink's: Ammo Dump":                               752,
    "Vending Fink's: Zed's Meds":                              753,
    "Vending Outwash: Ammo Dump":                              754,
    "Vending Outwash: Zed's Meds":                             755,
    "Vending Highlands Bridge: Ammo Dump":                     756,
    "Vending Highlands Bridge: Zed's Meds":                    757,
    "Vending Highlands Overlook: Guns":                        758,
    "Vending Highlands Overlook: Ammo Dump":                   759,
    # "Vending Highlands Overlook: Zed's Meds":                  760,
    # "Vending Extraction Plant: Zed's Meds":                    761,
    # "Vending Hyperion Bridge: Zed's Meds":                     762,
    "Vending HolySpirits: Guns":                               763,
    "Vending HolySpirits: Ammo Dump":                          764,
    "Vending HolySpirits: Zed's Meds":                         765,
    "Vending Dust Speedway: Ammo Dump":                        766,
    "Vending Dust Speedway: Zed's Meds":                       767,
    "Vending Dust Steve: Ammo Dump":                           768,
    "Vending Dust Steve: Zed's Meds":                          769,
    "Vending SanctuaryHole: Ammo Dump":                        770,
    "Vending SanctuaryHole: Zed's Meds":                       771,
    "Vending Caverns Spawn: Ammo Dump":                        772,
    "Vending Caverns Spawn: Zed's Meds":                       773,
    "Vending Caverns Shortcut: Guns":                          774,
    "Vending Preserve Spawn: Ammo Dump":                       775,
    "Vending Preserve Spawn: Zed's Meds":                      776,
    "Vending Preserve Halfway: Ammo Dump":                     777,
    "Vending Preserve Halfway: Zed's Meds":                    778,
    "Vending Creature: Ammo Dump":                             779,
    "Vending Creature: Zed's Meds":                            780,
    "Vending Thousand: Ammo Dump":                             781,
    "Vending Thousand: Zed's Meds":                            782,
    "Vending Lynchwood Spawn: Ammo Dump":                      783,
    "Vending Lynchwood Spawn: Zed's Meds":                     784,
    "Vending Lynchwood Gunslinger: Guns":                      785,
    "Vending Opportunity Spawn: Guns":                         786,
    "Vending Opportunity Spawn: Ammo Dump":                    787,
    "Vending Opportunity Spawn: Zed's Meds":                   788,
    "Vending Opportunity Office: Ammo Dump":                   789,
    "Vending Opportunity Office: Zed's Meds":                  790,
    "Vending Opportunity Square: Ammo Dump":                   791,
    "Vending Opportunity Square: Zed's Meds":                  792,
    "Vending Opportunity Residential: Guns":                   793,
    "Vending Opportunity Residential: Ammo Dump":              794,
    "Vending Bunker: Ammo Dump":                               795,
    "Vending Bunker: Zed's Meds":                              796,
    "Vending Blight Spawn: Ammo Dump":                         797,
    "Vending Blight Spawn: Zed's Meds":                        798,
    "Vending Blight Extraction: Ammo Dump":                    799,
    "Vending Blight Extraction: Zed's Meds":                   800,
    "Vending Blight Refinery: Guns":                           801,
    "Vending Blight Refinery: Ammo Dump":                      802,
    "Vending Blight Refinery: Zed's Meds":                     803,
    "Vending OreChasm: Guns":                                 804,
    "Vending OreChasm: Ammo Dump":                            805,
    "Vending OreChasm: Zed's Meds":                           806,
    "Vending Sawtooth Spawn: Ammo Dump":                       807,
    "Vending Sawtooth Spawn: Zed's Meds":                      808,
    "Vending Sawtooth Elevator: Ammo Dump":                    809,
    "Vending Boneyard Spawn: Ammo Dump":                       810,
    "Vending Boneyard Spawn: Zed's Meds":                      811,
    "Vending Badlands Fyrestone: Ammo Dump":                   812,
    "Vending Badlands Fyrestone: Zed's Meds":                  813,
    "Vending Badlands Baha: Guns":                             814,
    "Vending HerosPass Spawn: Ammo Dump":                      815,
    "Vending HerosPass Spawn: Zed's Meds":                     816,
    "Vending Warrior: Ammo Dump":                              817,
    "Vending Warrior: Zed's Meds":                             818,
    "Vending Terramorphous: Guns":                             819,
    "Vending Terramorphous: Ammo Dump":                        820,
    "Vending Terramorphous: Zed's Meds":                       821,
    # "Vending Oasis Town: Seraph Vendor":                       822,
    "Vending Oasis Town: Guns":                                823,
    "Vending Oasis Town: Ammo Dump":                           824,
    "Vending Oasis Town: Zed's Meds":                          825,
    "Vending Wurmwater Oasis Door: Ammo Dump":                 826,
    "Vending Wurmwater Oasis Door: Zed's Meds":                827,
    "Vending Wurmwater Canyon: Guns":                          828,
    "Vending Wurmwater Canyon: Ammo Dump":                     829,
    "Vending Wurmwater Fen: Ammo Dump":                        830,
    "Vending Wurmwater Ship: Guns":                            831,
    "Vending Wurmwater Ship: Ammo Dump":                       832,
    "Vending Wurmwater Ship: Zed's Meds":                      833,
    "Vending Wurmwater Rustyard: Guns":                        834,
    "Vending Hayters Spawn: Guns":                             835,
    "Vending Hayters Spawn: Ammo Dump":                        836,
    "Vending Hayters Spawn: Zed's Meds":                       837,
    "Vending Hayters Gee: Ammo Dump":                          838,
    "Vending Hayters Gee: Zed's Meds":                         839,
    "Vending Rustyards Spawn: Ammo Dump":                      840,
    "Vending Rustyards Spawn: Zed's Meds":                     841,
    "Vending Washburne Spawn: Ammo Dump":                      842,
    "Vending Washburne Spawn: Zed's Meds":                     843,
    "Vending Washburne Hyperius: Ammo Dump":                   844,
    "Vending Washburne Hyperius: Zed's Meds":                  845,
    "Vending Magnys Spawn: Ammo Dump":                         846,
    "Vending Magnys Spawn: Zed's Meds":                        847,
    "Vending Leviathan Body: Ammo Dump":                       848,
    "Vending Leviathan Body: Zed's Meds":                      849,
    "Vending Leviathan Lair: Ammo Dump":                       850,
    "Vending Leviathan Lair: Zed's Meds":                      851,
    "Vending Crater Spawn: Ammo Dump":                         852,
    "Vending Crater Spawn: Zed's Meds":                        853,
    # "Vending Crater Town: Seraph Vendor":                      854,
    "Vending Crater Town: Ammo Dump":                          855,
    "Vending Crater Town: Zed's Meds":                         856,
    "Vending Crater Forge: Torgue Vendor":                     857,
    "Vending Crater Forge: Ammo Dump":                         858,
    "Vending Crater Forge: Zed's Meds":                        859,
    "Vending Arena Inner: Torgue Vendor":                      860,
    "Vending Arena Inner: Ammo Dump":                          861,
    "Vending Arena Inner: Zed's Meds":                         862,
    "Vending Beatdown Spawn: Torgue Vendor":                   863,
    "Vending Beatdown Spawn: Ammo Dump":                       864,
    "Vending Beatdown Spawn: Zed's Meds":                      865,
    "Vending Beatdown Underpass: Torgue Vendor":               866,
    "Vending Beatdown Underpass: Ammo Dump":                   867,
    "Vending Beatdown Underpass: Zed's Meds":                  868,
    "Vending Pete's: Torgue Vendor":                           869,
    "Vending Pete's: Ammo Dump":                               870,
    "Vending Pete's: Zed's Meds":                              871,
    "Vending BadassBar: Torgue Vendor":                       872,
    "Vending BadassBar: Ammo Dump":                           873,
    "Vending BadassBar: Zed's Meds":                          874,
    "Vending Raceway: Torgue Vendor":                          875,
    "Vending Raceway: Ammo Dump":                              876,
    "Vending Raceway: Zed's Meds":                             877,
    "Vending Forge Spawn: Torgue Vendor":                      878,
    "Vending Forge Spawn: Ammo Dump":                          879,
    "Vending Forge Spawn: Zed's Meds":                         880,
    "Vending Forge Flyboy: Ammo Dump":                         881,
    "Vending Forge Flyboy: Zed's Meds":                        882,
    # "Vending Grotto Lodge: Seraph Vendor":                     883,
    "Vending Grotto Lodge: Guns":                              884,
    "Vending Grotto Lodge: Ammo Dump":                         885,
    "Vending Grotto Lodge: Zed's Meds":                        886,
    "Vending Scylla's Entrance: Guns":                         887,
    "Vending Scylla's Entrance: Ammo Dump":                    888,
    "Vending Scylla's Entrance: Zed's Meds":                   889,
    "Vending Scylla's Pukey: Zed's Meds":                      890,
    "Vending Ardorton Entrance: Ammo Dump":                    891,
    "Vending Ardorton Entrance: Zed's Meds":                   892,
    "Vending Ardorton Exit: Ammo Dump":                        893,
    "Vending Ardorton Exit: Zed's Meds":                       894,
    "Vending Crag Spawn: Ammo Dump":                           895,
    "Vending Crag Spawn: Zed's Meds":                          896,
    "Vending Crag Voracidous: Ammo Dump":                      897,
    "Vending Crag Voracidous: Zed's Meds":                     898,
    "Vending Terminus Entrance: Ammo Dump":                    899,
    "Vending Terminus Entrance: Zed's Meds":                   900,
    # "Vending Flamerock Refuge: Seraph Vendor":                 901,
    "Vending Flamerock Refuge: Guns/Cannons":                  902,
    "Vending Flamerock Refuge: Ammo Dump/Missiles":            903,
    "Vending Flamerock Refuge: Zed's Apothecary":              904,
    "Vending Forest Spawn: Ammo Dump/Missiles":                905,
    "Vending Forest Spawn: Zed's Apothecary":                  906,
    "Vending Immortal Spawn: Ammo Dump/Missiles":              907,
    "Vending Immortal Spawn: Zed's Apothecary":                908,
    "Vending Immortal Vitality Grove: Ammo Dump/Missiles":     909,
    "Vending Immortal Vitality Grove: Zed's Apothecary":       910,
    "Vending Avarice Spawn: Ammo Dump/Missiles":               911,
    "Vending Avarice Spawn: Zed's Apothecary":                 912,
    "Vending Avarice Greedtooth: Ammo Dump/Missiles":          913,
    "Vending Avarice Greedtooth: Zed's Apothecary":            914,
    "Vending Shadow Spawn: Ammo Dump/Missiles":                915,
    "Vending Shadow Spawn: Zed's Apothecary":                  916,
    "Vending Handsome Bridge: Guns/Cannons":                   917,
    "Vending Handsome Bridge: Ammo Dump/Missiles":             918,
    "Vending Handsome Bridge: Zed's Apothecary":               919,
    "Vending Agony Spawn: Ammo Dump/Missiles":                 920,
    "Vending Agony Spawn: Zed's Apothecary":                   921,
    "Vending Agony Daughter: Ammo Dump/Missiles":              922,
    "Vending Agony Daughter: Zed's Apothecary":                923,
    # "Vending Agony Hall of the Dead: Mr. Miz":                 924,
    "Vending DragonKeep: Ammo Dump/Missiles":                  925,
    "Vending DragonKeep: Zed's Apothecary":                    926,
    "Vending WingedStorm: Guns/Cannons":                       927,
    "Vending WingedStorm: Ammo Dump/Missiles":                 928,
    "Vending WingedStorm: Zed's Apothecary":                   929,
    "Vending Murderlin's Temple: Guns/Cannons":                930,
    "Vending Murderlin's Temple: Ammo Dump/Missiles":          931,
    "Vending Murderlin's Temple: Zed's Apothecary":            932,
    "Vending HallowedHollow Entrance: Ammo Dump":              933,
    "Vending HallowedHollow Entrance: Zed's Meds":             934,
    "Vending HallowedHollow Kingpin Approach: Zed's Meds":     935,
    "Vending HallowedHollow Kingpin Approach: Ammo Dump":      936,
    "Vending GlutGulch Entrance: Guns":                        937,
    "Vending GlutGulch Entrance: Ammo Dump":                   938,
    "Vending GlutGulch Entrance: Zed's Meds":                  939,
    "Vending GlutGulch Kitchen: Ammo Dump":                    940,
    "Vending GlutGulch Stabber Jabber: Guns":                  941,
    "Vending GlutGulch Tribute Station: Guns":                 942,
    "Vending GlutGulch Tribute Station: Zed's Meds":           943,
    "Vending GlutGulch Tribute Station: Ammo Dump":            944,
    "Vending MercenaryDay Entrance: Guns":                     945,
    "Vending MercenaryDay Entrance: Ammo Dump":                946,
    "Vending MercenaryDay Entrance: Zed's Meds":               947,
    "Vending MercenaryDay Tinder Arena: Zed's Meds":           948,
    "Vending MercenaryDay Tinder Arena: Ammo Dump":            949,
    "Vending Distillery Entrance: Zed's Meds":                 950,
    "Vending Distillery Entrance: Ammo Dump":                  951,
    "Vending Distillery Pot of Gold: Ammo Dump":               952,
    "Vending Distillery Wedding Venue: Zed's Meds":            953,
    "Vending Distillery Wedding Venue: Ammo Dump":             954,
    "Vending WamBam Entrance: Ammo Dump":                      955,
    "Vending WamBam Entrance: Zed's Meds":                     956,
    "Vending WamBam Water Wheel: Zed's Meds":                  957,
    "Vending WamBam Water Wheel: Ammo Dump":                   958,
    "Vending WamBam Son's Arena: Ammo Dump":                   959,
    "Vending WamBam Son's Arena: Zed's Meds":                  960,
    "Vending Backburner Entrance: Ammo Dump":                  961,
    "Vending Backburner Entrance: Zed's Meds":                 962,
    "Vending Backburner Vaughn's HQ: Guns":                    963,
    "Vending Backburner Vaughn's HQ: Ammo Dump":               964,
    "Vending Backburner Vaughn's HQ: Zed's Meds":              965,
    "Vending Backburner Marcus: Guns":                         966,
    "Vending Backburner Marcus: Ammo Dump":                    967,
    "Vending DahlAbandon Entrance: Ammo dump":                 968,
    "Vending DahlAbandon Entrance: Zed's Meds":                969,
    "Vending DahlAbandon Mine Door: Ammo Dump":                970,
    "Vending DahlAbandon Mine Door: Zed's Meds":               971,
    "Vending Burrows Entrance: Ammo Dump":                     972,
    "Vending Burrows Entrance: Zed's Meds":                    973,
    "Vending HeliosFallen Entrance: Ammo Dump":                974,
    "Vending HeliosFallen Entrance: Zed's Meds":               975,
    "Vending HeliosFallen Munitions Loading: Ammo Dump":       976,
    "Vending HeliosFallen Munitions Loading: Zed's Meds":      977,
    "Vending HeliosFallen The Arsenal: Ammo Dump":             978,
    "Vending HeliosFallen The Arsenal: Zed's Meds":            979,
    "Vending Mt.Scarab Entrance: Ammo Dump":                   980,
    "Vending Mt.Scarab Entrance: Zed's Meds":                  981,
    "Vending Mt.Scarab Observation Deck: Ammo Dump":           982,
    "Vending Mt.Scarab Observation Deck: Zed's Meds":          983,
    # "Vending Paradise Sanctum Entrance: Ammo Dump":            984,
    # "Vending Paradise Sanctum Entrance: Zed's Meds":           985,
    # "Vending Paradise Sanctum Marcus Munitions: Guns":         986,
    # "Vending Paradise Sanctum Marcus Munitions: Zed's Meds":   987,
    # "Vending Paradise Sanctum Hector: Ammo Dump":              988,
    # "Vending Paradise Sanctum Hector: Zed's Meds":             989,
    "Vending WrithingDeep: Ammo Dump":                         990,
    "Vending WrithingDeep: Zed's Meds":                        991,
    "Vending Digistruct Spawn: Guns":                          992,
    "Vending Digistruct Spawn: Ammo Dump":                     993,
    "Vending Digistruct Spawn: Zed's Meds":                    994,
    "Vending DigistructInner Butcher Base: Ammo Dump":              995,
    # "Vending DigistructInner Area of Anguish: Ammo Dump":           996,
    # "Vending DigistructInner Area of Anguish: Zed's Meds":          997,
    # "Vending DigistructInner Tower of Torment: Ammo Dump":          998,
}


item_name_to_id = {
    "3 Skill Points":                     1,
    "Progressive Money Cap":              2,
    "Weapon Slot":                        3,
    "$100":                               4,
    "10 Eridium":                         5,

    "Progressive Jump":                   6,
    "Melee":                              7,
    "Crouch":                             8,
    "Sprint":                             9,
    "Gear Leveler":                      10,
    "Vehicle Fire":                      11,

    # Map Areas
    # "Travel: Windshear Waste":                     301,
    "Travel: Arid Nexus Boneyard":                 302,
    "Travel: The Holy Spirits":                    303,
    "Travel: Southpaw Steam & Power":              304,
    "Travel: Sanctuary Hole":                      305,
    "Travel: Hero's Pass":                         306,
    "Travel: Bloodshot Stronghold":                307,
    "Travel: Three Horns Valley":                  308,
    "Travel: Sanctuary":                           309,
    "Travel: Thousand Cuts":                       310,
    "Travel: End of the Line":                     311,
    "Travel: Wildlife Exploitation Preserve":      312,
    "Travel: Terramorphous Peak":                  313,
    "Travel: Tundra Express":                      314,
    "Travel: The Fridge":                          315,
    "Travel: Fink's Slaughterhouse":               316,
    "Travel: Southern Shelf Bay":                  317,
    "Travel: Frostburn Canyon":                    318,
    "Travel: Three Horns Divide":                  319,
    "Travel: Highlands":                           320,
    "Travel: Natural Selection Annex":             321,
    "Travel: The Dust":                            322,
    "Travel: Friendship Gulag":                    323,
    "Travel: Opportunity":                         324,
    "Travel: Bloodshot Ramparts":                  325,
    "Travel: Arid Nexus Badlands":                 326,
    "Travel: Southern Shelf":                      327,
    "Travel: Highlands Outwash":                   328,
    "Travel: Caustic Caverns":                     329,
    "Travel: Lynchwood":                           330,
    "Travel: Sawtooth Cauldron":                   331,
    "Travel: Ore Chasm":                           332,
    "Travel: The Bunker":                          333,
    "Travel: Control Core Angel":                  334,
    "Travel: Vault of the Warrior":                335,
    "Travel: Eridium Blight":                      336,
    "Travel: Glutton Gulch":                       337,
    "Travel: Marcus's Mercenary Shop":             338,
    "Travel: Helios Fallen":                       339,
    "Travel: FFS Boss Fight":                      340,
    "Travel: The Backburner":                      341,
    "Travel: FFS Intro Sanctuary":                 342,
    "Travel: Dahl Abandon":                        343,
    "Travel: Mt. Scarab Research Center":          344,
    "Travel: The Burrows":                         345,
    "Travel: Writhing Deep":                       346,
    "Travel: The Forest":                          347,
    "Travel: Immortal Woods":                      348,
    "Travel: Dragon Keep":                         349,
    "Travel: Unassuming Docks":                    350,
    "Travel: Flamerock Refuge":                    351,
    "Travel: Hatred's Shadow":                     352,
    "Travel: Lair of Infinite Agony":              353,
    "Travel: Murderlin's Temple":                  354,
    "Travel: Mines of Avarice":                    355,
    "Travel: The Winged Storm":                    356,
    "Travel: Hallowed Hollow":                     357,
    "Travel: Torgue Arena Ring":                   358,
    "Travel: Torgue Arena":                        359,
    "Travel: The Beatdown":                        360,
    "Travel: The Forge":                           361,
    "Travel: Badass Crater":                       362,
    "Travel: Southern Raceway":                    363,
    "Travel: Pyro Pete's Bar":                     364,
    "Travel: Baddass Crater Bar":                  365,
    "Travel: Digistruct Peak":                     366,
    "Travel: Wam Bam Island":                      367,
    "Travel: Rotgut Distillery":                   368,
    "Travel: The Leviathan's Lair":                369,
    "Travel: Washburne Refinery":                  370,
    "Travel: Wurmwater":                           371,
    "Travel: Magnys Lighthouse":                   372,
    "Travel: The Rustyards":                       373,
    "Travel: Haytor's Folly":                      374,
    "Travel: Oasis":                               375,
    "Travel: Ardorton Station":                    376,
    "Travel: Hunter's Grotto":                     377,
    "Travel: Candlerakk's Cragg":                  378,
    "Travel: Terminus":                            379,
    "Travel: Scylla's Grove":                      380,

    # Traps
    "Trap Spawn: Saturn":                     400,
    "Trap Spawn: Black Queen":                401,
    "Trap Spawn: Assassins":                  402,
    "Trap Spawn: Dukino's Mom":               403,
    "Trap Spawn: Doc Mercy":                  404,
    "Trap Spawn: Creeper":                    405,
}

# stitch dictionaries together

loc_name_to_id.update(gear_kind_to_id)
loc_name_to_id.update(level_name_to_id)

item_name_to_id.update(gear_kind_to_id)

loc_id_to_name = {id: name for name, id in loc_name_to_id.items()}
item_id_to_name = {id: name for name, id in item_name_to_id.items()}
