# This file is intended to be shared between the Archipelago Client/World and the Game sdkmod.
# I don't expect to be able to have one source of truth distributed to both, so just keep the two files in sync.


level_name_to_id = {
    # 2 through 80
    "Level " + str(i) : i for i in range(2, 81)
}

gear_kind_to_id = {
    # Gear
    "Common Shield":                    100,
    "Uncommon Shield":                  101,
    "Rare Shield":                      102,
    "VeryRare Shield":                  103,
    # "E-Tech Shield":                    104,
    "Legendary Shield":                 105,
    # "Seraph Shield":                    106,
    # "Rainbow Shield":                   107,
    # "Pearlescent Shield":               108,
    # "Unique Shield":                    109,

    "Common GrenadeMod":                110,
    "Uncommon GrenadeMod":              111,
    "Rare GrenadeMod":                  112,
    "VeryRare GrenadeMod":              113,
    # "E-Tech GrenadeMod":                114,
    "Legendary GrenadeMod":             115,
    # "Seraph GrenadeMod":                116,
    # "Rainbow GrenadeMod":               117,
    # "Pearlescent GrenadeMod":           118,
    # "Unique GrenadeMod":                119,

    "Common ClassMod":                  120,
    "Uncommon ClassMod":                121,
    "Rare ClassMod":                    122,
    "VeryRare ClassMod":                123,
    # "E-Tech ClassMod":                  124,
    "Legendary ClassMod":               125,
    # "Seraph ClassMod":                  126,
    # "Rainbow ClassMod":                 127,
    # "Pearlescent ClassMod":             128,
    # "Unique ClassMod":                  129,

    "Common Relic":                     130,
    "Uncommon Relic":                   131,
    "Rare Relic":                       132,
    "VeryRare Relic":                   133,
    # "E-Tech Relic":                     134,
    # "Legendary Relic":                  135,
    # "Seraph Relic":                     136,
    # "Rainbow Relic":                    137,
    # "Pearlescent Relic":                138,
    # "Unique Relic":                     139,

    "Common Pistol":                    140,
    "Uncommon Pistol":                  141,
    "Rare Pistol":                      142,
    "VeryRare Pistol":                  143,
    "E-Tech Pistol":                    144,
    "Legendary Pistol":                 145,
    # "Seraph Pistol":                    146,
    # "Rainbow Pistol":                   147,
    # "Pearlescent Pistol":               148,
    "Unique Pistol":                    149,

    "Common Shotgun":                   150,
    "Uncommon Shotgun":                 151,
    "Rare Shotgun":                     152,
    "VeryRare Shotgun":                 153,
    "E-Tech Shotgun":                   154,
    "Legendary Shotgun":                155,
    # "Seraph Shotgun":                   156,
    # "Rainbow Shotgun":                  157,
    # "Pearlescent Shotgun":              158,
    "Unique Shotgun":                   159,

    "Common SMG":                       160,
    "Uncommon SMG":                     161,
    "Rare SMG":                         162,
    "VeryRare SMG":                     163,
    "E-Tech SMG":                       164,
    "Legendary SMG":                    165,
    # "Seraph SMG":                       166,
    # "Rainbow SMG":                      167,
    # "Pearlescent SMG":                  168,
    "Unique SMG":                       169,

    "Common SniperRifle":               170,
    "Uncommon SniperRifle":             171,
    "Rare SniperRifle":                 172,
    "VeryRare SniperRifle":             173,
    "E-Tech SniperRifle":               174,
    "Legendary SniperRifle":            175,
    # "Seraph SniperRifle":               176,
    # "Rainbow SniperRifle":              177,
    # "Pearlescent SniperRifle":          178,
    "Unique SniperRifle":               179,

    "Common AssaultRifle":              180,
    "Uncommon AssaultRifle":            181,
    "Rare AssaultRifle":                182,
    "VeryRare AssaultRifle":            183,
    "E-Tech AssaultRifle":              184,
    "Legendary AssaultRifle":           185,
    # "Seraph AssaultRifle":              186,
    # "Rainbow AssaultRifle":             187,
    # "Pearlescent AssaultRifle":         188,
    "Unique AssaultRifle":              189,

    "Common RocketLauncher":            190,
    "Uncommon RocketLauncher":          191,
    "Rare RocketLauncher":              192,
    "VeryRare RocketLauncher":          193,
    "E-Tech RocketLauncher":            194,
    "Legendary RocketLauncher":         195,
    # "Seraph RocketLauncher":            196,
    # "Rainbow RocketLauncher":           197,
    # "Pearlescent RocketLauncher":       198,
    "Unique RocketLauncher":            199,
}

loc_name_to_id = {

    # Enemies
    "Knuckle Dragger":                   301,
    "Midgemong":                         302,
    "Boom Bewm":                         303,
    "Captain Flynt":                     304,
    "Savage Lee":                        305,
    "Boll":                              306,
    "Doc Mercy":                         307,
    "Assassin Oney":                     308,
    "Assassin Wot":                      309,
    "Assassin Reeth":                    310,
    "Assassin Rouf":                     311,
    "Scorch":                            312,
    "Incinerator Clayton":               313,
    "Gettle":                            314,
    "Mobley":                            315,
    "Black Queen":                       316,
    "Bad Maw":                           317,
    "Mad Mike":                          318,
    "W4R-D3N":                           319,
    "Spycho":                            320,
    "McNally":                           321,
    "Mick/Tector":                       322,
    "Dan":                               323,
    "Lee":                               324,
    "Mick":                              325,
    "Ralph":                             326,
    "Flinter":                           327,
    "MadameVonBartlesby":                328,
    "Wilhelm":                           329,
    "LaneyWhite":                        330,
    "Rakkman":                           331,
    "SmashHead":                         332,
    "Sinkhole":                          333,
    "OldSlappy":                         334,
    "GluttonousThresher":                325,
    "Henry":                             336,
    "Blue":                              337,
    "BadassCreeper":                     338,
    "Tumbaa":                            339,
    "Pimon":                             340,
    "SonOfMothrakk":                     341,
    # "Bloodwing":                         342,
    # "GOD-liath":                         343,
    "DukinosMom":                        344,
    "MadDog":                            345,
    "SheriffNisha":                      346,
    "DeputyWinger":                      347,
    "ForemanJasper":                     348,
    "JackBodyDouble":                    349,
    # "BNK-3R":                            350,
    "KingMong":                          351,
    "DonkeyMong":                        352,
    "Mortar":                            353,
    "HunterHellquist":                   354,
    "BoneHead":                          355,
    "Saturn":                            356,
    # "Warrior":                           357,

    # Vault Symbols
    "Symbol Sanctuary: Rooftop":                            501,
    "Symbol Sanctuary: Moxxi's Corner":                     502,
    "Symbol Sanctuary: Trash Corner":                       503,
    "Symbol Sanctuary: Tire Corner":                        504,
    "Symbol Sanctuary: Parkour Door":                       505,
    "Symbol EridiumBlight: Hellsfont Crate":                506,
    "Symbol EridiumBlight: Stairs Door":                    507,
    "Symbol EridiumBlight: Refund Building":                508,
    "Symbol Fink's: Column":                                509,
    "Symbol Bunker: Backside":                              510,
    "Symbol WarriorVault: Elevator Bottom":                 511,
    "Symbol SouthernShelfBay: Blackburn Cove Corner":       512,
    "Symbol SouthernShelfBay: Ice Flows Shipwreck":         513,
    "Symbol Sawtooth: Refinery Container":                  514,
    "Symbol Sawtooth: Elevator":                            515,
    "Symbol CreatureSlaughter: Crate Ceiling":              516,
    "Symbol HerosPass: Strut":                              517,
    "Symbol HerosPass: Spawn":                              518,
    "Symbol Fridge: Secret Stash":                          519,
    "Symbol Fridge: Sheetmetal Roof":                       520,
    "Symbol ThreeHornsValley: Slums Wall":                  521,
    "Symbol ThreeHornsValley: Frostsprings Wall":           522,
    "Symbol ThreeHornsValley: Frostsprings Shack":          523,
    "Symbol AridNexusBoneyard: Pipe":                       524,
    "Symbol AridNexusBoneyard: Safety":                     525,
    "Symbol WindshearWaste: Claptrap's Closet":             526,
    "Symbol ThousandCuts: Buzzard Factory":                 527,
    "Symbol ThousandCuts: No Man's Land Shack":             528,
    "Symbol Lynchwood: Gunslinger Roof":                    529,
    "Symbol Lynchwood: Main Street":                        530,
    "Symbol Highlands: Highlands Tower":                    531,
    "Symbol FriendshipGulag: Gulag Container":              532,
    "Symbol Opportunity: Construction Site":                533,
    "Symbol Opportunity: Office Bridge":                    534,
    "Symbol ThreeHornsDivide Drydocks Corner":              535,
    "Symbol ThreeHornsDivide Billboard":                    536,
    "Symbol ThreeHornsDivide Windbreak Wall":               537,
    "Symbol Dust: 26":                                      538,
    "Symbol Dust: 4":                                       539,
    "Symbol Dust: 5":                                       540,
    "Symbol CausticCaverns: Gravestone Feature":            541,
    "Symbol CausticCaverns: Bloody Ladder":                 542,
    "Symbol Blodshot: Pizza Intercom":                      543,
    "Symbol Blodshot: Switch Room":                         544,
    "Symbol BlodshotRamparts: Ramp":                        545,
    "Symbol Frostburn: Blisterpus Cave":                    546,
    "Symbol Frostburn: Ashmouth Pit":                       547,
    "Symbol TorgueArenaRing: 678":                          548,
    "Symbol TorgueArenaRing: 772":                          549,
    "Symbol Beatdown: 425":                                 550,
    "Symbol Beatdown: 79":                                  551,
    "Symbol Forge: 214":                                    552,
    "Symbol Forge: 425":                                    553,
    "Symbol Forge: 61":                                     554,
    "Symbol SouthernRaceway: 6":                            555,
    "Symbol SouthernRaceway: 9":                            556,
    "Symbol BadassCrater: 11":                              557,
    "Symbol BadassCrater: 12":                              558,
    "Symbol BadassCrater: 678":                             559,
    "Symbol BadassCrater: 78":                              560,
    "Symbol HolySpirits: Bathroom":                         561,
    "Symbol HaytorsFolly: 347":                             562,
    "Symbol HaytorsFolly: 461":                             563,
    "Symbol Oasis: 347":                                    564,
    "Symbol Oasis: 348":                                    565,
    "Symbol Oasis: 349":                                    566,
    "Symbol Oasis: 367":                                    567,
    "Symbol WashburnRefinery: 496":                         568,
    "Symbol WashburnRefinery: 497":                         569,
    "Symbol Wurmwater: 347":                                570,
    "Symbol Wurmwater: 400":                                571,
    "Symbol Wurmwater: 401":                                572,
    "Symbol Rustyards: 22":                                 573,
    "Symbol Rustyards: 23":                                 574,
    "Symbol MagnysLighthouse: 10":                          575,
    "Symbol MagnysLighthouse: 22":                          576,
    "Symbol LeviathansLair: 497":                           577,
    "Symbol WildlifePreserve: 273":                         578,
    "Symbol WildlifePreserve: 274":                         579,
    "Symbol OreChasm: Elevator":                            580,
    "Symbol CandlerakksCragg: 129":                         581,
    "Symbol CandlerakksCragg: 71":                          582,
    "Symbol CandlerakksCragg: 84":                          583,
    "Symbol Terminus: 0":                                   584,
    "Symbol AdortonStation: 29":                            585,
    "Symbol AdortonStation: 5":                             586,
    "Symbol AdortonStation: 6":                             587,
    "Symbol AdortonStation: 7":                             588,
    "Symbol ScyllasGrove: 10":                              589,
    "Symbol ScyllasGrove: 6":                               590,
    "Symbol ScyllasGrove: 8":                               591,
    "Symbol ScyllasGrove: 9":                               592,
    "Symbol SanctuaryHole: Staircase Wall":                 593,
    "Symbol SouthernShelf: Flynt's Ship":                   594,
    "Symbol SouthernShelf: Safehouse":                      595,
    "Symbol Southpaw: 398":                                 596,
    "Symbol Southpaw: 399":                                 597,
    "Symbol Southpaw: 46":                                  598,
    "Symbol TerramorphousPeak: Dropdown":                   599,
    "Symbol TerramorphousPeak: Elevator":                   600,
    "Symbol EndOfTheLine: Wilhelm Wall":                    601,
    "Symbol TundraExpress: Fork Shack":                     602,
    "Symbol TundraExpress: Facility Roof":                  603,
    "Symbol Backburner: 2":                                 604,
    "Symbol Backburner: 3":                                 605,
    "Symbol HatredsShadow: 0":                              606,
    "Symbol HatredsShadow: 1":                              607,
    "Symbol HatredsShadow: 4":                              608,
    "Symbol DragonKeep: 0":                                 609,
    "Symbol TheForest: 0":                                  610,
    "Symbol TheForest: 1":                                  611,
    "Symbol ImmortalWoods: 1":                              612,
    "Symbol ImmortalWoods: 19":                             613,
    "Symbol ImmortalWoods: 20":                             614,
    "Symbol UnassumingDocks: 0":                            615,
    "Symbol UnassumingDocks: 1":                            616,
    "Symbol UnassumingDocks: 2":                            617,
    "Symbol WingedStorm: 0":                                618,
    "Symbol LairOfInfiniteAgony: 307":                      619,
    "Symbol LairOfInfiniteAgony: 308":                      620,
    "Symbol LairOfInfiniteAgony: 90":                       621,
    "Symbol HeliosFallen: 11":                              622,
    "Symbol HeliosFallen: 388":                             623,
    "Symbol HeliosFallen: 446":                             624,
    "Symbol HeliosFallen: 447":                             625,
    "Symbol HeliosFallen: 859":                             626,
    "Symbol HeliosFallen: 892":                             627,
    "Symbol HeliosFallen: 894":                             628,
    "Symbol MinesOfAvarice: 1":                             629,
    "Symbol MinesOfAvarice: 16":                            630,
    "Symbol MinesOfAvarice: 47":                            631,
    "Symbol DahlAbandon: 187":                              632,
    "Symbol DahlAbandon: 269":                              633,
    "Symbol DahlAbandon: 36":                               634,
    "Symbol DahlAbandon: 59":                               635,
    "Symbol DahlAbandon: 84":                               636,
    "Symbol MtScarab: 164":                                 637,
    "Symbol MtScarab: 167":                                 638,
    "Symbol MtScarab: 737":                                 639,
    "Symbol HuntersGrotto: 68":                             640,
    "Symbol HuntersGrotto: 69":                             641,
    "Symbol HuntersGrotto: 70":                             642,
    "Symbol HuntersGrotto: 71":                             643,
    "Symbol WrithingDeep: 1161":                            644,
    "Symbol WrithingDeep: 1162":                            645,
    "Symbol WrithingDeep: 1163":                            646,
    "Symbol TheBurrows: 46":                                647,
    "Symbol TheBurrows: 60":                                648,
    "Symbol MurderlinsTemple: 1":                           649,
    "Symbol MurderlinsTemple: 3":                           650,
    "Symbol FlamerockRefuge: 206":                          651,
    "Symbol FlamerockRefuge: 383":                          652,

    # Vending Machines
    "Vending Sanctuary Crimson Base: Guns":                 700,
    "Vending Sanctuary Crimson Base: Ammo Dump":            701,
    "Vending Sanctuary Zed's: Ammo Dump":                   702,
    "Vending Sanctuary Zed's: Zed's Meds 1":                703,
    "Vending Sanctuary Zed's: Zed's Meds 2":                704,
    "Vending Sanctuary Marcus's: Zed's Meds":               705,
    "Vending Sanctuary Marcus's: Ammo Dump":                706,
    "Vending Sanctuary Marcus's: Marcus":                   707,
    "Vending FriendshipGulag: Zed's Meds":                  708,
    "Vending FriendshipGulag: Ammo Dump":                   709,
    "Vending Dust: Zed's Meds":                             710,
    "Vending Dust: Ammo Dump":                              711,
    "Vending Shelf Hammerlock's: Guns":                     712,
    "Vending Shelf Liar's: Ammo Dump":                      713,
    "Vending Shelf Liar's: Zed's Meds":                     714,
    "Vending Shelf Safehouse: Zed's Meds":                  715,
    "Vending Shelf Dragon: Zed's Meds":                     716,
    "Vending Shelf Dragon: Ammo Dump":                      717,
    "Vending Bay Spawn: Ammo Dump":                         718,
    "Vending Bay Spawn: Zed's Meds":                        719,
    "Vending Bay Cove: Guns":                               720,
    "Vending Bay Cove: Ammo Dump":                          721,
    "Vending Bay Cove: Zed's Meds":                         722,
    "Vending Divide Jump: Ammo Dump":                       723,
    "Vending Divide Jump: Zed's Meds":                      724,
    "Vending Divide Crossroads: Guns":                      725,
    "Vending Divide Crossroads: Ammo Dump":                 726,
    "Vending Divide Crossroads: Zed's Meds":                727,
    "Vending Valley Motel: Guns":                           728,
    "Vending Valley Motel: Ammo Dump":                      729,
    "Vending Valley Motel: Zed's Meds":                     730,
    "Vending Southpaw: Ammo Dump":                          731,
    "Vending Southpaw: Zed's Meds":                         732,
    "Vending Frostburn Spawn: Ammo Dump":                   733,
    "Vending Frostburn Spawn: Zed's Meds":                  734,
    "Vending Frostburn Firehawk: Ammo Dump":                735,
    "Vending Frostburn Firehawk: Zed's Meds":               736,
    "Vending Stronghold: Ammo Dump":                        737,
    "Vending Stronghold: Zed's Meds":                       738,
    "Vending Ramparts: Ammo Dump":                          739,
    "Vending Ramparts: Zed's Meds":                         740,
    "Vending Tundra Spawn: Ammo Dump":                      741,
    "Vending Tundra Spawn: Zed's Meds":                     742,
    "Vending Tundra Farm: Guns":                            743,
    "Vending Tundra Tina: Ammo Dump":                       744,
    "Vending End of the Line: Ammo Dump":                   745,
    "Vending End of the Line: Zed's Meds":                  746,
    "Vending Fridge Spawn: Ammo Dump":                      747,
    "Vending Fridge Spawn: Zed's Meds":                     748,
    "Vending Fridge Elevator: Ammo Dump":                   749,
    "Vending Fridge Elevator: Zed's Meds":                  750,
    "Vending Fink's: Guns":                                 751,
    "Vending Fink's: Ammo Dump":                            752,
    "Vending Fink's: Zed's Meds":                           753,
    "Vending Outwash: Ammo Dump":                           754,
    "Vending Outwash: Zed's Meds":                          755,
    "Vending Highlands Bridge: Ammo Dump":                  756,
    "Vending Highlands Bridge: Zed's Meds":                 757,
    "Vending Highlands Overlook: Guns":                     758,
    "Vending Highlands Overlook: Ammo Dump":                759,
}


item_name_to_id = {
    "3 Skill Points":                     1,
    "Progressive Money Cap":              2,
    "Weapon Slot":                        3,
    "$100":                               4,
    "10 Eridium":                         5,

    "Jump":                               6,
    "Melee":                              7,
    "Crouch":                             8,
    "Sprint":                             9,
    "Gear Leveler":                      10,
    "Vehicle Fire":                      11,
}

# stitch dictionaries together

loc_name_to_id.update(gear_kind_to_id)
loc_name_to_id.update(level_name_to_id)

item_name_to_id.update(gear_kind_to_id)

loc_id_to_name = {id: name for name, id in loc_name_to_id.items()}
item_id_to_name = {id: name for name, id in item_name_to_id.items()}
