from typing import Dict, List, NamedTuple


class Borderlands2RegionData(NamedTuple):
    name: str = ""
    travel_item_name: str = ""
    connecting_regions: List[str] = []


region_data_table: Dict[str, Borderlands2RegionData] = {
    "Menu": Borderlands2RegionData("Menu", "", [
        "WindshearWaste",
        # "FFSIntroSanctuary",
        # "UnassumingDocks",
        # "BadassCrater",
        # "Oasis",
        # "HuntersGrotto",
        # "DigistructPeak",
        # "MarcusMercenaryShop",
        # "GluttonGulch",
        # "RotgutDistillery",
        # "WamBamIsland",
        # "HallowedHollow",
    ]),

    "WindshearWaste": Borderlands2RegionData("WindshearWaste", "", ["Menu", "SouthernShelf"]),
    "SouthernShelf": Borderlands2RegionData("SouthernShelf", "Travel: Southern Shelf", ["WindshearWaste", "SouthernShelfBay", "ThreeHornsDivide"]),
    "SouthernShelfBay": Borderlands2RegionData("SouthernShelfBay", "Travel: Southern Shelf Bay", ["SouthernShelf"]),
    "ThreeHornsDivide": Borderlands2RegionData("ThreeHornsDivide", "Travel: Three Horns Divide", ["ThreeHornsValley", "BloodshotStronghold", "FrostburnCanyon", "Fridge", "Dust", "Sanctuary", "SanctuaryHole", "SouthpawSteam&Power", "TundraExpress", "SouthernShelf"]),
    "ThreeHornsValley": Borderlands2RegionData("ThreeHornsValley", "Travel: Three Horns Valley", ["ThreeHornsDivide"]),
    "Sanctuary": Borderlands2RegionData("Sanctuary", "Travel: Sanctuary", ["ControlCoreAngel", "ThreeHornsDivide"]),
    "FrostburnCanyon": Borderlands2RegionData("FrostburnCanyon", "Travel: Frostburn Canyon", ["ThreeHornsDivide"]),
    "SouthpawSteam&Power": Borderlands2RegionData("SouthpawSteam&Power", "Travel: Southpaw Steam & Power", ["ThreeHornsDivide"]),
    "Dust": Borderlands2RegionData("Dust", "Travel: The Dust", ["EridiumBlight", "FriendshipGulag", "ThreeHornsDivide", "Lynchwood", "Highlands", "BloodshotRamparts"]),
    "BloodshotStronghold": Borderlands2RegionData("BloodshotStronghold", "Travel: Bloodshot Stronghold", ["BloodshotRamparts", "ThreeHornsDivide"]),
    "BloodshotRamparts": Borderlands2RegionData("BloodshotRamparts", "Travel: Bloodshot Ramparts", ["BloodshotStronghold", "Dust"]),
    "HighlandsOutwash": Borderlands2RegionData("HighlandsOutwash", "Travel: Highlands Outwash", ["Highlands", "Fridge"]),
    "Highlands": Borderlands2RegionData("Highlands", "Travel: Highlands", ["HighlandsOutwash", "ThousandCuts", "Opportunity", "Fridge", "Dust", "HolySpirits", "WildlifeExploitationPreserve"]),
    "FriendshipGulag": Borderlands2RegionData("FriendshipGulag", "Travel: Friendship Gulag", ["Dust"]),
    "Lynchwood": Borderlands2RegionData("Lynchwood", "Travel: Lynchwood", ["Dust"]),
    "Fridge": Borderlands2RegionData("Fridge", "Travel: The Fridge", ["FinksSlaughterhouse", "Highlands", "ThreeHornsDivide"]),
    "FinksSlaughterhouse": Borderlands2RegionData("FinksSlaughterhouse", "Travel: Fink's Slaughterhouse", ["Fridge"]),
    "SawtoothCauldron": Borderlands2RegionData("SawtoothCauldron", "Travel: Sawtooth Cauldron", ["EridiumBlight"]),
    "SanctuaryHole": Borderlands2RegionData("SanctuaryHole", "Travel: Sanctuary Hole", ["CausticCaverns", "ThreeHornsDivide"]),
    "TerramorphousPeak": Borderlands2RegionData("TerramorphousPeak", "Travel: Terramorphous Peak", ["ThousandCuts"]),
    "CausticCaverns": Borderlands2RegionData("CausticCaverns", "Travel: Caustic Caverns", ["SanctuaryHole"]),
    "Opportunity": Borderlands2RegionData("Opportunity", "Travel: Opportunity", ["Highlands"]),
    "HolySpirits": Borderlands2RegionData("HolySpirits", "Travel: The Holy Spirits", ["Highlands"]),
    "WildlifeExploitationPreserve": Borderlands2RegionData("WildlifeExploitationPreserve", "Travel: Wildlife Exploitation Preserve", ["Highlands", "NaturalSelectionAnnex"]),
    "NaturalSelectionAnnex": Borderlands2RegionData("NaturalSelectionAnnex", "Travel: Natural Selection Annex", ["WildlifeExploitationPreserve"]),
    "TundraExpress": Borderlands2RegionData("TundraExpress", "Travel: Tundra Express", ["EndOfTheLine", "ThreeHornsDivide"]),
    "EndOfTheLine": Borderlands2RegionData("EndOfTheLine", "Travel: End of the Line", ["TundraExpress"]),
    "Bunker": Borderlands2RegionData("Bunker", "Travel: The Bunker", ["ThousandCuts", "ControlCoreAngel"]),
    "ThousandCuts": Borderlands2RegionData("ThousandCuts", "Travel: Thousand Cuts", ["Highlands", "TerramorphousPeak", "Bunker"]),
    "EridiumBlight": Borderlands2RegionData("EridiumBlight", "Travel: Eridium Blight", ["VaultOfTheWarrior", "Dust", "OreChasm", "AridNexusBoneyard", "SawtoothCauldron", "HerosPass"]),
    "OreChasm": Borderlands2RegionData("OreChasm", "Travel: Ore Chasm", ["EridiumBlight"]),
    "ControlCoreAngel": Borderlands2RegionData("ControlCoreAngel", "Travel: Control Core Angel", ["Sanctuary", "Bunker"]),
    "AridNexusBoneyard": Borderlands2RegionData("AridNexusBoneyard", "Travel: Arid Nexus Boneyard", ["AridNexusBadlands", "EridiumBlight"]),
    "AridNexusBadlands": Borderlands2RegionData("AridNexusBadlands", "Travel: Arid Nexus Badlands", ["AridNexusBoneyard"]),
    "HerosPass": Borderlands2RegionData("HerosPass", "Travel: Hero's Pass", ["EridiumBlight", "VaultOfTheWarrior"]),
    "VaultOfTheWarrior": Borderlands2RegionData("VaultOfTheWarrior", "Travel: Vault of the Warrior", ["EridiumBlight", "HerosPass"]),

    # "FFSIntroSanctuary": Borderlands2RegionData("FFSIntroSanctuary", "Travel: FFS Intro Sanctuary", ["Menu", "Backburner"]),
    # "Burrows": Borderlands2RegionData("Burrows", "Travel: The Burrows", ["WrithingDeep", "HeliosFallen", "DahlAbandon"]),
    # "Backburner": Borderlands2RegionData("Backburner", "Travel: The Backburner", ["DahlAbandon", "FFSIntroSanctuary"]),
    # "DahlAbandon": Borderlands2RegionData("DahlAbandon", "Travel: Dahl Abandon", ["Backburner", "HeliosFallen", "Burrows", "Mt.ScarabResearchCenter"]),
    # "HeliosFallen": Borderlands2RegionData("HeliosFallen", "Travel: Helios Fallen", ["Burrows"]),
    # "WrithingDeep": Borderlands2RegionData("WrithingDeep", "Travel: Writhing Deep", ["Burrows"]),
    # "Mt.ScarabResearchCenter": Borderlands2RegionData("Mt.ScarabResearchCenter", "Travel: Mt. Scarab Research Center", ["DahlAbandon", "FFSBossFight"]),
    # "FFSBossFight": Borderlands2RegionData("FFSBossFight", "Travel: FFS Boss Fight", ["Mt.ScarabResearchCenter"]),

    # "UnassumingDocks": Borderlands2RegionData("UnassumingDocks", "Travel: Unassuming Docks", ["Menu", "FlamerockRefuge"]),
    # "FlamerockRefuge": Borderlands2RegionData("FlamerockRefuge", "Travel: Flamerock Refuge", ["UnassumingDocks", "Forest", "MinesOfAvarice", "MurderlinsTemple"]),
    # "HatredsShadow": Borderlands2RegionData("HatredsShadow", "Travel: Hatred's Shadow", ["DragonKeep", "LairOfInfiniteAgony", "MinesOfAvarice"]),
    # "LairOfInfiniteAgony": Borderlands2RegionData("LairOfInfiniteAgony", "Travel: Lair of Infinite Agony", ["HatredsShadow", "DragonKeep", "WingedStorm"]),
    # "ImmortalWoods": Borderlands2RegionData("ImmortalWoods", "Travel: Immortal Woods", ["Forest", "MinesOfAvarice"]),
    # "Forest": Borderlands2RegionData("Forest", "Travel: The Forest", ["ImmortalWoods", "MinesOfAvarice", "FlamerockRefuge"]),
    # "MinesOfAvarice": Borderlands2RegionData("MinesOfAvarice", "Travel: Mines of Avarice", ["HatredsShadow", "DragonKeep", "ImmortalWoods", "Forest", "FlamerockRefuge"]),
    # "MurderlinsTemple": Borderlands2RegionData("MurderlinsTemple", "Travel: Murderlin's Temple", ["FlamerockRefuge"]),
    # "WingedStorm": Borderlands2RegionData("WingedStorm", "Travel: The Winged Storm", ["LairOfInfiniteAgony"]),
    # "DragonKeep": Borderlands2RegionData("DragonKeep", "Travel: Dragon Keep", ["HatredsShadow", "LairOfInfiniteAgony"]),
    #
    # "BadassCrater": Borderlands2RegionData("BadassCrater", "Travel: Badass Crater", ["Menu", "Beatdown", "TorgueArena", "TorgueArenaRing", "Forge", "SouthernRaceway", "BaddassCraterBar"]),
    # "Beatdown": Borderlands2RegionData("Beatdown", "Travel: The Beatdown", ["Beatdown", "BadassCrater", "PyroPetesBar"]),
    # "TorgueArena": Borderlands2RegionData("TorgueArena", "Travel: Torgue Arena", ["BadassCrater"]),
    # "TorgueArenaRing": Borderlands2RegionData("TorgueArenaRing", "Travel: Torgue Arena Ring", ["BadassCrater"]),
    # "BaddassCraterBar": Borderlands2RegionData("BaddassCraterBar", "Travel: Baddass Crater Bar", ["BadassCrater"]),
    # "Forge": Borderlands2RegionData("Forge", "Travel: The Forge", ["BadassCrater"]),
    # "SouthernRaceway": Borderlands2RegionData("SouthernRaceway", "Travel: Southern Raceway", ["BadassCrater"]),
    # "PyroPetesBar": Borderlands2RegionData("PyroPetesBar", "Travel: Pyro Pete's Bar", ["Beatdown"]),
    #
    # "Oasis": Borderlands2RegionData("Oasis", "Travel: Oasis", ["Menu", "HaytorsFolly", "Wurmwater", "MagnysLighthouse", "LeviathansLair"]),
    # "HaytorsFolly": Borderlands2RegionData("HaytorsFolly", "Travel: Haytor's Folly", ["Oasis"]),
    # "Wurmwater": Borderlands2RegionData("Wurmwater", "Travel: Wurmwater", ["WashburneRefinery", "Rustyards", "MagnysLighthouse", "LeviathansLair", "Oasis"]),
    # "WashburneRefinery": Borderlands2RegionData("WashburneRefinery", "Travel: Washburne Refinery", ["Wurmwater"]),
    # "Rustyards": Borderlands2RegionData("Rustyards", "Travel: The Rustyards", ["Wurmwater"]),
    # "MagnysLighthouse": Borderlands2RegionData("MagnysLighthouse", "Travel: Magnys Lighthouse", ["Oasis", "Wurmwater"]),
    # "LeviathansLair": Borderlands2RegionData("LeviathansLair", "Travel: The Leviathan's Lair", ["Oasis", "Wurmwater"]),
    #
    # "HuntersGrotto": Borderlands2RegionData("HuntersGrotto", "Travel: Hunter's Grotto", ["Menu", "ScyllasGrove", "CandlerakksCragg", "ArdortonStation"]),
    # "CandlerakksCragg": Borderlands2RegionData("CandlerakksCragg", "Travel: Candlerakk's Cragg", ["HuntersGrotto", "Terminus"]),
    # "ArdortonStation": Borderlands2RegionData("ArdortonStation", "Travel: Ardorton Station", ["HuntersGrotto", "ScyllasGrove"]),
    # "ScyllasGrove": Borderlands2RegionData("ScyllasGrove", "Travel: Scylla's Grove", ["HuntersGrotto"]),
    # "Terminus": Borderlands2RegionData("Terminus", "Travel: Terminus", ["CandlerakksCragg"]),
    #
    # "DigistructPeak": Borderlands2RegionData("DigistructPeak", "Travel: Digistruct Peak", ["Menu", "DigistructPeakInner"]),
    # "DigistructPeakInner": Borderlands2RegionData("DigistructPeakInner", "", ["DigistructPeak"]),
    # "DigistructPeakOP5": Borderlands2RegionData("DigistructPeakOP5", "", ["DigistructPeakInner"]),
    #
    # "MarcusMercenaryShop": Borderlands2RegionData("MarcusMercenaryShop", "Travel: Marcus's Mercenary Shop", ["Menu"]),
    # "GluttonGulch": Borderlands2RegionData("GluttonGulch", "Travel: Glutton Gulch", ["Menu"]),
    # "RotgutDistillery": Borderlands2RegionData("RotgutDistillery", "Travel: Rotgut Distillery", ["Menu"]),
    # "WamBamIsland": Borderlands2RegionData("WamBamIsland", "Travel: Wam Bam Island", ["Menu"]),
    # "HallowedHollow": Borderlands2RegionData("HallowedHollow", "Travel: Hallowed Hollow", ["Menu"]),

}
