from typing import Dict, List, NamedTuple, Union


class Borderlands2RegionData(NamedTuple):
    name: str = ""
    travel_item_name: Union[str, List[str]] = ""
    connecting_regions: List[str] = []
    @property
    def primary_travel_item(self):
        if type(self.travel_item_name) is str:
            return self.travel_item_name
        elif len(self.travel_item_name) > 0:
            return self.travel_item_name[0]
        return ""

region_data_table: Dict[str, Borderlands2RegionData] = {
    "Menu": Borderlands2RegionData("Menu", "", [
        "WindshearWaste",
        "DigistructPeak",
        # "FFSIntroSanctuary",
        # "UnassumingDocks",
        # "BadassCrater",
        # "Oasis",
        # "HuntersGrotto",
        # "MarcusMercenaryShop",
        # "GluttonyGulch",
        # "RotgutDistillery",
        # "WamBamIsland",
        # "HallowedHollow",
    ]),

    "WindshearWaste": Borderlands2RegionData("WindshearWaste", "", ["SouthernShelf"]),
    "SouthernShelf": Borderlands2RegionData("SouthernShelf", "Travel: Southern Shelf", ["SouthernShelfBay", "ThreeHornsDivide"]),
    "SouthernShelfBay": Borderlands2RegionData("SouthernShelfBay", "Travel: Southern Shelf Bay", []),
    "ThreeHornsDivide": Borderlands2RegionData("ThreeHornsDivide", "Travel: Three Horns Divide", ["ThreeHornsValley", "Sanctuary"]),
    "ThreeHornsValley": Borderlands2RegionData("ThreeHornsValley", "Travel: Three Horns Valley", ["SouthpawSteam&Power", "Dust"]),
    "Sanctuary": Borderlands2RegionData("Sanctuary", "Travel: Sanctuary", ["FrostburnCanyon"]),
    "FrostburnCanyon": Borderlands2RegionData("FrostburnCanyon", "Travel: Frostburn Canyon", ["BloodshotStronghold", "FriendshipGulag"]),
    "SouthpawSteam&Power": Borderlands2RegionData("SouthpawSteam&Power", "Travel: Southpaw Steam & Power", []),
    "Dust": Borderlands2RegionData("Dust", "Travel: The Dust", ["FriendshipGulag", "Lynchwood"]),
    "BloodshotStronghold": Borderlands2RegionData("BloodshotStronghold", "Travel: Bloodshot Stronghold", ["BloodshotRamparts"]),
    "BloodshotRamparts": Borderlands2RegionData("BloodshotRamparts", "Travel: Bloodshot Ramparts", [
        "TundraExpress",
        "MarcusMercenaryShop",
        "GluttonyGulch",
        "RotgutDistillery",
        "WamBamIsland",
        "HallowedHollow",
        "BadassCrater",
        "Oasis",
    ]),
    "Fridge": Borderlands2RegionData("Fridge", "Travel: The Fridge", ["FinksSlaughterhouse", "HighlandsOutwash"]),
    "HighlandsOutwash": Borderlands2RegionData("HighlandsOutwash", "Travel: Highlands Outwash", ["Highlands"]),
    "Highlands": Borderlands2RegionData("Highlands", "Travel: Highlands", ["ThousandCuts", "Opportunity", "HolySpirits", "WildlifeExploitationPreserve"]),
    "FriendshipGulag": Borderlands2RegionData("FriendshipGulag", "Travel: Friendship Gulag", []),
    "Lynchwood": Borderlands2RegionData("Lynchwood", "Travel: Lynchwood", []),
    "FinksSlaughterhouse": Borderlands2RegionData("FinksSlaughterhouse", "Travel: Fink's Slaughterhouse", []),
    "SanctuaryHole": Borderlands2RegionData("SanctuaryHole", "Travel: Sanctuary Hole", ["CausticCaverns"]),
    "TerramorphousPeak": Borderlands2RegionData("TerramorphousPeak", "Travel: Terramorphous Peak", []),
    "CausticCaverns": Borderlands2RegionData("CausticCaverns", "Travel: Caustic Caverns", []),
    "Opportunity": Borderlands2RegionData("Opportunity", "Travel: Opportunity", []),
    "HolySpirits": Borderlands2RegionData("HolySpirits", "Travel: The Holy Spirits", []),
    "WildlifeExploitationPreserve": Borderlands2RegionData("WildlifeExploitationPreserve", "Travel: Wildlife Exploitation Preserve", ["NaturalSelectionAnnex"]),
    "NaturalSelectionAnnex": Borderlands2RegionData("NaturalSelectionAnnex", "Travel: Natural Selection Annex", []),
    "TundraExpress": Borderlands2RegionData("TundraExpress", "Travel: Tundra Express", ["EndOfTheLine"]),
    "EndOfTheLine": Borderlands2RegionData("EndOfTheLine", "Travel: End of the Line", ["SanctuaryHole", "Fridge"]),
    "Bunker": Borderlands2RegionData("Bunker", "Travel: The Bunker", ["ControlCoreAngel"]),
    "ThousandCuts": Borderlands2RegionData("ThousandCuts", "Travel: Thousand Cuts", ["Bunker"]),
    "EridiumBlight": Borderlands2RegionData("EridiumBlight", "Travel: Eridium Blight", ["OreChasm", "SawtoothCauldron"]),
    "SawtoothCauldron": Borderlands2RegionData("SawtoothCauldron", "Travel: Sawtooth Cauldron", ["AridNexusBoneyard"]),
    "OreChasm": Borderlands2RegionData("OreChasm", "Travel: Ore Chasm", []),
    "ControlCoreAngel": Borderlands2RegionData("ControlCoreAngel", "Travel: Control Core Angel", ["EridiumBlight"]),
    "AridNexusBoneyard": Borderlands2RegionData("AridNexusBoneyard", "Travel: Arid Nexus Boneyard", ["AridNexusBadlands"]),
    "AridNexusBadlands": Borderlands2RegionData("AridNexusBadlands", "Travel: Arid Nexus Badlands", ["HerosPass"]),
    "HerosPass": Borderlands2RegionData("HerosPass", "Travel: Hero's Pass", ["VaultOfTheWarrior"]),
    "VaultOfTheWarrior": Borderlands2RegionData("VaultOfTheWarrior", "Travel: Vault of the Warrior", ["TerramorphousPeak",
        "FFSIntroSanctuary",
        "UnassumingDocks",
        "BadassCrater",
        "Oasis",
        "HuntersGrotto",
        "DigistructPeakInner",
    ]),

    "FFSIntroSanctuary": Borderlands2RegionData("FFSIntroSanctuary", ["Travel: FFS Intro Sanctuary"], ["Backburner"]),
    "Burrows": Borderlands2RegionData("Burrows", ["Travel: The Burrows"], ["HeliosFallen"]),
    "Backburner": Borderlands2RegionData("Backburner", ["Travel: The Backburner", "Travel: FFS Intro Sanctuary"], ["DahlAbandon"]),
    "DahlAbandon": Borderlands2RegionData("DahlAbandon", ["Travel: Dahl Abandon"], ["Burrows"]),
    "HeliosFallen": Borderlands2RegionData("HeliosFallen", ["Travel: Helios Fallen"], ["Mt.ScarabResearchCenter"]),
    "WrithingDeep": Borderlands2RegionData("WrithingDeep", ["Travel: Writhing Deep"], []),
    "Mt.ScarabResearchCenter": Borderlands2RegionData("Mt.ScarabResearchCenter", ["Travel: Mt. Scarab Research Center"], ["FFSBossFight"]),
    "FFSBossFight": Borderlands2RegionData("FFSBossFight", ["Travel: FFS Boss Fight"], ["WrithingDeep"]),

    "UnassumingDocks": Borderlands2RegionData("UnassumingDocks", ["Travel: Unassuming Docks"], ["FlamerockRefuge"]),
    "FlamerockRefuge": Borderlands2RegionData("FlamerockRefuge", ["Travel: Flamerock Refuge"], ["Forest"]),
    "HatredsShadow": Borderlands2RegionData("HatredsShadow", ["Travel: Hatred's Shadow"], ["LairOfInfiniteAgony"]),
    "LairOfInfiniteAgony": Borderlands2RegionData("LairOfInfiniteAgony",["Travel: Lair of Infinite Agony"], ["DragonKeep"]),
    "ImmortalWoods": Borderlands2RegionData("ImmortalWoods", ["Travel: Immortal Woods"], ["MinesOfAvarice"]),
    "Forest": Borderlands2RegionData("Forest", ["Travel: The Forest"], ["ImmortalWoods"]),
    "MinesOfAvarice": Borderlands2RegionData("MinesOfAvarice", ["Travel: Mines of Avarice"], ["HatredsShadow"]),
    "MurderlinsTemple": Borderlands2RegionData("MurderlinsTemple", ["Travel: Murderlin's Temple"], []),
    "WingedStorm": Borderlands2RegionData("WingedStorm", ["Travel: The Winged Storm"], []),
    "DragonKeep": Borderlands2RegionData("DragonKeep", ["Travel: Dragon Keep"], ["WingedStorm", "MurderlinsTemple"]),

    "BadassCrater": Borderlands2RegionData("BadassCrater", ["Travel: Badass Crater"], ["TorgueArena"]),
    "Beatdown": Borderlands2RegionData("Beatdown", ["Travel: The Beatdown"], ["PyroPetesBar"]),
    "TorgueArena": Borderlands2RegionData("TorgueArena", ["Travel: Torgue Arena"], ["TorgueArenaRing","Beatdown"]),
    "TorgueArenaRing": Borderlands2RegionData("TorgueArenaRing", ["Travel: Torgue Arena Ring"], ["SouthernRaceway"]),
    "BadassCraterBar": Borderlands2RegionData("BadassCraterBar", ["Travel: Badass Crater Bar"], ["SouthernRaceway"]),
    "Forge": Borderlands2RegionData("Forge", ["Travel: The Forge"], []),
    "SouthernRaceway": Borderlands2RegionData("SouthernRaceway", ["Travel: Southern Raceway", "Travel: Torgue Arena Ring"], ["Forge"]),
    "PyroPetesBar": Borderlands2RegionData("PyroPetesBar", ["Travel: Pyro Pete's Bar"], ["BadassCraterBar"]),

    "Oasis": Borderlands2RegionData("Oasis", ["Travel: Oasis"], ["Wurmwater"]),
    "HaytorsFolly": Borderlands2RegionData("HaytorsFolly", ["Travel: Haytor's Folly"], ["Rustyards"]),
    "Wurmwater": Borderlands2RegionData("Wurmwater", ["Travel: Wurmwater"], ["HaytorsFolly"]),
    "WashburneRefinery": Borderlands2RegionData("WashburneRefinery", ["Travel: Washburne Refinery"],
                                                ["MagnysLighthouse"]),
    "Rustyards": Borderlands2RegionData("Rustyards", ["Travel: The Rustyards"], ["WashburneRefinery"]),
    "MagnysLighthouse": Borderlands2RegionData("MagnysLighthouse", ["Travel: Magnys Lighthouse"], ["LeviathansLair"]),
    "LeviathansLair": Borderlands2RegionData("LeviathansLair", ["Travel: The Leviathan's Lair"], []),

    "HuntersGrotto": Borderlands2RegionData("HuntersGrotto", ["Travel: Hunter's Grotto"], ["ScyllasGrove"]),
    "CandlerakksCrag": Borderlands2RegionData("CandlerakksCrag", ["Travel: Candlerakk's Cragg"], ["Terminus"]),
    "ArdortonStation": Borderlands2RegionData("ArdortonStation", ["Travel: Ardorton Station"], ["CandlerakksCrag"]),
    "ScyllasGrove": Borderlands2RegionData("ScyllasGrove", ["Travel: Scylla's Grove"], ["ArdortonStation"]),
    "Terminus": Borderlands2RegionData("Terminus", ["Travel: Terminus"], []),

    "DigistructPeak": Borderlands2RegionData("DigistructPeak", ["Travel: Digistruct Peak"], []),
    "DigistructPeakInner": Borderlands2RegionData("DigistructPeakInner", ["Travel: Digistruct Peak"], []),
    # "DigistructPeakOP5": Borderlands2RegionData("DigistructPeakOP5", "", []),

    "MarcusMercenaryShop": Borderlands2RegionData("MarcusMercenaryShop", ["Travel: Marcus's Mercenary Shop"], []),
    "GluttonyGulch": Borderlands2RegionData("GluttonyGulch", ["Travel: Gluttony Gulch"], []),
    "RotgutDistillery": Borderlands2RegionData("RotgutDistillery", ["Travel: Rotgut Distillery"], []),
    "WamBamIsland": Borderlands2RegionData("WamBamIsland", ["Travel: Wam Bam Island"], []),
    "HallowedHollow": Borderlands2RegionData("HallowedHollow", ["Travel: Hallowed Hollow"], []),
}

#free roam mode regions starts with Sanctuary instead of Windshear Waste

free_region_data_table: Dict[str, Borderlands2RegionData] = {
    "Menu": Borderlands2RegionData("Menu", "", [
        "Sanctuary",
        "Sanctuary Combat",
        "DigistructPeak",
        # "FFSIntroSanctuary",
        # "UnassumingDocks",
        # "BadassCrater",
        # "Oasis",
        # "HuntersGrotto",
        # "MarcusMercenaryShop",
        # "GluttonyGulch",
        # "RotgutDistillery",
        # "WamBamIsland",
        # "HallowedHollow",
    ]),

    #combat regions
    "Sanctuary Combat": Borderlands2RegionData("Sanctuary Combat", "", ["WindshearWaste Combat","SouthernShelf Combat","DigistructPeak Combat"]),
    "DigistructPeak Combat": Borderlands2RegionData("DigistructPeak Combat", "Travel: Digistruct Peak", ["WindshearWaste Combat","SouthernShelf Combat"]),
    "WindshearWaste Combat": Borderlands2RegionData("WindshearWaste Combat", "Travel: Windshear Waste", ["SouthernShelf Combat", "ThreeHornsDivide Combat"]),
    "SouthernShelf Combat": Borderlands2RegionData("SouthernShelf Combat", "Travel: Southern Shelf", ["WindshearWaste Combat","SouthernShelfBay Combat",
                                                                                                      "ThreeHornsDivide Combat","FrostburnCanyon Combat",
                                                                                                      "ThreeHornsValley Combat", "SouthpawSteam&Power Combat"]),
    "ThreeHornsDivide Combat": Borderlands2RegionData("ThreeHornsDivide Combat", "Travel: Three Horns Divide", ["FrostburnCanyon Combat", "ThreeHornsValley Combat",
                                                                                                                "SouthpawSteam&Power Combat","BloodshotStronghold Combat",
                                                                                                                "TundraExpress Combat"]),
    "FrostburnCanyon Combat": Borderlands2RegionData("FrostburnCanyon Combat", "Travel: Frostburn Canyon", ["ThreeHornsValley Combat", "SouthpawSteam&Power Combat",
                                                                                                            "ThreeHornsDivide Combat","BloodshotStronghold Combat",
                                                                                                            "TundraExpress Combat"]),
    "ThreeHornsValley Combat": Borderlands2RegionData("ThreeHornsValley Combat", "Travel: Three Horns Valley", ["FrostburnCanyon Combat", "SouthpawSteam&Power Combat",
                                                                                                            "ThreeHornsDivide Combat","BloodshotStronghold Combat",
                                                                                                            "TundraExpress Combat"]),
    "Dust Combat": Borderlands2RegionData("Dust Combat", "Travel: The Dust", ["EridiumBlight Combat",
                                                                             "Lynchwood Combat", "CausticCaverns Combat", "SawtoothCauldron Combat",
                                                                             "AridNexusBoneyard Combat","AridNexusBadlands Combat",
                                                                              "FriendshipGulag Combat"]),
    "BloodshotStronghold Combat": Borderlands2RegionData("BloodshotStronghold Combat", "Travel: Bloodshot Stronghold", ["BloodshotRamparts Combat","TundraExpress Combat",
                                                                                                                        "Fridge Combat", "HighlandsOutwash Combat",
                                                                                                                        "Highlands Combat",
                                                                                                      "HallowedHollow Combat","GluttonyGulch Combat",
                                                                                                      "MarcusMercenaryShop Combat","RotgutDistillery Combat",
                                                                                                      "WamBamIsland Combat"]),
    "TundraExpress Combat": Borderlands2RegionData("TundraExpress Combat", "Travel: Tundra Express", ["EndOfTheLine Combat", "BloodshotStronghold Combat",
                                                                                                      "Fridge Combat", "HighlandsOutwash Combat",
                                                                                                      "Highlands Combat",
                                                                                                      "HallowedHollow Combat","GluttonyGulch Combat",
                                                                                                      "MarcusMercenaryShop Combat","RotgutDistillery Combat",
                                                                                                      "WamBamIsland Combat"]),
    "Fridge Combat": Borderlands2RegionData("Fridge Combat", "Travel: The Fridge", ["HighlandsOutwash Combat","Highlands Combat",
                                                                                                      "WildlifeExploitationPreserve Combat", "ThousandCuts Combat","Opportunity Combat",
                                                                                                      "FinksSlaughterhouse Combat",
                                                                                                      "HallowedHollow Combat","GluttonyGulch Combat",
                                                                                                      "MarcusMercenaryShop Combat","RotgutDistillery Combat",
                                                                                                      "WamBamIsland Combat"]),
    "HighlandsOutwash Combat": Borderlands2RegionData("HighlandsOutwash Combat", "Travel: Highlands Outwash", ["Fridge Combat","Highlands Combat",
                                                                                                               "WildlifeExploitationPreserve Combat", "ThousandCuts Combat",
                                                                                                               "Opportunity Combat",
                                                                                                      "HallowedHollow Combat","GluttonyGulch Combat",
                                                                                                      "MarcusMercenaryShop Combat","RotgutDistillery Combat",
                                                                                                      "WamBamIsland Combat"]),
    "Highlands Combat": Borderlands2RegionData("Highlands Combat", "Travel: Highlands", ["Fridge Combat","HighlandsOutwash Combat",
                                                                                                      "WildlifeExploitationPreserve Combat","ThousandCuts Combat","Opportunity Combat",
                                                                                                      "HallowedHollow Combat","GluttonyGulch Combat",
                                                                                                      "MarcusMercenaryShop Combat","RotgutDistillery Combat",
                                                                                                      "WamBamIsland Combat", "HolySpirits Combat"]),
    "WildlifeExploitationPreserve Combat": Borderlands2RegionData("WildlifeExploitationPreserve Combat", "Travel: Wildlife Exploitation Preserve", ["ThousandCuts Combat","Opportunity Combat",
                                                                                                            "Dust Combat", "EridiumBlight Combat",
                                                                                                            "CausticCaverns Combat","Lynchwood Combat",
                                                                                                            "SawtoothCauldron Combat",
                                                                                                            "NaturalSelectionAnnex Combat"]),
    "ThousandCuts Combat": Borderlands2RegionData("ThousandCuts Combat", "Travel: Thousand Cuts", ["WildlifeExploitationPreserve Combat","Opportunity Combat",
                                                                                                            "Bunker Combat", "Dust Combat", "EridiumBlight Combat",
                                                                                                            "CausticCaverns Combat","Lynchwood Combat",
                                                                                                            "SawtoothCauldron Combat"]),
    "Opportunity Combat": Borderlands2RegionData("Opportunity Combat", "Travel: Opportunity", ["ThousandCuts Combat","WildlifeExploitationPreserve Combat",
                                                                                               "Dust Combat", "EridiumBlight Combat",
                                                                                                "CausticCaverns Combat","Lynchwood Combat",
                                                                                                "SawtoothCauldron Combat"]),
    "CausticCaverns Combat": Borderlands2RegionData("CausticCaverns Combat", "Travel: Caustic Caverns", ["EridiumBlight Combat","SanctuaryHole Combat",
                                                                                                         "Lynchwood Combat", "Dust Combat", "SawtoothCauldron Combat",
                                                                                                         "AridNexusBoneyard Combat","AridNexusBadlands Combat"]),
    "Bunker Combat": Borderlands2RegionData("Bunker Combat", "Travel: The Bunker", ["AridNexusBoneyard Combat","AridNexusBadlands Combat"]),
    "EridiumBlight Combat": Borderlands2RegionData("EridiumBlight Combat", "Travel: Eridium Blight", ["CausticCaverns Combat",
                                                                                                     "Lynchwood Combat", "Dust Combat", "SawtoothCauldron Combat",
                                                                                                     "AridNexusBoneyard Combat","AridNexusBadlands Combat",
                                                                                                      "OreChasm Combat"]),
    "SawtoothCauldron Combat": Borderlands2RegionData("SawtoothCauldron Combat", "Travel: Sawtooth Cauldron", ["EridiumBlight Combat",
                                                                                                         "Lynchwood Combat", "Dust Combat", "CausticCaverns Combat",
                                                                                                         "AridNexusBoneyard Combat","AridNexusBadlands Combat"]),
    "AridNexusBoneyard Combat": Borderlands2RegionData("AridNexusBoneyard Combat", "Travel: Arid Nexus Boneyard", ["AridNexusBadlands Combat","HerosPass Combat",
                                                                                                                   "Oasis Combat",
                                                                                                                   "BadassCrater Combat",
                                                                                                                   "HuntersGrotto Combat",
                                                                                                                   "UnassumingDocks Combat",
                                                                                                                   "FFSIntroSanctuary Combat", "DigistructPeakInner Combat"
                                                                                                                   ]),
    "AridNexusBadlands Combat": Borderlands2RegionData("AridNexusBadlands Combat", "Travel: Arid Nexus Badlands", ["AridNexusBoneyard Combat","HerosPass Combat",
                                                                                                                   "Oasis Combat",
                                                                                                                   "BadassCrater Combat",
                                                                                                                   "HuntersGrotto Combat",
                                                                                                                   "UnassumingDocks Combat",
                                                                                                                   "FFSIntroSanctuary Combat", "DigistructPeakInner Combat"
                                                                                                                   ]),
    "HerosPass Combat": Borderlands2RegionData("HerosPass Combat", "Travel: Hero's Pass", ["VaultOfTheWarrior Combat"]),
    "Lynchwood Combat": Borderlands2RegionData("Lynchwood Combat", "Travel: Lynchwood", ["EridiumBlight Combat",
                                                                                         "CausticCaverns Combat", "Dust Combat", "SawtoothCauldron Combat",
                                                                                         "AridNexusBoneyard Combat","AridNexusBadlands Combat"]),
    "SouthpawSteam&Power Combat": Borderlands2RegionData("SouthpawSteam&Power Combat", "Travel: Southpaw Steam & Power", ["ThreeHornsValley Combat", "FrostburnCanyon Combat",
                                                                                                    "ThreeHornsDivide Combat","BloodshotStronghold Combat",
                                                                                                    "TundraExpress Combat"]),
    "SouthernShelfBay Combat": Borderlands2RegionData("Lynchwood Combat", "Travel: Southern Shelf Bay", []),
    "EndOfTheLine Combat": Borderlands2RegionData("Lynchwood Combat", "Travel: End of the Line", []),
    "BloodshotRamparts Combat": Borderlands2RegionData("BloodshotRamparts Combat", "Travel: Bloodshot Ramparts", []),
    "FriendshipGulag Combat": Borderlands2RegionData("FriendshipGulag Combat", "Travel: Friendship Gulag", []),
    "SanctuaryHole Combat": Borderlands2RegionData("SanctuaryHole Combat", "Travel: Sanctuary Hole",[]),
    "HolySpirits Combat": Borderlands2RegionData("HolySpirits Combat", "Travel: The Holy Spirits", []),
    "VaultOfTheWarrior Combat": Borderlands2RegionData("VaultOfTheWarrior Combat",["Travel: Vault of the Warrior"],["TerramorphousPeak Combat"]),
    "TerramorphousPeak Combat": Borderlands2RegionData("TerramorphousPeak Combat","Travel: Terramorphous Peak",[]),
    "DigistructPeakInner Combat": Borderlands2RegionData("DigistructPeakInner Combat","Travel: Digistruct Peak",[]),

    "FinksSlaughterhouse Combat": Borderlands2RegionData("FinksSlaughterhouse Combat", "Travel: Fink's Slaughterhouse", []),
    "NaturalSelectionAnnex Combat": Borderlands2RegionData("NaturalSelectionAnnex Combat", "Travel: Natural Selection Annex", []),
    "OreChasm Combat": Borderlands2RegionData("OreChasm Combat", "Travel: Ore Chasm", []),

    "Oasis Combat": Borderlands2RegionData("Oasis Combat", ["Travel: Oasis"], ["Wurmwater Combat"]),
    "Wurmwater Combat": Borderlands2RegionData("Wurmwater Combat", ["Travel: Wurmwater"], ["HaytorsFolly Combat"]),
    "HaytorsFolly Combat": Borderlands2RegionData("HaytorsFolly Combat", ["Travel: Haytor's Folly"], ["Rustyards Combat"]),
    "Rustyards Combat": Borderlands2RegionData("Rustyards Combat", ["Travel: The Rustyards"], ["WashburneRefinery Combat"]),
    "WashburneRefinery Combat": Borderlands2RegionData("WashburneRefinery Combat", ["Travel: Washburne Refinery"], ["MagnysLighthouse Combat"]),
    "MagnysLighthouse Combat": Borderlands2RegionData("MagnysLighthouse Combat", ["Travel: Magnys Lighthouse"], ["LeviathansLair Combat"]),
    "LeviathansLair Combat": Borderlands2RegionData("LeviathansLair Combat", ["Travel: The Leviathan's Lair"], []),

    "BadassCrater Combat": Borderlands2RegionData("BadassCrater Combat", "Travel: Badass Crater", ["TorgueArena Combat"]),
    "TorgueArena Combat": Borderlands2RegionData("TorgueArena Combat", "Travel: Torgue Arena", ["Beatdown Combat"]),
    "Beatdown Combat": Borderlands2RegionData("Beatdown Combat", "Travel: The Beatdown", ["PyroPetesBar Combat"]),
    "PyroPetesBar Combat": Borderlands2RegionData("PyroPetesBar Combat", "Travel: Pyro Pete's Bar",["BadassCraterBar Combat"]),
    "BadassCraterBar Combat": Borderlands2RegionData("BadassCraterBar Combat", "Travel: Badass Crater Bar", ["TorgueArenaRing Combat"]),
    "TorgueArenaRing Combat": Borderlands2RegionData("TorgueArenaRing Combat", "Travel: Torgue Arena Ring", ["SouthernRaceway Combat"]),
    "SouthernRaceway Combat": Borderlands2RegionData("SouthernRaceway Combat", "Travel: Southern Raceway", ["Forge Combat"]),
    "Forge Combat": Borderlands2RegionData("Forge Combat", "Travel: The Forge", []),

    "HuntersGrotto Combat": Borderlands2RegionData("HuntersGrotto Combat", "Travel: Hunter's Grotto", ["ScyllasGrove Combat"]),
    "ScyllasGrove Combat": Borderlands2RegionData("ScyllasGrove Combat", "Travel: Scylla's Grove", ["ArdortonStation Combat"]),
    "ArdortonStation Combat": Borderlands2RegionData("ArdortonStation Combat", "Travel: Ardorton Station", ["CandlerakksCrag Combat"]),
    "CandlerakksCrag Combat": Borderlands2RegionData("CandlerakksCrag Combat",["Travel: Candlerakk's Cragg"], ["Terminus Combat"]),
    "Terminus Combat": Borderlands2RegionData("Terminus Combat", "Travel: Terminus", []),

    "UnassumingDocks Combat": Borderlands2RegionData("UnassumingDocks Combat", "Travel: Unassuming Docks", ["FlamerockRefuge Combat"]),
    "FlamerockRefuge Combat": Borderlands2RegionData("FlamerockRefuge Combat", "Travel: Flamerock Refuge", ["Forest Combat"]),
    "Forest Combat": Borderlands2RegionData("Forest Combat", "Travel: The Forest", ["ImmortalWoods Combat"]),
    "ImmortalWoods Combat": Borderlands2RegionData("ImmortalWoods Combat", "Travel: Immortal Woods", ["MinesOfAvarice Combat"]),
    "MinesOfAvarice Combat": Borderlands2RegionData("MinesOfAvarice Combat", "Travel: Mines of Avarice", ["HatredsShadow Combat"]),
    "HatredsShadow Combat": Borderlands2RegionData("HatredsShadow Combat", "Travel: Hatred's Shadow", ["LairOfInfiniteAgony Combat"]),
    "LairOfInfiniteAgony Combat": Borderlands2RegionData("LairOfInfiniteAgony Combat", ["Travel: Lair of Infinite Agony"], ["DragonKeep Combat"]),
    "DragonKeep Combat": Borderlands2RegionData("DragonKeep Combat", "Travel: Dragon Keep", ["WingedStorm Combat","MurderlinsTemple Combat"]),
    "WingedStorm Combat": Borderlands2RegionData("WingedStorm Combat", "Travel: Winged Storm", []),
    "MurderlinsTemple Combat": Borderlands2RegionData("MurderlinsTemple Combat", "Travel: Murderlin's Temple", []),

    "FFSIntroSanctuary Combat": Borderlands2RegionData("FFSIntroSanctuary Combat", "Travel: FFS Intro Sanctuary", ["Backburner Combat"]),
    "Backburner Combat": Borderlands2RegionData("Backburner Combat", "Travel: The Backburner", ["DahlAbandon Combat"]),
    "DahlAbandon Combat": Borderlands2RegionData("DahlAbandon Combat", "Travel: Dahl Abandon", ["Burrows Combat"]),
    "Burrows Combat": Borderlands2RegionData("Burrows Combat", "Travel: The Burrows", ["HeliosFallen Combat"]),
    "HeliosFallen Combat": Borderlands2RegionData("HeliosFallen Combat", "Travel: Helios Fallen", ["Mt.ScarabResearchCenter Combat"]),
    "Mt.ScarabResearchCenter Combat": Borderlands2RegionData("Mt.ScarabResearchCenter Combat", "Travel: Mt. Scarab Research Center", ["FFSBossFight Combat"]),
    "FFSBossFight Combat": Borderlands2RegionData("FFSBossFight Combat", "Travel: FFS Boss Fight", ["WrithingDeep Combat"]),
    "WrithingDeep Combat": Borderlands2RegionData("WrithingDeep Combat", "Travel: Writhing Deep", []),

    "HallowedHollow Combat": Borderlands2RegionData("HallowedHollow Combat", "Travel: Hallowed Hollow", ["Fridge Combat","HighlandsOutwash Combat","Highlands Combat",
                                                                                                        "WildlifeExploitationPreserve Combat","ThousandCuts Combat","Opportunity Combat",
                                                                                                        "GluttonyGulch Combat","MarcusMercenaryShop Combat",
                                                                                                         "RotgutDistillery Combat","WamBamIsland Combat"]),
    "GluttonyGulch Combat": Borderlands2RegionData("GluttonyGulch Combat", "Travel: Gluttony Gulch", ["Fridge Combat","HighlandsOutwash Combat","Highlands Combat",
                                                                                                      "WildlifeExploitationPreserve Combat","ThousandCuts Combat","Opportunity Combat",
                                                                                                      "HallowedHollow Combat",
                                                                                                      "MarcusMercenaryShop Combat",
                                                                                                      "RotgutDistillery Combat",
                                                                                                      "WamBamIsland Combat"]),
    "MarcusMercenaryShop Combat": Borderlands2RegionData("MarcusMercenaryShop Combat", "Travel: Marcus's Mercenary Shop", ["Fridge Combat","HighlandsOutwash Combat","Highlands Combat",
                                                                                                      "WildlifeExploitationPreserve Combat","ThousandCuts Combat","Opportunity Combat",
                                                                                                      "HallowedHollow Combat",
                                                                                                      "GluttonyGulch Combat",
                                                                                                      "RotgutDistillery Combat",
                                                                                                      "WamBamIsland Combat"]),
    "RotgutDistillery Combat": Borderlands2RegionData("RotgutDistillery Combat", "Travel: Rotgut Distillery", ["Fridge Combat","HighlandsOutwash Combat","Highlands Combat",
                                                                                                      "WildlifeExploitationPreserve Combat","ThousandCuts Combat","Opportunity Combat",
                                                                                                      "HallowedHollow Combat",
                                                                                                      "GluttonyGulch Combat",
                                                                                                      "MarcusMercenaryShop Combat",
                                                                                                      "WamBamIsland Combat"]),
    "WamBamIsland Combat": Borderlands2RegionData("WamBamIsland Combat", "Travel: Wam Bam Island", ["Fridge Combat","HighlandsOutwash Combat","Highlands Combat",
                                                                                                      "WildlifeExploitationPreserve Combat","ThousandCuts Combat","Opportunity Combat",
                                                                                                      "HallowedHollow Combat",
                                                                                                      "MarcusMercenaryShop Combat",
                                                                                                      "RotgutDistillery Combat",]),


    #non-combat regions
    "WindshearWaste": Borderlands2RegionData("WindshearWaste", "Travel: Windshear Waste", ["SouthernShelf"]),
    "SouthernShelf": Borderlands2RegionData("SouthernShelf", "Travel: Southern Shelf",
                                            ["SouthernShelfBay", "ThreeHornsDivide","WindshearWaste"]),
    "SouthernShelfBay": Borderlands2RegionData("SouthernShelfBay", "Travel: Southern Shelf Bay", ["SouthernShelf"]),
    "ThreeHornsDivide": Borderlands2RegionData("ThreeHornsDivide", "Travel: Three Horns Divide",
                                               ["ThreeHornsValley","SouthernShelf","FrostburnCanyon","TundraExpress","SanctuaryHole"]),
    "ThreeHornsValley": Borderlands2RegionData("ThreeHornsValley", "Travel: Three Horns Valley",
                                               ["SouthpawSteam&Power", "Dust","BloodshotStronghold","Fridge","ThreeHornsDivide"]),
    "Sanctuary": Borderlands2RegionData("Sanctuary", "", ["WindshearWaste","SouthernShelf","ThreeHornsDivide",
                                                                           "ThreeHornsValley","FrostburnCanyon","SouthpawSteam&Power",
                                                                           "Dust","BloodshotStronghold","Fridge","TundraExpress",
                                                                           "HighlandsOutwash","Highlands","WildlifeExploitationPreserve",
                                                                           "ThousandCuts","Opportunity","Lynchwood","EridiumBlight","HerosPass",
                                                                            "MarcusMercenaryShop",
                                                                            "GluttonyGulch",
                                                                            "RotgutDistillery",
                                                                            "WamBamIsland",
                                                                            "HallowedHollow",
                                                                           "SawtoothCauldron","AridNexusBoneyard","AridNexusBadlands"]),
    "FrostburnCanyon": Borderlands2RegionData("FrostburnCanyon", "Travel: Frostburn Canyon", ["ThreeHornsDivide"]),
    "SouthpawSteam&Power": Borderlands2RegionData("SouthpawSteam&Power", "Travel: Southpaw Steam & Power", ["ThreeHornsValley"]),
    "Dust": Borderlands2RegionData("Dust", "Travel: The Dust", ["Lynchwood","ThreeHornsValley","Highlands","EridiumBlight","FriendshipGulag"]),
    "BloodshotStronghold": Borderlands2RegionData("BloodshotStronghold", ["Travel: Bloodshot Stronghold"],
                                                  ["BloodshotRamparts","ThreeHornsValley"]),
    "BloodshotRamparts": Borderlands2RegionData("BloodshotRamparts", ["Travel: Bloodshot Ramparts"], []),
    "Fridge": Borderlands2RegionData("Fridge", ["Travel: The Fridge"], ["FinksSlaughterhouse", "HighlandsOutwash","ThreeHornsValley"]),
    "HighlandsOutwash": Borderlands2RegionData("HighlandsOutwash", ["Travel: Highlands Outwash"], ["Highlands","Fridge"]),
    "Highlands": Borderlands2RegionData("Highlands", ["Travel: Highlands"],
                                        ["HolySpirits", "WildlifeExploitationPreserve", "ThousandCuts", "Opportunity","HighlandsOutwash","Dust"]),
    "FriendshipGulag": Borderlands2RegionData("FriendshipGulag", ["Travel: Friendship Gulag"], []),
    "Lynchwood": Borderlands2RegionData("Lynchwood", ["Travel: Lynchwood"], ["Dust"]),
    "FinksSlaughterhouse": Borderlands2RegionData("FinksSlaughterhouse", ["Travel: Fink's Slaughterhouse"], []),
    "SanctuaryHole": Borderlands2RegionData("SanctuaryHole", ["Travel: Sanctuary Hole"], ["CausticCaverns"]),
    "TerramorphousPeak": Borderlands2RegionData("TerramorphousPeak", ["Travel: Terramorphous Peak"], []),
    "CausticCaverns": Borderlands2RegionData("CausticCaverns", ["Travel: Caustic Caverns"], []),
    "Opportunity": Borderlands2RegionData("Opportunity", ["Travel: Opportunity"], ["Highlands"]),
    "HolySpirits": Borderlands2RegionData("HolySpirits", ["Travel: The Holy Spirits"], []),
    "WildlifeExploitationPreserve": Borderlands2RegionData("WildlifeExploitationPreserve",
                                                           ["Travel: Wildlife Exploitation Preserve"],
                                                           ["NaturalSelectionAnnex","Highlands"]),
    "NaturalSelectionAnnex": Borderlands2RegionData("NaturalSelectionAnnex", ["Travel: Natural Selection Annex"], []),
    "TundraExpress": Borderlands2RegionData("TundraExpress", ["Travel: Tundra Express"], ["EndOfTheLine","ThreeHornsDivide"]),
    "EndOfTheLine": Borderlands2RegionData("EndOfTheLine", ["Travel: End of the Line"], []),
    "Bunker": Borderlands2RegionData("Bunker", ["Travel: The Bunker",], []),
    "ThousandCuts": Borderlands2RegionData("ThousandCuts", ["Travel: Thousand Cuts"], ["Bunker","Highlands","TerramorphousPeak"]),
    "EridiumBlight": Borderlands2RegionData("EridiumBlight", ["Travel: Eridium Blight"],
                                            ["OreChasm", "SawtoothCauldron","Dust","AridNexusBoneyard","HerosPass"]),
    "SawtoothCauldron": Borderlands2RegionData("SawtoothCauldron", ["Travel: Sawtooth Cauldron"],
                                               ["EridiumBlight"]),
    "OreChasm": Borderlands2RegionData("OreChasm", ["Travel: Ore Chasm"], []),
    "ControlCoreAngel": Borderlands2RegionData("ControlCoreAngel", ["Travel: Control Core Angel"], []),
    "AridNexusBoneyard": Borderlands2RegionData("AridNexusBoneyard", ["Travel: Arid Nexus Boneyard"],
                                                ["AridNexusBadlands","EridiumBlight",
                                                                               "Oasis",
                                                                               "BadassCrater",
                                                                               "UnassumingDocks",
                                                                               "HuntersGrotto",
                                                                               "DigistructPeakInner",
                                                                               "FFSIntroSanctuary"]),
    "AridNexusBadlands": Borderlands2RegionData("AridNexusBadlands", ["Travel: Arid Nexus Badlands"], ["AridNexusBoneyard",
                                                                               "Oasis",
                                                                               "BadassCrater",
                                                                               "UnassumingDocks",
                                                                               "HuntersGrotto",
                                                                               "DigistructPeakInner",
                                                                               "FFSIntroSanctuary"]),
    "HerosPass": Borderlands2RegionData("HerosPass", ["Travel: Hero's Pass"], ["VaultOfTheWarrior"]),
    "VaultOfTheWarrior": Borderlands2RegionData("VaultOfTheWarrior", ["Travel: Vault of the Warrior"],
                                                ["TerramorphousPeak"]),

    "FFSIntroSanctuary": Borderlands2RegionData("FFSIntroSanctuary", ["Travel: FFS Intro Sanctuary"], ["Backburner","HerosPass"]),
    "Burrows": Borderlands2RegionData("Burrows", ["Travel: The Burrows"], ["HeliosFallen","HerosPass"]),
    "Backburner": Borderlands2RegionData("Backburner", ["Travel: The Backburner", "Travel: FFS Intro Sanctuary"],
                                         ["DahlAbandon","HerosPass"]),
    "DahlAbandon": Borderlands2RegionData("DahlAbandon", ["Travel: Dahl Abandon"], ["Burrows","HerosPass"]),
    "HeliosFallen": Borderlands2RegionData("HeliosFallen", ["Travel: Helios Fallen"], ["Mt.ScarabResearchCenter","HerosPass"]),
    "WrithingDeep": Borderlands2RegionData("WrithingDeep", ["Travel: Writhing Deep"], ["HerosPass"]),
    "Mt.ScarabResearchCenter": Borderlands2RegionData("Mt.ScarabResearchCenter", ["Travel: Mt. Scarab Research Center"],
                                                      ["FFSBossFight","HerosPass"]),
    "FFSBossFight": Borderlands2RegionData("FFSBossFight", ["Travel: FFS Boss Fight"], ["WrithingDeep","HerosPass"]),

    "UnassumingDocks": Borderlands2RegionData("UnassumingDocks", ["Travel: Unassuming Docks"], ["FlamerockRefuge","HerosPass"]),
    "FlamerockRefuge": Borderlands2RegionData("FlamerockRefuge", ["Travel: Flamerock Refuge"], ["Forest","HerosPass"]),
    "HatredsShadow": Borderlands2RegionData("HatredsShadow", ["Travel: Hatred's Shadow"], ["LairOfInfiniteAgony","HerosPass"]),
    "LairOfInfiniteAgony": Borderlands2RegionData("LairOfInfiniteAgony", ["Travel: Lair of Infinite Agony"],
                                                  ["DragonKeep","HerosPass"]),
    "ImmortalWoods": Borderlands2RegionData("ImmortalWoods", ["Travel: Immortal Woods"], ["MinesOfAvarice","HerosPass"]),
    "Forest": Borderlands2RegionData("Forest", ["Travel: The Forest"], ["ImmortalWoods","HerosPass"]),
    "MinesOfAvarice": Borderlands2RegionData("MinesOfAvarice", ["Travel: Mines of Avarice"], ["HatredsShadow","HerosPass"]),
    "MurderlinsTemple": Borderlands2RegionData("MurderlinsTemple", ["Travel: Murderlin's Temple"], ["HerosPass"]),
    "WingedStorm": Borderlands2RegionData("WingedStorm", ["Travel: The Winged Storm"], ["HerosPass"]),
    "DragonKeep": Borderlands2RegionData("DragonKeep", ["Travel: Dragon Keep"], ["WingedStorm", "MurderlinsTemple","HerosPass"]),

    "BadassCrater": Borderlands2RegionData("BadassCrater", ["Travel: Badass Crater"], ["TorgueArena","HerosPass"]),
    "Beatdown": Borderlands2RegionData("Beatdown", ["Travel: The Beatdown"], ["PyroPetesBar","HerosPass"]),
    "TorgueArena": Borderlands2RegionData("TorgueArena", ["Travel: Torgue Arena"], ["TorgueArenaRing", "Beatdown","HerosPass"]),
    "TorgueArenaRing": Borderlands2RegionData("TorgueArenaRing", ["Travel: Torgue Arena Ring"], ["SouthernRaceway","HerosPass"]),
    "BadassCraterBar": Borderlands2RegionData("BadassCraterBar", ["Travel: Badass Crater Bar"], ["SouthernRaceway","HerosPass"]),
    "Forge": Borderlands2RegionData("Forge", ["Travel: The Forge"], ["HerosPass"]),
    "SouthernRaceway": Borderlands2RegionData("SouthernRaceway",
                                              ["Travel: Southern Raceway", "Travel: Torgue Arena Ring"], ["Forge","HerosPass"]),
    "PyroPetesBar": Borderlands2RegionData("PyroPetesBar", ["Travel: Pyro Pete's Bar"], ["BadassCraterBar","HerosPass"]),

    "Oasis": Borderlands2RegionData("Oasis", ["Travel: Oasis"], ["Wurmwater","HerosPass"]),
    "HaytorsFolly": Borderlands2RegionData("HaytorsFolly", ["Travel: Haytor's Folly"], ["Rustyards","HerosPass"]),
    "Wurmwater": Borderlands2RegionData("Wurmwater", ["Travel: Wurmwater"], ["HaytorsFolly","HerosPass"]),
    "WashburneRefinery": Borderlands2RegionData("WashburneRefinery", ["Travel: Washburne Refinery"],
                                                ["MagnysLighthouse","HerosPass"]),
    "Rustyards": Borderlands2RegionData("Rustyards", ["Travel: The Rustyards"], ["WashburneRefinery","HerosPass"]),
    "MagnysLighthouse": Borderlands2RegionData("MagnysLighthouse", ["Travel: Magnys Lighthouse"], ["LeviathansLair","HerosPass"]),
    "LeviathansLair": Borderlands2RegionData("LeviathansLair", ["Travel: The Leviathan's Lair"], ["HerosPass"]),

    "HuntersGrotto": Borderlands2RegionData("HuntersGrotto", ["Travel: Hunter's Grotto"], ["ScyllasGrove","HerosPass"]),
    "CandlerakksCrag": Borderlands2RegionData("CandlerakksCrag", ["Travel: Candlerakk's Cragg"], ["Terminus","HerosPass"]),
    "ArdortonStation": Borderlands2RegionData("ArdortonStation", ["Travel: Ardorton Station"], ["CandlerakksCrag","HerosPass"]),
    "ScyllasGrove": Borderlands2RegionData("ScyllasGrove", ["Travel: Scylla's Grove"], ["ArdortonStation","HerosPass"]),
    "Terminus": Borderlands2RegionData("Terminus", ["Travel: Terminus"], ["HerosPass"]),

    "DigistructPeak": Borderlands2RegionData("DigistructPeak", ["Travel: Digistruct Peak"], []),
    "DigistructPeakInner": Borderlands2RegionData("DigistructPeakInner", ["Travel: Digistruct Peak"], []),
    # "DigistructPeakOP5": Borderlands2RegionData("DigistructPeakOP5", "", []),

    "MarcusMercenaryShop": Borderlands2RegionData("MarcusMercenaryShop", ["Travel: Marcus's Mercenary Shop"], []),
    "GluttonyGulch": Borderlands2RegionData("GluttonyGulch", ["Travel: Gluttony Gulch"], []),
    "RotgutDistillery": Borderlands2RegionData("RotgutDistillery", ["Travel: Rotgut Distillery"], []),
    "WamBamIsland": Borderlands2RegionData("WamBamIsland", ["Travel: Wam Bam Island"], []),
    "HallowedHollow": Borderlands2RegionData("HallowedHollow", ["Travel: Hallowed Hollow"], []),

}
