from typing import Dict, List, NamedTuple


class Borderlands2RegionData(NamedTuple):
    name: str = ""
    travel_item_name: str = ""
    connecting_regions: List[str] = []


region_data_table: Dict[str, Borderlands2RegionData] = {
    "Menu": Borderlands2RegionData("Menu", "", [
        "WindshearWaste",
        "DigistructPeak",
        # "FFSIntroSanctuary",
        # "UnassumingDocks",
        # "BadassCrater",
        # "Oasis",
        # "HuntersGrotto",
        # "MarcusMercenaryShop",
        # "GluttonGulch",
        # "RotgutDistillery",
        # "WamBamIsland",
        # "HallowedHollow",
    ]),

    "WindshearWaste": Borderlands2RegionData("WindshearWaste", "", ["SouthernShelf"]),
    "SouthernShelf": Borderlands2RegionData("SouthernShelf", "Travel: Southern Shelf", ["SouthernShelfBay", "ThreeHornsDivide"]),
    "SouthernShelfBay": Borderlands2RegionData("SouthernShelfBay", "Travel: Southern Shelf Bay", []),
    "ThreeHornsDivide": Borderlands2RegionData("ThreeHornsDivide", "Travel: Three Horns Divide", ["ThreeHornsValley", "FrostburnCanyon", "Sanctuary", "SanctuaryHole", "TundraExpress"]),
    "ThreeHornsValley": Borderlands2RegionData("ThreeHornsValley", "Travel: Three Horns Valley", ["Fridge", "SouthpawSteam&Power", "Dust", "BloodshotStronghold"]),
    "Sanctuary": Borderlands2RegionData("Sanctuary", "Travel: Sanctuary", []),
    "FrostburnCanyon": Borderlands2RegionData("FrostburnCanyon", "Travel: Frostburn Canyon", []),
    "SouthpawSteam&Power": Borderlands2RegionData("SouthpawSteam&Power", "Travel: Southpaw Steam & Power", []),
    "Dust": Borderlands2RegionData("Dust", "Travel: The Dust", ["EridiumBlight", "FriendshipGulag", "Lynchwood", "Highlands", "BloodshotRamparts"]),
    "BloodshotStronghold": Borderlands2RegionData("BloodshotStronghold", "Travel: Bloodshot Stronghold", ["BloodshotRamparts"]),
    "BloodshotRamparts": Borderlands2RegionData("BloodshotRamparts", "Travel: Bloodshot Ramparts", [
        "MarcusMercenaryShop",
        "GluttonGulch",
        "RotgutDistillery",
        "WamBamIsland",
        "HallowedHollow",
    ]),
    "Fridge": Borderlands2RegionData("Fridge", "Travel: The Fridge", ["FinksSlaughterhouse", "HighlandsOutwash"]),
    "HighlandsOutwash": Borderlands2RegionData("HighlandsOutwash", "Travel: Highlands Outwash", ["Highlands"]),
    "Highlands": Borderlands2RegionData("Highlands", "Travel: Highlands", ["ThousandCuts", "Opportunity", "HolySpirits", "WildlifeExploitationPreserve"]),
    "FriendshipGulag": Borderlands2RegionData("FriendshipGulag", "Travel: Friendship Gulag", []),
    "Lynchwood": Borderlands2RegionData("Lynchwood", "Travel: Lynchwood", []),
    "FinksSlaughterhouse": Borderlands2RegionData("FinksSlaughterhouse", "Travel: Fink's Slaughterhouse", []),
    "SawtoothCauldron": Borderlands2RegionData("SawtoothCauldron", "Travel: Sawtooth Cauldron", []),
    "SanctuaryHole": Borderlands2RegionData("SanctuaryHole", "Travel: Sanctuary Hole", ["CausticCaverns"]),
    "TerramorphousPeak": Borderlands2RegionData("TerramorphousPeak", "Travel: Terramorphous Peak", []),
    "CausticCaverns": Borderlands2RegionData("CausticCaverns", "Travel: Caustic Caverns", []),
    "Opportunity": Borderlands2RegionData("Opportunity", "Travel: Opportunity", []),
    "HolySpirits": Borderlands2RegionData("HolySpirits", "Travel: The Holy Spirits", []),
    "WildlifeExploitationPreserve": Borderlands2RegionData("WildlifeExploitationPreserve", "Travel: Wildlife Exploitation Preserve", ["NaturalSelectionAnnex"]),
    "NaturalSelectionAnnex": Borderlands2RegionData("NaturalSelectionAnnex", "Travel: Natural Selection Annex", []),
    "TundraExpress": Borderlands2RegionData("TundraExpress", "Travel: Tundra Express", ["EndOfTheLine"]),
    "EndOfTheLine": Borderlands2RegionData("EndOfTheLine", "Travel: End of the Line", []),
    "Bunker": Borderlands2RegionData("Bunker", "Travel: The Bunker", ["ControlCoreAngel"]),
    "ThousandCuts": Borderlands2RegionData("ThousandCuts", "Travel: Thousand Cuts", ["TerramorphousPeak", "Bunker"]),
    "EridiumBlight": Borderlands2RegionData("EridiumBlight", "Travel: Eridium Blight", ["VaultOfTheWarrior", "OreChasm", "AridNexusBoneyard", "SawtoothCauldron", "HerosPass"]),
    "OreChasm": Borderlands2RegionData("OreChasm", "Travel: Ore Chasm", []),
    "ControlCoreAngel": Borderlands2RegionData("ControlCoreAngel", "Travel: Control Core Angel", []),
    "AridNexusBoneyard": Borderlands2RegionData("AridNexusBoneyard", "Travel: Arid Nexus Boneyard", ["AridNexusBadlands"]),
    "AridNexusBadlands": Borderlands2RegionData("AridNexusBadlands", "Travel: Arid Nexus Badlands", ["AridNexusBoneyard"]),
    "HerosPass": Borderlands2RegionData("HerosPass", "Travel: Hero's Pass", ["VaultOfTheWarrior"]),
    "VaultOfTheWarrior": Borderlands2RegionData("VaultOfTheWarrior", "Travel: Vault of the Warrior", [
        "FFSIntroSanctuary",
        "UnassumingDocks",
        "BadassCrater",
        "Oasis",
        "HuntersGrotto",
        "DigistructPeakInner",
    ]),

    "FFSIntroSanctuary": Borderlands2RegionData("FFSIntroSanctuary", "Travel: FFS Intro Sanctuary", ["Backburner"]),
    "Burrows": Borderlands2RegionData("Burrows", "Travel: The Burrows", ["WrithingDeep", "HeliosFallen", "DahlAbandon"]),
    "Backburner": Borderlands2RegionData("Backburner", "Travel: The Backburner", ["DahlAbandon"]),
    "DahlAbandon": Borderlands2RegionData("DahlAbandon", "Travel: Dahl Abandon", ["Backburner", "HeliosFallen", "Burrows", "Mt.ScarabResearchCenter"]),
    "HeliosFallen": Borderlands2RegionData("HeliosFallen", "Travel: Helios Fallen", ["Burrows"]),
    "WrithingDeep": Borderlands2RegionData("WrithingDeep", "Travel: Writhing Deep", []),
    "Mt.ScarabResearchCenter": Borderlands2RegionData("Mt.ScarabResearchCenter", "Travel: Mt. Scarab Research Center", ["DahlAbandon", "FFSBossFight"]),
    "FFSBossFight": Borderlands2RegionData("FFSBossFight", "Travel: FFS Boss Fight", []),

    "UnassumingDocks": Borderlands2RegionData("UnassumingDocks", "Travel: Unassuming Docks", ["FlamerockRefuge"]),
    "FlamerockRefuge": Borderlands2RegionData("FlamerockRefuge", "Travel: Flamerock Refuge", ["Forest", "MinesOfAvarice", "MurderlinsTemple"]),
    "HatredsShadow": Borderlands2RegionData("HatredsShadow", "Travel: Hatred's Shadow", ["DragonKeep", "LairOfInfiniteAgony"]),
    "LairOfInfiniteAgony": Borderlands2RegionData("LairOfInfiniteAgony", "Travel: Lair of Infinite Agony", ["HatredsShadow", "DragonKeep", "WingedStorm"]),
    "ImmortalWoods": Borderlands2RegionData("ImmortalWoods", "Travel: Immortal Woods", ["MinesOfAvarice"]),
    "Forest": Borderlands2RegionData("Forest", "Travel: The Forest", ["ImmortalWoods", "MinesOfAvarice"]),
    "MinesOfAvarice": Borderlands2RegionData("MinesOfAvarice", "Travel: Mines of Avarice", ["HatredsShadow", "DragonKeep", "ImmortalWoods"]),
    "MurderlinsTemple": Borderlands2RegionData("MurderlinsTemple", "Travel: Murderlin's Temple", []),
    "WingedStorm": Borderlands2RegionData("WingedStorm", "Travel: The Winged Storm", []),
    "DragonKeep": Borderlands2RegionData("DragonKeep", "Travel: Dragon Keep", []),

    "BadassCrater": Borderlands2RegionData("BadassCrater", "Travel: Badass Crater", ["Beatdown", "TorgueArena", "TorgueArenaRing", "Forge", "SouthernRaceway", "BaddassCraterBar"]),
    "Beatdown": Borderlands2RegionData("Beatdown", "Travel: The Beatdown", ["BadassCrater", "PyroPetesBar"]),
    "TorgueArena": Borderlands2RegionData("TorgueArena", "Travel: Torgue Arena", []),
    "TorgueArenaRing": Borderlands2RegionData("TorgueArenaRing", "Travel: Torgue Arena Ring", []),
    "BaddassCraterBar": Borderlands2RegionData("BaddassCraterBar", "Travel: Baddass Crater Bar", []),
    "Forge": Borderlands2RegionData("Forge", "Travel: The Forge", []),
    "SouthernRaceway": Borderlands2RegionData("SouthernRaceway", "Travel: Southern Raceway", []),
    "PyroPetesBar": Borderlands2RegionData("PyroPetesBar", "Travel: Pyro Pete's Bar", []),

    "Oasis": Borderlands2RegionData("Oasis", "Travel: Oasis", ["HaytorsFolly", "Wurmwater", "MagnysLighthouse", "LeviathansLair"]),
    "HaytorsFolly": Borderlands2RegionData("HaytorsFolly", "Travel: Haytor's Folly", []),
    "Wurmwater": Borderlands2RegionData("Wurmwater", "Travel: Wurmwater", ["WashburneRefinery", "Rustyards", "MagnysLighthouse", "LeviathansLair"]),
    "WashburneRefinery": Borderlands2RegionData("WashburneRefinery", "Travel: Washburne Refinery", []),
    "Rustyards": Borderlands2RegionData("Rustyards", "Travel: The Rustyards", []),
    "MagnysLighthouse": Borderlands2RegionData("MagnysLighthouse", "Travel: Magnys Lighthouse", []),
    "LeviathansLair": Borderlands2RegionData("LeviathansLair", "Travel: The Leviathan's Lair", []),

    "HuntersGrotto": Borderlands2RegionData("HuntersGrotto", "Travel: Hunter's Grotto", ["ScyllasGrove", "CandlerakksCragg", "ArdortonStation"]),
    "CandlerakksCragg": Borderlands2RegionData("CandlerakksCragg", "Travel: Candlerakk's Cragg", ["HuntersGrotto", "Terminus"]),
    "ArdortonStation": Borderlands2RegionData("ArdortonStation", "Travel: Ardorton Station", ["HuntersGrotto", "ScyllasGrove"]),
    "ScyllasGrove": Borderlands2RegionData("ScyllasGrove", "Travel: Scylla's Grove", ["HuntersGrotto"]),
    "Terminus": Borderlands2RegionData("Terminus", "Travel: Terminus", ["CandlerakksCragg"]),
    
    "DigistructPeak": Borderlands2RegionData("DigistructPeak", "Travel: Digistruct Peak", []),
    "DigistructPeakInner": Borderlands2RegionData("DigistructPeakInner", "Travel: Digistruct Peak", []),
    # "DigistructPeakOP5": Borderlands2RegionData("DigistructPeakOP5", "", []),

    "MarcusMercenaryShop": Borderlands2RegionData("MarcusMercenaryShop", "Travel: Marcus's Mercenary Shop", []),
    "GluttonGulch": Borderlands2RegionData("GluttonGulch", "Travel: Glutton Gulch", []),
    "RotgutDistillery": Borderlands2RegionData("RotgutDistillery", "Travel: Rotgut Distillery", []),
    "WamBamIsland": Borderlands2RegionData("WamBamIsland", "Travel: Wam Bam Island", []),
    "HallowedHollow": Borderlands2RegionData("HallowedHollow", "Travel: Hallowed Hollow", []),

}
