# auto generated from sync-defs.py
archi_data = {
    "loc": {
        "Level 2 Reached": 1,
        "Level 3 Reached": 2,
        "Level 4 Reached": 3,
        "Level 5 Reached": 4,
        "Level 6 Reached": 5,
        "Level 7 Reached": 6,
        "Level 8 Reached": 7,
        "Level 9 Reached": 8,
        "Level 10 Reached": 9,
        "Level 11 Reached": 10,
        "Level 12 Reached": 11,
        "Level 13 Reached": 12,
        "Level 14 Reached": 13,
        "Level 15 Reached": 14,
        "Level 16 Reached": 15,
        "Level 17 Reached": 16,
        "Level 18 Reached": 17,
        "Level 19 Reached": 18,
        "Level 20 Reached": 19,
        "Level 21 Reached": 20,
        "Level 22 Reached": 21,
        "Level 23 Reached": 22,
        "Level 24 Reached": 23,
        "Level 25 Reached": 24,
        "Level 26 Reached": 25,
        "Level 27 Reached": 26,
        "Level 28 Reached": 27,
        "Level 29 Reached": 28,
        "Level 30 Reached": 29,
        "Enemy: Flame Knuckle": 30,
        "Enemy: That Asshole": 31,
        "Enemy: Red": 32,
        "Enemy: Belly": 33,
        "Enemy: Red & Belly": 34,
        "Enemy: Bruce": 35,
        "Enemy: Opha Superior": 36,
        "Enemy: The Sentinel": 37,
        "Enemy: The Empyrean Sentinel": 38,
        "Enemy: The Invincible Sentinel": 39,
        "Enemy: The Invincible Empyrean Sentinel": 40,
        "Enemy: Colonel T. Zarpedon": 41,
        "Enemy: Tungsteena Zarpedon, Ascended": 42,
        "Enemy: Corporal Bob": 43,
        "Enemy: Meg": 44,
        "Enemy: Dean": 45,
        "Enemy: Lost Legion Courier": 46,
        "Enemy: Lost Legion Powersuit Noob": 47,
        "Enemy: Surrendering Dahl Soldier": 48,
        "Enemy: Raum-Kampfjet Mark V": 49,
        "Enemy: Rabid Adams": 50,
        "Enemy: Drongo Bones": 51,
        "Enemy: Boomer": 52,
        "Enemy: Tony Slows": 53,
        "Enemy: Poop Deck": 54,
        "Enemy: Bosun": 55,
        "Enemy: Deadlift": 56,
        "Enemy: Squat": 57,
        "Enemy: X-STLK-23": 58,
        "Enemy: Mini Destroyer": 59,
        "Enemy: Son of Flamey": 60,
        "Enemy: Grandson of Flamey": 61,
        "Enemy: Antagonized Kraggon": 62,
        "Enemy: Iwajira": 63,
        "Enemy: Even-More-Disgusting Tork": 64,
        "Enemy: Swagman": 65,
        "Enemy: Rooster Booster": 66,
        "Enemy: Felicity Rampant": 67,
        "Enemy: Magma Rivers": 68,
        "Enemy: Wally Wrong": 69,
        "Enemy: Fair Dinkum": 70,
        "Enemy: Giant Shuggurath of Ice": 71,
        "Enemy: Lunestalker Sr.": 72,
        "Enemy: Maureen": 73,
        "Enemy: Meat Head": 74,
        "Enemy: Oscar": 75,
        "Enemy: Eghood": 76,
        "Enemy: CL4P-L3K": 77,
        "Enemy: Master Poacher": 78,
        "Enemy: Dan Zando": 79,
        "Enemy: Nel": 80,
        "Enemy: Scavenger Beast": 81,
        "Enemy: Scav Beast Rider": 82,
        "Enemy: Lil' Scavenger Beast": 83,
        "Enemy: Lil' Scav": 84,
        "Enemy: Powersuit Felicity": 85,
        "Enemy: Defense Destroyer": 86,
        "Enemy: Lost Legion Eternal Powersuit": 87,
        "Enemy: Guardian Pondor": 88,
        "Enemy: Eclipse": 89,
        "Enemy: EOS": 90,
        "Enemy: Despair": 91,
        "Enemy: Self-Loathing": 92,
        "Enemy: The Sponx": 93,
        "Enemy: SH4D0W-TP": 94,
        "Enemy: Self-Esteem": 95,
        "Enemy: Hope": 96,
        "Enemy: Denial Subroutine": 97,
        "Enemy: 5UP4-3G0-TP": 98,
        "Enemy: Minion": 99,
        "Enemy: Teh Earworm": 100,
        "Enemy: MINAC Minion": 101,
        "Enemy: D1GN1TY-TP": 102,
        "Enemy: Shame": 103,
        "Enemy: Chip": 104,
        "Enemy: Cookie": 105,
        "Vending PandoraSimulation Firestone : Guns": 106,
        "Vending PandoraSimulation Firestone : Meds": 107,
        "Vending PandoraSimulation Firestone : Ammo": 108,
        "Vending OverlookSimulation Recall Handler Gamma: Guns": 109,
        "Vending OverlookSimulation Recall Handler Gamma: Meds": 110,
        "Vending OverlookSimulation Recall Handler Gamma: Ammo": 111,
        "Vending OverlookSimulation Gyrus Groove: Ammo": 112,
        "Vending OverlookSimulation Gyrus Groove: Meds": 113,
        "Vending TrainingFacility: Ammo": 114,
        "Vending TrainingFacility: Meds": 115,
        "Vending TrainingFacility: Guns": 116,
        "Vending Concordia Nina: Meds": 117,
        "Vending Concordia Nina: Ammo": 118,
        "Vending Concordia Earl: Meds": 119,
        "Vending Concordia Earl: Guns": 120,
        "Vending Concordia Grinder: Ammo": 121,
        "Vending Concordia Moxxi's: Ammo": 122,
        "Vending Concordia Moxxi's: Guns": 123,
        "Vending CrisisScar RedBelly Arena: Ammo": 124,
        "Vending CrisisScar RedBelly Arena: Meds": 125,
        "Vending CrisisScar RedBelly Arena: Guns": 126,
        "Vending Deck13 FastTravel: Guns": 127,
        "Vending Deck13 FastTravel: Ammo": 128,
        "Vending Deck13 FastTravel: Meds": 129,
        "Vending Deck13 TestingRange: Ammo": 130,
        "Vending Deck13 TestingRange: Guns": 131,
        "Vending FakeDeck13: Meds": 132,
        "Vending FakeDeck13: Ammo": 133,
        "Vending FakeDeck13: Guns": 134,
        "Vending Eleseer: Ammo": 135,
        "Vending Eleseer: Meds": 136,
        "Vending Eleseer: Guns": 137,
        "Vending EyeOfHelios: Ammo": 138,
        "Vending EyeOfHelios: Meds": 139,
        "Vending EyeOfHelios: Guns": 140,
        "Vending Intro CommandCenter: Ammo": 141,
        "Vending Intro Moonshot: Ammo": 142,
        "Vending Intro Moonshot: Meds": 143,
        "Vending HubOfHeroism Helios Immigration Station: Ammo": 144,
        "Vending HubOfHeroism Helios Immigration Station: Meds": 145,
        "Vending HubOfHeroism Central Terminal: Ammo": 146,
        "Vending HubOfHeroism Central Terminal: Meds": 147,
        "Vending HubOfHeroism Central Terminal: Guns": 148,
        "Vending LunarLaunchingStation Start: Ammo": 149,
        "Vending LunarLaunchingStation Start: Meds": 150,
        "Vending LunarLaunchingStation Start: Guns": 151,
        "Vending LunarLaunchingStation Hub: Ammo": 152,
        "Vending LunarLaunchingStation Hub: Meds": 153,
        "Vending LunarLaunchingStation Eye Entrance: Ammo": 154,
        "Vending LunarLaunchingStation Eye Entrance: Meds": 155,
        "Vending Motherlessboard Entrance: Guns": 156,
        "Vending Motherlessboard Entrance: Meds": 157,
        "Vending Motherlessboard Entrance: Ammo": 158,
        "Vending Motherlessboard Memory Bank 2: Meds": 159,
        "Vending Motherlessboard Memory Bank 2: Ammo": 160,
        "Vending Motherlessboard Memory Bank 2: Guns": 161,
        "Vending Motherlessboard Memory Bank 4: Meds": 162,
        "Vending Motherlessboard Memory Bank 4: Ammo": 163,
        "Vending Motherlessboard Memory Bank 4: Guns": 164,
        "Vending OutfallPumpingStation Start: Ammo": 165,
        "Vending OutfallPumpingStation Start: Meds": 166,
        "Vending OutfallPumpingStation Start: Guns": 167,
        "Vending OutlandsCanyon Start: Ammo": 168,
        "Vending OutlandsCanyon Start: Meds": 169,
        "Vending OutlandsCanyon Start: Guns": 170,
        "Vending OutlandsCanyon Fingersmith Halls: Ammo": 171,
        "Vending OutlandsCanyon Fingersmith Halls: Meds": 172,
        "Vending OutlandsCanyon Fingersmith Halls: Guns": 173,
        "Vending OutlandsSpur Start: Ammo": 174,
        "Vending OutlandsSpur Start: Meds": 175,
        "Vending OutlandsSpur Processing Plant: Ammo": 176,
        "Vending OutlandsSpur Processing Plant: Meds": 177,
        "Vending OutlandsSpur Pumping Station: Ammo": 178,
        "Vending OutlandsSpur Pumping Station: Meds": 179,
        "Vending PitysFall Start: Ammo": 180,
        "Vending PitysFall Start: Meds": 181,
        "Vending PitysFall Start: Guns": 182,
        "Vending PitysFall Drakensburg Gangway: Ammo": 183,
        "Vending PitysFall Drakensburg Gangway: Meds": 184,
        "Vending PitysFall Drakensburg Gangway: Guns": 185,
        "Vending PitysFall Starboard Ascent: Ammo": 186,
        "Vending PitysFall Engine Room: Ammo": 187,
        "Vending PitysFall Engine Room: Meds": 188,
        "Vending PitysFall Command Center: Ammo": 189,
        "Vending PitysFall Command Center: Meds": 190,
        "Vending RegolithRange Start: Ammo": 191,
        "Vending RegolithRange Start: Meds": 192,
        "Vending RegolithRange Waystation: Ammo": 193,
        "Vending RegolithRange Waystation: Meds": 194,
        "Vending RnD Start: Ammo": 195,
        "Vending RnD Start: Meds": 196,
        "Vending SerenitysWaste Janey: Ammo": 197,
        "Vending SerenitysWaste Janey: Meds": 198,
        "Vending Subconscious The Subconscious: Meds": 199,
        "Vending Subconscious The Subconscious: Ammo": 200,
        "Vending Subconscious Insertion Shard: Meds": 201,
        "Vending Subconscious Insertion Shard:  Guns": 202,
        "Vending subconscious Insertion Shard:  Ammo": 203,
        "Vending Subconscious Terrorhead Gorge:  Ammo": 204,
        "Vending Subconscious Terrorhead Gorge:  Meds": 205,
        "Vending Subconscious Sub-Subconscious: Meds": 206,
        "Vending Subconscious Sub-Subconscious: Guns": 207,
        "Vending Subconscious Sub-Subconscious: Ammo": 208,
        "Vending Subconscious Subliminal Plaza Entrance: Meds": 209,
        "Vending Subconscious Subliminal Plaza Entrance: Ammo": 210,
        "Vending Subconscious Subliminal Plaza: Meds": 211,
        "Vending Cortex Terminal Dendrite: Ammo": 212,
        "Vending Cortex Terminal Dendrite: Meds": 213,
        "Vending Cortex Terminal Dendrite: Guns": 214,
        "Vending Cortex The Cortex: Meds": 215,
        "Vending Cortex The Cortex: Guns": 216,
        "Vending Cortex The Cortex: Ammo": 217,
        "Vending The MeriffsOffice: Ammo": 218,
        "Vending The MeriffsOffice: Meds": 219,
        "Vending Nexus Positive Terminal: Guns": 220,
        "Vending Nexus Positive Terminal: Meds": 221,
        "Vending Nexus SYS_ADMIN: Ammo": 222,
        "Vending Nexus SYS_ADMIN: Meds": 223,
        "Vending Nexus Positive Terminal: Ammo": 224,
        "Vending Nexus SYS_ADMIN: Guns": 225,
        "Vending TitanIndustrialFacility Start: Ammo": 226,
        "Vending TitanIndustrialFacility Start: Meds": 227,
        "Vending TitanIndustrialFacility Start: Guns": 228,
        "Vending TitanIndustrialFacility Nexus: Ammo": 229,
        "Vending TitanIndustrialFacility Nexus: Meds": 230,
        "Vending TitanIndustrialFacility Production Plant Entrance: Ammo": 231,
        "Vending TitanRobotPlant Start: Ammo": 232,
        "Vending TitanRobotPlant Start: Meds": 233,
        "Vending TitanRobotPlant Start: Guns": 234,
        "Vending TitanRobotPlant Power Control: Guns": 235,
        "Vending TitanRobotPlant Unit Embarkation: Ammo": 236,
        "Vending TitanRobotPlant Unit Embarkation: Meds": 237,
        "Vending TitanRobotPlant Unit Embarkation: Guns": 238,
        "Vending TritonFlats Diemens Crater: Ammo": 239,
        "Vending TritonFlats Diemens Crater: Meds": 240,
        "Vending TritonFlats Diemens Crater: Guns": 241,
        "Vending TritonFlats Banjo Point: Ammo": 242,
        "Vending TritonFlats Banjo Point: Meds": 243,
        "Vending TritonFlats The Pale: Ammo": 244,
        "Vending TritonFlats Lunar Junction: Meds": 245,
        "Vending TritonFlats Lunar Junction: Guns": 246,
        "Vending TritonFlats Darksiders: Meds": 247,
        "Vending TritonFlats Darksiders: Guns": 248,
        "Vending TritonFlats Flinder's Needle: Ammo": 249,
        "Vending TritonFlats Flinder's Needle: Meds": 250,
        "Vending TychosRibs: Ammo": 251,
        "Vending TychosRibs: Meds": 252,
        "Vending VeinsOfHelios Start: Ammo": 253,
        "Vending VeinsOfHelios Start: Meds": 254,
        "Vending VeinsOfHelios Start: Guns": 255,
        "Vending VoragoSolitude Start: Ammo": 256,
        "Vending VoragoSolitude Start: Meds": 257,
        "Vending VoragoSolitude Start: Guns": 258,
        "Vending Holodome Start: Meds": 259,
        "Vending Holodome Start: Guns": 260,
        "Vending Holodome Arena: Ammo": 261,
        "Vending Holodome Arena: Meds": 262,
        "Vending Holodome Start: Ammo": 263,
        "Vending Holodome Arena: Guns": 264,
        "Generic: Badass": 265,
        "Generic: Kraggon": 266,
        "Generic: Rathyd": 267,
        "Generic: Shuggurath": 268,
        "Generic: Stalker": 269,
        "Generic: Thresher": 270,
        "Generic: Tork": 271,
        "Generic: Scav": 272,
        "Generic: Lunatic": 273,
        "Generic: Outlaw": 274,
        "Generic: Lost Legion": 275,
        "Generic: Powersuit": 276,
        "Generic: Boil": 277,
        "Generic: Guardian": 278,
        "Generic: Midget": 279,
        "Generic: Jet Fighter": 280,
        "Generic: Robot": 281,
        "Generic: B4nD1T": 282,
        "Generic: Insecurity": 283,
        "Generic: Bug": 284,
        "Generic: Glitch": 285,
        "Generic: Virus": 286,
        "Challenge Elemental: Chemical Burn": 287,
        "Challenge Elemental: Frost Bite": 288,
        "Challenge Elemental: Watt's Up?": 289,
        "Challenge Elemental: Way of the Enkindling": 290,
        "Challenge Elemental: Some Like It Hot": 291,
        "Challenge Elemental: Toxic Takedown": 292,
        "Challenge Elemental: Out with a Bang": 293,
        "Challenge Melee: Martial Marshal": 294,
        "Challenge Melee: Captain Cutty": 295,
        "Challenge Assault Rifle: Aim to Please": 296,
        "Challenge Assault Rifle: Assault With a Deadly Weapon": 297,
        "Challenge Assault Rifle: Hot Lead Injection": 298,
        "Challenge Assault Rifle: Crouch Potato": 299,
        "Challenge Assault Rifle: Assaulty Dog": 300,
        "Challenge Laser: Aggressive Lasik": 301,
        "Challenge Laser: Light 'em Up": 302,
        "Challenge Laser: Battle Star": 303,
        "Challenge Laser: Pew Pew": 304,
        "Challenge Laser: I See the Light": 305,
        "Challenge Rocket Launcher: Get a Rocket up Ya": 306,
        "Challenge Rocket Launcher: Collateral Damage": 307,
        "Challenge Rocket Launcher: Punker Buster": 308,
        "Challenge Rocket Launcher: Hand of God": 309,
        "Challenge Rocket Launcher: Missile Magnet": 310,
        "Challenge Rocket Launcher: Magic Missile": 311,
        "Challenge Pistol: Pistoleer": 312,
        "Challenge Pistol: Trigger Happy": 313,
        "Challenge Pistol: Magnum Maestro": 314,
        "Challenge Pistol: Gunslinger": 315,
        "Challenge Pistol: Pistol Whipped": 316,
        "Challenge Shotgun: Hello Uncle Buckshot": 317,
        "Challenge Shotgun: Boomstick Boogie": 318,
        "Challenge Shotgun: Shotty Workmanship": 319,
        "Challenge Shotgun: Over Achiever": 320,
        "Challenge Shotgun: Shotgunning the Breeze": 321,
        "Challenge SMG: Take It All!": 322,
        "Challenge SMG: Bring the Pain": 323,
        "Challenge SMG: Nice Spray Job": 324,
        "Challenge SMG: And Stay Down!": 325,
        "Challenge SMG: Dinky Death Dealer": 326,
        "Challenge Sniper: Melon Splitter": 327,
        "Challenge Sniper: Sharp Shooter": 328,
        "Challenge Sniper: Ol' Skool": 329,
        "Challenge Sniper: Penetrating Wound": 330,
        "Challenge Sniper: Clean and Simple": 331,
        "Challenge Sniper: Critical Reception": 332,
        "Challenge Sniper: Windage Adjustment": 333,
        "Challenge Recovery: Soup's Up!": 334,
        "Challenge Recovery: Rollin' the Ice": 335,
        "Challenge Recovery: Had a Bit of a Shocker": 336,
        "Challenge Recovery: The Phoenix": 337,
        "Challenge Recovery: Up Unt at Zem": 338,
        "Challenge Recovery: Doctor Feels Good": 339,
        "Challenge Recovery: Better You Than Me": 340,
        "Challenge Recovery: There Can Be Only... Me": 341,
        "Challenge Shields: Ammo Eater": 342,
        "Challenge Shields: Amplitude Killulation": 343,
        "Challenge Shields: Nova Say Die": 344,
        "Challenge Shields: Wet Work": 345,
        "Challenge Shields: That'll Learn Ya": 346,
        "Challenge Vehicles: Shut Up and Drive": 347,
        "Challenge Vehicles: Splat 'n' Slide": 348,
        "Challenge Vehicles: Fender Bender": 349,
        "Challenge Vehicles: Improvise, Adapt, Overcome": 350,
        "Challenge Vehicles: Road Warrior": 351,
        "Challenge Vehicles: Pancakes for Breakfast": 352,
        "Challenge Economy: Over the Moon": 353,
        "Challenge Economy: Mom Would Be Proud": 354,
        "Challenge Economy: Impulse Shopper": 355,
        "Challenge Economy: Pawn Broker": 356,
        "Challenge Economy: Mr. Money Pits": 357,
        "Challenge Economy: Trade Negotiations": 358,
        "Challenge Enemies: Kiss My Badass": 359,
        "Challenge Enemies: Crash & Burn": 360,
        "Challenge Enemies: Get Some!": 361,
        "Challenge Enemies: No Suit for You!": 362,
        "Challenge Enemies: More Where That Came From": 363,
        "Challenge Enemies: Not So Tough Now": 364,
        "Challenge Enemies: Dose of Death": 365,
        "Challenge Enemies: Slayer of Titans": 366,
        "Challenge Enemies: Big Game Hunt": 367,
        "Challenge Enemies: Gift That Keeps Giving": 368,
        "Challenge Enemies: Exterminator": 369,
        "Challenge Enemies: The One That Says B.A.M.F.": 370,
        "Challenge Enemies: It Wasn't Yours, Anyway": 371,
        "Challenge Enemies: Die, Moon Jerks": 372,
        "Challenge Enemies: Space Dead": 373,
        "Challenge Enemies: That Was Unpleasant": 374,
        "Challenge Enemies: Torkin' Out the Trash": 375,
        "Challenge Enemies: Pest Control": 376,
        "Challenge General: The Duelist": 377,
        "Challenge General: Barrel of Laughs": 378,
        "Challenge General: Having Trouble Breathing?": 379,
        "Challenge General: Projectile Proliferation": 380,
        "Challenge General: Last Gasp": 381,
        "Challenge General: Day of the Dead": 382,
        "Challenge General: Dark Sider": 383,
        "Challenge General: Executioner": 384,
        "Challenge General: Action Hero": 385,
        "Challenge General: Comet Crash": 386,
        "Challenge General: Ice to Meet You": 387,
        "Challenge General: One Man's Trash": 388,
        "Challenge General: Throw Me the Money!": 389,
        "Challenge Grenade: Home Nade Cookin'": 390,
        "Challenge Grenade: Sprayowee": 391,
        "Challenge Grenade: Betty Boom": 392,
        "Challenge Grenade: Big MIRV": 393,
        "Challenge Grenade: See Ya on the Other Side": 394,
        "Challenge Grenade: Pass the Chianti": 395,
        "Challenge Grinder: Master Chef": 396,
        "Challenge Grinder: Greater Than the Sum of its Parts": 397,
        "Challenge Grinder: This Time for Sure": 398,
        "Challenge Grinder: The Daily Grind": 399,
        "Challenge Loot: Aaaaaand OPEN!": 400,
        "Challenge Loot: Scrounging Around": 401,
        "Challenge Loot: One for Every Occasion": 402,
        "Challenge Loot: Rare as Rocking Horse...": 403,
        "Challenge Loot: A Chunk of Purest Green": 404,
        "Challenge Loot: The Happiest Color": 405,
        "Challenge Loot: Purple Haze": 406,
        "Challenge Loot: Junkyard Dog": 407,
        "Challenge Low Gravity: Eagle Eye": 408,
        "Challenge Low Gravity: Slampage!": 409,
        "Challenge Low Gravity: Roger Slamjet": 410,
        "Challenge Low Gravity: Boosted": 411,
        "Challenge Low Gravity: Death from Above": 412,
        "Challenge Low Gravity: Dragon Punch": 413,
        "Challenge Misc: We Have a Contender": 414,
        "Challenge Misc: OC/DC": 415,
        "Challenge Misc: Little on the Side": 416,
        "Challenge Tycho's Ribs: That Was Your Own Fault...": 417,
        "Challenge Tycho's Ribs: Mystery of the Crystal Skulls": 418,
        "Challenge Tycho's Ribs: Cult of the Vault": 419,
        "Challenge Serenity's Waste: Phonically Challenged": 420,
        "Challenge Serenity's Waste: Cult of the Vault": 421,
        "Challenge Hyperion Hub of Heroism: Feed the Fishes": 422,
        "Challenge Hyperion Hub of Heroism: Flame Off": 423,
        "Challenge Hyperion Hub of Heroism: Oh, the Humanity": 424,
        "Challenge Hyperion Hub of Heroism: Perfect Dive": 425,
        "Challenge Hyperion Hub of Heroism: Playing Chicken": 426,
        "Challenge Hyperion Hub of Heroism: Cult of the Vault": 427,
        "Challenge Hyperion Hub of Heroism: Window Shopping": 428,
        "Challenge Crisis Scar: Red Last": 429,
        "Challenge Crisis Scar: Lava Leap": 430,
        "Challenge Crisis Scar: Up Magma": 431,
        "Challenge Crisis Scar: Cult of the Vault": 432,
        "Challenge Titan Industrial Facility: Fast Shooter": 433,
        "Challenge Titan Industrial Facility: Be Quick or Be Dead": 434,
        "Challenge Titan Industrial Facility: Breath Holder": 435,
        "Challenge Titan Industrial Facility: Cult of the Vault": 436,
        "Challenge Titan Robot Production Plant: Cult of the Vault": 437,
        "Challenge Titan Robot Production Plant: Turret Engineer": 438,
        "Challenge Titan Robot Production Plant: I Can Do This Alone": 439,
        "Challenge Regolith Range: Dead Set": 440,
        "Challenge Regolith Range: Dead Weight": 441,
        "Challenge Regolith Range: Insulated": 442,
        "Challenge Regolith Range: Cult of the Vault": 443,
        "Challenge Vorago Solitude: Mind the Gap": 444,
        "Challenge Vorago Solitude: Eridian Archaeology": 445,
        "Challenge Vorago Solitude: Vorago's Dig Sights": 446,
        "Challenge Vorago Solitude: Cult of the Vault": 447,
        "Challenge Pity's Fall: You Call That a Shield?": 448,
        "Challenge Pity's Fall: A Conventional Death": 449,
        "Challenge Pity's Fall: Engineering 201": 450,
        "Challenge Pity's Fall: Bosun's Mate": 451,
        "Challenge Pity's Fall: Cult of the Vault": 452,
        "Challenge Eye of Helios: Finish Him": 453,
        "Challenge Eye of Helios: Loose Cannon": 454,
        "Challenge Eye of Helios: Power Play": 455,
        "Challenge Eye of Helios: Training Day": 456,
        "Challenge Eye of Helios: Tread Carefully": 457,
        "Challenge Eye of Helios: Cult of the Vault": 458,
        "Challenge Eleseer: One Step Ahead of You": 459,
        "Challenge Eleseer: Cult of the Vault": 460,
        "Challenge Eleseer: Aim for the Little Ones": 461,
        "Challenge Veins of Helios: Cannibal Corpse": 462,
        "Challenge Veins of Helios: Catch a Ride": 463,
        "Challenge Veins of Helios: Honorary Foreman": 464,
        "Challenge Veins of Helios: Jump for Joy": 465,
        "Challenge Veins of Helios: Thrill Seeker": 466,
        "Challenge Veins of Helios: Cult of the Vault": 467,
        "Challenge Jack's Office: Fiery Filer": 468,
        "Challenge Jack's Office: Cult of the Vault": 469,
        "Challenge Abandoned Training Facility: Jack Be Nimble": 470,
        "Challenge Abandoned Training Facility: Best Served Hot": 471,
        "Challenge Abandoned Training Facility: Cult of the Vault": 472,
        "Challenge Stanton's Liver: Hidden Treasure": 473,
        "Challenge Stanton's Liver: Killing Time": 474,
        "Challenge Stanton's Liver: Leap of Faith": 475,
        "Challenge Stanton's Liver: Cult of the Vault": 476,
        "Challenge Outlands Spur: Boomer's Bane": 477,
        "Challenge Outlands Spur: OHS Inspection": 478,
        "Challenge Outlands Spur: Pickle Picker": 479,
        "Challenge Outlands Spur: Cult of the Vault": 480,
        "Challenge Outlands Canyon: King of the Hill": 481,
        "Challenge Outlands Canyon: No Animal Harmed": 482,
        "Challenge Outlands Canyon: Perfect Timing": 483,
        "Challenge Outlands Canyon: Cult of the Vault": 484,
        "Challenge Research and Development: Data Recovery": 485,
        "Challenge Research and Development: Feed the Fish": 486,
        "Challenge Research and Development: Hook Shot": 487,
        "Challenge Research and Development: Leap of Faith II": 488,
        "Challenge Research and Development: Cult of the Vault": 489,
        "Challenge Research and Development: Can't See Me": 490,
        "Challenge Concordia: Clairvoyant": 491,
        "Challenge Concordia: Doin' the Robot": 492,
        "Challenge Concordia: It's a Fair Cop": 493,
        "Challenge Concordia: Jackpot!": 494,
        "Challenge Concordia: Cult of the Vault": 495,
        "Challenge Sub-Level 13: Cult of the Vault": 496,
        "Challenge Tycho's Ribs: History of Elpis' Interior": 497,
        "Challenge Vorago Solitude: Entirely Metal Outerwear": 498,
        "Challenge Stanton's Liver: Digging up the Past": 499,
        "Challenge Hyperion Hub of Heroism: Wise Owl": 500,
        "Challenge Hyperion Hub of Heroism: Interplanetary Ninja Chatterbox": 501,
        "Challenge Hyperion Hub of Heroism: Hard Knocks": 502,
        "Challenge Hyperion Hub of Heroism: Robotic Aspirations": 503,
        "Challenge Claptrap: Clean Sweep": 504,
        "Challenge Claptrap: Claptomaniac": 505,
        "Challenge Claptrap: Volakillity": 506,
        "Challenge Claptrap: I Like Surprises...": 507,
        "Challenge Claptrap: 99 Problems and a Glitch Aint One": 508,
        "Challenge Deck 13 \u00bd: Cult of the Vault": 509,
        "Challenge Deck 13.5: Platform Panic": 510,
        "Challenge Deck 13.5: Cult of the Vault": 511,
        "Challenge Cluster 00773 P4ND0R4: Cult of the Vault": 512,
        "Challenge Cluster 00773 P4ND0R4: Void Rage": 513,
        "Challenge Motherlessboard: Advanced Search": 514,
        "Challenge Motherlessboard: Bandwidth Hog": 515,
        "Challenge Motherlessboard: Board Jumper": 516,
        "Challenge Motherlessboard: Cult of the Vault": 517,
        "Challenge The Nexus: Dodgewall": 518,
        "Challenge The Nexus: Cult of the Vault": 519,
        "Challenge Cluster 99002 0V3RL00K: My Balloons! Those are my Balloons!": 520,
        "Challenge Cluster 99002 0V3RL00K: Faptrap": 521,
        "Challenge Cluster 99002 0V3RL00K: Cult of the Vault": 522,
        "Challenge The Cortex: Circuit Jumper": 523,
        "Challenge The Cortex: Cult of the Vault": 524,
        "Challenge Subconscious: Bobble, Bobble, Soil and Rubble": 525,
        "Challenge Subconscious: Finders Creepers": 526,
        "Challenge Subconscious: A Bubble for your Thoughts": 527,
        "Challenge Subconscious: Cult of the Vault": 528,
        "Challenge The Holodome: Power Surge": 529,
        "Challenge The Holodome: Take to the Skies": 530,
        "Challenge The Holodome: Cult of the Vault": 531,
        "Red Chest PandoraSimulation: B4D S3CT0R Tower": 532,
        "Red Chest PandoraSimulation: H-Source Room": 533,
        "Red Chest OverlookSimulation: Denial Subroutine Fight": 534,
        "Chest Concordia: Moxxi's Toy Box": 535,
        "Chest CrisisScar: Comms Facility Roof": 536,
        "Chest CrisisScar: Power Substation": 537,
        "Chest CrisisScar: RedBelly Chest #1": 538,
        "MoonChest CrisisScar: RedBelly Chest #2": 539,
        "Chest Eleseer: WSW corner": 540,
        "Special Eleseer: Collect Vault Symbol": 541,
        "MoonChest EyeOfHelios: Laser Catwalk": 542,
        "MoonChest EyeOfHelios: Above Laser Exit": 543,
        "Chest Intro: Behind That Asshole": 544,
        "Chest HubOfHeroism: Central Terminal": 545,
        "Chest HubOfHeroism: World of Shopping": 546,
        "Chest HubOfHeroism: Hall of Wonders": 547,
        "Chest Launching Station: Power Core Alpha": 548,
        "Chest Launching Station: Power Core Beta": 549,
        "Chest JacksOffice: Secret Chest": 550,
        "Chest Motherlessboard: Memory Bank 4": 551,
        "MoonChest OutfallPumpingStation: MKV Reward": 552,
        "Chest OutlandsCanyon: Bogan's Warren": 553,
        "Chest OutlandsCanyon: Research Facility": 554,
        "Chest OutlandsCanyon: House Overlooking BBall Court": 555,
        "Chest OutlandsSpur: Processing Plant": 556,
        "Chest OutlandsSpur: Pumping Station": 557,
        "Chest OutlandsSpur: Top of Treatment Plant": 558,
        "Chest PitysFall: Starboard Ascent": 559,
        "Chest PitysFall: Hangar Bay": 560,
        "MoonChest PitysFall: Engineering": 561,
        "MoonChest PitysFall: AI Hub": 562,
        "Chest PitysFall: AI Hub": 563,
        "Chest PitysFall: The Secret Chamber Reward": 564,
        "Chest RegolithRange: Deadlift Chest #1": 565,
        "Chest RegolithRange: Deadlift Chest #2": 566,
        "MoonChest RegolithRange: Waystation Tower Roof": 567,
        "Chest RegolithRange: Last Requests Reward": 568,
        "Chest RnD: Aquarium": 569,
        "Chest RnD: Synaptic Processing Chest #1": 570,
        "Chest RnD: Synaptic Processing Chest #2": 571,
        "Special RnD: Pet Benjamin Blue": 572,
        "Chest StantonsLiver: Piraud's Thrutch": 573,
        "Chest SubLevel13: Vents": 574,
        "Chest SubLevel13: ControlRoom": 575,
        "Chest Subconscious:Terrorhead Gorge": 576,
        "Chest Subconscious: The Sum of Some Fears": 577,
        "Chest Subconscious: Top of Sub-Subconscious": 578,
        "Red Chest Cortex: SH4D0W-TP Chest #1": 579,
        "Red Chest Cortex: SH4D0W-TP Chest #2": 580,
        "GlitchChest Cortex: l33t h4X0rz reward #1": 581,
        "GlitchChest Cortex: l33t h4X0rz reward #2": 582,
        "Chest TitanIndustrialFacility: Stingray Factory: Atrium": 583,
        "Chest TitanIndustrialFacility: Stingray Factory: Main Hall": 584,
        "MoonChest TitanRobotPlant: Locomotion Assembly": 585,
        "MoonChest TitanRobotPlant: Unit Embarkation": 586,
        "Chest TitanRobotPlant: Unit Embarkation #1": 587,
        "Chest TitanRobotPlant: Unit Embarkation #2": 588,
        "Chest TitanRobotPlant: Unit Embarkation #3": 589,
        "Red Chest TritonFlats: Chunder's Hole": 590,
        "Red Chest TritonFlats: Flinder's Needle": 591,
        "Red Chest TritonFlats: The Grabba": 592,
        "Chest TychosRibs: Compression Chamber": 593,
        "Chest TychosRibs: Particle Collection Chamber": 594,
        "Chest TychosRibs: Easter Egg Main Chest": 595,
        "Chest TychosRibs: Easter Egg Secret Chest": 596,
        "Chest TychosRibs: Exhaust Port": 597,
        "Chest VeinsOfHelios: South Chest": 598,
        "Chest VeinsOfHelios: Don't Get Cocky Reward #1": 599,
        "Chest VeinsOfHelios: Don't Get Cocky Reward #2": 600,
        "Chest VeinsOfHelios: Don't Get Cocky Reward #3": 601,
        "Chest VeinsOfHelios: North Chest": 602,
        "Chest VoragoSolitude: East Pumping Station": 603,
        "Chest VoragoSolitude: Solitude Junction": 604,
        "Chest VoragoSolitude: Solitude's Edge": 605,
        "Chest RegolithRange: Leaning Tower Roof": 606,
        "Chest Holodome: Vault Keys Reward #1": 607,
        "Chest Holodome: Vault Keys Reward #2": 608,
        "Chest Holodome: Vault Keys Reward #3": 609,
        "Chest Nexus: H0N3Y-P0T Chest": 610,
        "GlitchChest Nexus: Trash Compactor": 611,
        "Chest Motherlessboard: Quantum Shunt": 612,
        "Common Shield Found": 613,
        "Uncommon Shield Found": 614,
        "Rare Shield Found": 615,
        "VeryRare Shield Found": 616,
        "Legendary Shield Found": 617,
        "Unique Shield Found": 618,
        "Common GrenadeMod Found": 619,
        "Uncommon GrenadeMod Found": 620,
        "Rare GrenadeMod Found": 621,
        "VeryRare GrenadeMod Found": 622,
        "Legendary GrenadeMod Found": 623,
        "Unique GrenadeMod Found": 624,
        "Common ClassMod Found": 625,
        "Uncommon ClassMod Found": 626,
        "Rare ClassMod Found": 627,
        "VeryRare ClassMod Found": 628,
        "Legendary ClassMod Found": 629,
        "Common Oz Kit Found": 630,
        "Uncommon Oz Kit Found": 631,
        "Rare Oz Kit Found": 632,
        "VeryRare Oz Kit Found": 633,
        "Legendary Oz Kit Found": 634,
        "Unique Oz Kit Found": 635,
        "Common Pistol Found": 636,
        "Uncommon Pistol Found": 637,
        "Rare Pistol Found": 638,
        "VeryRare Pistol Found": 639,
        "Legendary Pistol Found": 640,
        "Glitch Pistol Found": 641,
        "Unique Pistol Found": 642,
        "Common Shotgun Found": 643,
        "Uncommon Shotgun Found": 644,
        "Rare Shotgun Found": 645,
        "VeryRare Shotgun Found": 646,
        "Legendary Shotgun Found": 647,
        "Glitch Shotgun Found": 648,
        "Unique Shotgun Found": 649,
        "Common SMG Found": 650,
        "Uncommon SMG Found": 651,
        "Rare SMG Found": 652,
        "VeryRare SMG Found": 653,
        "Legendary SMG Found": 654,
        "Glitch SMG Found": 655,
        "Unique SMG Found": 656,
        "Common SniperRifle Found": 657,
        "Uncommon SniperRifle Found": 658,
        "Rare SniperRifle Found": 659,
        "VeryRare SniperRifle Found": 660,
        "Legendary SniperRifle Found": 661,
        "Glitch SniperRifle Found": 662,
        "Unique SniperRifle Found": 663,
        "Common AssaultRifle Found": 664,
        "Uncommon AssaultRifle Found": 665,
        "Rare AssaultRifle Found": 666,
        "VeryRare AssaultRifle Found": 667,
        "Legendary AssaultRifle Found": 668,
        "Glitch AssaultRifle Found": 669,
        "Unique AssaultRifle Found": 670,
        "Common RocketLauncher Found": 671,
        "Uncommon RocketLauncher Found": 672,
        "Rare RocketLauncher Found": 673,
        "VeryRare RocketLauncher Found": 674,
        "Legendary RocketLauncher Found": 675,
        "Glitch RocketLauncher Found": 676,
        "Unique RocketLauncher Found": 677,
        "Common Laser Found": 678,
        "Uncommon Laser Found": 679,
        "Rare Laser Found": 680,
        "VeryRare Laser Found": 681,
        "Legendary Laser Found": 682,
        "Glitch Laser Found": 683,
        "Unique Laser Found": 684,
        "Quest: Welcome to Helios": 685,
        "Quest: Lost Legion Invasion": 686,
        "Quest: Land Among the Stars": 687,
        "Quest: Follow Your Heart": 688,
        "Quest: Tales from Elpis": 689,
        "Quest: Last Requests": 690,
        "Quest: Marooned": 691,
        "Quest: Nova? No Problem!": 692,
        "Quest: Torgue-o! Torgue-o!": 693,
        "Quest: Systems Jammed": 694,
        "Quest: Wherefore Art Thou?": 695,
        "Quest: The Empty Billabong": 696,
        "Quest: All the Little Creatures": 697,
        "Quest: Recruitment Drive": 698,
        "Quest: A New Direction": 699,
        "Quest: Bunch of Ice Holes": 700,
        "Quest: Grinders": 701,
        "Quest: Pop Racing": 702,
        "Quest: To Arms!": 703,
        "Quest: Zapped 1.0": 704,
        "Quest: Zapped 2.0": 705,
        "Quest: Zapped 3.0": 706,
        "Quest: Boomshakalaka": 707,
        "Quest: Space Slam": 708,
        "Quest: Intelligences of the Artificial Persuasion": 709,
        "Quest: The Secret Chamber": 710,
        "Quest: Wiping the Slate": 711,
        "Quest: No Such Thing as a Free Launch": 712,
        "Quest: Nothing is Never an Option": 713,
        "Quest: Treasures of ECHO Madre": 714,
        "Quest: Another Pickle": 715,
        "Quest: Home Delivery": 716,
        "Quest: Rough Love": 717,
        "Quest: Let's Build a Robot Army": 718,
        "Quest: Sub-Level 13": 719,
        "Quest: Sub-Level 13: Part 2": 720,
        "Quest: The Voyage of Captain Chef": 721,
        "Quest: Home Sweet Home": 722,
        "Quest: Hot Head": 723,
        "Quest: Voice Over": 724,
        "Quest: Boarding Party": 725,
        "Quest: An Urgent Message": 726,
        "Quest: Handsome AI": 727,
        "Quest: Paint Job": 728,
        "Quest: Kill Meg": 729,
        "Quest: Science and Violence": 730,
        "Quest: Infinite Loop": 731,
        "Quest: Fresh Air": 732,
        "Quest: It Ain't Rocket Surgery": 733,
        "Quest: Lab 19": 734,
        "Quest: Cleanliness Uprising": 735,
        "Quest: Watch Your Step": 736,
        "Quest: Red, Then Dead": 737,
        "Quest: Things That Go Boom": 738,
        "Quest: To the Moon": 739,
        "Quest: Lock and Load": 740,
        "Quest: Quarantine: Back On Schedule": 741,
        "Quest: Quarantine: Infestation": 742,
        "Quest: In Perfect Hibernation": 743,
        "Quest: Trouble with Space Hurps": 744,
        "Quest: Don't Get Cocky": 745,
        "Quest: Eradicate!": 746,
        "Quest: Eye to Eye": 747,
        "Quest: Picking Up the Pieces": 748,
        "Quest: These are the Bots": 749,
        "Quest: The Don": 750,
        "Quest: Return of Captain Chef": 751,
        "Quest: Don't Shoot the Messenger": 752,
        "Quest: Z8N-TP": 753,
        "Quest: The Beginning of the End": 754,
        "Quest: The Bestest Story Ever Told": 755,
        "Quest: Guardian Hunter": 756,
        "Quest: Sterwin Forever": 757,
        "Quest: DAHL Combat Training: Round 1": 758,
        "Quest: DAHL Combat Training: Round 2": 759,
        "Quest: DAHL Combat Training: Round 3": 760,
        "Quest: DAHL Combat Training: Round 4": 761,
        "Quest: DAHL Combat Training: Round 5": 762,
        "Quest: Alpha": 763,
        "Quest: Beta": 764,
        "Quest: Delta": 765,
        "Quest: Gamma": 766,
        "Quest: l33t h4X0rz": 767,
        "Quest: Enter the Claptrap": 768,
        "Quest: File Search": 769,
        "Quest: END OF LINE": 770,
        "Quest: System Shutdown": 771,
        "Quest: The Psychology of a Claptrap": 772,
        "Quest: A Deadlier Game": 773,
        "Quest: Byte Club": 774,
        "Quest: Chip's Data Mining Adventure": 775,
        "Quest: 3G0-TP": 776,
        "Quest: 1D-TP": 777,
        "Quest: Rose Tinting": 778,
        "Quest: Corrosion of Dignity": 779,
        "Quest: Spyware Who Came in from the Cold": 780,
        "Quest: You Can Stop the Music": 781,
        "Quest: The Sum of Some Fears": 782,
        "Quest: 5UP4-3G0-TP": 783,
        "Quest: The Temple of Boom": 784,
        "Quest: h4X0rz": 785,
        "Quest: Digistructed Madness: Round 1": 786,
        "Quest: Digistructed Madness: Round 2": 787,
        "Quest: Digistructed Madness: Round 3": 788,
        "Quest: Digistructed Madness: Round 4": 789,
        "Quest: Digistructed Madness: Round 5": 790,
        "Quest: Digistructed Madness: The Badass Round": 791
    },
    "item": {
        "3 Skill Points": 1,
        "3 Skill Points (p)": 2,
        "Progressive Money Cap": 3,
        "Progressive Weapon Slot": 4,
        "$100": 5,
        "10 Moonstones": 6,
        "Progressive Jump": 7,
        "Melee": 8,
        "Crouch": 9,
        "Progressive Sprint": 10,
        "Vehicle Fire": 11,
        "Moxxtail: Moxxis' Choice": 12,
        "Moxxtail: Lemon Lime & Bullets": 13,
        "Moxxtail: Gargle Blaster": 14,
        "Moxxtail: Fanalian Toddy": 15,
        "Moxxtail: Squill Syrup": 16,
        "Moxxtail: Penargilon Kangaroo": 17,
        "Moxxtail: Brick's Fist": 18,
        "Moxxtail: Hot Gazpacho": 19,
        "Moxxtail: Replicated Kali-fal": 20,
        "10% Exp": 21,
        "Travel: Abandoned Training Facility": 22,
        "Travel: Cluster 00773 P4ND0R4": 23,
        "Travel: Cluster 99002 0V3RL00K": 24,
        "Travel: Concordia": 25,
        "Travel: Crisis Scar": 26,
        "Travel: Deck 13 \u00bd": 27,
        "Travel: Deck 13.5": 28,
        "Travel: Eleseer": 29,
        "Travel: Eye of Helios": 30,
        "Travel: Hyperion Hub of Heroism": 31,
        "Travel: Jack's Office": 32,
        "Travel: Lunar Launching Station": 33,
        "Travel: Motherlessboard": 34,
        "Travel: Outfall Pumping Station": 35,
        "Travel: Outlands Canyon": 36,
        "Travel: Outlands Spur": 37,
        "Travel: Pity's Fall": 38,
        "Travel: Regolith Range": 39,
        "Travel: Research and Development": 40,
        "Travel: Serenity's Waste": 41,
        "Travel: Stanton's Liver": 42,
        "Travel: Sub-Level 13": 43,
        "Travel: Subconscious": 44,
        "Travel: The Cortex": 45,
        "Travel: The Holodome": 46,
        "Travel: The Meriff's Office": 47,
        "Travel: The Nexus": 48,
        "Travel: Titan Industrial Facility": 49,
        "Travel: Titan Robot Production Plant": 50,
        "Travel: Triton Flats": 51,
        "Travel: Tycho's Ribs": 52,
        "Travel: Veins of Helios": 53,
        "Travel: Vorago Solitude": 54,
        "Progressive Travel: Base Game": 55,
        "Progressive Travel: Side Area": 56,
        "Progressive Travel: The Holodome Onslaught DLC": 57,
        "Progressive Travel: Shock Drop Slaughter Pit DLC": 58,
        "Progressive Travel: Claptastic Voyage DLC": 59,
        "Trap Spawn: Opha": 60,
        "Trap Spawn: Pondor": 61,
        "Trap: Slippery": 62,
        "Trap: Item Explosion": 63,
        "Trap: Rubber Ducky": 64,
        "Trap: Clap-in-the-Box": 65,
        "Trap: Fling": 66,
        "Trap: Leaky Wallet": 67,
        "Override Level 15": 68,
        "Override Level 30": 69,
        "Max Ammo Pistol": 70,
        "Max Ammo Shotgun": 71,
        "Max Ammo SMG": 72,
        "Max Ammo SniperRifle": 73,
        "Max Ammo AssaultRifle": 74,
        "Max Ammo RocketLauncher": 75,
        "Max Ammo Laser": 76,
        "Max Grenade Count": 77,
        "Backpack Upgrade": 78,
        "Filler Gear: Bad Touch": 79,
        "Filler Gear: Cyber Eagle": 80,
        "Filler Gear: Ack Ack": 81,
        "Filler Gear: 3DD1.E": 82,
        "Filler Gear: Freedom": 83,
        "Filler Gear: Invigoration": 84,
        "Filler Gear: Moonlight Saga": 85,
        "Filler Gear: Oxidizer": 86,
        "Filler Gear: Cathartic": 87,
        "Filler Gear: Springs' Oz Kit": 88,
        "Filler Gear: Support Relay": 89,
        "Filler Gear: Systems Purge": 90,
        "Filler Gear: Bullpup": 91,
        "Filler Gear: Smasher": 92,
        "Filler Gear: Gwens Other Head": 93,
        "Filler Gear: Good Touch": 94,
        "Filler Gear: Ice Scream": 95,
        "Filler Gear: Wallop": 96,
        "Filler Gear: Hail": 97,
        "Filler Gear: Ol' Painful": 98,
        "Filler Gear: Mining Laser": 99,
        "Filler Gear: Firestarta": 100,
        "Filler Gear: Freezeeasy": 101,
        "Filler Gear: Vibra Pulse": 102,
        "Filler Gear: Toby's Bright Spadroon": 103,
        "Filler Gear: Vandergraffen": 104,
        "Filler Gear: Ol' Rosie": 105,
        "Filler Gear: E-Gun": 106,
        "Filler Gear: Volt Thrower": 107,
        "Filler Gear: Creamer": 108,
        "Filler Gear: Globber": 109,
        "Filler Gear: Fibber": 110,
        "Filler Gear: Moonface": 111,
        "Filler Gear: Boganella": 112,
        "Filler Gear: Heart Breaker": 113,
        "Filler Gear: Octo": 114,
        "Filler Gear: Wombat": 115,
        "Filler Gear: Too Scoops": 116,
        "Filler Gear: Boomacorn": 117,
        "Filler Gear: Jack-O'-Cannon": 118,
        "Filler Gear: Mareks Mouth": 119,
        "Filler Gear: Meat Grinder": 120,
        "Filler Gear: Fridgia": 121,
        "Filler Gear: Frostfire": 122,
        "Filler Gear: Black Snake": 123,
        "Filler Gear: Wet Week": 124,
        "Filler Gear: Fremington's Edge": 125,
        "Filler Gear: Razorback": 126,
        "Filler Gear: Ch\u00e8re-amie": 127,
        "Filler Gear: The Machine": 128,
        "Filler Gear: Lady Fist": 129,
        "Filler Gear: Torguemada": 130,
        "Filler Gear: Moxxi's Probe": 131,
        "Filler Gear: Boss Nova": 132,
        "Filler Gear: Tannis' Laser of Enlightenment": 133,
        "Filler Gear: Minac's Atonement": 134,
        "Filler Gear: Party Popper": 135,
        "Filler Gear: Hard Reboot": 136,
        "Filler Gear: Company Man": 137,
        "Filler Gear: Moonscaper": 138,
        "Filler Gear: Fast Talker": 139,
        "Filler Gear: Shield Of Ages": 140,
        "Filler Gear: Naught": 141,
        "Filler Gear: Heartfull Splodger": 142,
        "Filler Gear: Cutie Killer": 143,
        "Filler Gear: Perdy Lights": 144,
        "Filler Gear: Haymaker": 145,
        "Filler Gear: Deadly Bloom": 146,
        "Filler Gear: Asteroid Belt": 147,
        "Filler Gear: Rapid Release": 148,
        "Filler Gear: Sunshine": 149,
        "Filler Gear: Slammer": 150,
        "Filler Gear: Data Scrubber": 151,
        "Filler Gear: Baby Boomer": 152,
        "Filler Gear: Contraband Sky Rocket": 153,
        "Filler Gear: Snowball": 154,
        "Filler Gear: Kiss of Death": 155,
        "Filler Gear: Monster Trap": 156,
        "Filler Gear: Avalanche": 157,
        "Filler Gear: Shooting Star": 158,
        "Filler Gear: The Sham": 159,
        "Filler Gear: Kala": 160,
        "Filler Gear: Prismatic Bulwark": 161,
        "Filler Gear: Black Hole": 162,
        "Filler Gear: Supernova": 163,
        "Filler Gear: Fabled Tortoise": 164,
        "Filler Gear: Reogenator": 165,
        "Filler Gear: Whisky Tango Foxtrot": 166,
        "Filler Gear: Bigg Thumppr": 167,
        "Filler Gear: The Cradle": 168,
        "Filler Gear: Flyin' Maiden": 169,
        "Filler Gear: Bonus Package": 170,
        "Filler Gear: Quasar": 171,
        "Filler Gear: Bouncing Bazza": 172,
        "Filler Gear: Fire Bee": 173,
        "Filler Gear: Four Seasons": 174,
        "Filler Gear: Leech": 175,
        "Filler Gear: Nasty Surprise": 176,
        "Filler Gear: Pandemic": 177,
        "Filler Gear: Rolling Thunder": 178,
        "Filler Gear: Storm Front": 179,
        "Filler Gear: Excalibastard": 180,
        "Filler Gear: Longnail": 181,
        "Filler Gear: Torrent": 182,
        "Filler Gear: Striker": 183,
        "Filler Gear: KerBoom": 184,
        "Filler Gear: Cryophobia": 185,
        "Filler Gear: The ZX-1": 186,
        "Filler Gear: Fatale": 187,
        "Filler Gear: Blowfly": 188,
        "Filler Gear: Nukem": 189,
        "Filler Gear: Zim": 190,
        "Filler Gear: Hammer Buster II": 191,
        "Filler Gear: Skullmasher": 192,
        "Filler Gear: Flakker": 193,
        "Filler Gear: Invader": 194,
        "Filler Gear: Thingy": 195,
        "Filler Gear: Sledge's Shotty": 196,
        "Filler Gear: IVF": 197,
        "Filler Gear: Shredifier": 198,
        "Filler Gear: Major Tom": 199,
        "Filler Gear: Min Min Lighter": 200,
        "Filler Gear: Cat o' Nine Tails": 201,
        "Filler Gear: Badaboom": 202,
        "Filler Gear: Mongol": 203,
        "Filler Gear: Shooterang": 204,
        "Filler Gear: 88 Fragnum": 205,
        "Filler Gear: Maggie": 206,
        "Filler Gear: Logan's Gun": 207,
        "Filler Gear: Viral Marketer": 208,
        "Filler Gear: HellFire": 209,
        "Filler Gear: Pitchfork": 210,
        "Filler Gear: Magma": 211,
        "Filler Gear: Fusillade": 212,
        "Filler Gear: Longest Yard": 213,
        "Filler Gear: Absolute Zero": 214,
        "Filler Gear: Thunderfire": 215,
        "Filler Gear: Laser Disker": 216,
        "Filler Gear: Luck Cannon": 217,
        "Filler Gear: Kaneda's Laser": 218,
        "Filler Gear: Cheat Code": 219,
        "Filler Gear: Omni-Cannon": 220,
        "Filler Gear: Proletarian Revolution": 221,
        "Filler Gear: Meganade": 222,
        "Filler Gear: M0RQ": 223,
        "Filler Gear: Rerouter": 224,
        "Filler Gear: Flayer": 225,
        "Filler Gear: Berrigan": 226,
        "Filler Gear: Cry Baby": 227,
        "Filler Gear: T4s-R": 228,
        "Filler Gear: Party Line": 229,
        "Filler Gear: Boxxy Gunn": 230,
        "Filler Gear: Plunkett": 231,
        "License: Common Shield": 232,
        "License: Uncommon Shield": 233,
        "License: Rare Shield": 234,
        "License: VeryRare Shield": 235,
        "License: Legendary Shield": 236,
        "License: Unique Shield": 237,
        "License: Common GrenadeMod": 238,
        "License: Uncommon GrenadeMod": 239,
        "License: Rare GrenadeMod": 240,
        "License: VeryRare GrenadeMod": 241,
        "License: Legendary GrenadeMod": 242,
        "License: Unique GrenadeMod": 243,
        "License: Common ClassMod": 244,
        "License: Uncommon ClassMod": 245,
        "License: Rare ClassMod": 246,
        "License: VeryRare ClassMod": 247,
        "License: Legendary ClassMod": 248,
        "License: Common Oz Kit": 249,
        "License: Uncommon Oz Kit": 250,
        "License: Rare Oz Kit": 251,
        "License: VeryRare Oz Kit": 252,
        "License: Legendary Oz Kit": 253,
        "License: Unique Oz Kit": 254,
        "License: Common Pistol": 255,
        "License: Uncommon Pistol": 256,
        "License: Rare Pistol": 257,
        "License: VeryRare Pistol": 258,
        "License: Legendary Pistol": 259,
        "License: Glitch Pistol": 260,
        "License: Unique Pistol": 261,
        "License: Common Shotgun": 262,
        "License: Uncommon Shotgun": 263,
        "License: Rare Shotgun": 264,
        "License: VeryRare Shotgun": 265,
        "License: Legendary Shotgun": 266,
        "License: Glitch Shotgun": 267,
        "License: Unique Shotgun": 268,
        "License: Common SMG": 269,
        "License: Uncommon SMG": 270,
        "License: Rare SMG": 271,
        "License: VeryRare SMG": 272,
        "License: Legendary SMG": 273,
        "License: Glitch SMG": 274,
        "License: Unique SMG": 275,
        "License: Common SniperRifle": 276,
        "License: Uncommon SniperRifle": 277,
        "License: Rare SniperRifle": 278,
        "License: VeryRare SniperRifle": 279,
        "License: Legendary SniperRifle": 280,
        "License: Glitch SniperRifle": 281,
        "License: Unique SniperRifle": 282,
        "License: Common AssaultRifle": 283,
        "License: Uncommon AssaultRifle": 284,
        "License: Rare AssaultRifle": 285,
        "License: VeryRare AssaultRifle": 286,
        "License: Legendary AssaultRifle": 287,
        "License: Glitch AssaultRifle": 288,
        "License: Unique AssaultRifle": 289,
        "License: Common RocketLauncher": 290,
        "License: Uncommon RocketLauncher": 291,
        "License: Rare RocketLauncher": 292,
        "License: VeryRare RocketLauncher": 293,
        "License: Legendary RocketLauncher": 294,
        "License: Glitch RocketLauncher": 295,
        "License: Unique RocketLauncher": 296,
        "License: Common Laser": 297,
        "License: Uncommon Laser": 298,
        "License: Rare Laser": 299,
        "License: VeryRare Laser": 300,
        "License: Legendary Laser": 301,
        "License: Glitch Laser": 302,
        "License: Unique Laser": 303,
        "Reward: Welcome to Helios": 304,
        "Reward: Lost Legion Invasion": 305,
        "Reward: Land Among the Stars": 306,
        "Reward: Follow Your Heart": 307,
        "Reward: Tales from Elpis": 308,
        "Reward: Last Requests": 309,
        "Reward: Marooned": 310,
        "Reward: Nova? No Problem!": 311,
        "Reward: Torgue-o! Torgue-o!": 312,
        "Reward: Systems Jammed": 313,
        "Reward: Wherefore Art Thou?": 314,
        "Reward: The Empty Billabong": 315,
        "Reward: All the Little Creatures": 316,
        "Reward: Recruitment Drive": 317,
        "Reward: A New Direction": 318,
        "Reward: Bunch of Ice Holes": 319,
        "Reward: Grinders": 320,
        "Reward: Pop Racing": 321,
        "Reward: To Arms!": 322,
        "Reward: Zapped 1.0": 323,
        "Reward: Zapped 2.0": 324,
        "Reward: Zapped 3.0": 325,
        "Reward: Boomshakalaka": 326,
        "Reward: Space Slam": 327,
        "Reward: Intelligences of the Artificial Persuasion": 328,
        "Reward: The Secret Chamber": 329,
        "Reward: Wiping the Slate": 330,
        "Reward: No Such Thing as a Free Launch": 331,
        "Reward: Nothing is Never an Option": 332,
        "Reward: Treasures of ECHO Madre": 333,
        "Reward: Another Pickle": 334,
        "Reward: Home Delivery": 335,
        "Reward: Rough Love": 336,
        "Reward: Let's Build a Robot Army": 337,
        "Reward: Sub-Level 13": 338,
        "Reward: Sub-Level 13: Part 2": 339,
        "Reward: The Voyage of Captain Chef": 340,
        "Reward: Home Sweet Home": 341,
        "Reward: Hot Head": 342,
        "Reward: Voice Over": 343,
        "Reward: Boarding Party": 344,
        "Reward: An Urgent Message": 345,
        "Reward: Handsome AI": 346,
        "Reward: Paint Job": 347,
        "Reward: Kill Meg": 348,
        "Reward: Science and Violence": 349,
        "Reward: Infinite Loop": 350,
        "Reward: Fresh Air": 351,
        "Reward: It Ain't Rocket Surgery": 352,
        "Reward: Lab 19": 353,
        "Reward: Cleanliness Uprising": 354,
        "Reward: Watch Your Step": 355,
        "Reward: Red, Then Dead": 356,
        "Reward: Things That Go Boom": 357,
        "Reward: To the Moon": 358,
        "Reward: Lock and Load": 359,
        "Reward: Quarantine: Back On Schedule": 360,
        "Reward: Quarantine: Infestation": 361,
        "Reward: In Perfect Hibernation": 362,
        "Reward: Trouble with Space Hurps": 363,
        "Reward: Don't Get Cocky": 364,
        "Reward: Eradicate!": 365,
        "Reward: Eye to Eye": 366,
        "Reward: Picking Up the Pieces": 367,
        "Reward: These are the Bots": 368,
        "Reward: The Don": 369,
        "Reward: Return of Captain Chef": 370,
        "Reward: Don't Shoot the Messenger": 371,
        "Reward: Z8N-TP": 372,
        "Reward: The Beginning of the End": 373,
        "Reward: The Bestest Story Ever Told": 374,
        "Reward: Guardian Hunter": 375,
        "Reward: Sterwin Forever": 376,
        "Reward: DAHL Combat Training: Round 1": 377,
        "Reward: DAHL Combat Training: Round 2": 378,
        "Reward: DAHL Combat Training: Round 3": 379,
        "Reward: DAHL Combat Training: Round 4": 380,
        "Reward: DAHL Combat Training: Round 5": 381,
        "Reward: Alpha": 382,
        "Reward: Beta": 383,
        "Reward: Delta": 384,
        "Reward: Gamma": 385,
        "Reward: l33t h4X0rz": 386,
        "Reward: Enter the Claptrap": 387,
        "Reward: File Search": 388,
        "Reward: END OF LINE": 389,
        "Reward: System Shutdown": 390,
        "Reward: The Psychology of a Claptrap": 391,
        "Reward: A Deadlier Game": 392,
        "Reward: Byte Club": 393,
        "Reward: Chip's Data Mining Adventure": 394,
        "Reward: 3G0-TP": 395,
        "Reward: 1D-TP": 396,
        "Reward: Rose Tinting": 397,
        "Reward: Corrosion of Dignity": 398,
        "Reward: Spyware Who Came in from the Cold": 399,
        "Reward: You Can Stop the Music": 400,
        "Reward: The Sum of Some Fears": 401,
        "Reward: 5UP4-3G0-TP": 402,
        "Reward: The Temple of Boom": 403,
        "Reward: h4X0rz": 404,
        "Reward: Digistructed Madness: Round 1": 405,
        "Reward: Digistructed Madness: Round 2": 406,
        "Reward: Digistructed Madness: Round 3": 407,
        "Reward: Digistructed Madness: Round 4": 408,
        "Reward: Digistructed Madness: Round 5": 409,
        "Reward: Digistructed Madness: The Badass Round": 410,
        "Filler Gear: Common Shield": 411,
        "Filler Gear: Uncommon Shield": 412,
        "Filler Gear: Rare Shield": 413,
        "Filler Gear: VeryRare Shield": 414,
        "Filler Gear: Legendary Shield": 415,
        "Filler Gear: Unique Shield": 416,
        "Filler Gear: Common GrenadeMod": 417,
        "Filler Gear: Uncommon GrenadeMod": 418,
        "Filler Gear: Rare GrenadeMod": 419,
        "Filler Gear: VeryRare GrenadeMod": 420,
        "Filler Gear: Legendary GrenadeMod": 421,
        "Filler Gear: Unique GrenadeMod": 422,
        "Filler Gear: Common ClassMod": 423,
        "Filler Gear: Uncommon ClassMod": 424,
        "Filler Gear: Rare ClassMod": 425,
        "Filler Gear: VeryRare ClassMod": 426,
        "Filler Gear: Legendary ClassMod": 427,
        "Filler Gear: Common Oz Kit": 428,
        "Filler Gear: Uncommon Oz Kit": 429,
        "Filler Gear: Rare Oz Kit": 430,
        "Filler Gear: VeryRare Oz Kit": 431,
        "Filler Gear: Legendary Oz Kit": 432,
        "Filler Gear: Unique Oz Kit": 433,
        "Filler Gear: Common Pistol": 434,
        "Filler Gear: Uncommon Pistol": 435,
        "Filler Gear: Rare Pistol": 436,
        "Filler Gear: VeryRare Pistol": 437,
        "Filler Gear: Legendary Pistol": 438,
        "Filler Gear: Glitch Pistol": 439,
        "Filler Gear: Unique Pistol": 440,
        "Filler Gear: Common Shotgun": 441,
        "Filler Gear: Uncommon Shotgun": 442,
        "Filler Gear: Rare Shotgun": 443,
        "Filler Gear: VeryRare Shotgun": 444,
        "Filler Gear: Legendary Shotgun": 445,
        "Filler Gear: Glitch Shotgun": 446,
        "Filler Gear: Unique Shotgun": 447,
        "Filler Gear: Common SMG": 448,
        "Filler Gear: Uncommon SMG": 449,
        "Filler Gear: Rare SMG": 450,
        "Filler Gear: VeryRare SMG": 451,
        "Filler Gear: Legendary SMG": 452,
        "Filler Gear: Glitch SMG": 453,
        "Filler Gear: Unique SMG": 454,
        "Filler Gear: Common SniperRifle": 455,
        "Filler Gear: Uncommon SniperRifle": 456,
        "Filler Gear: Rare SniperRifle": 457,
        "Filler Gear: VeryRare SniperRifle": 458,
        "Filler Gear: Legendary SniperRifle": 459,
        "Filler Gear: Glitch SniperRifle": 460,
        "Filler Gear: Unique SniperRifle": 461,
        "Filler Gear: Common AssaultRifle": 462,
        "Filler Gear: Uncommon AssaultRifle": 463,
        "Filler Gear: Rare AssaultRifle": 464,
        "Filler Gear: VeryRare AssaultRifle": 465,
        "Filler Gear: Legendary AssaultRifle": 466,
        "Filler Gear: Glitch AssaultRifle": 467,
        "Filler Gear: Unique AssaultRifle": 468,
        "Filler Gear: Common RocketLauncher": 469,
        "Filler Gear: Uncommon RocketLauncher": 470,
        "Filler Gear: Rare RocketLauncher": 471,
        "Filler Gear: VeryRare RocketLauncher": 472,
        "Filler Gear: Legendary RocketLauncher": 473,
        "Filler Gear: Glitch RocketLauncher": 474,
        "Filler Gear: Unique RocketLauncher": 475,
        "Filler Gear: Common Laser": 476,
        "Filler Gear: Uncommon Laser": 477,
        "Filler Gear: Rare Laser": 478,
        "Filler Gear: VeryRare Laser": 479,
        "Filler Gear: Legendary Laser": 480,
        "Filler Gear: Glitch Laser": 481,
        "Filler Gear: Unique Laser": 482
    }
}