import unrealsdk
from mods_base import get_pc
challenge_dict = {
    "GD_Challenges.elemental.Elemental_DealCorrosiveDOTDamage":                     "Challenge Elemental: Chemical Burn",
    "GD_Challenges.elemental.Elemental_DealIceDOTDamage":                           "Challenge Elemental: Frost Bite",
    "GD_Challenges.elemental.Elemental_DealShockDOTDamage":                         "Challenge Elemental: Watt's Up?",
    "GD_Challenges.elemental.Elemental_SetEnemiesOnFire":                           "Challenge Elemental: Way of the Enkindling",
    "GD_Challenges.elemental.Elemental_DealFireDOTDamage":                          "Challenge Elemental: Some Like It Hot",
    "GD_Challenges.elemental.Elemental_KillEnemiesCorrosive":                       "Challenge Elemental: Toxic Takedown",
    "GD_Challenges.elemental.Elemental_KillEnemiesExplosive":                       "Challenge Elemental: Out with a Bang",
    "GD_Challenges.Melee.Melee_Kills":                                              "Challenge Melee: Martial Marshal",
    "GD_Challenges.Melee.Melee_KillsBladed":                                        "Challenge Melee: Captain Cutty",
    "GD_Challenges.Weapons.AssaultRifle_CriticalHits":                              "Challenge AssaultRifle: Aim to Please",
    "GD_Challenges.Weapons.AssaultRifle_Kills":                                     "Challenge AssaultRifle: Assault With a Deadly Weapon",
    "GD_Challenges.Weapons.AssaultRifle_CriticalHitKills":                          "Challenge AssaultRifle: Hot Lead Injection",
    "GD_Challenges.Weapons.AssaultRifle_KillsCrouched":                             "Challenge AssaultRifle: Crouch Potato",
    "GD_Challenges.Weapons.AssaultRifle_SecondWinds":                               "Challenge AssaultRifle: Assaulty Dog",
    "GD_Challenges.Weapons.Laser_CriticalHits":                                     "Challenge Laser: Aggressive Lasik",
    "GD_Challenges.Weapons.Laser_CriticalHitKills":                                 "Challenge Laser: Light 'em Up",
    "GD_Challenges.Weapons.Laser_FlyingKills":                                      "Challenge Laser: Battle Star",
    "GD_Challenges.Weapons.Laser_Kills":                                            "Challenge Laser: Pew Pew",
    "GD_Challenges.Weapons.Laser_SecondWinds":                                      "Challenge Laser: I See the Light",
    "GD_Challenges.Weapons.Launcher_Kills":                                         "Challenge RocketLauncher: Get a Rocket up Ya",
    "GD_Challenges.Weapons.Launcher_KillsSplashDamage":                             "Challenge RocketLauncher: Collateral Damage",
    "GD_Challenges.Weapons.Launcher_KillsFullShieldEnemy":                          "Challenge RocketLauncher: Punker Buster",
    "GD_Challenges.Weapons.Launcher_KillsLongRange":                                "Challenge RocketLauncher: Hand of God",
    "GD_Challenges.Weapons.Launcher_KillsDirectHit":                                "Challenge RocketLauncher: Missile Magnet",
    "GD_Challenges.Weapons.Launcher_SecondWinds":                                   "Challenge RocketLauncher: Magic Missile",
    "GD_Challenges.Weapons.Pistol_CriticalHits":                                    "Challenge Pistol: Pistoleer",
    "GD_Challenges.Weapons.Pistol_Kills":                                           "Challenge Pistol: Trigger Happy",
    "GD_Challenges.Weapons.Pistol_CriticalHitKills":                                "Challenge Pistol: Magnum Maestro",
    "GD_Challenges.Weapons.Pistol_KillsQuickshot":                                  "Challenge Pistol: Gunslinger",
    "GD_Challenges.Weapons.Pistol_SecondWinds":                                     "Challenge Pistol: Pistol Whipped",
    "GD_Challenges.Weapons.Shotgun_CriticalHits":                                   "Challenge Shotgun: Hello Uncle Buckshot",
    "GD_Challenges.Weapons.Shotgun_Kills":                                          "Challenge Shotgun: Boomstick Boogie",
    "GD_Challenges.Weapons.Shotgun_CriticalHitKills":                               "Challenge Shotgun: Shotty Workmanship",
    "GD_Challenges.Weapons.Shotgun_KillsLongRange":                                 "Challenge Shotgun: Over Achiever",
    "GD_Challenges.Weapons.Shotgun_SecondWinds":                                    "Challenge Shotgun: Shotgunning the Breeze",
    "GD_Challenges.Weapons.Shotgun_KillsPointBlank":                                "Challenge Shotgun: Take It All!",
    "GD_Challenges.Weapons.SMG_CriticalHits":                                       "Challenge SMG: Bring the Pain",
    "GD_Challenges.Weapons.SMG_Kills":                                              "Challenge SMG: Nice Spray Job",
    "GD_Challenges.Weapons.SMG_SecondWinds":                                        "Challenge SMG: And Stay Down!",
    "GD_Challenges.Weapons.SMG_CriticalHitKills":                                   "Challenge SMG: Dinky Death Dealer",
    "GD_Challenges.Weapons.Sniper_CriticalHits":                                    "Challenge Sniper: Melon Splitter",
    "GD_Challenges.Weapons.SniperRifle_Kills":                                      "Challenge Sniper: Sharp Shooter",
    "GD_Challenges.Weapons.SniperRifle_KillsFromHip":                               "Challenge Sniper: Ol' Skool",
    "GD_Challenges.Weapons.SniperRifle_KillsFullShieldEnemy":                       "Challenge Sniper: Penetrating Wound",
    "GD_Challenges.Weapons.SniperRifle_KillsUnaware":                               "Challenge Sniper: Clean and Simple",
    "GD_Challenges.Weapons.Sniper_CriticalHitKills":                                "Challenge Sniper: Critical Reception",
    "GD_Challenges.Weapons.Sniper_SecondWinds":                                     "Challenge Sniper: Windage Adjustment",
    "GD_Challenges.Player.Player_SecondWindFromCorrosive":                          "Challenge Recovery: Soup's Up!",
    "GD_Challenges.Player.Player_SecondWindFromShatter":                            "Challenge Recovery: Rollin' the Ice",
    "GD_Challenges.Player.Player_SecondWindFromShock":                              "Challenge Recovery: Had a Bit of a Shocker",
    "GD_Challenges.Player.Player_SecondWindFromFire":                               "Challenge Recovery: The Phoenix",
    "GD_Challenges.Player.Player_CoopRevivesOfFriends":                             "Challenge Recovery: Up Unt at Zem",
    "GD_Challenges.Player.Player_PointsHealed":                                     "Challenge Recovery: Doctor Feels Good",
    "GD_Challenges.Player.Player_SecondWind":                                       "Challenge Recovery: Better You Than Me",
    "GD_Challenges.Player.Player_SecondWindFromBadass":                             "Challenge Recovery: There Can Be Only... Me",
    "GD_Challenges.Shields.Shields_AbsorbAmmo":                                     "Challenge Shields: Ammo Eater",
    "GD_Challenges.Shields.Shields_KillsImpact":                                    "Challenge Shields: Amplitude Killulation",
    "GD_Challenges.Shields.Shields_KillsNova":                                      "Challenge Shields: Nova Say Die",
    "GD_Challenges.Shields.Shields_KillsRoid":                                      "Challenge Shields: Wet Work",
    "GD_Challenges.Shields.Shields_KillsSpikes":                                    "Challenge Shields: That'll Learn Ya",
    # "GD_Challenges.Vehicles.Vehicles_DriveMiles":                                   "Challenge Vehicles: Shut Up and Drive",
    "GD_Challenges.Vehicles.Vehicles_KillByPowerSlide":                             "Challenge Vehicles: Splat 'n' Slide",
    "GD_Challenges.Vehicles.Vehicles_KillByRamming":                                "Challenge Vehicles: Fender Bender",
    "GD_Challenges.Vehicles.Vehicles_KillsWithVehicleWeapon":                       "Challenge Vehicles: Improvise, Adapt, Overcome",
    "GD_Challenges.Vehicles.Vehicles_VehicleKillsVehicle":                          "Challenge Vehicles: Road Warrior",
    "GD_Challenges.Vehicles.Vehicles_KillByPancaking":                              "Challenge Vehicles: Pancakes for Breakfast",
    "GD_Challenges.Economy.Economy_BuyItemsWithMoonstone":                          "Challenge Economy: Over the Moon",
    "GD_Challenges.Economy.Economy_MoneySaved":                                     "Challenge Economy: Mom Would Be Proud",
    "GD_Challenges.Economy.Economy_PurchaseItemsOfTheDay":                          "Challenge Economy: Impulse Shopper",
    "GD_Challenges.Economy.Economy_SellItems":                                      "Challenge Economy: Pawn Broker",
    "GD_Challenges.Economy.General_MoneyFromCashDrops":                             "Challenge Economy: Mr. Money Pits",
    "GD_Challenges.Economy.Trade_ItemsWithPlayers":                                 "Challenge Economy: Trade Negotiations",
    "GD_Challenges.Enemies.Enemies_KillDahlBadasses":                               "Challenge Enemies: Kiss My Badass",
    "GD_Challenges.Enemies.Enemies_KillDahlFlyers":                                 "Challenge Enemies: Crash & Burn",
    "GD_Challenges.Enemies.Enemies_KillDahlInfantry":                               "Challenge Enemies: Get Some!",
    "GD_Challenges.Enemies.Enemies_KillDahlSuits":                                  "Challenge Enemies: No Suit for You!",
    "GD_Challenges.Enemies.Enemies_KillGuardianBosses":                             "Challenge Enemies: More Where That Came From",
    "GD_Challenges.Enemies.Enemies_KillGuardians":                                  "Challenge Enemies: Not So Tough Now",
    "GD_Challenges.Enemies.Enemies_KillHyperionInfantry":                           "Challenge Enemies: Dose of Death",
    "GD_Challenges.Enemies.Enemies_KillKraggonBadasses":                            "Challenge Enemies: Slayer of Titans",
    "GD_Challenges.Enemies.Enemies_KillKraggons":                                   "Challenge Enemies: Big Game Hunt",
    "GD_Challenges.Enemies.Enemies_KillLunarLooters":                               "Challenge Enemies: Gift That Keeps Giving",
    "GD_Challenges.Enemies.Enemies_KillRathyds":                                    "Challenge Enemies: Exterminator",
    "GD_Challenges.Enemies.Enemies_KillScavBadasses":                               "Challenge Enemies: The One That Says B.A.M.F.",
    "GD_Challenges.Enemies.Enemies_KillScavFlyers":                                 "Challenge Enemies: It Wasn't Yours, Anyway",
    "GD_Challenges.Enemies.Enemies_KillScavs":                                      "Challenge Enemies: Die, Moon Jerks",
    "GD_Challenges.Enemies.Enemies_KillScavSpacemen":                               "Challenge Enemies: Space Dead",
    "GD_Challenges.Enemies.Enemies_KillShugguraths":                                "Challenge Enemies: That Was Unpleasant",
    "GD_Challenges.Enemies.Enemies_KillTorkBadasses":                               "Challenge Enemies: Torkin' Out the Trash",
    "GD_Challenges.Enemies.Enemies_KillTorks":                                      "Challenge Enemies: Pest Control",
    "GD_Challenges.Dueling.DuelsWon_HatersGonnaHate":                               "Challenge General: The Duelist",
    "GD_Challenges.GeneralCombat.Barrels_KillEnemies":                              "Challenge General: Barrel of Laughs",
    "GD_Challenges.GeneralCombat.Break_Masks":                                      "Challenge General: Having Trouble Breathing?",
    "GD_Challenges.GeneralCombat.General_RoundsFired":                              "Challenge General: Projectile Proliferation",
    "GD_Challenges.GeneralCombat.Kills_Asphyxiation":                               "Challenge General: Last Gasp",
    "GD_Challenges.GeneralCombat.Kills_AtDay":                                      "Challenge General: Day of the Dead",
    "GD_Challenges.GeneralCombat.Kills_AtNight":                                    "Challenge General: Dark Sider",
    "GD_Challenges.GeneralCombat.Kills_FromCrits":                                  "Challenge General: Executioner",
    "GD_Challenges.GeneralCombat.Player_KillsWithActionSkill":                      "Challenge General: Action Hero",
    "GD_Challenges.GeneralCombat.Shatter_With_Falling":                             "Challenge General: Comet Crash",
    "GD_Challenges.GeneralCombat.Shatter_With_Weapons":                             "Challenge General: Ice to Meet You",
    "GD_Challenges.GeneralCombat.Tediore_DamageFromReloads":                        "Challenge General: One Man's Trash",
    "GD_Challenges.GeneralCombat.Tediore_KillWithReload":                           "Challenge General: Throw Me the Money!",
    "GD_Challenges.Grenades.Grenade_Kills":                                         "Challenge Grenade: Home Nade Cookin'",
    "GD_Challenges.Grenades.Grenade_KillsAoEoTType":                                "Challenge Grenade: Sprayowee",
    "GD_Challenges.Grenades.Grenade_KillsBouncing":                                 "Challenge Grenade: Betty Boom",
    "GD_Challenges.Grenades.Grenade_KillsMirvType":                                 "Challenge Grenade: Big MIRV",
    "GD_Challenges.Grenades.Grenade_KillsSingularityType":                          "Challenge Grenade: See Ya on the Other Side",
    "GD_Challenges.Grenades.Grenade_KillsTransfusionType":                          "Challenge Grenade: Pass the Chianti",
    "GD_Challenges.Grinder.Grinder_GrinderRecipes":                                 "Challenge Grinder: Master Chef",
    "GD_Challenges.Grinder.Grinder_MoonstoneAttachments":                           "Challenge Grinder: Greater Than the Sum of its Parts",
    "GD_Challenges.Grinder.Grinder_MoonstoneGrind":                                 "Challenge Grinder: This Time for Sure",
    "GD_Challenges.Grinder.Grinder_StandardGrind":                                  "Challenge Grinder: The Daily Grind",
    "GD_Challenges.Loot.Loot_OpenChests":                                           "Challenge Loot: Aaaaaand OPEN!",
    "GD_Challenges.Loot.Loot_OpenLootables":                                        "Challenge Loot: Scrounging Around",
    "GD_Challenges.Loot.Loot_PickUpWeapons":                                        "Challenge Loot: One for Every Occasion",
    "GD_Challenges.Pickups.Inventory_PickupBlueItems":                              "Challenge Loot: Rare as Rocking Horse...",
    "GD_Challenges.Pickups.Inventory_PickupGreenItems":                             "Challenge Loot: A Chunk of Purest Green",
    "GD_Challenges.Pickups.Inventory_PickupOrangeItems":                            "Challenge Loot: The Happiest Color",
    "GD_Challenges.Pickups.Inventory_PickupPurpleItems":                            "Challenge Loot: Purple Haze",
    "GD_Challenges.Pickups.Inventory_PickupWhiteItems":                             "Challenge Loot: Junkyard Dog",
    "GD_Challenges.LowGravity.LowGravity_CriticalsWhileAirborne":                   "Challenge Low Gravity: Eagle Eye",
    "GD_Challenges.LowGravity.LowGravity_DoubleJump":                               "Challenge Low Gravity: Boosted",
    "GD_Challenges.LowGravity.LowGravity_KillsWhileAirborne":                       "Challenge Low Gravity: Death from Above",
    "GD_Challenges.LowGravity.LowGravity_KillsWithSlam":                            "Challenge Low Gravity: Slampage!",
    "GD_Challenges.LowGravity.LowGravity_MeleeWhileAirborne":                       "Challenge Low Gravity: Dragon Punch",
    "GD_Challenges.LowGravity.LowGravity_SlamDamage":                               "Challenge Low Gravity: Roger Slamjet",
    "GD_Challenges.Miscellaneous.Misc_CompleteChallenges":                          "Challenge Misc: We Have a Contender",
    "GD_Challenges.Miscellaneous.Missions_OptionalObjectivesCompleted":             "Challenge Misc: OC/DC",
    "GD_Challenges.Miscellaneous.Missions_SideMissionsCompleted":                   "Challenge Misc: Little on the Side",
    "GD_Challenges.Co_LevelChallenges.Access_EridianShield":                        "Challenge Tycho's Ribs: That Was Your Own Fault...",
    "GD_Challenges.Co_LevelChallenges.Access_SmashCystalSkulls":                    "Challenge Tycho's Ribs: Mystery of the Crystal Skulls",
    "GD_Challenges.Co_LevelChallenges.Access_VaultRoy":                             "Challenge Tycho's Ribs: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.Airstrip_PhonicallyChallenged":               "Challenge Serenity's Waste: Phonically Challenged",
    "GD_Challenges.Co_LevelChallenges.Airstrip_VaultRoy":                           "Challenge Serenity's Waste: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.CentralTerminal_FeedtheFishes":               "Challenge Hyperion Hub of Heroism: Feed the Fishes",
    "GD_Challenges.Co_LevelChallenges.CentralTerminal_FlameOff":                    "Challenge Hyperion Hub of Heroism: Flame Off",
    "GD_Challenges.Co_LevelChallenges.CentralTerminal_OhTheHumanity":               "Challenge Hyperion Hub of Heroism: Oh, the Humanity",
    "GD_Challenges.Co_LevelChallenges.CentralTerminal_PerfectDive":                 "Challenge Hyperion Hub of Heroism: Perfect Dive",
    "GD_Challenges.Co_LevelChallenges.CentralTerminal_PlayingChicken":              "Challenge Hyperion Hub of Heroism: Playing Chicken",
    "GD_Challenges.Co_LevelChallenges.CentralTerminal_VaultRoy":                    "Challenge Hyperion Hub of Heroism: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.CentralTerminal_WindowShopping":              "Challenge Hyperion Hub of Heroism: Window Shopping",
    "GD_Challenges.Co_LevelChallenges.CommFacility_RedLast":                        "Challenge Crisis Scar: Red Last",
    "GD_Challenges.Co_LevelChallenges.CommsFacility_LavaLeap":                      "Challenge Crisis Scar: Lava Leap",
    "GD_Challenges.Co_LevelChallenges.CommsFacility_UpMagma":                       "Challenge Crisis Scar: Up Magma",
    "GD_Challenges.Co_LevelChallenges.CommsFacility_VaultRoy":                      "Challenge Crisis Scar: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.DahlFactory_FastShooter":                     "Challenge Titan Industrial Facility: Fast Shooter",
    "GD_Challenges.Co_LevelChallenges.DahlFactory_QuickOrDead":                     "Challenge Titan Industrial Facility: Be Quick or Be Dead",
    "GD_Challenges.Co_LevelChallenges.DahlFactory_SpeedRun":                        "Challenge Titan Industrial Facility: Breath Holder",
    "GD_Challenges.Co_LevelChallenges.DahlFactory_VaultRoy":                        "Challenge Titan Industrial Facility: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.DahlFactoryBoss_VaultRoy":                    "Challenge Titan Robot Production Plant: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.DahlFactoryBoss_TakeOutLegs":                 "Challenge Titan Robot Production Plant: Turret Engineer",
    "GD_Challenges.Co_LevelChallenges.DahlFactoryBoss_DoThisAlone":                 "Challenge Titan Robot Production Plant: I Can Do This Alone",
    "GD_Challenges.Co_LevelChallenges.Deadsurface_DeadSet":                         "Challenge Regolith Range: Dead Set",
    "GD_Challenges.Co_LevelChallenges.Deadsurface_DeadWeight":                      "Challenge Regolith Range: Dead Weight",
    "GD_Challenges.Co_LevelChallenges.DeadSurface_Insulated":                       "Challenge Regolith Range: Insulated",
    "GD_Challenges.Co_LevelChallenges.Deadsurface_VaultRoy":                        "Challenge Regolith Range: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.Digsite_BigJump":                             "Challenge Vorago Solitude: Mind the Gap",
    "GD_Challenges.Co_LevelChallenges.Digsite_EridianArtifacts":                    "Challenge Vorago Solitude: Eridian Archaeology",
    "GD_Challenges.Co_LevelChallenges.Digsite_Telescope":                           "Challenge Vorago Solitude: Vorago's Dig Sights",
    "GD_Challenges.Co_LevelChallenges.Digsite_VaultRoy":                            "Challenge Vorago Solitude: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.Drakensburg_CallThatAShield":                 "Challenge Pity's Fall: You Call That a Shield?",
    "GD_Challenges.Co_LevelChallenges.Drakensburg_ConventionalDeath":               "Challenge Pity's Fall: A Conventional Death",
    "GD_Challenges.Co_LevelChallenges.Drakensburg_Engineering201":                  "Challenge Pity's Fall: Engineering 201",
    "GD_Challenges.Co_LevelChallenges.Drakensburg_Stash":                           "Challenge Pity's Fall: Bosun's Mate",
    "GD_Challenges.Co_LevelChallenges.Drakensburg_VaultRoy":                        "Challenge Pity's Fall: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.EyeOfHelios_FinishHim":                       "Challenge Eye of Helios: Finish Him",
    "GD_Challenges.Co_LevelChallenges.EyeOfHelios_LooseCannon":                     "Challenge Eye of Helios: Loose Cannon",
    "GD_Challenges.Co_LevelChallenges.EyeOfHelios_PowerPlay":                       "Challenge Eye of Helios: Power Play",
    "GD_Challenges.Co_LevelChallenges.EyeOfHelios_TrainingDay":                     "Challenge Eye of Helios: Training Day",
    "GD_Challenges.Co_LevelChallenges.EyeOfHelios_TreadCarefully":                  "Challenge Eye of Helios: Tread Carefully",
    "GD_Challenges.Co_LevelChallenges.EyeOfHelios_VaultRoy":                        "Challenge Eye of Helios: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.InnerCore_OneStepAhead":                      "Challenge Eleseer: One Step Ahead of You",
    "GD_Challenges.Co_LevelChallenges.InnerCore_VaultRoy":                          "Challenge Eleseer: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.InnerCore_AintNobodyGotTime":                 "Challenge Eleseer: Aim for the Little Ones",
    "GD_Challenges.Co_LevelChallenges.InnerHull_CannibalCorpse":                    "Challenge Veins of Helios: Cannibal Corpse",
    "GD_Challenges.Co_LevelChallenges.InnerHull_CatchARide":                        "Challenge Veins of Helios: Catch a Ride",
    "GD_Challenges.Co_LevelChallenges.InnerHull_HonoraryForeman":                   "Challenge Veins of Helios: Honorary Foreman",
    "GD_Challenges.Co_LevelChallenges.InnerHull_JumpForJoy_Critical":               "Challenge Veins of Helios: Jump for Joy",
    "GD_Challenges.Co_LevelChallenges.InnerHull_JumpForJoy_Secret":                 "Challenge Veins of Helios: Thrill Seeker",
    "GD_Challenges.Co_LevelChallenges.InnerHull_VaultRoy":                          "Challenge Veins of Helios: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.JacksOffice_FieryFiler":                      "Challenge Jack's Office: Fiery Filer",
    "GD_Challenges.Co_LevelChallenges.JacksOffice_VaultRoy":                        "Challenge Jack's Office: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.MoonSlaughter_JackBeNimble":                  "Challenge Abandoned Training Facility: Jack Be Nimble",
    "GD_Challenges.Co_LevelChallenges.MoonSlaughter_ServeHot":                      "Challenge Abandoned Training Facility: Best Served Hot",
    "GD_Challenges.Co_LevelChallenges.MoonSlaughter_VaultRoy":                      "Challenge Abandoned Training Facility: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.MoonSurface_HiddenTreasure":                  "Challenge Stanton's Liver: Hidden Treasure",
    "GD_Challenges.Co_LevelChallenges.MoonSurface_KillingTime":                     "Challenge Stanton's Liver: Killing Time",
    "GD_Challenges.Co_LevelChallenges.MoonSurface_LeapOfFaith":                     "Challenge Stanton's Liver: Leap of Faith",
    "GD_Challenges.Co_LevelChallenges.MoonSurface_VaultRoy":                        "Challenge Stanton's Liver: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.Outlands_AntiAirman":                         "Challenge Outlands Spur: Boomer's Bane",
    "GD_Challenges.Co_LevelChallenges.Outlands_OHSInspection":                      "Challenge Outlands Spur: OHS Inspection",
    "GD_Challenges.Co_LevelChallenges.Outlands_PicklePicker":                       "Challenge Outlands Spur: Pickle Picker",
    "GD_Challenges.Co_LevelChallenges.Outlands_VaultRoy":                           "Challenge Outlands Spur: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.OutlandsCanyon_KingOfTheHill":                "Challenge Outlands Canyon: King of the Hill",
    "GD_Challenges.Co_LevelChallenges.OutlandsCanyon_NoAnimalHarmed":               "Challenge Outlands Canyon: No Animal Harmed",
    "GD_Challenges.Co_LevelChallenges.OutlandsCanyon_PerfectTiming":                "Challenge Outlands Canyon: Perfect Timing",
    "GD_Challenges.Co_LevelChallenges.OutlandsCanyon_VaultRoy":                     "Challenge Outlands Canyon: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.RnDFacility_DataRecovery":                    "Challenge Research and Development: Data Recovery",
    "GD_Challenges.Co_LevelChallenges.RnDFacility_FeedtheFish":                     "Challenge Research and Development: Feed the Fish",
    "GD_Challenges.Co_LevelChallenges.RnDFacility_HookShot":                        "Challenge Research and Development: Hook Shot",
    "GD_Challenges.Co_LevelChallenges.RnDFacility_LeapOfFaithII":                   "Challenge Research and Development: Leap of Faith II",
    "GD_Challenges.Co_LevelChallenges.RnDFacility_VaultRoy":                        "Challenge Research and Development: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.RnDFactility_CantSeeMe":                      "Challenge Research and Development: Can't See Me",
    "GD_Challenges.Co_LevelChallenges.Spaceport_Clairvoyant":                       "Challenge Concordia: Clairvoyant",
    "GD_Challenges.Co_LevelChallenges.Spaceport_Dancing":                           "Challenge Concordia: Doin' the Robot",
    "GD_Challenges.Co_LevelChallenges.Spaceport_FairCop":                           "Challenge Concordia: It's a Fair Cop",
    "GD_Challenges.Co_LevelChallenges.Spaceport_Jackpot":                           "Challenge Concordia: Jackpot!",
    "GD_Challenges.Co_LevelChallenges.Spaceport_VaultRoy":                          "Challenge Concordia: Cult of the Vault",
    "GD_Challenges.Co_LevelChallenges.SubLevel13_VaultRoy":                         "Challenge Sub-Level 13: Cult of the Vault",
    "GD_Challenges.Co_LevelECHOChallenges.MapECHO_Access":                          "Challenge Tycho's Ribs: History of Elpis' Interior",
    "GD_Challenges.Co_LevelECHOChallenges.MapECHO_Digsite":                         "Challenge Vorago Solitude: Entirely Metal Outerwear",
    "GD_Challenges.Co_LevelECHOChallenges.MapECHO_MoonSurface":                     "Challenge Stanton's Liver: Digging up the Past",
    "GD_Challenges.LevelECHOChallenges.MapECHO_Athena":                             "Challenge Hyperion Hub of Heroism: Wise Owl",
    "GD_Challenges.LevelECHOChallenges.MapECHO_Fragtrap":                           "Challenge Hyperion Hub of Heroism: Interplanetary Ninja Chatterbox",
    "GD_Challenges.LevelECHOChallenges.MapECHO_Nisha":                              "Challenge Hyperion Hub of Heroism: Hard Knocks",
    "GD_Challenges.LevelECHOChallenges.MapECHO_Wilhelm":                            "Challenge Hyperion Hub of Heroism: Robotic Aspirations",
    "GD_Marigold_Challenges.Enemies.Enemies_KillCorruptions":                       "Challenge Claptrap: Clean Sweep",
    "GD_Marigold_Challenges.Enemies.Enemies_KillInsecuityForces":                   "Challenge Claptrap: Claptomaniac",
    "GD_Marigold_Challenges.Enemies.Enemies_KillsFromBitBombs":                     "Challenge Claptrap: Volakillity",
    "GD_Marigold_Challenges.Loot.Loot_OpenGlitchedChests":                          "Challenge Claptrap: I Like Surprises...",
    "GD_Marigold_Challenges.Loot.Loot_PickupGlitchedItems":                         "Challenge Claptrap: 99 Problems and a Glitch Aint One",
    "GD_Marigold_Challenges.LevelChallenges.Deck13_VaultRoy":                       "Challenge Deck 13 ½: Cult of the Vault",
    "GD_Marigold_Challenges.LevelChallenges.FinalBoss_PlatformPanic":               "Challenge EOSArena: Platform Panic",
    "GD_Marigold_Challenges.LevelChallenges.FinalBoss_VaultRoy":                    "Challenge EOSArena: Cult of the Vault",
    "GD_Marigold_Challenges.LevelChallenges.LeftCluster_VaultRoy":                  "Challenge Cluster 00773 P4ND0R4: Cult of the Vault",
    "GD_Marigold_Challenges.LevelChallenges.LeftCluster_VoidRage":                  "Challenge Cluster 00773 P4ND0R4: Void Rage",
    "GD_Marigold_Challenges.LevelChallenges.Motherboard_AdvancedSearch":            "Challenge Motherlessboard: Advanced Search",
    "GD_Marigold_Challenges.LevelChallenges.Motherboard_BandwidthHog":              "Challenge Motherlessboard: Bandwidth Hog",
    "GD_Marigold_Challenges.LevelChallenges.Motherboard_BoardJumper":               "Challenge Motherlessboard: Board Jumper",
    "GD_Marigold_Challenges.LevelChallenges.Motherboard_VaultRoy":                  "Challenge Motherlessboard: Cult of the Vault",
    "GD_Marigold_Challenges.LevelChallenges.Nexus_Dodgewall":                       "Challenge The Nexus: Dodgewall",
    "GD_Marigold_Challenges.LevelChallenges.Nexus_VaultRoy":                        "Challenge The Nexus: Cult of the Vault",
    "GD_Marigold_Challenges.LevelChallenges.RightCluster_Balloons":                 "Challenge Cluster 99002 0V3RL00K: My Balloons! Those are my Balloons!",
    "GD_Marigold_Challenges.LevelChallenges.RightCluster_Faptrap":                  "Challenge Cluster 99002 0V3RL00K: Faptrap",
    "GD_Marigold_Challenges.LevelChallenges.RightCluster_VaultRoy":                 "Challenge Cluster 99002 0V3RL00K: Cult of the Vault",
    "GD_Marigold_Challenges.LevelChallenges.SubBoss_CircuitJumper":                 "Challenge The Cortex: Circuit Jumper",
    "GD_Marigold_Challenges.LevelChallenges.SubBoss_VaultRoy":                      "Challenge The Cortex: Cult of the Vault",
    "GD_Marigold_Challenges.LevelChallenges.Subconscious_Bobble":                   "Challenge Subconscious: Bobble, Bobble, Soil and Rubble",
    "GD_Marigold_Challenges.LevelChallenges.Subconscious_FindersCreepers":          "Challenge Subconscious: Finders Creepers",
    "GD_Marigold_Challenges.LevelChallenges.Subconscious_ThoughtBubbles":           "Challenge Subconscious: A Bubble for your Thoughts",
    "GD_Marigold_Challenges.LevelChallenges.Subconscious_VaultRoy":                 "Challenge Subconscious: Cult of the Vault",
    "GD_Petunia_Challenges.EridianSlaughter_Beam":                                  "Challenge The Holodome: Power Surge",
    "GD_Petunia_Challenges.EridianSlaughter_Sky":                                   "Challenge The Holodome: Take to the Skies",
    "GD_Petunia_Challenges.EridianSlaughter_VaultRoy":                              "Challenge The Holodome: Cult of the Vault",
    # "GD_Challenges.LevelChallenges.Interlude_Cara-Van":                             "Challenge TYPE: The Van Is Damned",
}


annoying_challenges = [
    "GD_Challenges.Co_LevelChallenges.Spaceport_Jackpot",
    "GD_Challenges.Weapons.Launcher_KillsDirectHit",
    "GD_Challenges.Weapons.Shotgun_KillsLongRange",
]

def reveal_annoying_challenges():
    print("reveal_annoying_challenges")
    for chal_name in annoying_challenges:
        try:
            chal = unrealsdk.find_object("ChallengeDefinition", chal_name)
            get_pc().ReceiveChallenge(ChalDef=chal)
        except ValueError:
            pass
