# keys for this dictionary are either WillowAIPawn.AIClass.Name or WillowAIPawn.BalanceDefinitionState.BalanceDefinition.Name
enemy_class_to_loc_name = {
    "CharClass_DahlSergeant_Knuckle":                       "Enemy: Flame Knuckle",
    "CharClass_Ma_DataWorm":                                "Enemy: Denial Subroutine",
    "CharClass_Ned":                                        "Enemy: Red",
    "CharClass_Kelly":                                      "Enemy: Belly",
    "CharClass_RedBelly_Proxy":                             "Enemy: Red & Belly",
    "Bal_Bruce":                                            "Enemy: Bruce",
    "CharClass_LoaderUltimateBadass":                       "Enemy: Eclipse",
    "CharClass_EyeOfHelios":                                "Enemy: EOS",  #CharClass_Ma_Helios
    "CharClass_OphaBoss":                                   "Enemy: Opha Superior",
    "PawnBalance_FinalBossCork":                            "Enemy: The Sentinel",
    "PawnBalance_RaidBossCork":                             "Enemy: The Invincible Sentinel", 
    # "CharClass_FBCBig_Face":                              "Enemy: The Invincible Empyrean Sentinel",  #CharClass_FBCBig
    "CharClass_ColZMech":                                   "Enemy: Colonel T. Zarpedon",
    "CharClass_ColZ":                                       "Enemy: Tungsteena Zarpedon, Ascended",
    "CharClass_DahlMarine_CentralTerm":                     "Enemy: Corporal Bob",
    "CharClass_Meg":                                        "Enemy: Meg",  #CharClass_Tentacle_Meg, CharClass_Tentacle_Meg_B
    "CharClass_Dean":                                       "Enemy: Dean",
    "CharClass_DahlRedShirt":                               "Enemy: Lost Legion Courier",
    "CharClass_DahlRedShirtPowersuit":                      "Enemy: Lost Legion Powersuit Noob",
    "CharClass_NPCInjuredSoldier":                          "Enemy: Surrendering Dahl Soldier",
    "CharClass_RabidAdams":                                 "Enemy: Rabid Adams",
    "CharClass_DrongoBones":                                "Enemy: Drongo Bones",
    "CharClass_BoomerJetFighter":                           "Enemy: Boomer",
    "CharClass_TonyTinCan":                                 "Enemy: Tony Slows",
    "CharClass_PoopDeck":                                   "Enemy: Poop Deck",
    "CharClass_Bosun":                                      "Enemy: Bosun",
    "CharClass_SpacemanDeadlift":                           "Enemy: Deadlift",
    "CharClass_Squat":                                      "Enemy: Squat",
    "CharClass_Stalker_RnD":                                "Enemy: X-STLK-23",
    "CharClass_DestroyerMini":                              "Enemy: Mini Destroyer",
    "CharClass_SonFlamey":                                  "Enemy: Son of Flamey",
    "PawnBalance_GrandsonFlamey":                           "Enemy: Grandson of Flamey", #named minibeast
    "CharClass_UniqueCharger":                              "Enemy: Antagonized Kraggon",
    "CharClass_Rockzilla":                                  "Enemy: Iwajira",
    "PawnBalance_NotCuteBadassTork":                        "Enemy: Even-More-Disgusting Tork",
    "CharClass_ScavWastelandWalker":                        "Enemy: Swagman",
    "CharClass_RoosterBooster":                             "Enemy: Rooster Booster",
    "CharClass_Ma_Despair":                                 "Enemy: Despair",
    "CharClass_Ma_SelfLoathing":                            "Enemy: Self-Loathing",
    "CharClass_Ma_Sponx":                                   "Enemy: The Sponx",
    "CharClass_Ma_SH4D0W-TP":                               "Enemy: SH4D0W-TP",
    "CharClass_Ma_SelfEsteem":                              "Enemy: Self-Esteem",
    "CharClass_Ma_Hope":                                    "Enemy: Hope",
    "CharClass_LittleDarksiderBadassBandit":                "Enemy: Magma Rivers",
    "CharClass_DarksiderBadassBandit":                      "Enemy: Wally Wrong",
    "CharClass_DarksiderBadassPsycho":                      "Enemy: Fair Dinkum",
    "PawnBalance_GiantCryodunk":                            "Enemy: Giant Shuggurath of Ice",
    "PawnBalance_LunestalkerSnrRider":                      "Enemy: Lunestalker Sr.", #CharClass_ScavJetFighterRider 
    "PawnBalance_MaureenRider":                             "Enemy: Maureen",  #CharClass_ScavJetFighterRider
    "CharClass_MeatHead":                                   "Enemy: Meat Head",
    "PawnBalance_ScavSuicidePsycho_Oscar":                  "Enemy: Oscar",
    # "CharClass_BoilGuard":                                "Enemy: Meat Is Murder", 
    # "CharClass_BoilWorker":                               "Enemy: Better With Butter", 
    # "CharClass_BoilWorker":                               "Enemy: One of Us", 
    # "CharClass_BoilWorker":                               "Enemy: Slimy Yet Satisfying", 
    # "CharClass_BoilWorker":                               "Enemy: Vegans Are Weird", 
    # "CharClass_HypRatWorker":                             "Enemy: Eat At Boil's", 
    # "CharClass_HypRatWorker":                             "Enemy: Free-Range, Farm-Fresh", 
    # "CharClass_HypRatWorker":                             "Enemy: Marinated Morsel", 
    # "CharClass_HypRatWorker":                             "Enemy: Yummy Down On This", 
    # "CharClass_HypRatWorker":                             "Enemy: Choice Cut", 
    "CharClass_Eghood":                                     "Enemy: Eghood",
    "CharacterClass_Clap_L3K":                              "Enemy: CL4P-L3K",
    "PawnDef_MasterPoacher":                                "Enemy: Master Poacher",
    "CharClass_DanZando":                                   "Enemy: Dan Zando",
    "CharClass_Nel":                                        "Enemy: Nel",
    "CharClass_DahlCombatSuit_Felicity":                    "Enemy: Powersuit Felicity",
    "CharClass_Petunia_DestroyerMini":                      "Enemy: Defense Destroyer",
    "CharClass_DahlEternalPowersuit":                       "Enemy: Lost Legion Eternal Powersuit",
    "CharClass_GuardianPondor":                             "Enemy: Guardian Pondor",
    "CharClass_ElementalRider":                             "Enemy: Scavenger Beast",
    "CharClass_BanditRider":                                "Enemy: Scav Beast Rider",
    "CharClass_ElementalRider_Lil":                         "Enemy: Lil' Scavenger Beast",
    "CharClass_ScavBanditMidget_Rider":                     "Enemy: Lil' Scav",
    # "CharClass_Ma_Virus_Deletion":                        "Enemy: Reluctant Virus", 
    # "CharClass_Ma_Virus_Deletion":                        "Enemy: Ravenous Virus", 
    "CharacterClass_Ma_SuperEgoTrap":                       "Enemy: 5UP4-3G0-TP",
    "CharClass_Ma_MinacMinion":                             "Enemy: MINAC Minion",
    "CharacterClass_DignityTrap":                           "Enemy: D1GN1TY-TP",
    "CharClass_Ma_MiniTrojan_Shame":                        "Enemy: Shame",
    "CharClass_Ma_Chip":                                    "Enemy: Chip",
    "CharClass_Ma_Cookie":                                  "Enemy: Cookie",
    "CharClass_Ma_InsecurityBot":                           "Enemy: Minion",
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Catchy Hook!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Floor Filler!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Key Change!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Most Requested!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Sparkly Formula!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Tween Favorite!", 
    # "CharClass_Ma_EarWormTentacle":                       "Enemy: Verse Chorus Verse Chorus Bridge Chorus (x2)!", 
    "CharClass_Ma_EarWorm":                                 "Enemy: Teh Earworm",
}
generic_enemy_lookup = {
    "elebeast":                                             "Generic: Kraggon",
    "rodunk":                                               "Generic: Rathyd",
    "hiveflyer":                                            "Generic: Shuggurath",
    "stalker":                                              "Generic: Stalker",
    "thresher":                                             "Generic: Thresher",
    "tork":                                                 "Generic: Tork",
    "bugs":                                                 "Generic: Bug",
    "glitches":                                             "Generic: Glitch",
    "virus":                                                "Generic: Virus",
    "bandit":                                               "Generic: Scav",
    "psycho":                                               "Generic: Lunatic",
    "nomad":                                                "Generic: Outlaw",
    "spaceman":                                             "Generic: Outlaw",
    "colz":                                                 "Generic: Lost Legion",
    "dahl":                                                 "Generic: Lost Legion",
    "dahlpowersuit":                                        "Generic: Vehicle",
    "dahlcombatsuit":                                       "Generic: Vehicle",
    "dahleternalpowersuit":                                 "Generic: Vehicle",
    # "buggy":                                                "Generic: Vehicle", #does not work due to buggy not being an AIPawn
    # we use single quote here as the 
    # str(pawn) returns "aipawndef'GD_something.ScavPowerSuit'" so ' can be used to denote endswith
    "jetfighter'":                                          "Generic: Vehicle",
    "scavpowersuit'":                                       "Generic: Vehicle", #no riders
    "scavpowersuit_onerider'":                              "Generic: Vehicle", #the powersuit with one rider
    "scavpowersuit_tworiders'":                             "Generic: Vehicle", #the powersuit with one rider on each shoulder 
    
    "boils":                                                "Generic: Boil",
    "population_rat":                                       "Generic: Boil",
    "guardian":                                             "Generic: Guardian",
    # "eridian_putti":                                        "Generic: Guardian",
    "eridian_opha":                                         "Generic: Guardian",
    "fragmented":                                           "Generic: B4nD1T",
    "gd_ma_pop_trojan":                                     "Generic: B4nD1T",
    "claptrapforces":                                       "Generic: Insecurity",
    "midget":                                               "Generic: Midget",
    "little":                                               "Generic: Midget",
    "protowarbot":                                          "Generic: Machine",
    "population_turret":                                    "Generic: Machine",
    "dahlturret":                                           "Generic: Machine",
    "engineershield":                                       "Generic: Machine",
}