# These use the nicely formatted names
# TODO: potentially only need one per entrance. Not sure if they are all the right way round though
from BouncyLootGod.state import get_globals
entrance_to_req_areas = {
    # LevelTravelStationDefinition
    "MoonShotIntroToAirstrip":                 ["Serenity's Waste"],#
    "MoonsurfaceToDeadsurface":                ["Serenity's Waste", "Regolith Range"],
    "MoonsurfaceToDeadsurfaceMoonZoomy":       ["Serenity's Waste", "Regolith Range"],
    "AirstripToSpaceport":                     ["Serenity's Waste", "Concordia"],
    "DeadsurfaceToMoonsurface":                ["Regolith Range", "Serenity's Waste"],
    "DeadsurfaceToMoonsurfaceMoonZoomy":       ["Regolith Range", "Serenity's Waste"],
    "SecretSpaceportToMoon":                   ["Concordia", "Triton Flats"],
    "SpaceportToMeriff":                       ["Concordia", "The Meriff's Office"],
    "SpaceportToAirstrip":                     ["Concordia", "Serenity's Waste"],
    "SpaceportToMoon":                         ["Concordia", "Triton Flats"],
    "MainMoonToComFacility":                   ["Triton Flats", "Crisis Scar"],
    "SecretMoonToSpaceport":                   ["Triton Flats", "Concordia"],
    "MoonToDahlFactory":                       ["Triton Flats", "Titan Industrial Facility"],
    "MoonSurfaceToStantonsLiver":              ["Triton Flats", "Stanton's Liver"],
    "MoonSurfaceToDigSite":                    ["Triton Flats", "Vorago Solitude"],
    "MoonToSpaceport":                         ["Triton Flats", "Concordia"],
    "MoonToComFacility":                       ["Triton Flats", "Crisis Scar"],
    "MoonToOutlands":                          ["Triton Flats", "Outlands Spur"],
    "ComFacilityToMoon":                       ["Crisis Scar", "Triton Flats"],
    "MainComFacilityToMoon":                   ["Crisis Scar", "Triton Flats"],
    "StantonsLiverToMoonSurface":              ["Stanton's Liver", "Triton Flats"],
    "MeriffToSpaceport":                       ["The Meriff's Office", "Concordia"],
    "Outlands2ToMoon":                         ["Outlands Canyon", "Triton Flats"],
    "Outlands2ToMoonSlaughter":                ["Outlands Canyon", "Abandoned Training Facility"],
    "Outlands2ToOutlands":                     ["Outlands Canyon", "Outlands Spur"],
    "MoonSlaughterToOutlands":                 ["Abandoned Training Facility", "Outlands Spur"],
    "OutlandsToOutlands2":                     ["Outlands Spur", "Outlands Canyon"],
    "OutlandsToWreck":                         ["Outlands Spur", "Pity's Fall"],
    "WreckToOutlands":                         ["Pity's Fall", "Outlands Spur"],
    "DahlFactoryToMoon":                       ["Titan Industrial Facility", "Triton Flats"],
    "FactoryToFactoryBoss":                    ["Titan Industrial Facility", "Titan Robot Production Plant"],
    "FactoryToSublevel13":                     ["Titan Industrial Facility", "Sub-Level 13"],
    "Sublevel13ToFactory":                     ["Sub-Level 13", "Titan Industrial Facility"],
    "FactoryBossToFactory":                    ["Titan Robot Production Plant", "Titan Industrial Facility"],
    "CentralTerminalToInnerHull":              ["Hyperion Hub of Heroism", "Veins of Helios"],
    "CentralTerminalToJacksOffice":            ["Hyperion Hub of Heroism", "Jack's Office"],
    "CentralTerminalToRandDFacility":          ["Hyperion Hub of Heroism", "Research and Development"],
    "JacksOfficeToCentralTerminal":            ["Jack's Office", "Hyperion Hub of Heroism"],
    "RandDFacilityToCentralTerminal":          ["Research and Development", "Hyperion Hub of Heroism"],
    "InnerHullToCentralTerminal":              ["Veins of Helios", "Hyperion Hub of Heroism"],
    "InnerHullToLaser":                        ["Veins of Helios", "Lunar Launching Station"],
    "LaserToInnerHull":                        ["Lunar Launching Station", "Veins of Helios"],
    "LaserToLaserBoss":                        ["Lunar Launching Station", "Eye of Helios"],
    "LaserBossToLaser":                        ["Eye of Helios", "Lunar Launching Station"],
    "Vorago_To_Outfall":                       ["Vorago Solitude", "Outfall Pumping Station"],
    "DigSiteToMoonSurface":                    ["Vorago Solitude", "Triton Flats"],
    "DigSiteToShaft":                          ["Outfall Pumping Station", "Tycho's Ribs"],
    "Outfall_To_Vorago":                       ["Outfall Pumping Station", "Vorago Solitude"],
    "AcessToDigsite":                          ["Tycho's Ribs", "Vorago Solitude"], #Acess is typo'd in the game files
    "AcessToMoonCore":                         ["Tycho's Ribs", "Eleseer"], #Acess is typo'd in the game files  1 
    "MoonCoreToShaft":                         ["Eleseer", "Tycho's Ribs"],
    #claptrap
    "Deck13ToNexus":                           ["Deck 13 ½", "The Nexus"],
    "NexusToMotherboard":                      ["The Nexus", "Motherlessboard"],
    "NexusToDeck13":                           ["The Nexus", "Deck 13 ½"],
    "NexusToSub":                              ["The Nexus", "Subconscious"],
    "MotherboardToNexus":                      ["Motherlessboard", "The Nexus"],
    "MotherboardToRight":                      ["Motherlessboard", "Cluster 99002 0V3RL00K"],
    "MotherboardToLeft":                       ["Motherlessboard", "Cluster 00773 P4ND0R4"],
    "LeftToMotherboard":                       ["Cluster 00773 P4ND0R4", "Motherlessboard"],
    "RightToMotherboard":                      ["Cluster 99002 0V3RL00K", "Motherlessboard"],
    "SubToNexus":                              ["Subconscious", "The Nexus"],
    "SubToSubBoss":                            ["Subconscious", "The Cortex"],
    "SubBossToSub":                            ["The Cortex", "Subconscious"],
    "SubBossToFinalBoss":                      ["The Cortex", "EOSArena"],
    "FinalBossToDeck13":                       ["EOSArena", "Deck 13 ½"],
    "FinalBossToSubBoss":                      ["EOSArena", "The Cortex"],
    
    #unused, discarded or dev entrances, does not appear in LevelTravelStation list when in the appropriate map
    
    # "HiddenMoonShotToAirstrip":                ["Serenity's Waste"],
    # "MoonSlaughterToWreck":                    ["Abandoned Training Facility", "Pity's Fall"],
    # "StantonsLiver_P":                         ["FROM", "TO"],
    # "11B_ElevatortoDigsite":                   ["Tycho's Ribs", "Vorago Solitude"],
    # "CoreVaultToMoonCore":                     ["FROM", "TO"],
    # "ElevatorShaftToDigSite":                  ["Tycho's Ribs", "Vorago Solitude"],
    # "RnDToDahlFactory":                        ["FROM", "Titan Industrial Facility"],
    # "MoonCoreToCoreVault":                     ["FROM", "TO"],
    # "11BElevatortoMoonCore":                   ["FROM", "TO"],
    # "AirstripToMoonSurface":                   ["FROM", "Serenity's Waste"],
    # "DahlFactoryToRnD":                        ["Titan Industrial Facility", "TO"],
    # "Digsite_To_Rk5arena":                     ["FROM", "TO"],
    # "DigsiteJunctionToDigsite":                ["FROM", "Vorago Solitude"],
    # "DigSiteToDigsiteJunction":                ["Vorago Solitude", "TO"],
    # "ElevatorShaftToMoonCore":                 ["FROM", "TO"],
    # "FactoryBossToTerminal":                   ["FROM", "TO"],
    # "TerminalToFactory":                       ["FROM", "TO"],
    # "LabsToRnD":                               ["FROM", "TO"],
    # "RnDToLabs":                               ["FROM", "TO"],
    # "MoonShaftToEridianSlaughter":             ["FROM", "TO"],
    # "MoonSurfaceToAirstrip":                   ["Serenity's Waste", "Stanton's Liver"],
    # "MoonToWaterfront":                        ["Triton Flats", "TO"],
    # "MoonToWreck":                             ["Triton Flats", "Pity's Fall"],
    # "WreckToMoon":                             ["Pity's Fall", "Triton Flats"],
    # "OutlandsToMoon":                          ["Outlands Spur", "Triton Flats"],
    # "OutlandsToMoonSlaughter":                 ["Outlands Spur", "Abandoned Training Facility"],
    # "Rk5arena_To_Digsite":                     ["FROM", "TO"],
    # "RnDToStationSlaughter":                   ["FROM", "TO"],
    # "StationSlaughterToRnD":                   ["FROM", "TO"],
    # "ShaftToDigSite":                          ["FROM", "Vorago Solitude"],
    # "ShaftToMoonCore":                         ["FROM", "TO"],
    # "SolitudeJunction":                        ["FROM", "TO"],
    # "SpaceportToNewHaven":                     ["Concordia", "TO"],
    # "WaterfrontToMoon":                        ["FROM", "Triton Flats"],
    # "WreckToMoonSlaughter":                    ["Pity's Fall", "Abandoned Training Facility"],
    # "Deck13ToFinalBoss":                       ["Deck 13 ½", "TO"],
    # "Deck13toMotherboard":                     ["Deck 13 ½", "Motherlessboard"],
    # "MotherboardToDeck13":                     ["Motherlessboard", "Deck 13 ½"],

    # FastTravelStationDefinition
    # "MoonShotIntro":            ["Helios Station"], #exit only
    # "MoonshotFT":               ["Moonshot Facility"],  #not player reachable
    # "MoonshotIntroFT":          ["Moonshot Escape"],  #not player reachable
    "Airstrip":                 ["Serenity's Waste"],
    "Spaceport":                ["Concordia"],
    "MoonSurfaceFastTravel":    ["Triton Flats"],
    "ComFacility":              ["Crisis Scar"],
    "StantonsLiver_P":          ["Stanton's Liver"],
    "Outlands2":                ["Outlands Canyon"],
    "Outlands":                 ["Outlands Spur"],
    "WreckCrater":              ["Pity's Fall"],
    "DahlFactory":              ["Titan Industrial Facility"],
    "DahlFactoryBossStart":     ["Titan Robot Production Plant"],
    # "DahlFactoryBoss":          ["Titan Robot Embarkation"], #exit only
    "CentralTerminal":          ["Hyperion Hub of Heroism"],
    "JacksOffice":              ["Jack's Office"],
    "RandDFacility":            ["Research and Development"],
    "Laser":                    ["Lunar Launching Station"],
    # "LaserBoss":                ["Eye of Helios"], #exit only
    "AccessShaft":              ["Tycho's Ribs"],
    "DigSite":                  ["Vorago Solitude"],
    "MoonCore":                 ["Eleseer"],
    # "11BElevator":              ["11B_Elevator"], #not player reachable
    # "CoreVault":                ["Core Vault"], #not player reachable
    # "Elevator":                 ["Elevator"], #not player reachable
    # "ElevatorRide":             ["Shaft"], #not player reachable
    "EridianSlaughter":         ["The Holodome"],
    # "RnD":                      ["R&D Facility"], #not player reachable
    "Ma_Deck13_FT":             ["Deck 13 ½"],
    "Ma_Nexus_FT":              ["The Nexus"],
    "Ma_LeftCluster_FT":        ["Cluster 00773 P4ND0R4"],
    # "Ma_LeftCluster_1way_FT":   ["00773 VAULT EXCAVATION SITE"], #exit only
    "Ma_RightCluster_FT":       ["Cluster 99002 0V3RL00K"],
    "Ma_Sub_FT":                ["Subconscious"],
    "MA_SubSub_FT":             ["Sub-Subconscious"],
    "Ma_FinalBoss_FT":          ["EOSArena"],
}

travel_targets = {
    "Helios Station":                     "GD_FastTravelStations.MoonShotIntro",
    "Abandoned Training Facility":        "GD_LevelTravelStations.MoonSlaughterToOutlands",#
    "Cluster 00773 P4ND0R4":              "GD_Ma_FastTravelStations.Ma_LeftCluster_FT",
    "Cluster 99002 0V3RL00K":             "GD_Ma_FastTravelStations.Ma_RightCluster_FT",
    "Concordia":                          "GD_FastTravelStations.Spaceport",
    "Crisis Scar":                        "GD_FastTravelStations.ComFacility",
    "Deck 13 ½":                          "GD_Ma_FastTravelStations.Ma_Deck13_FT",
    "EOSArena":                          "GD_Ma_FastTravelStations.Ma_FinalBoss_FT",
    "Eleseer":                            "GD_FastTravelStations.MoonCore",
    "Eye of Helios":                      "GD_FastTravelStations.LaserBoss",
    "Hyperion Hub of Heroism":            "GD_FastTravelStations.Zone_3.CentralTerminal",
    "Jack's Office":                      "GD_FastTravelStations.Zone_3.JacksOffice",
    "Lunar Launching Station":            "GD_FastTravelStations.Laser",
    "Motherlessboard":                    "GD_Ma_LevelTravelStations.MotherboardToDeck13",
    "Outfall Pumping Station":            "GD_LevelTravelStations.Rk5arena_To_Digsite",
    "Outlands Canyon":                    "GD_FastTravelStations.Outlands2",
    "Outlands Spur":                      "GD_FastTravelStations.Outlands",
    "Pity's Fall":                        "GD_FastTravelStations.WreckCrater",
    "Regolith Range":                     "GD_LevelTravelStations.DeadsurfaceToMoonsurface",
    "Research and Development":           "GD_FastTravelStations.RandDFacility",
    "Serenity's Waste":                   "GD_FastTravelStations.Airstrip",
    "Stanton's Liver":                    "GD_FastTravelStations.StantonsLiver_P",
    "Sub-Level 13":                       "GD_LevelTravelStations.Sublevel13ToFactory",
    "Subconscious":                       "GD_Ma_FastTravelStations.Ma_Sub_FT",
    "The Cortex":                         "GD_Ma_LevelTravelStations.SubBossToSub",
    "The Holodome":                       "GD_Pet_FastTravelStations.EridianSlaughter",
    "The Meriff's Office":                "GD_LevelTravelStations.MeriffToSpaceport",
    "The Nexus":                          "GD_Ma_FastTravelStations.Ma_Nexus_FT",
    "Titan Industrial Facility":          "GD_FastTravelStations.DahlFactory",
    "Titan Robot Production Plant":       "GD_FastTravelStations.DahlFactoryBossStart",
    "Triton Flats":                       "GD_FastTravelStations.MoonSurfaceFastTravel",
    "Tycho's Ribs":                       "GD_FastTravelStations.AccessShaft", 
    "Veins of Helios":                    "GD_LevelTravelStations.Zone_3.InnerHullToCentralTerminal",
    "Vorago Solitude":                    "GD_FastTravelStations.DigSite",
    # "TODO": "GD_FastTravelStations.AccessShaft",
    # "TODO": "GD_FastTravelStations.Airstrip",
    # "TODO": "GD_FastTravelStations.CoreVault",
    # "TODO": "GD_FastTravelStations.DahlFactoryBoss",
    # "TODO": "GD_FastTravelStations.11BElevator",## crash
    # "TODO": "GD_FastTravelStations.Elevator", ##crash
    # "TODO": "GD_FastTravelStations.ElevatorRide", ##crash
    # "TODO": "GD_FastTravelStations.MoonshotFT",
    # "TODO": "GD_FastTravelStations.MoonshotIntroFT", #crashh
    # "TODO": "GD_FastTravelStations.RnD", #crash
    # "TODO": "GD_Ma_FastTravelStations.Ma_LeftCluster_1way_FT",
    # "TODO": "GD_Ma_FastTravelStations.MA_SubSub_FT",
    
}

region_translation_dict = {
    "intro":                           "Helios Station",
    "heliosstation":                   "Helios Station",
    "abandonedtrainingfacility":       "Abandoned Training Facility",
    "trainingfacility":                "Abandoned Training Facility",
    "cluster00773p4nd0r4":             "Cluster 00773 P4ND0R4",
    "00773":                           "Cluster 00773 P4ND0R4",
    "clusterpandora":                  "Cluster 00773 P4ND0R4",
    "pandorasimulation":               "Cluster 00773 P4ND0R4",
    "cluster990020v3rl00k":            "Cluster 99002 0V3RL00K",
    "99002":                           "Cluster 99002 0V3RL00K",
    "clusteroverlook":                 "Cluster 99002 0V3RL00K",
    "overlooksimulation":              "Cluster 99002 0V3RL00K",
    "concordia":                       "Concordia",
    "crisisscar":                      "Crisis Scar",
    "deck13":                          "Deck 13 ½",
    "fakedeck13":                      "EOSArena",
    "eos":                             "EOSArena",
    "eleseer":                         "Eleseer",
    "eyeofhelios":                     "Eye of Helios",
    "eye":                             "Eye of Helios",
    "hyperionhubofheroism":            "Hyperion Hub of Heroism",
    "hubofheroism":                    "Hyperion Hub of Heroism",
    "hun":                             "Hyperion Hub of Heroism",
    "jacksoffice":                     "Jack's Office",
    "lunarlaunchingstation":           "Lunar Launching Station",
    "launchingstation":                "Lunar Launching Station",
    "motherlessboard":                 "Motherlessboard",
    "outfallpumpingstation":           "Outfall Pumping Station",
    "pumpingstation":                  "Outfall Pumping Station",
    "outfall":                         "Outfall Pumping Station",
    "outlandscanyon":                  "Outlands Canyon",
    "canyon":                          "Outlands Canyon",
    "outlandsspur":                    "Outlands Spur",
    "spur":                            "Outlands Spur",
    "pitysfall":                       "Pity's Fall",
    "drakensburg":                     "Pity's Fall",
    "regolith":                        "Regolith Range",
    "regolithrange":                   "Regolith Range",
    "researchanddevelopment":          "Research and Development",
    "rnd":                             "Research and Development",
    "serenityswaste":                  "Serenity's Waste",
    "serenity":                        "Serenity's Waste",
    "stantonsliver":                   "Stanton's Liver",
    "stanton":                         "Stanton's Liver",
    "sublevel13":                      "Sub-Level 13",
    "subconscious":                    "Subconscious",
    "thecortex":                       "The Cortex",
    "cortex":                          "The Cortex",
    "theholodome":                     "The Holodome",
    "holodome":                        "The Holodome",
    "themeriffsoffice":                "The Meriff's Office",
    "meriffsoffice":                   "The Meriff's Office",
    "meriff":                          "The Meriff's Office",
    "thenexus":                        "The Nexus",
    "nexus":                           "The Nexus",
    "titanindustrialfacility":         "Titan Industrial Facility",
    "factory":                         "Titan Industrial Facility",
    "facility":                        "Titan Industrial Facility",
    "titanrobotproductionplant":       "Titan Robot Production Plant",
    "titanrobotplant":                 "Titan Robot Production Plant",
    "robotplant":                      "Titan Robot Production Plant",
    "robot":                           "Titan Robot Production Plant",
    "tritonflats":                     "Triton Flats",
    "triton":                          "Triton Flats",
    "tychosribs":                      "Tycho's Ribs",
    "tychoribs":                       "Tycho's Ribs",
    "tychos":                          "Tycho's Ribs",
    "tycho":                           "Tycho's Ribs",
    "veinsofhelios":                   "Veins of Helios",
    "veins":                           "Veins of Helios",
    "voragosolitude":                  "Vorago Solitude",
    "vorago":                          "Vorago Solitude",
    "solitude":                          "Vorago Solitude",
    
}

progressive_travel_lookup = {
    "basegame": [
        "Helios Station", # index 0 always available
        "Serenity's Waste",
        "Regolith Range",
        "Concordia",
        "Triton Flats",
        "Crisis Scar",
        "The Meriff's Office",
        "Outlands Canyon",
        "Outlands Spur",
        "Pity's Fall",
        "Titan Industrial Facility",
        "Titan Robot Production Plant",
        "Hyperion Hub of Heroism",
        "Jack's Office",
        "Research and Development",
        "Veins of Helios",
        "Lunar Launching Station",
        "Eye of Helios",
        "Vorago Solitude",
        "Outfall Pumping Station",
        "Tycho's Ribs",
        "Eleseer",
    ],
    "basegame_side": [
        "",
        "Stanton's Liver",
        "Sub-Level 13", # TODO
    ],
    "claptrap": [
        "",
        "Deck 13 ½",
        "The Nexus",
        "Motherlessboard",
        "The Cortex",
        "Cluster 00773 P4ND0R4",
        "Cluster 99002 0V3RL00K",
        "Subconscious",
        "EOSArena",
    ],
    "shock_drop": [
        "",
        "Abandoned Training Facility",
    ],
    "holodome": [
        "",
        "The Holodome",
    ],
}

progressive_travel_items = {
    "basegame": "Progressive Travel: Base Game",
    "basegame_side": "Progressive Travel: Side Area",
    "holodome": "Progressive Travel: The Holodome Onslaught DLC",
    "shock_drop": "Progressive Travel: Shock Drop Slaughter Pit DLC",
    "claptrap": "Progressive Travel: Claptastic Voyage DLC"
}
progressive_travel_groups = {v: k for k, v in progressive_travel_items.items()}
