# auto generated from sync-defs.py
archi_data = {
    "loc": {
        "Level 2 Reached": 1,
        "Level 3 Reached": 2,
        "Level 4 Reached": 3,
        "Level 5 Reached": 4,
        "Level 6 Reached": 5,
        "Level 7 Reached": 6,
        "Level 8 Reached": 7,
        "Level 9 Reached": 8,
        "Level 10 Reached": 9,
        "Level 11 Reached": 10,
        "Level 12 Reached": 11,
        "Level 13 Reached": 12,
        "Level 14 Reached": 13,
        "Level 15 Reached": 14,
        "Level 16 Reached": 15,
        "Level 17 Reached": 16,
        "Level 18 Reached": 17,
        "Level 19 Reached": 18,
        "Level 20 Reached": 19,
        "Level 21 Reached": 20,
        "Level 22 Reached": 21,
        "Level 23 Reached": 22,
        "Level 24 Reached": 23,
        "Level 25 Reached": 24,
        "Level 26 Reached": 25,
        "Level 27 Reached": 26,
        "Level 28 Reached": 27,
        "Level 29 Reached": 28,
        "Level 30 Reached": 29,
        "Enemy: Knuckle Dragger": 30,
        "Enemy: Midgemong": 31,
        "Enemy: Boom": 32,
        "Enemy: Bewm": 33,
        "Enemy: Captain Flynt": 34,
        "Enemy: Savage Lee": 35,
        "Enemy: Boll": 36,
        "Enemy: Doc Mercy": 37,
        "Enemy: Assassin Oney": 38,
        "Enemy: Assassin Wot": 39,
        "Enemy: Assassin Reeth": 40,
        "Enemy: Assassin Rouf": 41,
        "Enemy: Scorch": 42,
        "Enemy: Incinerator Clayton": 43,
        "Enemy: Gettle": 44,
        "Enemy: Mobley": 45,
        "Enemy: Black Queen": 46,
        "Enemy: Bad Maw": 47,
        "Enemy: Mad Mike": 48,
        "Enemy: W4R-D3N": 49,
        "Enemy: Spycho": 50,
        "Enemy: McNally": 51,
        "Enemy: Mick/Tector": 52,
        "Enemy: Dan": 53,
        "Enemy: Lee": 54,
        "Enemy: Mick": 55,
        "Enemy: Ralph": 56,
        "Enemy: Flinter": 57,
        "Enemy: Madame Von Bartlesby": 58,
        "Enemy: Prospector Zeke": 59,
        "Enemy: Wilhelm": 60,
        "Enemy: Laney White": 61,
        "Enemy: Rakkman": 62,
        "Enemy: SmashHead": 63,
        "Enemy: Shorty": 64,
        "Enemy: Sinkhole": 65,
        "Enemy: Bloody (Laney Midget)": 66,
        "Enemy: Crabby (Laney Midget)": 67,
        "Enemy: Creepy (Laney Midget)": 68,
        "Enemy: Dirty (Laney Midget)": 69,
        "Enemy: Greedy (Laney Midget)": 70,
        "Enemy: Sleazy (Laney Midget)": 71,
        "Enemy: Tipsy (Laney Midget)": 72,
        "Enemy: Old Slappy": 73,
        "Enemy: Gluttonous Thresher": 74,
        "Enemy: Henry": 75,
        "Enemy: Bagman": 76,
        "Enemy: Blue": 77,
        "Enemy: Badass Creeper": 78,
        "Enemy: Tumbaa": 79,
        "Enemy: Pimon": 80,
        "Enemy: Son of Mothrakk": 81,
        "Enemy: Bloodwing": 82,
        "Enemy: GOD-liath": 83,
        "Enemy: Sarcastic Slab": 84,
        "Enemy: Face McShooty": 85,
        "Enemy: Dukino's Mom": 86,
        "Enemy: Mad Dog": 87,
        "Enemy: Sheriff Nisha": 88,
        "Enemy: Deputy Winger": 89,
        "Enemy: Foreman Jasper": 90,
        "Enemy: Jack's Body Double": 91,
        "Enemy: BNK-3R": 92,
        "Enemy: King Mong": 93,
        "Enemy: Donkey Mong": 94,
        "Enemy: Mortar": 95,
        "Enemy: Hunter Hellquist": 96,
        "Enemy: Bone Head 2.0": 97,
        "Enemy: Saturn": 98,
        "Enemy: Warrior": 99,
        "Enemy: Terramorphous the Invincible": 100,
        "Enemy: Sully the Blacksmith": 101,
        "Enemy: Pumpkin Kingpin": 102,
        "Enemy: Jacques O'Lantern": 103,
        "Enemy: Cryptkeeper Clark": 104,
        "Enemy: Chef Gouda Remsay": 105,
        "Enemy: The Rat in the Hat": 106,
        "Enemy: Chef Brulee": 107,
        "Enemy: Chef Bork Bork": 108,
        "Enemy: Wattle Gobbler": 109,
        "Enemy: Glasspool, Tribute of Wurmwater": 110,
        "Enemy: William, Tribute of Wurmwater": 111,
        "Enemy: Axel, Tribute of Opportunity": 112,
        "Enemy: Rose, Tribute of Opportunity": 113,
        "Enemy: Strip, Tribute of Southern Shelf": 114,
        "Enemy: Flay, Tribute of Southern Shelf": 115,
        "Enemy: Bailly, Tribute of Sawtooth Cauldron": 116,
        "Enemy: Moretus, Tribute of Sawtooth Cauldron": 117,
        "Enemy: Cynder, Tribute of Frostburn": 118,
        "Enemy: Fuse, Tribute of Frostburn": 119,
        "Enemy: Annie, Tribute of Lynchwood": 120,
        "Enemy: Garret, Tribute of Lynchwood": 121,
        "Enemy: Fiona, Tribute of Sanctuary": 122,
        "Enemy: Max, Tribute of Sanctuary": 123,
        "Enemy: Tinder Snowflake": 124,
        "Enemy: Colin Zaford": 125,
        "Enemy: Bridget Hodunk": 126,
        "Enemy: BLNG Loader": 127,
        "Enemy: Stella (Rotgut)": 128,
        "Enemy: Ed (Rotgut)": 129,
        "Enemy: Innuendobot 5000": 130,
        "Enemy: Sigmand": 131,
        "Enemy: Ikaroa": 132,
        "Enemy: Moby": 133,
        "Enemy: Fire Crak'n": 134,
        "Enemy: Rue, the Love Thresher": 135,
        "Enemy: Son of Crawmerax": 136,
        "Enemy: Son of Crawmerax Raid Boss": 137,
        "Enemy: Sparky Flynt": 138,
        "Enemy: No Beard": 139,
        "Enemy: Tinkles": 140,
        "Enemy: Grendel": 141,
        "Enemy: Sandman": 142,
        "Enemy: Big Sleep": 143,
        "Enemy: Benny the Booster": 144,
        "Enemy: Deckhand": 145,
        "Enemy: Toothless Terry": 146,
        "Enemy: P3RV-E": 147,
        "Enemy: H3RL-E": 148,
        "Enemy: DJ Tanner": 149,
        "Enemy: Mr. Bubbles": 150,
        "Enemy: Lieutenant Hoffman (Pirate)": 151,
        "Enemy: Lieutenant White (Pirate)": 152,
        "Enemy: Roscoe": 153,
        "Enemy: The Leviathan": 154,
        "Enemy: Hyperius": 155,
        "Enemy: Master Gee": 156,
        "Enemy: Pyro Pete": 157,
        "Enemy: Sully the Stabber": 158,
        "Enemy: Hamhock": 159,
        "Enemy: Buff Gamer": 160,
        "Enemy: Game Critic": 161,
        "Enemy: Motor Mama": 162,
        "Enemy: Anonymous Troll": 163,
        "Enemy: Uriah": 164,
        "Enemy: Piston's Blimp": 165,
        "Enemy: Badassasaurus": 166,
        "Enemy: Piston": 167,
        "Enemy: Pyro Pete the Invincible": 168,
        "Enemy: Arizona": 169,
        "Enemy: Thermitage": 170,
        "Enemy: Rakkanoth": 171,
        "Enemy: Dribbles": 172,
        "Enemy: Woundspike": 173,
        "Enemy: The Bulwark": 174,
        "Enemy: Rouge": 175,
        "Enemy: Bloodtail": 176,
        "Enemy: Jackenstein": 177,
        "Enemy: Dr. Nakayama": 178,
        "Enemy: Bulstoss": 179,
        "Enemy: Mr. Boney Pants Guy": 180,
        "Enemy: Unmotivated Golem": 181,
        "Enemy: Sir Reginald von Bartlesby": 182,
        "Enemy: Spiderpants": 183,
        "Enemy: Arguk the Butcher": 184,
        "Enemy: Warlord Grug": 185,
        "Enemy: -=n00bkiller=-": 186,
        "Enemy: 420_E-Sports_Masta": 187,
        "Enemy: [720NoScope]Headshotz": 188,
        "Enemy: xxDatVaultHuntrxx": 189,
        "Enemy: King Aliah": 190,
        "Enemy: King Crono": 191,
        "Enemy: King Seth": 192,
        "Enemy: King Nazar": 193,
        "Enemy: Maxibillion": 194,
        "Enemy: Magical Orc": 195,
        "Enemy: Magical Spider": 196,
        "Enemy: Gold Golem": 197,
        "Enemy: Canine": 198,
        "Enemy: Molehill": 199,
        "Enemy: Sir Boil": 200,
        "Enemy: Sir Mash": 201,
        "Enemy: Sir Stew": 202,
        "Enemy: Handsome Dragon": 203,
        "Enemy: Sorcerer's Daughter": 204,
        "Enemy: Edgar/Simon": 205,
        "Enemy: Handsome Sorcerer": 206,
        "Enemy: Incinerator": 207,
        "Enemy: Healianth": 208,
        "Enemy: Brood": 209,
        "Enemy: Boost": 210,
        "Enemy: Warlord Turge": 211,
        "Enemy: Warlord Slog": 212,
        "Enemy: Ghost": 213,
        "Enemy: The Dark Web": 214,
        "Enemy: Uranus Bot": 215,
        "Enemy: Lt. Angvar (New Pandora)": 216,
        "Enemy: Lt. Bolson (New Pandora)": 217,
        "Enemy: Lt. Tetra (New Pandora)": 218,
        "Enemy: Lt. Hoffman (New Pandora)": 219,
        "Enemy: Cassius": 220,
        "Enemy: Hector": 221,
        "Enemy: Dexiduous the Invincible": 222,
        "Enemy: Omnd-Omnd-Ohk": 223,
        "Enemy: Chief Ngwatu": 224,
        "Enemy: Voracidous the Invincible": 225,
        "Enemy: Haderax the Invincible": 226,
        "Enemy: Vermivorous the Invincible": 227,
        "Vending Arid Badlands Fyrestone: Meds": 228,
        "Vending Arid Badlands Fyrestone: Ammo": 229,
        "Vending Arid Badlands Fyrestone: Guns": 230,
        "Vending Arid Badlands Shep: Meds": 231,
        "Vending Arid Badlands Headlands Entrance: Ammo": 232,
        "Vending Arid Badlands Headlands Entrance: Meds": 233,
        "Vending Arid Badlands Bruce McClane: Guns": 234,
        "Vending Skag Gully Entrance: Meds": 235,
        "Vending Skag Gully Entrance: Ammo": 236,
        "Vending Skag Gully 9-Toes: Meds": 237,
        "Vending Skag Gully 9-Toes: Ammo": 238,
        "Vending Arid Hills: Ammo": 239,
        "Vending Arid Hills: Meds": 240,
        "Vending Lost Cave: Meds": 241,
        "Vending Lost Cave: Ammo": 242,
        "Vending Sledges Safehouse: Meds": 243,
        "Vending Sledges Safehouse: Ammo": 244,
        "Vending Headstone Mine: Ammo": 245,
        "Vending Headstone Mine: Meds": 246,
        "Vending Dahl Headlands Luckys: Ammo": 247,
        "Vending Dahl Headlands Luckys: Guns": 248,
        "Vending Dahl Headlands Luckys: Meds": 249,
        "Vending Dahl Headlands Entrance: Meds": 250,
        "Vending Dahl Headlands Entrance: Ammo": 251,
        "Vending Dahl Headlands Speedway: Guns": 252,
        "Vending Dahl Headlands Underground: Guns": 253,
        "Vending Dahl Headlands Underground: Meds": 254,
        "Vending New Haven Entrance: Meds": 255,
        "Vending New Haven Entrance: Ammo": 256,
        "Vending New Haven: Guns": 257,
        "Vending New Haven: Ammo": 258,
        "Vending New Haven: Meds": 259,
        "Vending New Haven Hidden: Guns": 260,
        "Vending Tetanus Warrens: Ammo": 261,
        "Vending Tetanus Warrens: Meds": 262,
        "Vending Crazy Earl's Scrapyard: Ammo": 263,
        "Vending Crazy Earl's Scrapyard: Meds": 264,
        "Vending Rust Commons West: Meds": 265,
        "Vending Rust Commons West: Ammo": 266,
        "Vending Rust Commons West: Guns": 267,
        "Vending Treachers Landing: Ammo": 268,
        "Vending Treachers Landing: Meds": 269,
        "Vending Rust Commons East Middle of Nowhere: Ammo": 270,
        "Vending Rust Commons East Middle of Nowhere: Meds": 271,
        "Vending Rust Commons East Middle of Nowhere: Guns": 272,
        "Vending Rust Commons East Gas Station: Guns": 273,
        "Vending Rust Commons East The Cauldron: Meds": 274,
        "Vending Rust Commons East The Cauldron: Ammo": 275,
        "Vending Rust Commons East Salt Flats Entrance: Meds": 276,
        "Vending Rust Commons East Salt Flats Entrance: Ammo": 277,
        "Vending Kroms Canyon: Meds": 278,
        "Vending Kroms Canyon: Ammo": 279,
        "Vending Old Haven: Ammo": 280,
        "Vending Old Haven: Meds": 281,
        "Vending Old Haven: Guns": 282,
        "Vending Trash Coast: Meds": 283,
        "Vending Trash Coast: Ammo": 284,
        "Vending Salt Flats Fast Travel: Guns": 285,
        "Vending Salt Flats Fast Travel: Meds": 286,
        "Vending Salt Flats Entrance: Guns": 287,
        "Vending Salt Flats Entrance: Meds": 288,
        "Vending The Back Door: Ammo": 289,
        "Vending Crimson Fastness: Ammo": 290,
        "Vending Crimson Fastness: Meds": 291,
        "Vending Crimson Enclave: Meds": 292,
        "Vending Crimson Enclave: Ammo": 293,
        "Vending Eridian Promontory: Meds": 294,
        "Vending Eridian Promontory: Ammo": 295,
        "Vending Jakobs Cove: Ammo": 296,
        "Vending Jakobs Cove: Guns": 297,
        "Vending Jakobs Cove: Meds": 298,
        "Vending Jakobs Cove: Jakobs Vendor": 299,
        "Vending Hallows End Entrance: Ammo": 300,
        "Vending Hallows End Entrance: Meds": 301,
        "Vending Hallows End Town: Meds": 302,
        "Vending Hallows End Town: Ammo": 303,
        "Vending Hallows End Town: Guns": 304,
        "Vending Generally Hospital: Meds": 305,
        "Vending Generally Hospital: Ammo": 306,
        "Vending Dead Haven Entrance: Ammo": 307,
        "Vending Dead Haven Entrance: Meds": 308,
        "Vending Dead Haven: Guns": 309,
        "Vending Dead Haven Franken Bill: Meds": 310,
        "Vending Dead Haven Franken Bill: Ammo": 311,
        "Vending Lumber Yard: Ammo": 312,
        "Vending Lumber Yard: Meds": 313,
        "Vending Lumber Yard: Guns": 314,
        "Vending The Mill: Meds": 315,
        "Vending The Mill: Ammo": 316,
        "Vending The Underdome: Guns": 317,
        "Vending The Underdome: Ammo": 318,
        "Vending The Underdome: Meds": 319,
        "Vending T-Bone Junction Entrance: Ammo": 320,
        "Vending T-Bone Junction Scooters: Ammo": 321,
        "Vending T-Bone Junction Marcus: Ammo": 322,
        "Vending T-Bone Junction: Guns": 323,
        "Vending T-Bone Junction: Meds": 324,
        "Vending Crimson Tollway Entrance: Meds": 325,
        "Vending Crimson Tollway Entrance: Ammo": 326,
        "Vending Crimson Tollway Turrets: Ammo": 327,
        "Vending Crimson Tollway Midway: Ammo": 328,
        "Vending Crimson Tollway Exit: Meds": 329,
        "Vending Crimson Tollway Exit: Ammo": 330,
        "Vending Deep Fathoms Entrance: Meds": 331,
        "Vending Deep Fathoms Entrance: Ammo": 332,
        "Vending Deep Fathoms Bridge: Meds": 333,
        "Vending Deep Fathoms Bridge: Ammo": 334,
        "Vending Moxxis Red Light: Ammo": 335,
        "Vending Moxxis Red Light: Guns": 336,
        "Vending Ridgeway Entrance: Ammo": 337,
        "Vending Ridgeway Entrance: Meds": 338,
        "Vending Ridgeway Exit: Meds": 339,
        "Vending Ridgeway Exit: Ammo": 340,
        "Vending Sunken Sea Entrance: Meds": 341,
        "Vending Sunken Sea Entrance: Ammo": 342,
        "Vending Sunken Sea Thristy: Ammo": 343,
        "Vending Sunken Sea Largest Bullet: Ammo": 344,
        "Vending Sunken Sea Largest Bullet: Guns": 345,
        "Vending Sunken Sea Prison Ramp: Ammo": 346,
        "Vending Lockdown Palace Entrance: Meds": 347,
        "Vending Lockdown Palace Entrance: Ammo": 348,
        "Vending Lockdown Palace Chaz: Ammo": 349,
        "Vending Lockdown Palace Chaz: Meds": 350,
        "Vending Lockdown Palace: Guns": 351,
        "Vending Roads End: Meds": 352,
        "Vending Roads End: Ammo": 353,
        "Vending Roads End Gondola: Guns": 354,
        "Vending Roads End Gondola: Ammo": 355,
        "Vending Road End Exit: Meds": 356,
        "Vending Road End Exit: Ammo": 357,
        "Vending Crimson Armory: Ammo": 358,
        "Vending Crimson Armory: Meds": 359,
        "Vending Crawmeraxs Lair: Ammo": 360,
        "Vending Crawmeraxs Lair: Meds": 361,
        "Vending Crawmeraxs Lair: Guns": 362,
        "Vending Circle of Duty: Guns Right": 363,
        "Vending Circle of Duty: Ammo": 364,
        "Vending Circle of Duty: Meds": 365,
        "Vending Hyperion Dump: Guns": 366,
        "Vending Hyperion Dump: Ammo": 367,
        "Vending Hyperion Dump: Meds": 368,
        "Vending Tartarus Station Marcus: Ammo": 369,
        "Vending Tartarus Station Marcus: Guns": 370,
        "Vending Tartarus Station Town: Meds": 371,
        "Vending Sanders Gorge Entrance: Meds": 372,
        "Vending Sanders Gorge Entrance: Ammo": 373,
        "Vending Sanders Gorge Power Station: Meds": 374,
        "Vending Sanders Gorge Power Station: Ammo": 375,
        "Vending Dividing Faults: Meds": 376,
        "Vending Dividing Faults: Ammo": 377,
        "Vending Scorched Snake Canyon Entrance: Ammo": 378,
        "Vending Scorched Snake Canyon Entrance: Meds": 379,
        "Vending Scorched Snake Canyon Steele: Ammo": 380,
        "Vending Scorched Snake Canyon Steele: Meds": 381,
        "Vending Wayward Pass Entrance: Meds": 382,
        "Vending Wayward Pass Entrance: Ammo": 383,
        "Vending Wayward Pass Entrance: Guns": 384,
        "Vending Wayward Pass Exit: Guns": 385,
        "Vending Wayward Pass Exit: Ammo": 386,
        "Vending Wayward Pass Exit: Meds": 387,
        "Vending Tartarus Station Gift Shop: Guns": 388,
        "Vending Tartarus Station Gift Shop: Ammo": 389,
        "Vending Tartarus Station Gift Shop: Meds": 390,
        "Generic: Skag": 391,
        "Generic: Rakk": 392,
        "Generic: Bullymong": 393,
        "Generic: Psycho": 394,
        "Generic: Rat": 395,
        "Generic: Spiderant": 396,
        "Generic: Varkid": 397,
        "Generic: Goliath": 398,
        "Generic: Marauder": 399,
        "Generic: Stalker": 400,
        "Generic: Midget": 401,
        "Generic: Nomad": 402,
        "Generic: Thresher": 403,
        "Generic: Badass": 404,
        "Generic: Skeleton": 405,
        "Generic: Loader": 406,
        "Generic: Crystalisk": 407,
        "Generic: Surveyor": 408,
        "Generic: Hyperion Personnel": 409,
        "Generic: Constructor": 410,
        "Generic: Buzzard": 411,
        "Generic: Pirate": 412,
        "Generic: Sand Worm": 413,
        "Generic: Biker": 414,
        "Generic: Flyboy Buzzard": 415,
        "Generic: Torgue Loader": 416,
        "Generic: Borok": 417,
        "Generic: Savage": 418,
        "Generic: Witch Doctor": 419,
        "Generic: Drifter": 420,
        "Generic: Scaylion": 421,
        "Generic: Spore": 422,
        "Generic: Golem": 423,
        "Generic: Spider": 424,
        "Generic: Treant": 425,
        "Generic: Pixie": 426,
        "Generic: Orc": 427,
        "Generic: Knight": 428,
        "Generic: Dragon": 429,
        "Generic: Mimic": 430,
        "Generic: Dwarf": 431,
        "Generic: Spellcaster": 432,
        "Generic: Infected": 433,
        "Generic: New Pandora Unit": 434,
        "Generic: Pump-Kin": 435,
        "Generic: Chef": 436,
        "Generic: TorgueVision": 437,
        "Generic: Stabber Jabber": 438,
        "Generic: Yeti": 439,
        "Generic: Snowman": 440,
        "Generic: Crab-Kin": 441,
        "Challenge Elemental: 12 Days of Pandora": 442,
        "Challenge Humans: Headhunter": 443,
        "Challenge Humans: Not Really a People Person": 444,
        "Challenge Humans: Misanthrope": 445,
        "Challenge Humans: War Criminal": 446,
        "Challenge Criticals: Lucky Shot!": 447,
        "Challenge Criticals: Crack Shot": 448,
        "Challenge Criticals: Don't You Ever Miss?": 449,
        "Challenge Criticals: Brain Surgeon": 450,
        "Challenge Kill Chain: Relentless": 451,
        "Challenge Kill Chain: Chain Killer": 452,
        "Challenge Kill Chain: Killing Spree": 453,
        "Challenge Kill Chain: Conveyor of Death": 454,
        "Challenge Action Skill: Action Hero": 455,
        "Challenge Action Skill: Beware!  Mad Skills!": 456,
        "Challenge Action Skill: Why do you even carry a gun?": 457,
        "Challenge Action Skill: Your Kung Fu is Best": 458,
        "Challenge Total Kills: Seasoned Killer": 459,
        "Challenge Total Kills: Numb to the Voices": 460,
        "Challenge Total Kills: Terror of Pandora": 461,
        "Challenge Total Kills: I am become Death...": 462,
        "Challenge Economy: Pocket Change": 463,
        "Challenge Economy: Money.  It buys Happiness": 464,
        "Challenge Economy: The Rich get Richer": 465,
        "Challenge Economy: How Much For The Planet?": 466,
        "Challenge Duels: Duelist": 467,
        "Challenge Duels: Smack Down!": 468,
        "Challenge Duels: Bragging Rights": 469,
        "Challenge Duels: Invincible": 470,
        "Challenge Enemies: Skag Slayer": 471,
        "Challenge Enemies: SIT! STAY! PLAY DEAD!": 472,
        "Challenge Enemies: I hate dogs": 473,
        "Challenge Enemies: You Are The Skagpocalypse": 474,
        "Challenge Enemies: Spiderant Slayer": 475,
        "Challenge Enemies: Bug Crusher": 476,
        "Challenge Enemies: I hate bugs": 477,
        "Challenge Enemies: The Exterminator": 478,
        "Challenge Enemies: Rakk Slayer": 479,
        "Challenge Enemies: If it flies, it dies": 480,
        "Challenge Enemies: Rakk Flak": 481,
        "Challenge Enemies: If I can't fly, no one flies": 482,
        "Challenge Enemies: What is that thing?": 483,
        "Challenge Enemies: The Vault is mine": 484,
        "Challenge Enemies: Xenophobe": 485,
        "Challenge Enemies: Dominant species": 486,
        "Challenge Rifle: Spray and Prey": 487,
        "Challenge Rifle: Size matters": 488,
        "Challenge Rifle: Make Chunks": 489,
        "Challenge Rifle: One Man Army": 490,
        "Challenge Pistol: Draw!": 491,
        "Challenge Pistol: Size doesn't matter": 492,
        "Challenge Pistol: No one's laughing now": 493,
        "Challenge Pistol: Pistolero": 494,
        "Challenge Shotgun: Get off my lawn!": 495,
        "Challenge Shotgun: Taste the red mist": 496,
        "Challenge Shotgun: Instant Autopsy": 497,
        "Challenge Shotgun: Buckshot Legend": 498,
        "Challenge Launcher: Boom": 499,
        "Challenge Launcher: BOOM": 500,
        "Challenge Launcher: KaBOOM!": 501,
        "Challenge Launcher: KA BOOOOOOOM!!!!": 502,
        "Challenge SMG: Rat a Tat!": 503,
        "Challenge SMG: So many little holes...": 504,
        "Challenge SMG: Bullet Hose": 505,
        "Challenge SMG: Human Tsunami": 506,
        "Challenge Sniper: One Shot, One Kill": 507,
        "Challenge Sniper: I'll wait back here...": 508,
        "Challenge Sniper: Brain Ventilator": 509,
        "Challenge Sniper: Finger of God": 510,
        "Challenge Melee: Punchy": 511,
        "Challenge Melee: Brawler": 512,
        "Challenge Melee: Boxer": 513,
        "Challenge Melee: Heavyweight Champion": 514,
        "Challenge Fire: Hot! Too Hot!": 515,
        "Challenge Fire: Toasty!": 516,
        "Challenge Fire: Plays with matches": 517,
        "Challenge Fire: Pyromaniac": 518,
        "Challenge Shock: Zap!": 519,
        "Challenge Shock: Nikola is a friend of mine": 520,
        "Challenge Shock: Puts forks in sockets": 521,
        "Challenge Shock: Shocker": 522,
        "Challenge Corrosive: Chemistry Rocks!": 523,
        "Challenge Corrosive: Why is the floor all gooey?": 524,
        "Challenge Corrosive: Mixes household chemicals": 525,
        "Challenge Corrosive: Chemist": 526,
        "Challenge Explosive: Boom goes the Dynamite!": 527,
        "Challenge Explosive: Too bad about the Tinnitus": 528,
        "Challenge Explosive: Crosses border for fireworks": 529,
        "Challenge Explosive: Demolitionist": 530,
        "Challenge Vehicle: Road Rage": 531,
        "Challenge Vehicle: Vehicular Manslaughter": 532,
        "Challenge Vehicle: School bus Driver": 533,
        "Challenge Vehicle: Hell on Wheels": 534,
        "Challenge Loot: What's in here?": 535,
        "Challenge Loot: Scavenger": 536,
        "Challenge Loot: Wilderness Survivor": 537,
        "Challenge Loot: No stone unturned": 538,
        "Challenge Loot: Ooo! Shiney!": 539,
        "Challenge Loot: Treasure Hunter": 540,
        "Challenge Loot: Swag Master": 541,
        "Challenge Loot: Envy of Pirates": 542,
        "Challenge Economy: How much for the gun?": 543,
        "Challenge Economy: Gun runner": 544,
        "Challenge Economy: Arms dealer": 545,
        "Challenge Economy: Merchant of Death": 546,
        "Challenge Economy: Impulse buyer": 547,
        "Challenge Economy: Good Consumer": 548,
        "Challenge Economy: I want it all!": 549,
        "Challenge Economy: Self contained economy": 550,
        "Challenge Shots Fired: Lots of shots": 551,
        "Challenge Shots Fired: Keep firing": 552,
        "Challenge Shots Fired: Who made that man a gunner?": 553,
        "Challenge Shots Fired: I fired every bullet ever": 554,
        "Challenge Vehicle: Hang Time": 555,
        "Challenge Vehicle: Airborne": 556,
        "Challenge Vehicle: This is not a flight simulator": 557,
        "Challenge Vehicle: Orbit Achieved": 558,
        "Chest Arid Badlands: Gas Station Roof": 559,
        "Chest Arid Badlands: Intro Chest": 560,
        "Chest Arid Badlands: Next to Colosseum": 561,
        "Chest Arid Badlands: Windmills Roof": 562,
        "Chest Arid Badlands: Bruce McClane": 563,
        "Chest Arid Badlands: Combat Rifle Scavenge": 564,
        "Chest Arid Badlands: Cigars Cliffside": 565,
        "Chest Arid Badlands: Skull Collection Upper": 566,
        "Chest Arid Badlands: Skull Collection Lower": 567,
        "Chest Arid Badlands: T.K.s House": 568,
        "Chest Skag Gully: 9 Toes": 569,
        "Chest Skag Gully: Echo Log #1": 570,
        "Chest Skag Gully: Skar": 571,
        "Chest Skag Gully: Seed Collection Cave": 572,
        "Chest Skag Gully: Seed Collection Exit": 573,
        "Chest Arid Hills: Moe & Marley": 574,
        "Chest Arid Hills: Above Sledges Safehouse": 575,
        "Chest Sledges Safehouse: Damaged Claptrap": 576,
        "Chest Sledges Safehouse: Claptraps Room": 577,
        "Chest Sledges Safehouse: Checkpoint Room": 578,
        "Chest Sledges Safehouse: Midget Room Roof": 579,
        "Chest Lost Cave: Checkpoint": 580,
        "Chest Lost Cave: Skag Hill": 581,
        "Chest Lost Cave: Bandit Camp Cave": 582,
        "Chest Lost Cave: Bandit Camp": 583,
        "Chest Lost Cave: Skag Den #1": 584,
        "Chest Lost Cave: Skag Den #2": 585,
        "Chest Headstone Mine: Hidden Roof": 586,
        "Chest Headstone Mine: Across From Turret Room": 587,
        "Chest Headstone Mine: Hut Outside of Sledges": 588,
        "Chest Headstone Mine: Sledges Elevator": 589,
        "Chest Dahl Headland: Luckys Backyard": 590,
        "Chest Dahl Headland: Speedway Roof": 591,
        "Chest Dahl Headland: Bandit Camp #1": 592,
        "Chest Dahl Headland: Bandit Camp #2": 593,
        "Chest Dahl Headland: Underground Eridians": 594,
        "Chest Dahl Headland: X Marks the Spot": 595,
        "Chest Old Haven: Rider Chest": 596,
        "Chest Tetanus Warrens: Left Bandit Camp Roof": 597,
        "Chest Tetanus Warrens: Right Bandit Camp Roof": 598,
        "Chest Tetanus Warrens: Spiderant Ambush": 599,
        "Chest Tetanus Warrens: Wee Wees House": 600,
        "Chest Rust Commons West: Above the Underpass": 601,
        "Chest Rust Commons West: Tannis Area #1": 602,
        "Chest Rust Commons West: Tannis Area #2": 603,
        "Chest Rust Commons West: Badass Hut": 604,
        "Chest Rust Commons West: Spiderant Cliffside #1": 605,
        "Chest Rust Commons West: Spiderant Cliffside #2": 606,
        "Chest Rust Commons West: Secret Cliffside": 607,
        "Chest Rust Commons West: Middle Bandit Camp Walkway": 608,
        "Chest Rust Commons West: Up To Our Ears Walkway": 609,
        "Chest Crazy Earls Scrapyard: Claptrap Repair #1": 610,
        "Chest Crazy Earls Scrapyard: Claptrap Repair #2": 611,
        "Chest Crazy Earls Scrapyard: Bandit Camp Jump": 612,
        "Chest Crazy Earls Scrapyard: High Explosives #1": 613,
        "Chest Crazy Earls Scrapyard: High Explosives #2": 614,
        "Chest Treachers Landing: Bandit Camp Crows Nest": 615,
        "Chest Treachers Landing: Tannis on a Fish": 616,
        "Chest Treachers Landing: Exit Shortcut": 617,
        "Chest Rust Commons East: North Beacon": 618,
        "Chest Rust Commons East: Behind Middle of Nowhere": 619,
        "Chest Rust Commons East: Jaynis Kobb": 620,
        "Chest Rust Commons East: Taylor Kobb": 621,
        "Chest Rust Commons East: Helob": 622,
        "Chest Rust Commons East: The Cauldron Cliff": 623,
        "Chest Rust Commons East: Overlook Beacon": 624,
        "Chest Rust Commons East: New Religion Overlook": 625,
        "Chest Rust Commons East: New Religion Camp": 626,
        "Chest Kroms Canyon: Above Fast Travel": 627,
        "Chest Kroms Canyon: Claptrap Repair": 628,
        "Chest Kroms Canyon: Food Collection Hidden Chest": 629,
        "Chest Kroms Canyon: Reaver Exit Shortcut": 630,
        "Chest Kroms Canyon: Hidden Bandit Camp": 631,
        "Chest Kroms Canyon: Krom": 632,
        "Chest Old Haven: Center Street Rooftop #1": 633,
        "Chest Old Haven: Center Street Rooftop #2": 634,
        "Chest Old Haven: Above Fast Travel Rooftop": 635,
        "Chest Old Haven: Turrets": 636,
        "Chest Trash Coast: Claptrap": 637,
        "Chest Trash Coast: Skrappy #1": 638,
        "Chest Trash Coast: Skrappy #2": 639,
        "Chest Trash Coast: Skrappy #3": 640,
        "Chest Trash Coast: Skrappy #4": 641,
        "Chest Trash Coast: Skrappy #5": 642,
        "Chest Trash Coast: Above King Aracobb #1": 643,
        "Chest Trash Coast: Above King Aracobb #2": 644,
        "Chest Trash Coast: All the way in the Back": 645,
        "Chest Trash Coast: Before Rakkhive": 646,
        "Chest Salt Flats: Entrance Bandit Camp": 647,
        "Chest Salt Flats: Silo Bandit Camp": 648,
        "Chest Salt Flats: Silo Bandit Camp Hidden": 649,
        "Chest Salt Flats: Claptrap Repair": 650,
        "Chest Salt Flats: Outside Elevator": 651,
        "Chest Salt Flats: Inside Elevator": 652,
        "Chest Salt Flats: Flynt Fight #1": 653,
        "Chest Salt Flats: Flynt Fight #2": 654,
        "Chest Salt Flats: Lance Outpost Roof": 655,
        "Chest Back Door: Checkpoint": 656,
        "Chest Back Door: Vendor #1": 657,
        "Chest Back Door: Vendor #2": 658,
        "Chest Back Door: Hidden McCloud": 659,
        "Chest Crimson Fastness: Turret Room": 660,
        "Chest Crimson Fastness: Claptrap Repair #1": 661,
        "Chest Crimson Fastness: Claptrap Repair #2": 662,
        "Chest Crimson Fastness: Tannis Room Upper": 663,
        "Chest Crimson Fastness: Tannis Room Lower": 664,
        "Chest Crimson Fastness: Exit #1": 665,
        "Chest Crimson Fastness: Exit #2": 666,
        "Chest Crimson Enclave: South Relay": 667,
        "Chest Crimson Enclave: West Relay": 668,
        "Chest Crimson Enclave: North Relay": 669,
        "Chest The Descent: Entrance #1": 670,
        "Chest The Descent: Entrance #2": 671,
        "Chest The Descent: The Pit #1": 672,
        "Chest The Descent: The Pit #2": 673,
        "Chest Eridian Promontory: Ambush": 674,
        "Chest Eridian Promontory: The Arch": 675,
        "Chest Eridian Promontory: Behind Lance Rockets": 676,
        "Chest Eridian Promontory: Lance Rockets": 677,
        "Chest Eridian Promontory: Exit Area": 678,
        "Chest Eridian Promontory: Exit Cliffside": 679,
        "Common Shield Found": 680,
        "Uncommon Shield Found": 681,
        "Rare Shield Found": 682,
        "VeryRare Shield Found": 683,
        "Legendary Shield Found": 684,
        "Seraph Shield Found": 685,
        "Rainbow Shield Found": 686,
        "Unique Shield Found": 687,
        "Common GrenadeMod Found": 688,
        "Uncommon GrenadeMod Found": 689,
        "Rare GrenadeMod Found": 690,
        "VeryRare GrenadeMod Found": 691,
        "Legendary GrenadeMod Found": 692,
        "Seraph GrenadeMod Found": 693,
        "Rainbow GrenadeMod Found": 694,
        "Unique GrenadeMod Found": 695,
        "Common ClassMod Found": 696,
        "Uncommon ClassMod Found": 697,
        "Rare ClassMod Found": 698,
        "VeryRare ClassMod Found": 699,
        "Legendary ClassMod Found": 700,
        "Common Relic Found": 701,
        "Uncommon Relic Found": 702,
        "Rare Relic Found": 703,
        "VeryRare Relic Found": 704,
        "E-Tech Relic Found": 705,
        "Seraph Relic Found": 706,
        "Rainbow Relic Found": 707,
        "Unique Relic Found": 708,
        "Common Pistol Found": 709,
        "Uncommon Pistol Found": 710,
        "Rare Pistol Found": 711,
        "VeryRare Pistol Found": 712,
        "E-Tech Pistol Found": 713,
        "Legendary Pistol Found": 714,
        "Seraph Pistol Found": 715,
        "Pearlescent Pistol Found": 716,
        "Unique Pistol Found": 717,
        "Common Shotgun Found": 718,
        "Uncommon Shotgun Found": 719,
        "Rare Shotgun Found": 720,
        "VeryRare Shotgun Found": 721,
        "E-Tech Shotgun Found": 722,
        "Legendary Shotgun Found": 723,
        "Seraph Shotgun Found": 724,
        "Rainbow Shotgun Found": 725,
        "Pearlescent Shotgun Found": 726,
        "Unique Shotgun Found": 727,
        "Common SMG Found": 728,
        "Uncommon SMG Found": 729,
        "Rare SMG Found": 730,
        "VeryRare SMG Found": 731,
        "E-Tech SMG Found": 732,
        "Legendary SMG Found": 733,
        "Seraph SMG Found": 734,
        "Rainbow SMG Found": 735,
        "Pearlescent SMG Found": 736,
        "Unique SMG Found": 737,
        "Common SniperRifle Found": 738,
        "Uncommon SniperRifle Found": 739,
        "Rare SniperRifle Found": 740,
        "VeryRare SniperRifle Found": 741,
        "E-Tech SniperRifle Found": 742,
        "Legendary SniperRifle Found": 743,
        "Seraph SniperRifle Found": 744,
        "Rainbow SniperRifle Found": 745,
        "Pearlescent SniperRifle Found": 746,
        "Unique SniperRifle Found": 747,
        "Common AssaultRifle Found": 748,
        "Uncommon AssaultRifle Found": 749,
        "Rare AssaultRifle Found": 750,
        "VeryRare AssaultRifle Found": 751,
        "E-Tech AssaultRifle Found": 752,
        "Legendary AssaultRifle Found": 753,
        "Seraph AssaultRifle Found": 754,
        "Rainbow AssaultRifle Found": 755,
        "Pearlescent AssaultRifle Found": 756,
        "Unique AssaultRifle Found": 757,
        "Common RocketLauncher Found": 758,
        "Uncommon RocketLauncher Found": 759,
        "Rare RocketLauncher Found": 760,
        "VeryRare RocketLauncher Found": 761,
        "E-Tech RocketLauncher Found": 762,
        "Legendary RocketLauncher Found": 763,
        "Seraph RocketLauncher Found": 764,
        "Rainbow RocketLauncher Found": 765,
        "Pearlescent RocketLauncher Found": 766,
        "Unique RocketLauncher Found": 767,
        "Quest: Job Hunting": 768,
        "Quest: Claptrap Rescue": 769,
        "Quest: Fresh Off The Bus": 770,
        "Quest: The Doctor Is In": 771,
        "Quest: Find Steele": 772,
        "Quest: Another Piece Of The Puzzle": 773,
        "Quest: Jaynistown: Cleaning Up Your Mess": 774,
        "Quest: Get Some Answers": 775,
        "Quest: Talk to Tannis": 776,
        "Quest: Destroy The Destroyer": 777,
        "Quest: Bring The Vault Key To Tannis": 778,
        "Quest: Blinding Nine-Toes": 779,
        "Quest: Nine-Toes: Meet T.K. Baha": 780,
        "Quest: Sledge: To The Safe House": 781,
        "Quest: The Final Piece": 782,
        "Quest: Jaynistown: Unintended Consequences": 783,
        "Quest: Powering The Fast Travel Network": 784,
        "Quest: Ghosts Of The Vault": 785,
        "Quest: Big Game Hunter": 786,
        "Quest: Leaving Fyrestone": 787,
        "Quest: Road Warriors: Hot Shots": 788,
        "Quest: Road Warriors: Bandit Apocalypse": 789,
        "Quest: Power To The People": 790,
        "Quest: Fuel Feud": 791,
        "Quest: Death Race Pandora": 792,
        "Quest: Getting Lucky": 793,
        "Quest: Well There's Your Problem Right There": 794,
        "Quest: Scavenger: Revolver": 795,
        "Quest: Scavenger: Machine Gun": 796,
        "Quest: Not Without My Claptrap": 797,
        "Quest: Middle Of Nowhere No More: Small Favor": 798,
        "Quest: Skags At The Gate": 799,
        "Quest: Return To Zed": 800,
        "Quest: The Piss Wash Hurdle": 801,
        "Quest: Sledge: Meet Shep": 802,
        "Quest: Why Are They Here?": 803,
        "Quest: Get A Little Blood On The Tires": 804,
        "Quest: Bone Head's Theft": 805,
        "Quest: Nine-Toes: Time To Collect": 806,
        "Quest: Catch-A-Ride": 807,
        "Quest: Got Grenades?": 808,
        "Quest: Nine-Toes: T.K.'s Food": 809,
        "Quest: Nine-Toes: Take Him Down": 810,
        "Quest: Keep Your Insides Inside": 811,
        "Quest: Circle Of Death: Meat And Greet": 812,
        "Quest: Sledge: The Mine Key": 813,
        "Quest: Circle Of Death: Round 1": 814,
        "Quest: Circle Of Death: Round 2": 815,
        "Quest: Circle Of Death: Final Round": 816,
        "Quest: Claptrap Rescue: The Lost Cave": 817,
        "Quest: Claptrap Rescue: Safe House": 818,
        "Quest: Fix'er Upper": 819,
        "Quest: By The Seeds Of Your Pants": 820,
        "Quest: T.K. Has More Work": 821,
        "Quest: T.K.'s Life And Limb": 822,
        "Quest: Shock Crystal Harvest": 823,
        "Quest: Sledge: Battle For The Badlands": 824,
        "Quest: Is T.K. O.K.?": 825,
        "Quest: The Legend Of Moe and Marley": 826,
        "Quest: Like A Moth To Flame": 827,
        "Quest: Product Recall": 828,
        "Quest: Find Bruce McClane": 829,
        "Quest: What Hit The Fan": 830,
        "Quest: Get The Flock Outta Here": 831,
        "Quest: Hidden Journal: The Arid Badlands": 832,
        "Quest: Two Wrongs Make A Right": 833,
        "Quest: Missing Persons": 834,
        "Quest: Schemin' That Sabotage": 835,
        "Quest: Scavenger: Combat Rifle": 836,
        "Quest: Scavenger: Sniper Rifle": 837,
        "Quest: Insult To Injury": 838,
        "Quest: Braking Wind": 839,
        "Quest: A Bug Problem": 840,
        "Quest: The Next Piece": 841,
        "Quest: Altar Ego: Burning Heresy": 842,
        "Quest: Jack's Other Eye": 843,
        "Quest: Firepower: Market Correction": 844,
        "Quest: Bait And Switch": 845,
        "Quest: Bandit Treasure: Three Corpses, Three Keys": 846,
        "Quest: Bandit Treasure: X Marks The Spot": 847,
        "Quest: Get Off My Lawn!": 848,
        "Quest: Meet 'Crazy' Earl": 849,
        "Quest: Hair Of The Dog": 850,
        "Quest: Claptrap Rescue: Krom's Canyon": 851,
        "Quest: Claptrap Rescue: New Haven": 852,
        "Quest: Claptrap Rescue: Old Haven": 853,
        "Quest: Claptrap Rescue: Scrapyard": 854,
        "Quest: Claptrap Rescue: Tetanus Warren": 855,
        "Quest: Claptrap Rescue: Trash Coast": 856,
        "Quest: Today's Lesson: High Explosives": 857,
        "Quest: Earl's Best Friend": 858,
        "Quest: Seek Out Tannis": 859,
        "Quest: Firepower: All Sales Are Final": 860,
        "Quest: Firepower: Plight Of The Middle Man": 861,
        "Quest: Corrosive Crystal Harvest": 862,
        "Quest: Green Thumb": 863,
        "Quest: I've Got A Sinking Feeling...": 864,
        "Quest: Jaynistown: Getting What's Coming To You": 865,
        "Quest: Altar Ego: Godless Monsters": 866,
        "Quest: Altar Ego: The New Religion": 867,
        "Quest: Jaynistown: A Brother's Love": 868,
        "Quest: Jaynistown: Secret Rendezvous": 869,
        "Quest: Jaynistown: Spread The Word": 870,
        "Quest: King Tossing": 871,
        "Quest: Middle Of Nowhere No More: Fuses? Really?": 872,
        "Quest: Middle Of Nowhere No More: Investigate": 873,
        "Quest: Middle Of Nowhere No More: Scoot On Back": 874,
        "Quest: Dumpster Diving For Great Justice": 875,
        "Quest: Smoke Signals: Investigate Old Haven": 876,
        "Quest: Smoke Signals: Shut Them Down": 877,
        "Quest: Hidden Journal: Rust Commons West": 878,
        "Quest: Relight The Beacons": 879,
        "Quest: Scavenger: Submachine Gun": 880,
        "Quest: Scavenger: Shotgun": 881,
        "Quest: Scooter's Used Car Parts": 882,
        "Quest: Earl Needs Food...Badly": 883,
        "Quest: Circle Of Slaughter: Meat and Greet": 884,
        "Quest: Circle Of Slaughter: Round 1": 885,
        "Quest: Circle Of Slaughter: Round 2": 886,
        "Quest: Circle Of Slaughter: Final Round": 887,
        "Quest: House Hunting": 888,
        "Quest: Up To Our Ears": 889,
        "Quest: Wanted: Fresh Fish": 890,
        "Quest: Claptrap Rescue: Crimson Fastness": 891,
        "Quest: Claptrap Rescue: The Salt Flats": 892,
        "Quest: Find the ECHO Command Console": 893,
        "Quest: Reactivate the ECHO Comm System": 894,
        "Quest: Hidden Journal: Rust Commons East": 895,
        "Quest: Welcoming Committee": 896,
        "Quest: Is The Doctor In?": 897,
        "Quest: There May Be Some Side Effects...": 898,
        "Quest: House of the Ned": 899,
        "Quest: Secrets and Mysteries": 900,
        "Quest: Jakobs Fodder": 901,
        "Quest: Hitching A Ride": 902,
        "Quest: Night of the Living Ned": 903,
        "Quest: Ned's undead, baby, Ned's undead": 904,
        "Quest: Brains": 905,
        "Quest: Braaains": 906,
        "Quest: Braaaaains": 907,
        "Quest: Braaaaaaaaaaaains": 908,
        "Quest: Braaaaaaaaaaaaaaaaains": 909,
        "Quest: Leave It To The Professionals": 910,
        "Quest: Here We Go Again": 911,
        "Quest: Missing: Hank Reiss": 912,
        "Quest: Eggcellent Opportunity!": 913,
        "Quest: TK Lives!": 914,
        "Quest: It's Alive!": 915,
        "Quest: The Pack": 916,
        "Quest: Upsale": 917,
        "Quest: Pumpkinhead": 918,
        "Quest: Claptrap Rescue: The Lumber Yard": 919,
        "Quest: A Bridge Too Ned": 920,
        "Quest: Prove Yourself.": 921,
        "Quest: Scooter?  But I Don't Even Know Her.": 922,
        "Quest: Boost the Monster": 923,
        "Quest: Greasemonkey": 924,
        "Quest: You've Got Moxxi: Roadblock": 925,
        "Quest: You've Got Moxxi: Moxxi's Red Light": 926,
        "Quest: Prison Break: Road Warrior": 927,
        "Quest: Prison Break: Over the Wall": 928,
        "Quest: Prison Break: Try Not to Get Shanked": 929,
        "Quest: Rendezvous": 930,
        "Quest: Code Breaker: Analysis": 931,
        "Quest: Code Breaker: Time is Bullets": 932,
        "Quest: Athena Set Up Us The Bomb": 933,
        "Quest: Bridging the Gap": 934,
        "Quest: Armory Assault": 935,
        "Quest: Loot Larceny": 936,
        "Quest: Little People, Big Experiments": 937,
        "Quest: Claptrap Rescue: Lockdown Palace": 938,
        "Quest: OMG APC": 939,
        "Quest: Purple Juice!": 940,
        "Quest: Wanted: Dead!": 941,
        "Quest: Road Rage": 942,
        "Quest: Drifter Lifter": 943,
        "Quest: Thrown for a Loop": 944,
        "Quest: Knoxxed Out": 945,
        "Quest: Lost Lewts": 946,
        "Quest: Core Collection": 947,
        "Quest: Bugged": 948,
        "Quest: Stain Removal": 949,
        "Quest: This Bitch is Payback": 950,
        "Quest: This Bitch is Payback, pt. 2": 951,
        "Quest: Power Leech": 952,
        "Quest: You. Will. Die.": 953,
        "Quest: Mop Up": 954,
        "Quest: Local Trouble": 955,
        "Quest: Super-Marcus Sweep": 956,
        "Quest: It's Like Christmas!": 957,
        "Quest: Big Crimson Brother is Watching": 958,
        "Quest: Circle of Duty: New Recruit": 959,
        "Quest: Circle of Duty: Cadet": 960,
        "Quest: Circle of Duty: Private": 961,
        "Quest: Circle of Duty: Corporal": 962,
        "Quest: Circle of Duty: Sergeant": 963,
        "Quest: Circle of Duty: Medal of Duty": 964,
        "Quest: Not My Fault": 965,
        "Quest: Operation Trap Claptrap Trap, Phase Two: Industrial Revolution": 966,
        "Quest: Taking Stock": 967,
        "Quest: Are You From These Parts?": 968,
        "Quest: Burnin' Rubber": 969,
        "Quest: Fight For Your Right To Part-E": 970,
        "Quest: Parts Is Parts": 971,
        "Quest: We All Have Our Part To Play": 972,
        "Quest: A Part Of Something Larger Than Yourself": 973,
        "Quest: Eleven Rakk And Spices": 974,
        "Quest: Finger Lickin' Bad!": 975,
        "Quest: Operation Trap Claptrap Trap, Phase One": 976,
        "Quest: Operation Trap Claptrap Trap, Phase Three: TripWIRED": 977,
        "Quest: Old Spicy": 978,
        "Quest: Helping Is Its Own Reward... Wait No It Isn't!": 979,
        "Quest: New Contact": 980,
        "Quest: It's A Trap... Clap": 981,
        "Quest: Like Shootin' Rakk In A Barrel": 982,
        "Quest: Spa Vs. Spa": 983,
        "Quest: One-UpmanPipp": 984,
        "Quest: Operation Trap Claptrap Trap, Phase Four: Reboot": 985
    },
    "item": {
        "3 Skill Points": 1,
        "3 Skill Points (p)": 2,
        "Progressive Money Cap": 3,
        "Progressive Weapon Slot": 4,
        "$100": 5,
        "10 Eridium": 6,
        "Progressive Jump": 7,
        "Melee": 8,
        "Crouch": 9,
        "Progressive Sprint": 10,
        "Vehicle Fire": 11,
        "YellowCandy": 12,
        "RedCandy": 13,
        "GreenCandy": 14,
        "BlueCandy": 15,
        "RandomCandy": 16,
        "10% Exp": 17,
        "Travel: Arid Nexus Boneyard": 18,
        "Travel: The Holy Spirits": 19,
        "Travel: Southpaw Steam & Power": 20,
        "Travel: Sanctuary Hole": 21,
        "Travel: Hero's Pass": 22,
        "Travel: Bloodshot Stronghold": 23,
        "Travel: Three Horns Valley": 24,
        "Travel: Sanctuary": 25,
        "Travel: Thousand Cuts": 26,
        "Travel: End of the Line": 27,
        "Travel: Wildlife Exploitation Preserve": 28,
        "Travel: Terramorphous Peak": 29,
        "Travel: Tundra Express": 30,
        "Travel: The Fridge": 31,
        "Travel: Fink's Slaughterhouse": 32,
        "Travel: Southern Shelf Bay": 33,
        "Travel: Frostburn Canyon": 34,
        "Travel: Three Horns Divide": 35,
        "Travel: Highlands": 36,
        "Travel: Natural Selection Annex": 37,
        "Travel: The Dust": 38,
        "Travel: Friendship Gulag": 39,
        "Travel: Opportunity": 40,
        "Travel: Bloodshot Ramparts": 41,
        "Travel: Arid Nexus Badlands": 42,
        "Travel: Southern Shelf": 43,
        "Travel: Highlands Outwash": 44,
        "Travel: Caustic Caverns": 45,
        "Travel: Lynchwood": 46,
        "Travel: Sawtooth Cauldron": 47,
        "Travel: Ore Chasm": 48,
        "Travel: The Bunker": 49,
        "Travel: Control Core Angel": 50,
        "Travel: Vault of the Warrior": 51,
        "Travel: Eridium Blight": 52,
        "Travel: Gluttony Gulch": 53,
        "Travel: Marcus's Mercenary Shop": 54,
        "Travel: Helios Fallen": 55,
        "Travel: FFS Boss Fight": 56,
        "Travel: The Backburner": 57,
        "Travel: FFS Intro Sanctuary": 58,
        "Travel: Dahl Abandon": 59,
        "Travel: Mt. Scarab Research Center": 60,
        "Travel: The Burrows": 61,
        "Travel: Writhing Deep": 62,
        "Travel: The Forest": 63,
        "Travel: Immortal Woods": 64,
        "Travel: Dragon Keep": 65,
        "Travel: Unassuming Docks": 66,
        "Travel: Flamerock Refuge": 67,
        "Travel: Hatred's Shadow": 68,
        "Travel: Lair of Infinite Agony": 69,
        "Travel: Murderlin's Temple": 70,
        "Travel: Mines of Avarice": 71,
        "Travel: The Winged Storm": 72,
        "Travel: Hallowed Hollow": 73,
        "Travel: Torgue Arena": 74,
        "Travel: The Beatdown": 75,
        "Travel: The Forge": 76,
        "Travel: Badass Crater": 77,
        "Travel: Southern Raceway": 78,
        "Travel: Pyro Pete's Bar": 79,
        "Travel: Badass Crater Bar": 80,
        "Travel: Digistruct Peak": 81,
        "Travel: Wam Bam Island": 82,
        "Travel: Rotgut Distillery": 83,
        "Travel: The Leviathan's Lair": 84,
        "Travel: Washburne Refinery": 85,
        "Travel: Wurmwater": 86,
        "Travel: Magnys Lighthouse": 87,
        "Travel: The Rustyards": 88,
        "Travel: Hayter's Folly": 89,
        "Travel: Oasis": 90,
        "Travel: Ardorton Station": 91,
        "Travel: Hunter's Grotto": 92,
        "Travel: Candlerakk's Cragg": 93,
        "Travel: Terminus": 94,
        "Travel: Scylla's Grove": 95,
        "Progressive Travel: Base Game": 96,
        "Progressive Travel: Side Area": 97,
        "Progressive Travel: Fight For Sanctuary DLC": 98,
        "Progressive Travel: Tina DLC": 99,
        "Progressive Travel: Torgue DLC": 100,
        "Progressive Travel: Scarlett DLC": 101,
        "Progressive Travel: Hammerlock DLC": 102,
        "Progressive Travel: Headhunters": 103,
        "Trap Spawn: Saturn": 104,
        "Trap Spawn: Black Queen": 105,
        "Trap Spawn: Assassins": 106,
        "Trap Spawn: Dukino's Mom": 107,
        "Trap Spawn: Doc Mercy": 108,
        "Trap Spawn: Creepers": 109,
        "Override Level 15": 110,
        "Override Level 30": 111,
        "Max Ammo Pistol": 112,
        "Max Ammo Shotgun": 113,
        "Max Ammo SMG": 114,
        "Max Ammo SniperRifle": 115,
        "Max Ammo AssaultRifle": 116,
        "Max Ammo RocketLauncher": 117,
        "Max Grenade Count": 118,
        "Backpack Upgrade": 119,
        "Filler Gear: Gemstone Pistol": 120,
        "Filler Gear: Gemstone Shotgun": 121,
        "Filler Gear: Gemstone SMG": 122,
        "Filler Gear: Gemstone SniperRifle": 123,
        "Filler Gear: Gemstone AssaultRifle": 124,
        "Filler Gear: 1340 Shield": 125,
        "Filler Gear: Aequitas": 126,
        "Filler Gear: Antagonist": 127,
        "Filler Gear: Big Boom Blaster": 128,
        "Filler Gear: Black Hole": 129,
        "Filler Gear: Blockade": 130,
        "Filler Gear: Cracked Sash": 131,
        "Filler Gear: Deadly Bloom": 132,
        "Filler Gear: Easy Mode": 133,
        "Filler Gear: Evolution": 134,
        "Filler Gear: Fabled Tortoise": 135,
        "Filler Gear: Flame of the Firehawk": 136,
        "Filler Gear: Hide of Terramorphous": 137,
        "Filler Gear: Hoplite": 138,
        "Filler Gear: Impaler": 139,
        "Filler Gear: Love Thumper": 140,
        "Filler Gear: Manly Man Shield": 141,
        "Filler Gear: Neogenator": 142,
        "Filler Gear: Order": 143,
        "Filler Gear: Pot O' Gold": 144,
        "Filler Gear: Pun-chee": 145,
        "Filler Gear: Retainer": 146,
        "Filler Gear: Sponge": 147,
        "Filler Gear: The Bee": 148,
        "Filler Gear: The Cradle": 149,
        "Filler Gear: The Rough Rider": 150,
        "Filler Gear: The Sham": 151,
        "Filler Gear: The Transformer": 152,
        "Filler Gear: Whisky Tango Foxtrot": 153,
        "Filler Gear: Antifection": 154,
        "Filler Gear: Bonus Package": 155,
        "Filler Gear: Bouncing Bonny": 156,
        "Filler Gear: Breath of Terramorphous": 157,
        "Filler Gear: Chain Lightning": 158,
        "Filler Gear: Contraband Sky Rocket": 159,
        "Filler Gear: Crossfire": 160,
        "Filler Gear: Fastball": 161,
        "Filler Gear: Fire Bee": 162,
        "Filler Gear: Fire Storm": 163,
        "Filler Gear: Fireball": 164,
        "Filler Gear: Fuster Cluck": 165,
        "Filler Gear: Kiss of Death": 166,
        "Filler Gear: Leech": 167,
        "Filler Gear: Lightning Bolt": 168,
        "Filler Gear: Magic Missile": 169,
        "Filler Gear: Magic Missile (Purple)": 170,
        "Filler Gear: Meteor Shower": 171,
        "Filler Gear: Midnight Star": 172,
        "Filler Gear: Nasty Surprise": 173,
        "Filler Gear: O-Negative": 174,
        "Filler Gear: Pandemic": 175,
        "Filler Gear: Quasar": 176,
        "Filler Gear: Rolling Thunder": 177,
        "Filler Gear: Storm Front": 178,
        "Filler Gear: The Electric Chair": 179,
        "Filler Gear: Blood of Terramorphous": 180,
        "Filler Gear: Blood of the Ancients": 181,
        "Filler Gear: Blood of the Seraphs": 182,
        "Filler Gear: Bone of the Ancients": 183,
        "Filler Gear: Breath of the Seraphs": 184,
        "Filler Gear: Deputy's Badge": 185,
        "Filler Gear: Hard Carry": 186,
        "Filler Gear: Heart of the Ancients": 187,
        "Filler Gear: Lucrative Opportunity": 188,
        "Filler Gear: Might of the Seraphs": 189,
        "Filler Gear: Mouthwash": 190,
        "Filler Gear: Moxxi's Endowment": 191,
        "Filler Gear: Mysterious Amulet": 192,
        "Filler Gear: Otto Idol": 193,
        "Filler Gear: Shadow of the Seraphs": 194,
        "Filler Gear: Sheriff's Badge": 195,
        "Filler Gear: Skin of the Ancients": 196,
        "Filler Gear: The Afterburner": 197,
        "Filler Gear: Vault Hunter's Relic": 198,
        "Filler Gear: Winter is Over": 199,
        "Filler Gear: 12 Pounder": 200,
        "Filler Gear: Actualizer": 201,
        "Filler Gear: Ahab": 202,
        "Filler Gear: Ahab (ERROR)": 203,
        "Filler Gear: Amigo Sincero": 204,
        "Filler Gear: Avenger": 205,
        "Filler Gear: Baby Maker": 206,
        "Filler Gear: Bad Touch": 207,
        "Filler Gear: Badaboom": 208,
        "Filler Gear: Bane": 209,
        "Filler Gear: Bearcat": 210,
        "Filler Gear: Bekah": 211,
        "Filler Gear: Bitch": 212,
        "Filler Gear: Blockhead": 213,
        "Filler Gear: Bone Shredder": 214,
        "Filler Gear: Boom Puppy": 215,
        "Filler Gear: Buffalo": 216,
        "Filler Gear: Bunny": 217,
        "Filler Gear: Butcher": 218,
        "Filler Gear: CHOPPER": 219,
        "Filler Gear: Carnage": 220,
        "Filler Gear: Chulainn": 221,
        "Filler Gear: Ch\u00e8re-amie": 222,
        "Filler Gear: Cobra": 223,
        "Filler Gear: Commerce": 224,
        "Filler Gear: Conference Call": 225,
        "Filler Gear: Creamer": 226,
        "Filler Gear: Crit": 227,
        "Filler Gear: Dahlminator": 228,
        "Filler Gear: Damned Cowboy": 229,
        "Filler Gear: Deliverance": 230,
        "Filler Gear: Devastator": 231,
        "Filler Gear: Dog": 232,
        "Filler Gear: Elephant Gun": 233,
        "Filler Gear: Emperor": 234,
        "Filler Gear: Evil Smasher": 235,
        "Filler Gear: Fibber": 236,
        "Filler Gear: Flakker": 237,
        "Filler Gear: Florentine": 238,
        "Filler Gear: Fremington's Edge": 239,
        "Filler Gear: Godfinger": 240,
        "Filler Gear: Good Touch": 241,
        "Filler Gear: Greed": 242,
        "Filler Gear: Grog Nozzle": 243,
        "Filler Gear: Gub": 244,
        "Filler Gear: Gunerang": 245,
        "Filler Gear: Gwen's Head": 246,
        "Filler Gear: Hail": 247,
        "Filler Gear: Hammer Buster": 248,
        "Filler Gear: Hawk Eye": 249,
        "Filler Gear: Heart Breaker": 250,
        "Filler Gear: Hector's Paradise": 251,
        "Filler Gear: Hellfire": 252,
        "Filler Gear: Hive": 253,
        "Filler Gear: Hornet": 254,
        "Filler Gear: Hot Mama": 255,
        "Filler Gear: Hydra": 256,
        "Filler Gear: Infection": 257,
        "Filler Gear: Infection Cleaner": 258,
        "Filler Gear: Infinity": 259,
        "Filler Gear: Interfacer": 260,
        "Filler Gear: Invader": 261,
        "Filler Gear: Jolly Roger": 262,
        "Filler Gear: Judge": 263,
        "Filler Gear: KerBlaster": 264,
        "Filler Gear: Kitten": 265,
        "Filler Gear: Lady Fist": 266,
        "Filler Gear: Landscaper": 267,
        "Filler Gear: Lascaux": 268,
        "Filler Gear: Law": 269,
        "Filler Gear: Lead Storm": 270,
        "Filler Gear: Little Evie": 271,
        "Filler Gear: Logan's Gun": 272,
        "Filler Gear: Longbow": 273,
        "Filler Gear: Lyuda": 274,
        "Filler Gear: M2828 Thumpson": 275,
        "Filler Gear: Madhous!": 276,
        "Filler Gear: Maggie": 277,
        "Filler Gear: Mongol": 278,
        "Filler Gear: Morningstar": 279,
        "Filler Gear: Nirvana": 280,
        "Filler Gear: Norfleet": 281,
        "Filler Gear: Nukem": 282,
        "Filler Gear: Octo": 283,
        "Filler Gear: Ogre": 284,
        "Filler Gear: Omen": 285,
        "Filler Gear: Orc": 286,
        "Filler Gear: Orphan Maker": 287,
        "Filler Gear: Overcompensator": 288,
        "Filler Gear: Patriot": 289,
        "Filler Gear: Peak Opener": 290,
        "Filler Gear: Pimpernel": 291,
        "Filler Gear: Pitchfork": 292,
        "Filler Gear: Pocket Rocket": 293,
        "Filler Gear: Pyrophobia": 294,
        "Filler Gear: Rapier": 295,
        "Filler Gear: Retcher": 296,
        "Filler Gear: Rex": 297,
        "Filler Gear: Roaster": 298,
        "Filler Gear: RokSalt": 299,
        "Filler Gear: Rubi": 300,
        "Filler Gear: SWORDSPLOSION": 301,
        "Filler Gear: Sand Hawk": 302,
        "Filler Gear: Sawbar": 303,
        "Filler Gear: Scorpio": 304,
        "Filler Gear: Seeker": 305,
        "Filler Gear: Seraphim": 306,
        "Filler Gear: Shotgun 1340": 307,
        "Filler Gear: Shredifier": 308,
        "Filler Gear: Skullmasher": 309,
        "Filler Gear: Slagga": 310,
        "Filler Gear: Sledge's Shotgun": 311,
        "Filler Gear: Sloth": 312,
        "Filler Gear: Slow Hand": 313,
        "Filler Gear: Stalker": 314,
        "Filler Gear: Stinger": 315,
        "Filler Gear: Stinkpot": 316,
        "Filler Gear: Stomper": 317,
        "Filler Gear: Storm": 318,
        "Filler Gear: Striker": 319,
        "Filler Gear: Tattler": 320,
        "Filler Gear: Teapot": 321,
        "Filler Gear: Teeth of Terramorphous": 322,
        "Filler Gear: Thunderball Fists": 323,
        "Filler Gear: Tidal Wave": 324,
        "Filler Gear: Tinderbox": 325,
        "Filler Gear: Toothpick": 326,
        "Filler Gear: Trespasser": 327,
        "Filler Gear: Triquetra": 328,
        "Filler Gear: Tunguska": 329,
        "Filler Gear: Twister": 330,
        "Filler Gear: Unforgiven": 331,
        "Filler Gear: Unicornsplosion": 332,
        "Filler Gear: Unkempt Harold": 333,
        "Filler Gear: Veritas": 334,
        "Filler Gear: Veruc": 335,
        "Filler Gear: Volcano": 336,
        "Filler Gear: Wanderlust": 337,
        "Filler Gear: World Burn": 338,
        "Filler Gear: Yellow Jacket": 339,
        "License: Common Shield": 340,
        "License: Uncommon Shield": 341,
        "License: Rare Shield": 342,
        "License: VeryRare Shield": 343,
        "License: Legendary Shield": 344,
        "License: Seraph Shield": 345,
        "License: Rainbow Shield": 346,
        "License: Unique Shield": 347,
        "License: Common GrenadeMod": 348,
        "License: Uncommon GrenadeMod": 349,
        "License: Rare GrenadeMod": 350,
        "License: VeryRare GrenadeMod": 351,
        "License: Legendary GrenadeMod": 352,
        "License: Seraph GrenadeMod": 353,
        "License: Rainbow GrenadeMod": 354,
        "License: Unique GrenadeMod": 355,
        "License: Common ClassMod": 356,
        "License: Uncommon ClassMod": 357,
        "License: Rare ClassMod": 358,
        "License: VeryRare ClassMod": 359,
        "License: Legendary ClassMod": 360,
        "License: Common Relic": 361,
        "License: Uncommon Relic": 362,
        "License: Rare Relic": 363,
        "License: VeryRare Relic": 364,
        "License: E-Tech Relic": 365,
        "License: Seraph Relic": 366,
        "License: Rainbow Relic": 367,
        "License: Unique Relic": 368,
        "License: Common Pistol": 369,
        "License: Uncommon Pistol": 370,
        "License: Rare Pistol": 371,
        "License: VeryRare Pistol": 372,
        "License: E-Tech Pistol": 373,
        "License: Legendary Pistol": 374,
        "License: Seraph Pistol": 375,
        "License: Pearlescent Pistol": 376,
        "License: Unique Pistol": 377,
        "License: Common Shotgun": 378,
        "License: Uncommon Shotgun": 379,
        "License: Rare Shotgun": 380,
        "License: VeryRare Shotgun": 381,
        "License: E-Tech Shotgun": 382,
        "License: Legendary Shotgun": 383,
        "License: Seraph Shotgun": 384,
        "License: Rainbow Shotgun": 385,
        "License: Pearlescent Shotgun": 386,
        "License: Unique Shotgun": 387,
        "License: Common SMG": 388,
        "License: Uncommon SMG": 389,
        "License: Rare SMG": 390,
        "License: VeryRare SMG": 391,
        "License: E-Tech SMG": 392,
        "License: Legendary SMG": 393,
        "License: Seraph SMG": 394,
        "License: Rainbow SMG": 395,
        "License: Pearlescent SMG": 396,
        "License: Unique SMG": 397,
        "License: Common SniperRifle": 398,
        "License: Uncommon SniperRifle": 399,
        "License: Rare SniperRifle": 400,
        "License: VeryRare SniperRifle": 401,
        "License: E-Tech SniperRifle": 402,
        "License: Legendary SniperRifle": 403,
        "License: Seraph SniperRifle": 404,
        "License: Rainbow SniperRifle": 405,
        "License: Pearlescent SniperRifle": 406,
        "License: Unique SniperRifle": 407,
        "License: Common AssaultRifle": 408,
        "License: Uncommon AssaultRifle": 409,
        "License: Rare AssaultRifle": 410,
        "License: VeryRare AssaultRifle": 411,
        "License: E-Tech AssaultRifle": 412,
        "License: Legendary AssaultRifle": 413,
        "License: Seraph AssaultRifle": 414,
        "License: Rainbow AssaultRifle": 415,
        "License: Pearlescent AssaultRifle": 416,
        "License: Unique AssaultRifle": 417,
        "License: Common RocketLauncher": 418,
        "License: Uncommon RocketLauncher": 419,
        "License: Rare RocketLauncher": 420,
        "License: VeryRare RocketLauncher": 421,
        "License: E-Tech RocketLauncher": 422,
        "License: Legendary RocketLauncher": 423,
        "License: Seraph RocketLauncher": 424,
        "License: Rainbow RocketLauncher": 425,
        "License: Pearlescent RocketLauncher": 426,
        "License: Unique RocketLauncher": 427,
        "Reward: Job Hunting": 428,
        "Reward: Claptrap Rescue": 429,
        "Reward: Fresh Off The Bus": 430,
        "Reward: The Doctor Is In": 431,
        "Reward: Find Steele": 432,
        "Reward: Another Piece Of The Puzzle": 433,
        "Reward: Jaynistown: Cleaning Up Your Mess": 434,
        "Reward: Get Some Answers": 435,
        "Reward: Talk to Tannis": 436,
        "Reward: Destroy The Destroyer": 437,
        "Reward: Bring The Vault Key To Tannis": 438,
        "Reward: Blinding Nine-Toes": 439,
        "Reward: Nine-Toes: Meet T.K. Baha": 440,
        "Reward: Sledge: To The Safe House": 441,
        "Reward: The Final Piece": 442,
        "Reward: Jaynistown: Unintended Consequences": 443,
        "Reward: Powering The Fast Travel Network": 444,
        "Reward: Ghosts Of The Vault": 445,
        "Reward: Big Game Hunter": 446,
        "Reward: Leaving Fyrestone": 447,
        "Reward: Road Warriors: Hot Shots": 448,
        "Reward: Road Warriors: Bandit Apocalypse": 449,
        "Reward: Power To The People": 450,
        "Reward: Fuel Feud": 451,
        "Reward: Death Race Pandora": 452,
        "Reward: Getting Lucky": 453,
        "Reward: Well There's Your Problem Right There": 454,
        "Reward: Scavenger: Revolver": 455,
        "Reward: Scavenger: Machine Gun": 456,
        "Reward: Not Without My Claptrap": 457,
        "Reward: Middle Of Nowhere No More: Small Favor": 458,
        "Reward: Skags At The Gate": 459,
        "Reward: Return To Zed": 460,
        "Reward: The Piss Wash Hurdle": 461,
        "Reward: Sledge: Meet Shep": 462,
        "Reward: Why Are They Here?": 463,
        "Reward: Get A Little Blood On The Tires": 464,
        "Reward: Bone Head's Theft": 465,
        "Reward: Nine-Toes: Time To Collect": 466,
        "Reward: Catch-A-Ride": 467,
        "Reward: Got Grenades?": 468,
        "Reward: Nine-Toes: T.K.'s Food": 469,
        "Reward: Nine-Toes: Take Him Down": 470,
        "Reward: Keep Your Insides Inside": 471,
        "Reward: Circle Of Death: Meat And Greet": 472,
        "Reward: Sledge: The Mine Key": 473,
        "Reward: Circle Of Death: Round 1": 474,
        "Reward: Circle Of Death: Round 2": 475,
        "Reward: Circle Of Death: Final Round": 476,
        "Reward: Claptrap Rescue: The Lost Cave": 477,
        "Reward: Claptrap Rescue: Safe House": 478,
        "Reward: Fix'er Upper": 479,
        "Reward: By The Seeds Of Your Pants": 480,
        "Reward: T.K. Has More Work": 481,
        "Reward: T.K.'s Life And Limb": 482,
        "Reward: Shock Crystal Harvest": 483,
        "Reward: Sledge: Battle For The Badlands": 484,
        "Reward: Is T.K. O.K.?": 485,
        "Reward: The Legend Of Moe and Marley": 486,
        "Reward: Like A Moth To Flame": 487,
        "Reward: Product Recall": 488,
        "Reward: Find Bruce McClane": 489,
        "Reward: What Hit The Fan": 490,
        "Reward: Get The Flock Outta Here": 491,
        "Reward: Hidden Journal: The Arid Badlands": 492,
        "Reward: Two Wrongs Make A Right": 493,
        "Reward: Missing Persons": 494,
        "Reward: Schemin' That Sabotage": 495,
        "Reward: Scavenger: Combat Rifle": 496,
        "Reward: Scavenger: Sniper Rifle": 497,
        "Reward: Insult To Injury": 498,
        "Reward: Braking Wind": 499,
        "Reward: A Bug Problem": 500,
        "Reward: The Next Piece": 501,
        "Reward: Altar Ego: Burning Heresy": 502,
        "Reward: Jack's Other Eye": 503,
        "Reward: Firepower: Market Correction": 504,
        "Reward: Bait And Switch": 505,
        "Reward: Bandit Treasure: Three Corpses, Three Keys": 506,
        "Reward: Bandit Treasure: X Marks The Spot": 507,
        "Reward: Get Off My Lawn!": 508,
        "Reward: Meet 'Crazy' Earl": 509,
        "Reward: Hair Of The Dog": 510,
        "Reward: Claptrap Rescue: Krom's Canyon": 511,
        "Reward: Claptrap Rescue: New Haven": 512,
        "Reward: Claptrap Rescue: Old Haven": 513,
        "Reward: Claptrap Rescue: Scrapyard": 514,
        "Reward: Claptrap Rescue: Tetanus Warren": 515,
        "Reward: Claptrap Rescue: Trash Coast": 516,
        "Reward: Today's Lesson: High Explosives": 517,
        "Reward: Earl's Best Friend": 518,
        "Reward: Seek Out Tannis": 519,
        "Reward: Firepower: All Sales Are Final": 520,
        "Reward: Firepower: Plight Of The Middle Man": 521,
        "Reward: Corrosive Crystal Harvest": 522,
        "Reward: Green Thumb": 523,
        "Reward: I've Got A Sinking Feeling...": 524,
        "Reward: Jaynistown: Getting What's Coming To You": 525,
        "Reward: Altar Ego: Godless Monsters": 526,
        "Reward: Altar Ego: The New Religion": 527,
        "Reward: Jaynistown: A Brother's Love": 528,
        "Reward: Jaynistown: Secret Rendezvous": 529,
        "Reward: Jaynistown: Spread The Word": 530,
        "Reward: King Tossing": 531,
        "Reward: Middle Of Nowhere No More: Fuses? Really?": 532,
        "Reward: Middle Of Nowhere No More: Investigate": 533,
        "Reward: Middle Of Nowhere No More: Scoot On Back": 534,
        "Reward: Dumpster Diving For Great Justice": 535,
        "Reward: Smoke Signals: Investigate Old Haven": 536,
        "Reward: Smoke Signals: Shut Them Down": 537,
        "Reward: Hidden Journal: Rust Commons West": 538,
        "Reward: Relight The Beacons": 539,
        "Reward: Scavenger: Submachine Gun": 540,
        "Reward: Scavenger: Shotgun": 541,
        "Reward: Scooter's Used Car Parts": 542,
        "Reward: Earl Needs Food...Badly": 543,
        "Reward: Circle Of Slaughter: Meat and Greet": 544,
        "Reward: Circle Of Slaughter: Round 1": 545,
        "Reward: Circle Of Slaughter: Round 2": 546,
        "Reward: Circle Of Slaughter: Final Round": 547,
        "Reward: House Hunting": 548,
        "Reward: Up To Our Ears": 549,
        "Reward: Wanted: Fresh Fish": 550,
        "Reward: Claptrap Rescue: Crimson Fastness": 551,
        "Reward: Claptrap Rescue: The Salt Flats": 552,
        "Reward: Find the ECHO Command Console": 553,
        "Reward: Reactivate the ECHO Comm System": 554,
        "Reward: Hidden Journal: Rust Commons East": 555,
        "Reward: Welcoming Committee": 556,
        "Reward: Is The Doctor In?": 557,
        "Reward: There May Be Some Side Effects...": 558,
        "Reward: House of the Ned": 559,
        "Reward: Secrets and Mysteries": 560,
        "Reward: Jakobs Fodder": 561,
        "Reward: Hitching A Ride": 562,
        "Reward: Night of the Living Ned": 563,
        "Reward: Ned's undead, baby, Ned's undead": 564,
        "Reward: Brains": 565,
        "Reward: Braaains": 566,
        "Reward: Braaaaains": 567,
        "Reward: Braaaaaaaaaaaains": 568,
        "Reward: Braaaaaaaaaaaaaaaaains": 569,
        "Reward: Leave It To The Professionals": 570,
        "Reward: Here We Go Again": 571,
        "Reward: Missing: Hank Reiss": 572,
        "Reward: Eggcellent Opportunity!": 573,
        "Reward: TK Lives!": 574,
        "Reward: It's Alive!": 575,
        "Reward: The Pack": 576,
        "Reward: Upsale": 577,
        "Reward: Pumpkinhead": 578,
        "Reward: Claptrap Rescue: The Lumber Yard": 579,
        "Reward: A Bridge Too Ned": 580,
        "Reward: Prove Yourself.": 581,
        "Reward: Scooter?  But I Don't Even Know Her.": 582,
        "Reward: Boost the Monster": 583,
        "Reward: Greasemonkey": 584,
        "Reward: You've Got Moxxi: Roadblock": 585,
        "Reward: You've Got Moxxi: Moxxi's Red Light": 586,
        "Reward: Prison Break: Road Warrior": 587,
        "Reward: Prison Break: Over the Wall": 588,
        "Reward: Prison Break: Try Not to Get Shanked": 589,
        "Reward: Rendezvous": 590,
        "Reward: Code Breaker: Analysis": 591,
        "Reward: Code Breaker: Time is Bullets": 592,
        "Reward: Athena Set Up Us The Bomb": 593,
        "Reward: Bridging the Gap": 594,
        "Reward: Armory Assault": 595,
        "Reward: Loot Larceny": 596,
        "Reward: Little People, Big Experiments": 597,
        "Reward: Claptrap Rescue: Lockdown Palace": 598,
        "Reward: OMG APC": 599,
        "Reward: Purple Juice!": 600,
        "Reward: Wanted: Dead!": 601,
        "Reward: Road Rage": 602,
        "Reward: Drifter Lifter": 603,
        "Reward: Thrown for a Loop": 604,
        "Reward: Knoxxed Out": 605,
        "Reward: Lost Lewts": 606,
        "Reward: Core Collection": 607,
        "Reward: Bugged": 608,
        "Reward: Stain Removal": 609,
        "Reward: This Bitch is Payback": 610,
        "Reward: This Bitch is Payback, pt. 2": 611,
        "Reward: Power Leech": 612,
        "Reward: You. Will. Die.": 613,
        "Reward: Mop Up": 614,
        "Reward: Local Trouble": 615,
        "Reward: Super-Marcus Sweep": 616,
        "Reward: It's Like Christmas!": 617,
        "Reward: Big Crimson Brother is Watching": 618,
        "Reward: Circle of Duty: New Recruit": 619,
        "Reward: Circle of Duty: Cadet": 620,
        "Reward: Circle of Duty: Private": 621,
        "Reward: Circle of Duty: Corporal": 622,
        "Reward: Circle of Duty: Sergeant": 623,
        "Reward: Circle of Duty: Medal of Duty": 624,
        "Reward: Not My Fault": 625,
        "Reward: Operation Trap Claptrap Trap, Phase Two: Industrial Revolution": 626,
        "Reward: Taking Stock": 627,
        "Reward: Are You From These Parts?": 628,
        "Reward: Burnin' Rubber": 629,
        "Reward: Fight For Your Right To Part-E": 630,
        "Reward: Parts Is Parts": 631,
        "Reward: We All Have Our Part To Play": 632,
        "Reward: A Part Of Something Larger Than Yourself": 633,
        "Reward: Eleven Rakk And Spices": 634,
        "Reward: Finger Lickin' Bad!": 635,
        "Reward: Operation Trap Claptrap Trap, Phase One": 636,
        "Reward: Operation Trap Claptrap Trap, Phase Three: TripWIRED": 637,
        "Reward: Old Spicy": 638,
        "Reward: Helping Is Its Own Reward... Wait No It Isn't!": 639,
        "Reward: New Contact": 640,
        "Reward: It's A Trap... Clap": 641,
        "Reward: Like Shootin' Rakk In A Barrel": 642,
        "Reward: Spa Vs. Spa": 643,
        "Reward: One-UpmanPipp": 644,
        "Reward: Operation Trap Claptrap Trap, Phase Four: Reboot": 645,
        "Filler Gear: Common Shield": 646,
        "Filler Gear: Uncommon Shield": 647,
        "Filler Gear: Rare Shield": 648,
        "Filler Gear: VeryRare Shield": 649,
        "Filler Gear: Legendary Shield": 650,
        "Filler Gear: Seraph Shield": 651,
        "Filler Gear: Rainbow Shield": 652,
        "Filler Gear: Unique Shield": 653,
        "Filler Gear: Common GrenadeMod": 654,
        "Filler Gear: Uncommon GrenadeMod": 655,
        "Filler Gear: Rare GrenadeMod": 656,
        "Filler Gear: VeryRare GrenadeMod": 657,
        "Filler Gear: Legendary GrenadeMod": 658,
        "Filler Gear: Seraph GrenadeMod": 659,
        "Filler Gear: Rainbow GrenadeMod": 660,
        "Filler Gear: Unique GrenadeMod": 661,
        "Filler Gear: Common ClassMod": 662,
        "Filler Gear: Uncommon ClassMod": 663,
        "Filler Gear: Rare ClassMod": 664,
        "Filler Gear: VeryRare ClassMod": 665,
        "Filler Gear: Legendary ClassMod": 666,
        "Filler Gear: Common Relic": 667,
        "Filler Gear: Uncommon Relic": 668,
        "Filler Gear: Rare Relic": 669,
        "Filler Gear: VeryRare Relic": 670,
        "Filler Gear: E-Tech Relic": 671,
        "Filler Gear: Seraph Relic": 672,
        "Filler Gear: Rainbow Relic": 673,
        "Filler Gear: Unique Relic": 674,
        "Filler Gear: Common Pistol": 675,
        "Filler Gear: Uncommon Pistol": 676,
        "Filler Gear: Rare Pistol": 677,
        "Filler Gear: VeryRare Pistol": 678,
        "Filler Gear: E-Tech Pistol": 679,
        "Filler Gear: Legendary Pistol": 680,
        "Filler Gear: Seraph Pistol": 681,
        "Filler Gear: Pearlescent Pistol": 682,
        "Filler Gear: Unique Pistol": 683,
        "Filler Gear: Common Shotgun": 684,
        "Filler Gear: Uncommon Shotgun": 685,
        "Filler Gear: Rare Shotgun": 686,
        "Filler Gear: VeryRare Shotgun": 687,
        "Filler Gear: E-Tech Shotgun": 688,
        "Filler Gear: Legendary Shotgun": 689,
        "Filler Gear: Seraph Shotgun": 690,
        "Filler Gear: Rainbow Shotgun": 691,
        "Filler Gear: Pearlescent Shotgun": 692,
        "Filler Gear: Unique Shotgun": 693,
        "Filler Gear: Common SMG": 694,
        "Filler Gear: Uncommon SMG": 695,
        "Filler Gear: Rare SMG": 696,
        "Filler Gear: VeryRare SMG": 697,
        "Filler Gear: E-Tech SMG": 698,
        "Filler Gear: Legendary SMG": 699,
        "Filler Gear: Seraph SMG": 700,
        "Filler Gear: Rainbow SMG": 701,
        "Filler Gear: Pearlescent SMG": 702,
        "Filler Gear: Unique SMG": 703,
        "Filler Gear: Common SniperRifle": 704,
        "Filler Gear: Uncommon SniperRifle": 705,
        "Filler Gear: Rare SniperRifle": 706,
        "Filler Gear: VeryRare SniperRifle": 707,
        "Filler Gear: E-Tech SniperRifle": 708,
        "Filler Gear: Legendary SniperRifle": 709,
        "Filler Gear: Seraph SniperRifle": 710,
        "Filler Gear: Rainbow SniperRifle": 711,
        "Filler Gear: Pearlescent SniperRifle": 712,
        "Filler Gear: Unique SniperRifle": 713,
        "Filler Gear: Common AssaultRifle": 714,
        "Filler Gear: Uncommon AssaultRifle": 715,
        "Filler Gear: Rare AssaultRifle": 716,
        "Filler Gear: VeryRare AssaultRifle": 717,
        "Filler Gear: E-Tech AssaultRifle": 718,
        "Filler Gear: Legendary AssaultRifle": 719,
        "Filler Gear: Seraph AssaultRifle": 720,
        "Filler Gear: Rainbow AssaultRifle": 721,
        "Filler Gear: Pearlescent AssaultRifle": 722,
        "Filler Gear: Unique AssaultRifle": 723,
        "Filler Gear: Common RocketLauncher": 724,
        "Filler Gear: Uncommon RocketLauncher": 725,
        "Filler Gear: Rare RocketLauncher": 726,
        "Filler Gear: VeryRare RocketLauncher": 727,
        "Filler Gear: E-Tech RocketLauncher": 728,
        "Filler Gear: Legendary RocketLauncher": 729,
        "Filler Gear: Seraph RocketLauncher": 730,
        "Filler Gear: Rainbow RocketLauncher": 731,
        "Filler Gear: Pearlescent RocketLauncher": 732,
        "Filler Gear: Unique RocketLauncher": 733
    }
}