from BouncyLootGod.state import get_globals
from mods_base import get_pc

from unrealsdk import find_all, load_package,make_struct,find_object,find_class
from unrealsdk.hooks import Type, Block, prevent_hooking_direct_calls
from unrealsdk.unreal import UObject, WrappedStruct, BoundFunction
from mods_base import hook, get_pc, SliderOption, build_mod,BoolOption,ObjectFlags,command
from typing import Any


challenge_dict = {
    "gd_challenges.AchievementSpecific.12DaysOfPandora":                               "Challenge Elemental: 12 Days of Pandora",
    "gd_challenges.Enemies.Enemy_Human_1_HeadHunter":                                  "Challenge Humans: Headhunter",
    "gd_challenges.Enemies.Enemy_Human_2_NotReallyAPeoplePerson":                      "Challenge Humans: Not Really a People Person",
    "gd_challenges.Enemies.Enemy_Human_3_IHateHumans":                                 "Challenge Humans: Misanthrope",
    "gd_challenges.Enemies.Enemy_Human_4_WarCriminal":                                 "Challenge Humans: War Criminal",
    "gd_challenges.KillTotals.Critical_1_LuckyShot":                                   "Challenge Criticals: Lucky Shot!",
    "gd_challenges.KillTotals.Critical_2_CrackShot":                                   "Challenge Criticals: Crack Shot",
    "gd_challenges.KillTotals.Critical_3_DontYouEverMiss":                             "Challenge Criticals: Don't You Ever Miss?",
    "gd_challenges.KillTotals.Critical_4_BrainSurgeon":                                "Challenge Criticals: Brain Surgeon",
    "gd_challenges.KillTotals.KillChain_1_Relentless":                                 "Challenge Kill Chain: Relentless",
    "gd_challenges.KillTotals.KillChain_2_ChainKiller":                                "Challenge Kill Chain: Chain Killer",
    "gd_challenges.KillTotals.KillChain_3_KillingSpree":                               "Challenge Kill Chain: Killing Spree",
    "gd_challenges.KillTotals.KillChain_4_ConveyorOfDeath":                            "Challenge Kill Chain: Conveyor of Death",
    "gd_challenges.KillTotals.ActionKills_1_ActionHero":                               "Challenge Action Skill: Action Hero",
    "gd_challenges.KillTotals.ActionKills_2_BewareMadSkills":                          "Challenge Action Skill: Beware!  Mad Skills!",
    "gd_challenges.KillTotals.ActionKills_3_WhyDoYouEvenCarryAGun":                    "Challenge Action Skill: Why do you even carry a gun?",
    "gd_challenges.KillTotals.ActionKills_4_YourKungFuIsBest":                         "Challenge Action Skill: Your Kung Fu is Best",
    "gd_challenges.KillTotals.TotalKills_1_SeasonedKiller":                            "Challenge Total Kills: Seasoned Killer",
    "gd_challenges.KillTotals.TotalKills_2_NumbToTheVoices":                           "Challenge Total Kills: Numb to the Voices",
    "gd_challenges.KillTotals.TotalKills_3_TerrorOfPandora":                           "Challenge Total Kills: Terror of Pandora",
    "gd_challenges.KillTotals.TotalKills_4_IAmBecomeDeath":                            "Challenge Total Kills: I am become Death...",
    "gd_challenges.More.Currency_1_PocketChange":                                      "Challenge Economy: Pocket Change",
    "gd_challenges.More.Currency_2_MoneyItBuysHappiness":                              "Challenge Economy: Money.  It buys Happiness",
    "gd_challenges.More.Currency_3_TheRichGetRicher":                                  "Challenge Economy: The Rich get Richer",
    "gd_challenges.More.Currency_4_HowMuchForThatPlanet":                              "Challenge Economy: How Much For The Planet?",
    "gd_challenges.KillTotals.DuelWin_1_Duelist":                                      "Challenge Duels: Duelist",
    "gd_challenges.KillTotals.DuelWin_2_SmackDown":                                    "Challenge Duels: Smack Down!",
    "gd_challenges.KillTotals.DuelWin_3_BraggingRights":                               "Challenge Duels: Bragging Rights",
    "gd_challenges.KillTotals.DuelWin_4_Invincible":                                   "Challenge Duels: Invincible",
    "gd_challenges.Enemies.Enemy_Skag_1_SkagSlayer":                                   "Challenge Enemies: Skag Slayer",
    "gd_challenges.Enemies.Enemy_Skag_2_SitStayPlayDead":                              "Challenge Enemies: SIT! STAY! PLAY DEAD!",
    "gd_challenges.Enemies.Enemy_Skag_3_IHateDogs":                                    "Challenge Enemies: I hate dogs",
    "gd_challenges.Enemies.Enemy_Skag_4_YouAreTheSkagpocalypse":                       "Challenge Enemies: You Are The Skagpocalypse",
    "gd_challenges.Enemies.Enemy_Spiderant_1_SpiderantSlayer":                         "Challenge Enemies: Spiderant Slayer",
    "gd_challenges.Enemies.Enemy_Spiderant_2_BugCrusher":                              "Challenge Enemies: Bug Crusher",
    "gd_challenges.Enemies.Enemy_Spiderant_3_IHateBugs":                               "Challenge Enemies: I hate bugs",
    "gd_challenges.Enemies.Enemy_Spiderant_4_TheExterminator":                         "Challenge Enemies: The Exterminator",
    "gd_challenges.Enemies.Enemy_Rakk_1_RakkSlayer":                                   "Challenge Enemies: Rakk Slayer",
    "gd_challenges.Enemies.Enemy_Rakk_2_IfItFliesItDies":                              "Challenge Enemies: If it flies, it dies",
    "gd_challenges.Enemies.Enemy_Rakk_3_RakkFlak":                                     "Challenge Enemies: Rakk Flak",
    "gd_challenges.Enemies.Enemy_Rakk_4_IfICantFlyNooneFlies":                         "Challenge Enemies: If I can't fly, no one flies",
    "gd_challenges.Enemies.Enemy_Guardian_1_WhatIsThatThing":                          "Challenge Enemies: What is that thing?",
    "gd_challenges.Enemies.Enemy_Guardian_2_TheVaultIsMine":                           "Challenge Enemies: The Vault is mine",
    "gd_challenges.Enemies.Enemy_Guardian_3_Xenophobe":                                "Challenge Enemies: Xenophobe",
    "gd_challenges.Enemies.Enemy_Guardian_4_DominantSpecies":                          "Challenge Enemies: Dominant species",
    "gd_challenges.Weapons.RifleKills_1_SprayAndPrey":                                 "Challenge Rifle: Spray and Prey",
    "gd_challenges.Weapons.RifleKills_2_SizeMatters":                                  "Challenge Rifle: Size matters",
    "gd_challenges.Weapons.RifleKills_3_MakeChunks":                                   "Challenge Rifle: Make Chunks",
    "gd_challenges.Weapons.RifleKills_4_OneManArmy":                                   "Challenge Rifle: One Man Army",
    "gd_challenges.Weapons.PistolKills_1_Draw":                                        "Challenge Pistol: Draw!",
    "gd_challenges.Weapons.PistolKills_2_SizeDoesntMatter":                            "Challenge Pistol: Size doesn't matter",
    "gd_challenges.Weapons.PistolKills_3_NoOnesLaughingNow":                           "Challenge Pistol: No one's laughing now",
    "gd_challenges.Weapons.PistolKills_4_Pistolero":                                   "Challenge Pistol: Pistolero",
    "gd_challenges.Weapons.ShotgunKills_1_GetOffMyLawn":                               "Challenge Shotgun: Get off my lawn!",
    "gd_challenges.Weapons.ShotgunKills_2_TasteTheRedMist":                            "Challenge Shotgun: Taste the red mist",
    "gd_challenges.Weapons.ShotgunKills_3_InstantAutopsy":                             "Challenge Shotgun: Instant Autopsy",
    "gd_challenges.Weapons.ShotgunKills_4_BuckshotLegend":                             "Challenge Shotgun: Buckshot Legend",
    "gd_challenges.Weapons.LauncherKills_1_Boom":                                      "Challenge Launcher: Boom",
    "gd_challenges.Weapons.LauncherKills_2_BOOM":                                      "Challenge Launcher: BOOM",
    "gd_challenges.Weapons.LauncherKills_3_KaBOOM":                                    "Challenge Launcher: KaBOOM!",
    "gd_challenges.Weapons.LauncherKills_4_KABOOOOOOOM":                               "Challenge Launcher: KA BOOOOOOOM!!!!",
    "gd_challenges.Weapons.SMGKills_1_RatATat":                                        "Challenge SMG: Rat a Tat!",
    "gd_challenges.Weapons.SMGKills_2_SoManyLittleHoles":                              "Challenge SMG: So many little holes...",
    "gd_challenges.Weapons.SMGKills_3_BulletHose":                                     "Challenge SMG: Bullet Hose",
    "gd_challenges.Weapons.SMGKills_4_HumanTsunami":                                   "Challenge SMG: Human Tsunami",
    "gd_challenges.Weapons.SniperKills_1_OneShotOneKill":                              "Challenge Sniper: One Shot, One Kill",
    "gd_challenges.Weapons.SniperKills_2_IllWaitBackHere":                             "Challenge Sniper: I'll wait back here...",
    "gd_challenges.Weapons.SniperKills_3_BrainVentilator":                             "Challenge Sniper: Brain Ventilator",
    "gd_challenges.Weapons.SniperKills_4_FingerOfGod":                                 "Challenge Sniper: Finger of God",
    "gd_challenges.Weapons.MeleeKills_1_Punchy":                                       "Challenge Melee: Punchy",
    "gd_challenges.Weapons.MeleeKills_2_Brawler":                                      "Challenge Melee: Brawler",
    "gd_challenges.Weapons.MeleeKills_3_Boxer":                                        "Challenge Melee: Boxer",
    "gd_challenges.Weapons.MeleeKills_4_HeavyweightChampion":                          "Challenge Melee: Heavyweight Champion",
    "gd_challenges.KillTotals.FireKills_1_HotTooHot":                                  "Challenge Fire: Hot! Too Hot!",
    "gd_challenges.KillTotals.FireKills_2_Toasty":                                     "Challenge Fire: Toasty!",
    "gd_challenges.KillTotals.FireKills_3_PlaysWithMatches":                           "Challenge Fire: Plays with matches",
    "gd_challenges.KillTotals.FireKills_4_Pyromaniac":                                 "Challenge Fire: Pyromaniac",
    "gd_challenges.KillTotals.ShockKills_1_Zap":                                       "Challenge Shock: Zap!",
    "gd_challenges.KillTotals.ShockKills_2_NikolaIsAFriendOfMine":                     "Challenge Shock: Nikola is a friend of mine",
    "gd_challenges.KillTotals.ShockKills_3_PutsForksInSockets":                        "Challenge Shock: Puts forks in sockets",
    "gd_challenges.KillTotals.ShockKills_4_Shocker":                                   "Challenge Shock: Shocker",
    "gd_challenges.KillTotals.CorrosiveKills_1_ChemistryRocks":                        "Challenge Corrosive: Chemistry Rocks!",
    "gd_challenges.KillTotals.CorrosiveKills_2_WhyIsTheFloorAllGooey":                 "Challenge Corrosive: Why is the floor all gooey?",
    "gd_challenges.KillTotals.CorrosiveKills_3_MixesHouseholdChemicals":               "Challenge Corrosive: Mixes household chemicals",
    "gd_challenges.KillTotals.CorrosiveKills_4_Chemist":                               "Challenge Corrosive: Chemist",
    "gd_challenges.KillTotals.ExplosiveKills_1_BoomGoesTheDynamite":                   "Challenge Explosive: Boom goes the Dynamite!",
    "gd_challenges.KillTotals.ExplosiveKills_2_TooBadAboutTheTinnitus":                "Challenge Explosive: Too bad about the Tinnitus",
    "gd_challenges.KillTotals.ExplosiveKills_3_CrossesBorderForFireworks":             "Challenge Explosive: Crosses border for fireworks",
    "gd_challenges.KillTotals.ExplosiveKills_4_Demolitionist":                         "Challenge Explosive: Demolitionist",
    "gd_challenges.Weapons.VehicleKills_1_RoadRage":                                   "Challenge Vehicle: Road Rage",
    "gd_challenges.Weapons.VehicleKills_2_VehicularManslaughter":                      "Challenge Vehicle: Vehicular Manslaughter",
    "gd_challenges.Weapons.VehicleKills_3_SchoolBusDriver":                            "Challenge Vehicle: School bus Driver",
    "gd_challenges.Weapons.VehicleKills_4_HellOnWheels":                               "Challenge Vehicle: Hell on Wheels",
    "gd_challenges.More.LootableOpened_1_WhatsInHere":                                 "Challenge Loot: What's in here?",
    "gd_challenges.More.LootableOpened_2_Scavenger":                                   "Challenge Loot: Scavenger",
    "gd_challenges.More.LootableOpened_3_WildernessSurvivor":                          "Challenge Loot: Wilderness Survivor",
    "gd_challenges.More.LootableOpened_4_NoStoneUnturned":                             "Challenge Loot: No stone unturned",
    "gd_challenges.More.ChestOpened_1_OooShiney":                                      "Challenge Loot: Ooo! Shiney!",
    "gd_challenges.More.ChestOpened_2_TreasureHunter":                                 "Challenge Loot: Treasure Hunter",
    "gd_challenges.More.ChestOpened_3_SwagMaster":                                     "Challenge Loot: Swag Master",
    "gd_challenges.More.ChestOpened_4_EnvyOfPirates":                                  "Challenge Loot: Envy of Pirates",
    "gd_challenges.More.ItemsSold_1_HowMuchForTheGun":                                 "Challenge Economy: How much for the gun?",
    "gd_challenges.More.ItemsSold_2_GunRunner":                                        "Challenge Economy: Gun runner",
    "gd_challenges.More.ItemsSold_3_ArmsDealer":                                       "Challenge Economy: Arms dealer",
    "gd_challenges.More.ItemsSold_4_MerchantOfDeath":                                  "Challenge Economy: Merchant of Death",
    "gd_challenges.More.ItemsBought_1_ImpulseBuyer":                                   "Challenge Economy: Impulse buyer",
    "gd_challenges.More.ItemsBought_2_GoodConsumer":                                   "Challenge Economy: Good Consumer",
    "gd_challenges.More.ItemsBought_3_IWantItAll":                                     "Challenge Economy: I want it all!",
    "gd_challenges.More.ItemsBought_4_SelfContainedEconomy":                           "Challenge Economy: Self contained economy",
    "gd_challenges.More.ShotsFired_1_LotsOfShots":                                     "Challenge Shots Fired: Lots of shots",
    "gd_challenges.More.ShotsFired_2_KeepFiring":                                      "Challenge Shots Fired: Keep firing",
    "gd_challenges.More.ShotsFired_3_WhoMadeThatManAGunner":                           "Challenge Shots Fired: Who made that man a gunner?",
    "gd_challenges.More.ShotsFired_4_IFiredEveryBulletEver":                           "Challenge Shots Fired: I fired every bullet ever",
    "gd_challenges.More.VehicleHang_1_HangTime":                                       "Challenge Vehicle: Hang Time",
    "gd_challenges.More.VehicleHang_2_Airborne":                                       "Challenge Vehicle: Airborne",
    "gd_challenges.More.VehicleHang_3_ThisIsNotAFlightSimulator":                      "Challenge Vehicle: This is not a flight simulator",
    "gd_challenges.More.VehicleHang_4_OrbitAchieved":                                  "Challenge Vehicle: Orbit Achieved",
}

def reveal_annoying_challenges():
    pass
