mission_name_to_ue_str = {
    "Job Hunting":                                                            "Z0_Missions.Missions.M_BountyBoard",
    "Claptrap Rescue":                                                        "Z0_Missions.Missions.M_RepairClapTrap_02",
    "Fresh Off The Bus":                                                      "Z0_Missions.Missions.M_IntroStateSaver",
    "The Doctor Is In":                                                       "Z0_Missions.Missions.M_AccessStores",
    "Find Steele":                                                            "Z2_Missions.Missions.M_FindSteele",
    "Another Piece Of The Puzzle":                                            "Z1_Missions.Missions.M_AnotherLittleSuprise",
    "Jaynistown: Cleaning Up Your Mess":                                      "Z1_Missions.Missions.M_JaynisCleaningUp",
    "Get Some Answers":                                                       "Z2_Missions.Missions.M_unknown",
    "Talk to Tannis":                                                         "Z2_Missions.Missions.M_SpeakToTannis",
    "Destroy The Destroyer":                                                  "Z2_Missions.Missions.M_FindTheVault",
    "Bring The Vault Key To Tannis":                                          "Z2_Missions.Missions.M_ReturnKey",
    "Blinding Nine-Toes":                                                     "Z0_Missions.Missions.M_KillBandits",
    "Nine-Toes: Meet T.K. Baha":                                              "Z0_Missions.Missions.M_MeetAl",
    "Sledge: To The Safe House":                                              "Z0_Missions.Missions.M_KillSledge1",
    "The Final Piece":                                                        "Z1_Missions.Missions.M_FinalArtifact",
    "Jaynistown: Unintended Consequences":                                    "Z1_Missions.Missions.M_JaynisUnintendedConseq",
    "Powering The Fast Travel Network":                                       "I1_Missions.Missions.M_Powerlines",
    "Ghosts Of The Vault":                                                    "I1_Missions.Missions.M_AbandonedDig",
    "Big Game Hunter":                                                        "I1_Missions.Missions.M_Assassinate_SkagZilla",
    "Leaving Fyrestone":                                                      "Z0_Missions.Missions.M_TravelToNH",
    "Road Warriors: Hot Shots":                                               "I1_Missions.Missions.M_BanditConvoy01",
    "Road Warriors: Bandit Apocalypse":                                       "I1_Missions.Missions.M_BanditConvoy03",
    "Power To The People":                                                    "Z1_Missions.Missions.M_NewHavenGenerators",
    "Fuel Feud":                                                              "I1_Missions.Missions.M_FuelSupply",
    "Death Race Pandora":                                                     "I1_Missions.Missions.M_OpeningTheRaceTrack",
    "Getting Lucky":                                                          "I1_Missions.Missions.M_RoadBlocks",
    "Well There's Your Problem Right There":                                  "I1_Missions.Missions.M_RepairGasPipes",
    "Scavenger: Revolver":                                                    "I1_Missions.Missions.M_Scavenger3",
    "Scavenger: Machine Gun":                                                 "I2_Missions.Missions.M_Scavenger6",
    "Not Without My Claptrap":                                                "Z1_Missions.Missions.M_ReachTheSaltFlats",
    "Middle Of Nowhere No More: Small Favor":                                 "Z1_Missions.Missions.M_Miscommunication_SmallFavor",
    "Skags At The Gate":                                                      "Z0_Missions.Missions.M_KillSkags_Zed",
    "Return To Zed":                                                          "Z0_Missions.Missions.M_BackToZed",
    "The Piss Wash Hurdle":                                                   "Z0_Missions.Missions.M_JumpTheGap",
    "Sledge: Meet Shep":                                                      "Z0_Missions.Missions.M_MeetShep",
    "Why Are They Here?":                                                     "Z0_Missions.Missions.M_BanditPresence1",
    "Get A Little Blood On The Tires":                                        "Z0_Missions.Missions.M_BloodOnTheTires",
    "Bone Head's Theft":                                                      "Z0_Missions.Missions.M_FixVSS",
    "Nine-Toes: Time To Collect":                                             "Z0_Missions.Missions.M_NineToesGetReward",
    "Catch-A-Ride":                                                           "Z0_Missions.Missions.M_InvestigateVSS",
    "Got Grenades?":                                                          "Z0_Missions.Missions.M_BuyGrenades",
    "Nine-Toes: T.K.'s Food":                                                 "Z0_Missions.Missions.M_ExterminateSkag",
    "Nine-Toes: Take Him Down":                                               "Z0_Missions.Missions.M_OpenGatetoSkag",
    "Keep Your Insides Inside":                                               "Z0_Missions.Missions.M_BuyShield",
    "Circle Of Death: Meat And Greet":                                        "Z0_Missions.Missions.M_CircleMeatAndGreet",
    "Sledge: The Mine Key":                                                   "Z0_Missions.Missions.M_SubstationKey",
    "Circle Of Death: Round 1":                                               "Z0_Missions.Missions.M_CircleOfDeath01",
    "Circle Of Death: Round 2":                                               "Z0_Missions.Missions.M_CircleOfDeath02",
    "Circle Of Death: Final Round":                                           "Z0_Missions.Missions.M_CircleOfDeath03",
    "Claptrap Rescue: The Lost Cave":                                         "Z0_Missions.Missions.M_ClaptrapRescueLostCave",
    "Claptrap Rescue: Safe House":                                            "Z0_Missions.Missions.M_ClaptrapRescueSafehouse",
    "Fix'er Upper":                                                           "Z0_Missions.Missions.M_FixHealthVending",
    "By The Seeds Of Your Pants":                                             "Z0_Missions.Missions.M_GatherSeeds",
    "T.K. Has More Work":                                                     "Z0_Missions.Missions.M_TKHasMoreWork",
    "T.K.'s Life And Limb":                                                   "Z0_Missions.Missions.M_GetMyLegBack",
    "Shock Crystal Harvest":                                                  "Z0_Missions.Missions.M_HarvestCrystals_Electrical",
    "Sledge: Battle For The Badlands":                                        "Z0_Missions.Missions.M_KillSledge2",
    "Is T.K. O.K.?":                                                          "Z0_Missions.Missions.M_MissingTools",
    "The Legend Of Moe and Marley":                                           "Z0_Missions.Missions.M_MoeMarley",
    "Like A Moth To Flame":                                                   "Z0_Missions.Missions.M_Mothrak",
    "Product Recall":                                                         "Z0_Missions.Missions.M_OwedMoneyDebt",
    "Find Bruce McClane":                                                     "Z0_Missions.Missions.M_OwedMoneyInvestigate",
    "What Hit The Fan":                                                       "Z0_Missions.Missions.M_RakkDebris",
    "Get The Flock Outta Here":                                               "Z0_Missions.Missions.M_RakkMenace",
    "Hidden Journal: The Arid Badlands":                                      "Z0_Missions.Missions.M_RecoverLostData_1",
    "Two Wrongs Make A Right":                                                "Z0_Missions.Missions.M_RefugeeTwoWrongs",
    "Missing Persons":                                                        "Z1_Missions.Missions.M_RefugeeMissingPersons",
    "Schemin' That Sabotage":                                                 "Z0_Missions.Missions.M_Saboteur",
    "Scavenger: Combat Rifle":                                                "Z0_Missions.Missions.M_Scavenger1",
    "Scavenger: Sniper Rifle":                                                "Z0_Missions.Missions.M_Scavenger2",
    "Insult To Injury":                                                       "Z0_Missions.Missions.M_TheSkulls",
    "Braking Wind":                                                           "Z0_Missions.Missions.M_WindTurbine_Activate",
    "A Bug Problem":                                                          "Z1_Missions.Missions.M_ABugProblem",
    "The Next Piece":                                                         "Z1_Missions.Missions.M_ThirdFragment",
    "Altar Ego: Burning Heresy":                                              "Z1_Missions.Missions.M_AltarEgo",
    "Jack's Other Eye":                                                       "Z1_Missions.Missions.M_AssassinateJack",
    "Firepower: Market Correction":                                           "Z1_Missions.Missions.M_FirepowerMunitions",
    "Bait And Switch":                                                        "Z1_Missions.Missions.M_BaitResearch",
    "Bandit Treasure: Three Corpses, Three Keys":                             "Z1_Missions.Missions.M_BanditTreasureThree",
    "Bandit Treasure: X Marks The Spot":                                      "Z1_Missions.Missions.M_BanditTreasureXMarks",
    "Get Off My Lawn!":                                                       "Z1_Missions.Missions.M_BridgesDamnTrespassers",
    "Meet 'Crazy' Earl":                                                      "Z1_Missions.Missions.M_FindEarl",
    "Hair Of The Dog":                                                        "Z1_Missions.Missions.M_BridgesGetABeer",
    "Claptrap Rescue: Krom's Canyon":                                         "Z1_Missions.Missions.M_ClaptrapRescueCanyon",
    "Claptrap Rescue: New Haven":                                             "Z1_Missions.Missions.M_ClaptrapRescueNewHaven",
    "Claptrap Rescue: Old Haven":                                             "Z1_Missions.Missions.M_ClaptrapRescueOldHaven",
    "Claptrap Rescue: Scrapyard":                                             "Z1_Missions.Missions.M_ClaptrapRescueScrapyard",
    "Claptrap Rescue: Tetanus Warren":                                        "Z1_Missions.Missions.M_ClaptrapRescueTrashCave",
    "Claptrap Rescue: Trash Coast":                                           "Z1_Missions.Missions.M_ClaptrapRescueTrashCoast",
    "Today's Lesson: High Explosives":                                        "Z1_Missions.Missions.M_EarlBanditOutpostDestroyed",
    "Earl's Best Friend":                                                     "Z1_Missions.Missions.M_EarlsBestFriend",
    "Seek Out Tannis":                                                        "Z1_Missions.Missions.M_SeekTannis",
    "Firepower: All Sales Are Final":                                         "Z1_Missions.Missions.M_FirepowerPlans",
    "Firepower: Plight Of The Middle Man":                                    "Z1_Missions.Missions.M_FirepowerWeapons",
    "Corrosive Crystal Harvest":                                              "Z1_Missions.Missions.M_GreenCrystalHarvest",
    "Green Thumb":                                                            "Z1_Missions.Missions.M_GreenThumb",
    "I've Got A Sinking Feeling...":                                          "Z1_Missions.Missions.M_GunboatSabotage",
    "Jaynistown: Getting What's Coming To You":                               "Z1_Missions.Missions.M_JaynisGettingWhatsComing",
    "Altar Ego: Godless Monsters":                                            "Z1_Missions.Missions.M_HeathensGodlessMonsters",
    "Altar Ego: The New Religion":                                            "Z1_Missions.Missions.M_HeathensInvestigate",
    "Jaynistown: A Brother's Love":                                           "Z1_Missions.Missions.M_JaynisBrotherLove",
    "Jaynistown: Secret Rendezvous":                                          "Z1_Missions.Missions.M_JaynisSecretRendezvous",
    "Jaynistown: Spread The Word":                                            "Z1_Missions.Missions.M_JaynisSpreadTheWord",
    "King Tossing":                                                           "Z1_Missions.Missions.M_KingWeeWee",
    "Middle Of Nowhere No More: Fuses? Really?":                              "Z1_Missions.Missions.M_Miscommunication_FindParts",
    "Middle Of Nowhere No More: Investigate":                                 "Z1_Missions.Missions.M_Miscommunication_Investigate",
    "Middle Of Nowhere No More: Scoot On Back":                               "Z1_Missions.Missions.M_Miscommunication_ReturnToHelena",
    "Dumpster Diving For Great Justice":                                      "Z1_Missions.Missions.M_NewHavenDefenses",
    "Smoke Signals: Investigate Old Haven":                                   "Z1_Missions.Missions.M_OldHaven_Investigate",
    "Smoke Signals: Shut Them Down":                                          "Z1_Missions.Missions.M_OldHaven_Smoked",
    "Hidden Journal: Rust Commons West":                                      "Z1_Missions.Missions.M_RecoverLostData_2",
    "Relight The Beacons":                                                    "Z1_Missions.Missions.M_RelightTheBeacons",
    "Scavenger: Submachine Gun":                                              "Z1_Missions.Missions.M_Scavenger4",
    "Scavenger: Shotgun":                                                     "Z1_Missions.Missions.M_Scavenger5",
    "Scooter's Used Car Parts":                                               "Z1_Missions.Missions.M_ScootersUsedCarParts",
    "Earl Needs Food...Badly":                                                "Z1_Missions.Missions.M_SkrappyNeedsFood",
    "Circle Of Slaughter: Meat and Greet":                                    "Z1_Missions.Missions.M_SlaughterMeatAndGreet",
    "Circle Of Slaughter: Round 1":                                           "Z1_Missions.Missions.M_SlaughterWave1",
    "Circle Of Slaughter: Round 2":                                           "Z1_Missions.Missions.M_SlaughterWave2",
    "Circle Of Slaughter: Final Round":                                       "Z1_Missions.Missions.M_SlaughterWave3",
    "House Hunting":                                                          "Z1_Missions.Missions.M_SquatterHouseHunting",
    "Up To Our Ears":                                                         "Z1_Missions.Missions.M_TurnOnTheStank",
    "Wanted: Fresh Fish":                                                     "Z1_Missions.Missions.M_WantedFreshFish",
    "Claptrap Rescue: Crimson Fastness":                                      "Z2_Missions.Missions.M_ClaptrapRescueLanceBunker",
    "Claptrap Rescue: The Salt Flats":                                        "Z2_Missions.Missions.M_ClaptrapRescueSanctuary",
    "Find the ECHO Command Console":                                          "Z2_Missions.Missions.M_FindEcho",
    "Reactivate the ECHO Comm System":                                        "Z2_Missions.Missions.M_ReactivateEcho",
    "Hidden Journal: Rust Commons East":                                      "Z2_Missions.Missions.M_RecoverLostData_3",
    "Welcoming Committee":                                                    "dlc1_missions.MainMissions.M_dlc1_DefendTown",
    "Is The Doctor In?":                                                      "dlc1_missions.MainMissions.M_dlc1_NedsNote",
    "There May Be Some Side Effects...":                                      "dlc1_missions.MainMissions.M_dlc1_Wereskag",
    "House of the Ned":                                                       "dlc1_missions.MainMissions.M_dlc1_MeetNed",
    "Secrets and Mysteries":                                                  "dlc1_missions.MainMissions.M_dlc1_NedLab",
    "Jakobs Fodder":                                                          "dlc1_missions.MainMissions.M_dlc1_TellJakobs",
    "Hitching A Ride":                                                        "dlc1_missions.MainMissions.M_dlc1_ReturnToIsland",
    "Night of the Living Ned":                                                "dlc1_missions.MainMissions.M_dlc1_KillNed",
    "Ned's undead, baby, Ned's undead":                                       "dlc1_missions.MainMissions.M_dlc1_KillZombieNed",
    "Brains":                                                                 "dlc1_missions.SideMissions.M_dlc1_TKBrains1",
    "Braaains":                                                               "dlc1_missions.SideMissions.M_dlc1_TKBrains2",
    "Braaaaains":                                                             "dlc1_missions.SideMissions.M_dlc1_TKBrains3",
    "Braaaaaaaaaaaains":                                                      "dlc1_missions.SideMissions.M_dlc1_TKBrains4",
    "Braaaaaaaaaaaaaaaaains":                                                 "dlc1_missions.SideMissions.M_dlc1_TKBrains5",
    "Leave It To The Professionals":                                          "dlc1_missions.SideMissions.M_dlc1_BountyHunterLogs_priest",
    "Here We Go Again":                                                       "dlc1_missions.SideMissions.M_dlc1_BountyHunterLogs_Mill",
    "Missing: Hank Reiss":                                                    "dlc1_missions.SideMissions.M_dlc1_LogCollection",
    "Eggcellent Opportunity!":                                                "dlc1_missions.SideMissions.M_dlc1_Eggs",
    "TK Lives!":                                                              "dlc1_missions.SideMissions.M_dlc1_FindZombieTK",
    "It's Alive!":                                                            "dlc1_missions.SideMissions.M_dlc1_FrankenBill",
    "The Pack":                                                               "dlc1_missions.SideMissions.M_dlc1_WereskagPack",
    "Upsale":                                                                 "dlc1_missions.SideMissions.M_dlc1_FixJakobsVending",
    "Pumpkinhead":                                                            "dlc1_missions.SideMissions.M_dlc1_PumpkinHead",
    "Claptrap Rescue: The Lumber Yard":                                       "dlc1_missions.SideMissions.M_dlc1_RepairClaptrap",
    "A Bridge Too Ned":                                                       "dlc1_missions.MainMissions.M_dlc1_LowerBridge",
    "Prove Yourself.":                                                        "dlc2_missions.Missions.M_ClearArenas",
    "Scooter?  But I Don't Even Know Her.":                                   "dlc3_MainMissions.MainMissions.M_dlc3_MeetScooter",
    "Boost the Monster":                                                      "dlc3_MainMissions.MainMissions.M_dlc3_GetCarParts",
    "Greasemonkey":                                                           "dlc3_MainMissions.MainMissions.M_dlc3_BuildCar",
    "You've Got Moxxi: Roadblock":                                            "dlc3_MainMissions.MainMissions.M_dlc3_Roadblocks1",
    "You've Got Moxxi: Moxxi's Red Light":                                    "dlc3_MainMissions.MainMissions.M_dlc3_MeetMoxxi",
    "Prison Break: Road Warrior":                                             "dlc3_MainMissions.MainMissions.M_dlc3_Roadblocks2",
    "Prison Break: Over the Wall":                                            "dlc3_MainMissions.MainMissions.M_dlc3_PrisonInfiltrate",
    "Prison Break: Try Not to Get Shanked":                                   "dlc3_MainMissions.MainMissions.M_dlc3_PrisonMrShank",
    "Rendezvous":                                                             "dlc3_MainMissions.MainMissions.M_dlc3_MeetInformant",
    "Code Breaker: Analysis":                                                 "dlc3_MainMissions.MainMissions.M_dlc3_FindCodeBunker",
    "Code Breaker: Time is Bullets":                                          "dlc3_MainMissions.MainMissions.M_dlc3_FindCodeEarl",
    "Athena Set Up Us The Bomb":                                              "dlc3_MainMissions.MainMissions.M_dlc3_GetDetonator",
    "Bridging the Gap":                                                       "dlc3_MainMissions.MainMissions.M_dlc3_ActivateBridge",
    "Armory Assault":                                                         "dlc3_MainMissions.MainMissions.M_dlc3_DestroyDepot",
    "Loot Larceny":                                                           "dlc3_MainMissions.MainMissions.M_dlc3_GetLoot",
    "Little People, Big Experiments":                                         "dlc3_SideMissions.SideMissions.M_dlc3_Motorhead",
    "Claptrap Rescue: Lockdown Palace":                                       "dlc3_SideMissions.SideMissions.M_dlc3_ClaptrapRescue",
    "OMG APC":                                                                "dlc3_SideMissions.SideMissions.M_dlc3_Digistruct",
    "Purple Juice!":                                                          "dlc3_SideMissions.SideMissions.M_dlc3_DryWell",
    "Wanted: Dead!":                                                          "dlc3_SideMissions.SideMissions.M_dlc3_Hitman",
    "Road Rage":                                                              "dlc3_SideMissions.SideMissions.M_dlc3_CPaws01",
    "Drifter Lifter":                                                         "dlc3_SideMissions.SideMissions.M_dlc3_Drifter",
    "Thrown for a Loop":                                                      "dlc3_SideMissions.SideMissions.M_dlc3_LoopDeLoop",
    "Knoxxed Out":                                                            "dlc3_SideMissions.SideMissions.M_dlc3_KnoxxECHOCollection",
    "Lost Lewts":                                                             "dlc3_SideMissions.SideMissions.M_dlc3_Treasure",
    "Core Collection":                                                        "dlc3_SideMissions.SideMissions.M_dlc3_PowerCores",
    "Bugged":                                                                 "dlc3_SideMissions.SideMissions.M_dlc3_Gondola",
    "Stain Removal":                                                          "dlc3_SideMissions.SideMissions.M_dlc3_Graffiti",
    "This Bitch is Payback":                                                  "dlc3_SideMissions.SideMissions.M_dlc3_LanceCommander01",
    "This Bitch is Payback, pt. 2":                                           "dlc3_SideMissions.SideMissions.M_dlc3_LanceCommander02",
    "Power Leech":                                                            "dlc3_SideMissions.SideMissions.M_dlc3_Power",
    "You. Will. Die.":                                                        "dlc3_SideMissions.SideMissions.M_dlc3_UberBoss",
    "Mop Up":                                                                 "dlc3_SideMissions.SideMissions.M_dlc3_KillStuff01",
    "Local Trouble":                                                          "dlc3_SideMissions.SideMissions.M_dlc3_KillStuff02",
    "Super-Marcus Sweep":                                                     "dlc3_SideMissions.SideMissions.M_dlc3_GetLoot02",
    "It's Like Christmas!":                                                   "dlc3_SideMissions.SideMissions.M_dlc3_GetLoot03",
    "Big Crimson Brother is Watching":                                        "dlc3_SideMissions.SideMissions.M_dlc3_Drones",
    "Circle of Duty: New Recruit":                                            "dlc3_CircleMissions.MainMissions.M_dlc3_CircleMeet",
    "Circle of Duty: Cadet":                                                  "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave1",
    "Circle of Duty: Private":                                                "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave2",
    "Circle of Duty: Corporal":                                               "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave3",
    "Circle of Duty: Sergeant":                                               "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave4",
    "Circle of Duty: Medal of Duty":                                          "dlc3_CircleMissions.MainMissions.M_dlc3_Circle_Wave5",
    "Not My Fault":                                                           "DLC4_D_Faults_Missions.SideMissions.M_DLC4_DFault",
    "Operation Trap Claptrap Trap, Phase Two: Industrial Revolution":         "DLC4_D_Faults_Missions.MainMissions.M_DLC4_OTCT_Phase2",
    "Taking Stock":                                                           "DLC4_D_Faults_Missions.SideMissions.M_DLC4_TakingStock",
    "Are You From These Parts?":                                              "DLC4_Hyperion_Dump_Missions.MainMissions.M_dlc4_AreyoufromtheseParts",
    "Burnin' Rubber":                                                         "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_Burn_Rubber",
    "Fight For Your Right To Part-E":                                         "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_TannisParts2",
    "Parts Is Parts":                                                         "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_TannisParts3",
    "We All Have Our Part To Play":                                           "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_TannisParts4",
    "A Part Of Something Larger Than Yourself":                               "DLC4_Hyperion_Dump_Missions.SideMissions.M_dlc4_TannisParts5",
    "Eleven Rakk And Spices":                                                 "DLC4_Sanders_Gorge_Missions.MainMissions.M_dlc4_Eleven_Rakks_Spices",
    "Finger Lickin' Bad!":                                                    "DLC4_Sanders_Gorge_Missions.MainMissions.M_dlc4_Finger_Lickin_Bad",
    "Operation Trap Claptrap Trap, Phase One":                                "DLC4_Sanders_Gorge_Missions.MainMissions.M_dlc4_OTCT_Phase_One",
    "Operation Trap Claptrap Trap, Phase Three: TripWIRED":                   "DLC4_SS_Canyon_Missions.MainMissions.M_DLC4_TripWIRED",
    "Old Spicy":                                                              "DLC4_SS_Canyon_Missions.SideMissions.M_side_dlc4_OldSpicy",
    "Helping Is Its Own Reward... Wait No It Isn't!":                         "DLC4_Tartarus_Stat_Missions.MainMissions.M_dlc4_M7_Helping_is_its_own_reward",
    "New Contact":                                                            "DLC4_Tartarus_Stat_Missions.MainMissions.M_dlc4_New_Contact",
    "It's A Trap... Clap":                                                    "DLC4_Tartarus_Stat_Missions.SideMissions.M_dlc4_Repair_Trap_Clap",
    "Like Shootin' Rakk In A Barrel":                                         "DLC4_Tartarus_Stat_Missions.SideMissions.M_dlc4_Shooting_Rakks_Barrel",
    "Spa Vs. Spa":                                                            "DLC4_Tartarus_Stat_Missions.SideMissions.M_dlc4_Spa_Vs_Spa",
    "One-UpmanPipp":                                                          "DLC4_Tartarus_Stat_Missions.SideMissions.M_side_dlc4_OneUpmanPipp",
    "Operation Trap Claptrap Trap, Phase Four: Reboot":                       "DLC4_Wayward_Pass_Missions.MainMissions.M_dlc4_OTCT_Reboot",
}

mission_ue_str_to_name = {v.split('.')[-1]: k for k, v in mission_name_to_ue_str.items()}