# This file is intended to be shared between the Archipelago Client/World and the Game sdkmod.
# I don't expect to be able to have one source of truth distributed to both, so just keep the two files in sync.


level_name_to_id = {
    # 2 through 80
    "Level " + str(i) : i for i in range(2, 81)
}

gear_kind_to_id = {
    # Gear
    "Common Shield":                    100,
    "Uncommon Shield":                  101,
    "Rare Shield":                      102,
    "VeryRare Shield":                  103,
    # "E-Tech Shield":                    104,
    "Legendary Shield":                 105,
    # "Seraph Shield":                    106,
    # "Rainbow Shield":                   107,
    # "Pearlescent Shield":               108,
    # "Unique Shield":                    109,

    "Common GrenadeMod":                110,
    "Uncommon GrenadeMod":              111,
    "Rare GrenadeMod":                  112,
    "VeryRare GrenadeMod":              113,
    # "E-Tech GrenadeMod":                114,
    "Legendary GrenadeMod":             115,
    # "Seraph GrenadeMod":                116,
    # "Rainbow GrenadeMod":               117,
    # "Pearlescent GrenadeMod":           118,
    # "Unique GrenadeMod":                119,

    "Common ClassMod":                  120,
    "Uncommon ClassMod":                121,
    "Rare ClassMod":                    122,
    "VeryRare ClassMod":                123,
    # "E-Tech ClassMod":                  124,
    "Legendary ClassMod":               125,
    # "Seraph ClassMod":                  126,
    # "Rainbow ClassMod":                 127,
    # "Pearlescent ClassMod":             128,
    # "Unique ClassMod":                  129,

    "Common Relic":                     130,
    "Uncommon Relic":                   131,
    "Rare Relic":                       132,
    "VeryRare Relic":                   133,
    # "E-Tech Relic":                     134,
    # "Legendary Relic":                  135,
    # "Seraph Relic":                     136,
    # "Rainbow Relic":                    137,
    # "Pearlescent Relic":                138,
    # "Unique Relic":                     139,

    "Common Pistol":                    140,
    "Uncommon Pistol":                  141,
    "Rare Pistol":                      142,
    "VeryRare Pistol":                  143,
    "E-Tech Pistol":                    144,
    "Legendary Pistol":                 145,
    # "Seraph Pistol":                    146,
    # "Rainbow Pistol":                   147,
    # "Pearlescent Pistol":               148,
    "Unique Pistol":                    149,

    "Common Shotgun":                   150,
    "Uncommon Shotgun":                 151,
    "Rare Shotgun":                     152,
    "VeryRare Shotgun":                 153,
    "E-Tech Shotgun":                   154,
    "Legendary Shotgun":                155,
    # "Seraph Shotgun":                   156,
    # "Rainbow Shotgun":                  157,
    # "Pearlescent Shotgun":              158,
    "Unique Shotgun":                   159,

    "Common SMG":                       160,
    "Uncommon SMG":                     161,
    "Rare SMG":                         162,
    "VeryRare SMG":                     163,
    "E-Tech SMG":                       164,
    "Legendary SMG":                    165,
    # "Seraph SMG":                       166,
    # "Rainbow SMG":                      167,
    # "Pearlescent SMG":                  168,
    "Unique SMG":                       169,

    "Common SniperRifle":               170,
    "Uncommon SniperRifle":             171,
    "Rare SniperRifle":                 172,
    "VeryRare SniperRifle":             173,
    "E-Tech SniperRifle":               174,
    "Legendary SniperRifle":            175,
    # "Seraph SniperRifle":               176,
    # "Rainbow SniperRifle":              177,
    # "Pearlescent SniperRifle":          178,
    "Unique SniperRifle":               179,

    "Common AssaultRifle":              180,
    "Uncommon AssaultRifle":            181,
    "Rare AssaultRifle":                182,
    "VeryRare AssaultRifle":            183,
    "E-Tech AssaultRifle":              184,
    "Legendary AssaultRifle":           185,
    # "Seraph AssaultRifle":              186,
    # "Rainbow AssaultRifle":             187,
    # "Pearlescent AssaultRifle":         188,
    "Unique AssaultRifle":              189,

    "Common RocketLauncher":            190,
    "Uncommon RocketLauncher":          191,
    "Rare RocketLauncher":              192,
    "VeryRare RocketLauncher":          193,
    "E-Tech RocketLauncher":            194,
    "Legendary RocketLauncher":         195,
    # "Seraph RocketLauncher":            196,
    # "Rainbow RocketLauncher":           197,
    # "Pearlescent RocketLauncher":       198,
    "Unique RocketLauncher":            199,
}

loc_name_to_id = {

    # Enemies
    "Knuckle Dragger":                   301,
    "Midgemong":                         302,
    "Boom Bewm":                         303,
    "Captain Flynt":                     304,
    "Savage Lee":                        305,
    "Boll":                              306,
    "Doc Mercy":                         307,
    "Assassin Oney":                     308,
    "Assassin Wot":                      309,
    "Assassin Reeth":                    310,
    "Assassin Rouf":                     311,
    "Scorch":                            312,
    "Incinerator Clayton":               313,
    "Gettle":                            314,
    "Mobley":                            315,
    "Black Queen":                       316,
    "Bad Maw":                           317,
    "Mad Mike":                          318,
    "W4R-D3N":                           319,
    "Spycho":                            320,
    "McNally":                           321,
    "Mick/Tector":                       322,
    "Dan":                               323,
    "Lee":                               324,
    "Mick":                              325,
    "Ralph":                             326,
    "Flinter":                           327,
    "MadameVonBartlesby":                328,
    "Wilhelm":                           329,
    "LaneyWhite":                        330,
    "Rakkman":                           331,
    "SmashHead":                         332,
    "Sinkhole":                          333,
    "OldSlappy":                         334,
    "GluttonousThresher":                325,
    "Henry":                             336,
    "Blue":                              337,
    "BadassCreeper":                     338,
    "Tumbaa":                            339,
    "Pimon":                             340,
    "SonOfMothrakk":                     341,
    # "Bloodwing":                         342,
    # "GOD-liath":                         343,
    "DukinosMom":                        344,
    "MadDog":                            345,
    "SheriffNisha":                      346,
    "DeputyWinger":                      347,
    "ForemanJasper":                     348,
    "JackBodyDouble":                    349,
    # "BNK-3R":                            350,
    "KingMong":                          351,
    "DonkeyMong":                        352,
    "Mortar":                            353,
    "HunterHellquist":                   354,
    "BoneHead":                          355,
    "Saturn":                            356,
    # "Warrior":                           357,

    "Symbol Sanctuary: Rooftop":                           501,
    "Symbol Sanctuary: Moxxi's Corner":                    502,
    "Symbol Sanctuary: Trash Corner":                      503,
    "Symbol Sanctuary: Tire Corner":                       504,
    "Symbol Sanctuary: Parkour Door":                      505,
    "Symbol EridiumBlight: 1":                             506,
    "Symbol EridiumBlight: 181":                           507,
    "Symbol EridiumBlight: Stairs Door":                   508,
    "Symbol EridiumBlight: 518":                           509,
    "Symbol EridiumBlight: 519":                           510,
    "Symbol EridiumBlight: 520":                           511,
    "Symbol EridiumBlight: 521":                           512,
    "Symbol EridiumBlight: 522":                           513,
    "Symbol EridiumBlight: 523":                           514,
    "Symbol EridiumBlight: 524":                           515,
    "Symbol EridiumBlight: 525":                           516,
    "Symbol EridiumBlight: 526":                           517,
    "Symbol Fink's: 29":                                   518,
    "Symbol Bunker: Backside":                             519,
    "Symbol WarriorVault: Elevator Bottom":                520,
    "Symbol SouthernShelfBay: Blackburn Cove Corner":      521,
    "Symbol SouthernShelfBay: Ice Flows Shipwreck":        522,
    "Symbol Sawtooth: 27":                                 523,
    "Symbol Sawtooth: 7":                                  524,
    "Symbol CreatureSlaughter: 0":                         525,
    "Symbol HerosPass: 0":                                 526,
    "Symbol HerosPass: 6":                                 527,
    "Symbol Fridge: Secret Stash":                         528,
    "Symbol Fridge: Sheetmetal Roof":                      529,
    "Symbol ThreeHornsValley: Frostsprings Shack":         530,
    "Symbol ThreeHornsValley: Frostsprings Wall":          531,
    "Symbol ThreeHornsValley: Slums Wall":                 532,
    "Symbol AridNexusBoneyard: 0":                         533,
    "Symbol AridNexusBoneyard: 3":                         534,
    "Symbol WindshearWaste: Claptrap's Closet":            535,
    "Symbol ThousandCuts: Buzzard Factory":                536,
    "Symbol ThousandCuts: No Man's Land Shack":            537,
    "Symbol Lynchwood: 145":                               538,
    "Symbol Lynchwood: 146":                               539,
    "Symbol Lynchwood: 147":                               540,
    "Symbol Lynchwood: 148":                               541,
    "Symbol Lynchwood: 2":                                 542,
    "Symbol Lynchwood: Gunslinger Roof":                   543,
    "Symbol Lynchwood: Main Street":                       544,
    "Symbol Highlands: Highlands Tower":                   545,
    "Symbol FriendshipGulag: Gulag Container":             546,
    "Symbol Opportunity: Construction Site":               547,
    "Symbol Opportunity: Office Bridge":                   548,
    "Symbol ThreeHornsDivide Drydocks Corner":             549,
    "Symbol ThreeHornsDivide Billboard":                   550,
    "Symbol ThreeHornsDivide Windbreak Wall":              551,
    "Symbol Dust: 26":                                     552,
    "Symbol Dust: 4":                                      553,
    "Symbol Dust: 5":                                      554,
    "Symbol CausticCaverns: Gravestone Feature":           555,
    "Symbol CausticCaverns: Bloody Ladder":                556,
    "Symbol Blodshot: Pizza Intercom":                     557,
    "Symbol Blodshot: Switch Room":                        558,
    "Symbol BlodshotRamparts: Ramp":                       559,
    "Symbol Frostburn: Blisterpus Cave":                   560,
    "Symbol Frostburn: Ashmouth Pit":                      561,
    "Symbol TorgueArenaRing: 678":                         562,
    "Symbol TorgueArenaRing: 772":                         563,
    "Symbol Beatdown: 425":                                564,
    "Symbol Beatdown: 79":                                 565,
    "Symbol Forge: 214":                                   566,
    "Symbol Forge: 425":                                   567,
    "Symbol Forge: 61":                                    568,
    "Symbol SouthernRaceway: 6":                           569,
    "Symbol SouthernRaceway: 9":                           570,
    "Symbol BadassCrater: 11":                             571,
    "Symbol BadassCrater: 12":                             572,
    "Symbol BadassCrater: 678":                            573,
    "Symbol BadassCrater: 78":                             574,
    "Symbol HolySpirits: 16":                              575,
    "Symbol HaytorsFolly: 347":                            576,
    "Symbol HaytorsFolly: 461":                            577,
    "Symbol Oasis: 347":                                   578,
    "Symbol Oasis: 348":                                   579,
    "Symbol Oasis: 349":                                   580,
    "Symbol Oasis: 367":                                   581,
    "Symbol WashburnRefinery: 496":                        582,
    "Symbol WashburnRefinery: 497":                        583,
    "Symbol Wurmwater: 347":                               584,
    "Symbol Wurmwater: 400":                               585,
    "Symbol Wurmwater: 401":                               586,
    "Symbol Rustyards: 22":                                587,
    "Symbol Rustyards: 23":                                588,
    "Symbol MagnysLighthouse: 10":                         589,
    "Symbol MagnysLighthouse: 22":                         590,
    "Symbol LeviathansLair: 497":                          591,
    "Symbol WildlifePreserve: 273":                        592,
    "Symbol WildlifePreserve: 274":                        593,
    "Symbol OreChasm: 15":                                 594,
    "Symbol CandlerakksCragg: 129":                        595,
    "Symbol CandlerakksCragg: 71":                         596,
    "Symbol CandlerakksCragg: 84":                         597,
    "Symbol Terminus: 0":                                  598,
    "Symbol AdortonStation: 29":                           599,
    "Symbol AdortonStation: 5":                            600,
    "Symbol AdortonStation: 6":                            601,
    "Symbol AdortonStation: 7":                            602,
    "Symbol ScyllasGrove: 10":                             603,
    "Symbol ScyllasGrove: 6":                              604,
    "Symbol ScyllasGrove: 8":                              605,
    "Symbol ScyllasGrove: 9":                              606,
    "Symbol SanctuaryHole: Staircase Wall":                607,
    "Symbol SouthernShelf: Flynt's Ship":                  608,
    "Symbol SouthernShelf: Safehouse":                     609,
    "Symbol Southpaw: 398":                                610,
    "Symbol Southpaw: 399":                                611,
    "Symbol Southpaw: 46":                                 612,
    "Symbol TerramorphousPeak: 116":                       613,
    "Symbol TerramorphousPeak: 364":                       614,
    "Symbol EndOfTheLine: Wilhelm Wall":                   615,
    "Symbol TundraExpress: Fork Shack":                    616,
    "Symbol TundraExpress: Facility Roof":                 617,
    "Symbol Backburner: 2":                                618,
    "Symbol Backburner: 3":                                619,
    "Symbol HatredsShadow: 0":                             620,
    "Symbol HatredsShadow: 1":                             621,
    "Symbol HatredsShadow: 4":                             622,
    "Symbol DragonKeep: 0":                                623,
    "Symbol TheForest: 0":                                 624,
    "Symbol TheForest: 1":                                 625,
    "Symbol ImmortalWoods: 1":                             626,
    "Symbol ImmortalWoods: 19":                            627,
    "Symbol ImmortalWoods: 20":                            628,
    "Symbol UnassumingDocks: 0":                           629,
    "Symbol UnassumingDocks: 1":                           630,
    "Symbol UnassumingDocks: 2":                           631,
    "Symbol WingedStorm: 0":                               632,
    "Symbol LairOfInfiniteAgony: 307":                     633,
    "Symbol LairOfInfiniteAgony: 308":                     634,
    "Symbol LairOfInfiniteAgony: 90":                      635,
    "Symbol HeliosFallen: 11":                             636,
    "Symbol HeliosFallen: 388":                            637,
    "Symbol HeliosFallen: 446":                            638,
    "Symbol HeliosFallen: 447":                            639,
    "Symbol HeliosFallen: 859":                            640,
    "Symbol HeliosFallen: 892":                            641,
    "Symbol HeliosFallen: 894":                            642,
    "Symbol MinesOfAvarice: 1":                            643,
    "Symbol MinesOfAvarice: 16":                           644,
    "Symbol MinesOfAvarice: 47":                           645,
    "Symbol DahlAbandon: 187":                             646,
    "Symbol DahlAbandon: 269":                             647,
    "Symbol DahlAbandon: 36":                              648,
    "Symbol DahlAbandon: 59":                              649,
    "Symbol DahlAbandon: 84":                              650,
    "Symbol MtScarab: 164":                                651,
    "Symbol MtScarab: 167":                                652,
    "Symbol MtScarab: 737":                                653,
    "Symbol HuntersGrotto: 68":                            654,
    "Symbol HuntersGrotto: 69":                            655,
    "Symbol HuntersGrotto: 70":                            656,
    "Symbol HuntersGrotto: 71":                            657,
    "Symbol WrithingDeep: 1161":                           658,
    "Symbol WrithingDeep: 1162":                           659,
    "Symbol WrithingDeep: 1163":                           660,
    "Symbol TheBurrows: 46":                               661,
    "Symbol TheBurrows: 60":                               662,
    "Symbol MurderlinsTemple: 1":                          663,
    "Symbol MurderlinsTemple: 3":                          664,
    "Symbol FlamerockRefuge: 206":                         665,
    "Symbol FlamerockRefuge: 383":                         666,
}


item_name_to_id = {
    "3 Skill Points":                     1,
    "Progressive Money Cap":              2,
    "Weapon Slot":                        3,
    "$100":                               4,
    "10 Eridium":                         5,

    "Jump":                               6,
    "Melee":                              7,
    "Crouch":                             8,
    "Sprint":                             9,
    "Gear Leveler":                      10,
    "Vehicle Fire":                      11,
}

# stitch dictionaries together

loc_name_to_id.update(gear_kind_to_id)
loc_name_to_id.update(level_name_to_id)

item_name_to_id.update(gear_kind_to_id)

loc_id_to_name = {id: name for name, id in loc_name_to_id.items()}
item_id_to_name = {id: name for name, id in item_name_to_id.items()}
