# This file is intended to be shared between the Archipelago Client/World and the Game sdkmod.
# I don't expect to be able to have one source of truth distributed to both, so just keep the two files in sync.


level_name_to_id = {
    # 2 through 80
    "Level " + str(i) : i for i in range(2, 81)
}

gear_kind_to_id = {
    # Gear
    "Common Shield":                    100,
    "Uncommon Shield":                  101,
    "Rare Shield":                      102,
    "VeryRare Shield":                  103,
    # "E-Tech Shield":                    104,
    "Legendary Shield":                 105,
    # "Seraph Shield":                    106,
    # "Rainbow Shield":                   107,
    # "Pearlescent Shield":               108,
    # "Unique Shield":                    109,

    "Common GrenadeMod":                110,
    "Uncommon GrenadeMod":              111,
    "Rare GrenadeMod":                  112,
    "VeryRare GrenadeMod":              113,
    # "E-Tech GrenadeMod":                114,
    "Legendary GrenadeMod":             115,
    # "Seraph GrenadeMod":                116,
    # "Rainbow GrenadeMod":               117,
    # "Pearlescent GrenadeMod":           118,
    # "Unique GrenadeMod":                119,

    "Common ClassMod":                  120,
    "Uncommon ClassMod":                121,
    "Rare ClassMod":                    122,
    "VeryRare ClassMod":                123,
    # "E-Tech ClassMod":                  124,
    "Legendary ClassMod":               125,
    # "Seraph ClassMod":                  126,
    # "Rainbow ClassMod":                 127,
    # "Pearlescent ClassMod":             128,
    # "Unique ClassMod":                  129,

    "Common Relic":                     130,
    "Uncommon Relic":                   131,
    "Rare Relic":                       132,
    "VeryRare Relic":                   133,
    # "E-Tech Relic":                     134,
    # "Legendary Relic":                  135,
    # "Seraph Relic":                     136,
    # "Rainbow Relic":                    137,
    # "Pearlescent Relic":                138,
    # "Unique Relic":                     139,

    "Common Pistol":                    140,
    "Uncommon Pistol":                  141,
    "Rare Pistol":                      142,
    "VeryRare Pistol":                  143,
    "E-Tech Pistol":                    144,
    "Legendary Pistol":                 145,
    # "Seraph Pistol":                    146,
    # "Rainbow Pistol":                   147,
    # "Pearlescent Pistol":               148,
    "Unique Pistol":                    149,

    "Common Shotgun":                   150,
    "Uncommon Shotgun":                 151,
    "Rare Shotgun":                     152,
    "VeryRare Shotgun":                 153,
    "E-Tech Shotgun":                   154,
    "Legendary Shotgun":                155,
    # "Seraph Shotgun":                   156,
    # "Rainbow Shotgun":                  157,
    # "Pearlescent Shotgun":              158,
    "Unique Shotgun":                   159,

    "Common SMG":                       160,
    "Uncommon SMG":                     161,
    "Rare SMG":                         162,
    "VeryRare SMG":                     163,
    "E-Tech SMG":                       164,
    "Legendary SMG":                    165,
    # "Seraph SMG":                       166,
    # "Rainbow SMG":                      167,
    # "Pearlescent SMG":                  168,
    "Unique SMG":                       169,

    "Common SniperRifle":               170,
    "Uncommon SniperRifle":             171,
    "Rare SniperRifle":                 172,
    "VeryRare SniperRifle":             173,
    "E-Tech SniperRifle":               174,
    "Legendary SniperRifle":            175,
    # "Seraph SniperRifle":               176,
    # "Rainbow SniperRifle":              177,
    # "Pearlescent SniperRifle":          178,
    "Unique SniperRifle":               179,

    "Common AssaultRifle":              180,
    "Uncommon AssaultRifle":            181,
    "Rare AssaultRifle":                182,
    "VeryRare AssaultRifle":            183,
    "E-Tech AssaultRifle":              184,
    "Legendary AssaultRifle":           185,
    # "Seraph AssaultRifle":              186,
    # "Rainbow AssaultRifle":             187,
    # "Pearlescent AssaultRifle":         188,
    "Unique AssaultRifle":              189,

    "Common RocketLauncher":            190,
    "Uncommon RocketLauncher":          191,
    "Rare RocketLauncher":              192,
    "VeryRare RocketLauncher":          193,
    "E-Tech RocketLauncher":            194,
    "Legendary RocketLauncher":         195,
    # "Seraph RocketLauncher":            196,
    # "Rainbow RocketLauncher":           197,
    # "Pearlescent RocketLauncher":       198,
    "Unique RocketLauncher":            199,
}

loc_name_to_id = {

    # Enemies
    "Knuckle Dragger":                   301,
    "Midgemong":                         302,
    "Boom Bewm":                         303,
    "Captain Flynt":                     304,
    "Savage Lee":                        305,
    "Boll":                              306,
    "Doc Mercy":                         307,
    "Assassin Oney":                     308,
    "Assassin Wot":                      309,
    "Assassin Reeth":                    310,
    "Assassin Rouf":                     311,
    "Scorch":                            312,
    "Incinerator Clayton":               313,
    "Gettle":                            314,
    "Mobley":                            315,
    "Black Queen":                       316,
    "Bad Maw":                           317,
    "Mad Mike":                          318,
    "W4R-D3N":                           319,
    "Spycho":                            320,
    "McNally":                           321,
    "Mick/Tector":                       322,
    "Dan":                               323,
    "Lee":                               324,
    "Mick":                              325,
    "Ralph":                             326,
    "Flinter":                           327,
    "MadameVonBartlesby":                328,
    "Wilhelm":                           329,
    "LaneyWhite":                        330,
    "Rakkman":                           331,
    "SmashHead":                         332,
    "Sinkhole":                          333,
    "OldSlappy":                         334,
    "GluttonousThresher":                325,
    "Henry":                             336,
    "Blue":                              337,
    "BadassCreeper":                     338,
    "Tumbaa":                            339,
    "Pimon":                             340,
    "SonOfMothrakk":                     341,
    # "Bloodwing":                         342,
    # "GOD-liath":                         343,
    "DukinosMom":                        344,
    "MadDog":                            345,
    "SheriffNisha":                      346,
    "DeputyWinger":                      347,
    "ForemanJasper":                     348,
    "JackBodyDouble":                    349,
    # "BNK-3R":                            350,
    "KingMong":                          351,
    "DonkeyMong":                        352,
    "Mortar":                            353,
    "HunterHellquist":                   354,
    "BoneHead":                          355,
    "Saturn":                            356,
    # "Warrior":                           357,

    "Symbol Sanctuary 0":                501,
    "Symbol Sanctuary 1":                502,
    "Symbol Sanctuary 2":                503,
    "Symbol Sanctuary 263":              504,
    "Symbol Sanctuary 98":               505,
    "Symbol Ash 1":                      506,
    "Symbol Ash 181":                    507,
    "Symbol Ash 3":                      508,
    "Symbol Ash 518":                    509,
    "Symbol Ash 519":                    510,
    "Symbol Ash 520":                    511,
    "Symbol Ash 521":                    512,
    "Symbol Ash 522":                    513,
    "Symbol Ash 523":                    514,
    "Symbol Ash 524":                    515,
    "Symbol Ash 525":                    516,
    "Symbol Ash 526":                    517,
    "Symbol BanditSlaughter 29":         518,
    "Symbol Boss_Cliffs 0":              519,
    "Symbol Boss_Volcano 181":           520,
    "Symbol Cove 180":                   521,
    "Symbol Cove 235":                   522,
    "Symbol CraterLake 27":              523,
    "Symbol CraterLake 7":               524,
    "Symbol CreatureSlaughter 0":        525,
    "Symbol FinalBossAscent 0":          526,
    "Symbol FinalBossAscent 6":          527,
    "Symbol Fridge 89":                  528,
    "Symbol Fridge 90":                  529,
    "Symbol Frost 5":                    530,
    "Symbol Frost 31":                   531,
    "Symbol Frost 5":                    532,
    "Symbol Fyrestone 0":                533,
    "Symbol Fyrestone 3":                534,
    "Symbol Glacial 214":                535,
    "Symbol Grass_Cliffs 174":           536,
    "Symbol Grass_Cliffs 302":           537,
    "Symbol Grass_Lynchwood 145":        538,
    "Symbol Grass_Lynchwood 146":        539,
    "Symbol Grass_Lynchwood 147":        540,
    "Symbol Grass_Lynchwood 148":        541,
    "Symbol Grass_Lynchwood 2":          542,
    "Symbol Grass_Lynchwood 298":        543,
    "Symbol Grass_Lynchwood 601":        544,
    "Symbol Grass 346":                  545,
    "Symbol HypInterlude 12":            546,
    "Symbol HyperionCity 180":           547,
    "Symbol HyperionCity 181":           548,
    "Symbol Ice 238":                    549,
    "Symbol Ice 5":                      550,
    "Symbol Ice 79":                     551,
    "Symbol Interlude 26":               552,
    "Symbol caverns 641":                553,
    "Symbol caverns 89":                 554,
    "Symbol dam 137":                    555,
    "Symbol dam 138":                    556,
    "Symbol damtop 0":                   557,
    "Symbol icecanyon 51":               558,
    "Symbol icecanyon 53":               559,
    "Symbol Interlude 4":                560,
    "Symbol Interlude 5":                561,
    "Symbol Iris_DL1 678":               562,
    "Symbol Iris_DL1 772":               563,
    "Symbol Iris_DL2 425":               564,
    "Symbol Iris_DL2 79":                565,
    "Symbol Iris_DL3 214":               566,
    "Symbol Iris_DL3 425":               567,
    "Symbol Iris_DL3 61":                568,
    "Symbol Iris_Hub2 6":                569,
    "Symbol Iris_Hub2 9":                570,
    "Symbol Iris_Hub 11":                571,
    "Symbol Iris_Hub 12":                572,
    "Symbol Iris_Hub 678":               573,
    "Symbol Iris_Hub 78":                574,
    "Symbol Luckys 16":                  575,
    "Symbol ORCHID_CAVES 347":           576,
    "Symbol ORCHID_CAVES 461":           577,
    "Symbol Orchid_OasisTown 347":       578,
    "Symbol Orchid_OasisTown 348":       579,
    "Symbol Orchid_OasisTown 349":       580,
    "Symbol Orchid_OasisTown 367":       581,
    "Symbol Orchid_Refinery 496":        582,
    "Symbol Orchid_Refinery 497":        583,
    "Symbol Orchid_SaltFlats 347":       584,
    "Symbol Orchid_SaltFlats 400":       585,
    "Symbol Orchid_SaltFlats 401":       586,
    "Symbol Orchid_ShipGraveyard 22":    587,
    "Symbol Orchid_ShipGraveyard 23":    588,
    "Symbol Orchid_Spire 10":            589,
    "Symbol Orchid_Spire 22":            590,
    "Symbol Orchid_WormBelly 497":       591,
    "Symbol PandoraPark 273":            592,
    "Symbol PandoraPark 274":            593,
    "Symbol RobotSlaughter 15":          594,
    "Symbol Sage_Cliffs 129":            595,
    "Symbol Sage_Cliffs 71":             596,
    "Symbol Sage_Cliffs 84":             597,
    "Symbol Sage_HyperionShip 0":        598,
    "Symbol Sage_PowerStation 29":       599,
    "Symbol Sage_PowerStation 5":        600,
    "Symbol Sage_PowerStation 6":        601,
    "Symbol Sage_PowerStation 7":        602,
    "Symbol Sage_RockForest 10":         603,
    "Symbol Sage_RockForest 6":          604,
    "Symbol Sage_RockForest 8":          605,
    "Symbol Sage_RockForest 9":          606,
    "Symbol Sanctuary_Hole 6":           607,
    "Symbol SouthernShelf 181":          608,
    "Symbol SouthernShelf 397":          609,
    "Symbol SouthpawFactory 398":        610,
    "Symbol SouthpawFactory 399":        611,
    "Symbol SouthpawFactory 46":         612,
    "Symbol ThresherRaid 116":           613,
    "Symbol ThresherRaid 364":           614,
    "Symbol TundraTrain 0":              615,
    "Symbol tundraexpress 206":          616,
    "Symbol tundraexpress 207":          617,
    "Symbol BackBurner 2":               618,
    "Symbol BackBurner 3":               619,
    "Symbol CastleExterior 0":           620,
    "Symbol CastleExterior 1":           621,
    "Symbol CastleExterior 4":           622,
    "Symbol CastleKeep 0":               623,
    "Symbol Dark_Forest 0":              624,
    "Symbol Dark_Forest 1":              625,
    "Symbol Dead_Forest 1":              626,
    "Symbol Dead_Forest 19":             627,
    "Symbol Dead_Forest 20":             628,
    "Symbol Docks 0":                    629,
    "Symbol Docks 1":                    630,
    "Symbol Docks 2":                    631,
    "Symbol DungeonRaid 0":              632,
    "Symbol Dungeon 307":                633,
    "Symbol Dungeon 308":                634,
    "Symbol Dungeon 90":                 635,
    "Symbol Helios 11":                  636,
    "Symbol Helios 388":                 637,
    "Symbol Helios 446":                 638,
    "Symbol Helios 447":                 639,
    "Symbol Helios 859":                 640,
    "Symbol Helios 892":                 641,
    "Symbol Helios 894":                 642,
    "Symbol Mines 1":                    643,
    "Symbol Mines 16":                   644,
    "Symbol Mines 47":                   645,
    "Symbol OldDust 187":                646,
    "Symbol OldDust 269":                647,
    "Symbol OldDust 36":                 648,
    "Symbol OldDust 59":                 649,
    "Symbol OldDust 84":                 650,
    "Symbol ResearchCenter 164":         651,
    "Symbol ResearchCenter 167":         652,
    "Symbol ResearchCenter 737":         653,
    "Symbol Sage_Underground 68":        654,
    "Symbol Sage_Underground 69":        655,
    "Symbol Sage_Underground 70":        656,
    "Symbol Sage_Underground 71":        657,
    "Symbol SandwormLair 1161":          658,
    "Symbol SandwormLair 1162":          659,
    "Symbol SandwormLair 1163":          660,
    "Symbol Sandworm 46":                661,
    "Symbol Sandworm 60":                662,
    "Symbol TempleSlaughter_Combat 1":   663,
    "Symbol TempleSlaughter_Combat 3":   664,
    "Symbol Village 206":                665,
    "Symbol Village 383":                666,
}


item_name_to_id = {
    "3 Skill Points":                     1,
    "Progressive Money Cap":              2,
    "Weapon Slot":                        3,
    "$100":                               4,
    "10 Eridium":                         5,

    "Jump":                               6,
    "Melee":                              7,
    "Crouch":                             8,
    "Sprint":                             9,
    "Gear Leveler":                      10,
    "Vehicle Fire":                      11,
}

# stitch dictionaries together

loc_name_to_id.update(gear_kind_to_id)
loc_name_to_id.update(level_name_to_id)

item_name_to_id.update(gear_kind_to_id)

loc_id_to_name = {id: name for name, id in loc_name_to_id.items()}
item_id_to_name = {id: name for name, id in item_name_to_id.items()}
