# unused
entrance_name_dict = {
    # LevelTravelStationDefinition
    "BackburnerToOldDust":                     "Backburner To DahlAbandon",
    "BackburnerToSanctIntro":                  "Backburner To FFSSanctIntro",
    "HeliosToSandwormCavern":                  "HeliosFallen To TheBurrows",
    "OldDustToBackburner":                     "DahlAbandon To Backburner",
    "OldDustToResearchCenter":                 "DahlAbandon To ResearchCenter",
    "OldDustToSandwormCavern":                 "DahlAbandon To TheBurrows",
    "RaidBossToSandwormCavern":                "WrithingDeep To TheBurrows",
    "ResearchCenterToOldDust":                 "ResearchCenter To DahlAbandon",
    "ResearchCenterToSanctuary":               "ResearchCenter To Sanctuary",
    "SanctIntroToBackburner":                  "FFSSanctIntro To Backburner",
    "SanctuaryToResearchCenter":               "Sanctuary To ResearchCenter",
    "SandwormCavernToHelios":                  "TheBurrows To HeliosFallen",
    "SandwormCavernToOldDust":                 "TheBurrows To DahlAbandon",
    "SandwormCavernToRaidBoss":                "TheBurrows To WrithingDeep",
    "CastleExteriorToCastleKeepFake":          "HatredsShadow To CastleKeepFake",
    "CastleExteriorToDungeon":                 "HatredsShadow To LairOfInfiniteAgony",
    "CastleExteriorToDungeons":                "HatredsShadow To Dungeons",
    "CastleExteriorToMines":                   "HatredsShadow To MinesOfAvarice",
    "CastleKeepToCastleExteriorFake":          "DragonKeep To CastleExteriorFake",
    "CastleKeepToDungeon":                     "DragonKeep To Dungeon",
    "CastleKeepToDungeons":                    "DragonKeep To Dungeons",
    "DarkForestToDeadForest":                  "TheForest To ImmortalWoods",
    "DarkForestToMines":                       "TheForest To MinesOfAvarice",
    "DarkForestToVillage":                     "TheForest To FlamerockRefuge",
    "DeadForestToDarkForest":                  "ImmortalWoods To TheForest",
    "DeadForestToMines":                       "ImmortalWoods To MinesOfAvarice",
    "DocksToVillage":                          "Docks To FlamerockRefuge",
    "DungeonRaidToDungeon":                    "WingedStorm To LairOfInfiniteAgony",
    "DungeonRaidToDungeons":                   "WingedStorm To Dungeons",
    "DungeonsToCastleExterior":                "Dungeons To HatredsShadow",
    "DungeonsToCastleKeep":                    "Dungeons To DragonKeep",
    "DungeonsToDungeonRaid":                   "Dungeons To WingedStorm",
    "DungeonToCastleExterior":                 "LairOfInfiniteAgony To HatredsShadow",
    "DungeonToCastleKeep":                     "LairOfInfiniteAgony To DragonKeep",
    "DungeonToDungeonRaid":                    "LairOfInfiniteAgony To WingedStorm",
    "MinesToCastleExterior":                   "MinesOfAvarice To HatredsShadow",
    "MinesToDarkForest":                       "MinesOfAvarice To TheForest",
    "MinesToDeadForest":                       "MinesOfAvarice To ImmortalWoods",
    "TempleOfSlaughterToVillage":              "TempleOfSlaughter To FlamerockRefuge",
    "VillageToDarkForest":                     "FlamerockRefuge To TheForest",
    "VillageToDocks":                          "FlamerockRefuge To Docks",
    "VillageToMines":                          "FlamerockRefuge To MinesOfAvarice",
    "VillageToTempleOfSlaughter":              "FlamerockRefuge To TempleOfSlaughter",
    "BeatdowntoPyroPeats":                     "Beatdown to PyroPeats",
    "BeatdowntoPyroPetes2":                    "Beatdown to PyroPetes2",
    "CraterToKickedOut":                       "Crater To KickedOut",
    "ArenaTASToCrater":                        "TorgueArena To Crater",
    "ArenaToCrater":                           "TorgueArenaRing To Crater",
    "BackdoorToCrater":                        "Backdoor To Crater",
    "BeatdownToCrater":                        "Beatdown To Crater",
    "ForgeToCrater":                           "Forge To Crater",
    "CraterToArena":                           "Crater To TorgueArenaRing",
    "CraterToArenaTAS":                        "Crater To TorgueArena",
    "CraterToBackdoor":                        "Crater To Backdoor",
    "CraterToBeatdown":                        "Crater To Beatdown",
    "CraterToForge":                           "Crater To Forge",
    "CraterToMamma":                           "Crater To Mamma",
    "CraterToMoxxi":                           "Crater To Moxxi",
    "MammaToCrater":                           "Mamma To Crater",
    "MoxxiToCrater":                           "Moxxi To Crater",
    "KickedOutToCrater":                       "KickedOut To Crater",
    "PyroPetesToBeatdown":                     "PyroPetes To Beatdown",
    "PyroPetesToBeatdown2":                    "PyroPetes To Beatdown2",
    "PyroPeteToBeatdown":                      "PyroPete To Beatdown",
    "PyroPetetoBeatdown2":                     "PyroPete to Beatdown2",
    "AridNexusToStockade":                     "AridNexus To Stockade",
    "AshToVolcano":                            "EridiumBlight To VaultOfTheWarrior",
    "FrostToIce":                              "ThreeHornsValley To ThreeHornsDivide",
    "FrostToIce2":                             "ThreeHornsValley To ThreeHornsDivide2",
    "GrassRoadToOutwash":                      "GrassRoad To Outwash",
    "IcetoFrost":                              "ThreeHornsDivide to ThreeHornsValley",
    "IceToFrost2":                             "ThreeHornsDivide To ThreeHornsValley2",
    "HypInterToInterlude":                     "FriendshipGulag To Dust",
    "InterludeToAsh":                          "Dust To EridiumBlight",
    "InterludeToDamTop":                       "Dust To DamTop",
    "InterludeToDLC":                          "Dust To DLC",
    "InterludeToGrass":                        "Dust To Grass",
    "InterludeToHypInter":                     "Dust To FriendshipGulag",
    "InterludeToIce":                          "Dust To ThreeHornsDivide",
    "InterludeToLynchwood":                    "Dust To Lynchwood",
    "LynchwoodToInterlude":                    "Lynchwood To Dust",
    "OutwashToFridge":                         "Outwash To Fridge",
    "OutwashToGrass":                          "Outwash To Grass",
    "OutwashToGrassRoad":                      "Outwash To GrassRoad",
    "StockadeToAridNexus":                     "Stockade To AridNexus",
    "TundraExpressToWilhelm":                  "TundraExpress To EndOfTheLine",
    "VolcanoToAsh":                            "VaultOfTheWarrior To EridiumBlight",
    "WilhelmToTundraExpress":                  "EndOfTheLine To TundraExpress",
    "CavernsToSanctuaryHole":                  "CausticCaverns To SanctuaryHole",
    "CoveToWaterfront":                        "Cove To Waterfront",
    "DamToDamTop":                             "BloodshotStronghold To Ramparts",
    "DamToIce":                                "BloodshotStronghold To ThreeHornsDivide",
    "DamTopToDam":                             "Ramparts To BloodshotStronghold",
    "DamTopToInterlude":                       "Ramparts To Dust",
    "GlacialToWaterfront":                     "Glacial To Waterfront",
    "IceCanyonToIce":                          "FrostburnCanyon To ThreeHornsDivide",
    "IceToDam":                                "ThreeHornsDivide To Dam",
    "IceToFridge":                             "ThreeHornsDivide To Fridge",
    "IceToIceCanyon":                          "ThreeHornsDivide To FrostburnCanyon",
    "IceToInterlude":                          "ThreeHornsDivide To Dust",
    "IceToSanctuary":                          "ThreeHornsDivide To Sanctuary",
    "IceToSanctuaryHole":                      "ThreeHornsDivide To SanctuaryHole",
    "IceToSouthpawFactory":                    "ThreeHornsDivide To SouthpawFactory",
    "IceToTundraExpress":                      "ThreeHornsDivide To TundraExpress",
    "IceToWaterfront":                         "ThreeHornsDivide To Waterfront",
    "SanctuaryHoleToCaverns":                  "SanctuaryHole To CausticCaverns",
    "SanctuaryHoleToIce":                      "SanctuaryHole To ThreeHornsDivide",
    "SanctuaryToIce":                          "Sanctuary To ThreeHornsDivide",
    "SanctuaryToVOGsChamber":                  "Sanctuary To ControlCoreAngel",
    "SouthpawFactoryToIce":                    "SouthpawFactory To ThreeHornsDivide",
    "TundraExpressToIce":                      "TundraExpress To ThreeHornsDivide",
    "WaterfrontDocksToIce":                    "WaterfrontDocks To ThreeHornsDivide",
    "WaterfrontToCove":                        "Waterfront To Cove",
    "WaterfrontToGlacial":                     "Waterfront To Glacial",
    "WaterfrontToIce":                         "Waterfront To ThreeHornsDivide",
    "BanditSlaughterToFridge":                 "BanditSlaughter To Fridge",
    "BossCliffsToCliffs":                      "Bunker To ThousandCuts",
    "BossCliffsToVOGsChamber":                 "Bunker To ControlCoreAngel",
    "CliffsToBossCliffs":                      "ThousandCuts To Bunker",
    "CliffsToGrass":                           "ThousandCuts To Highlands",
    "CliffsToThresherRaid":                    "ThousandCuts To ThresherRaid",
    "CreatureSlaughterToPandoraPark":          "CreatureSlaughter To WildlifePreserve",
    "FridgeToBanditSlaughter":                 "Fridge To BanditSlaughter",
    "FridgeToGrass":                           "Fridge To Highlands",
    "FridgeToIce":                             "Fridge To ThreeHornsDivide",
    "GrassToCliffs":                           "Highlands To ThousandCuts",
    "GrassToFridge":                           "Highlands To Fridge",
    "GrassToHyperionCity":                     "Highlands To Opportunity",
    "GrassToInterlude":                        "Highlands To Dust",
    "GrassToLuckys":                           "Highlands To HolySpirits",
    "GrassToPandoraPark":                      "Highlands To WildlifePreserve",
    "HyperionCityToGrass":                     "Opportunity To Highlands",
    "LuckysToGrass":                           "HolySpirits To Highlands",
    "PandoraParkToCreatureSlaughter":          "WildlifePreserve To CreatureSlaughter",
    "PandoraParkToGrass":                      "WildlifePreserve To Highlands",
    "ThresherRaidToCliffs":                    "ThresherRaid To ThousandCuts",
    "VOGsChamberToBossCliffs":                 "ControlCoreAngel To Bunker",
    "VOGsChamberToSanctuary":                  "ControlCoreAngel To Sanctuary",
    "AshToCraterLake":                         "EridiumBlight To CraterLake",
    "AshToFinalBossAscent":                    "EridiumBlight To HerosPass",
    "AshToFyrestone":                          "EridiumBlight To AridNexusBoneyard",
    "AshToInterlude":                          "EridiumBlight To Dust",
    "AshToRobotSlaughter":                     "EridiumBlight To RobotSlaughter",
    "CraterLakeToAsh":                         "CraterLake To EridiumBlight",
    "FinalBossAscentToAsh":                    "HerosPass To EridiumBlight",
    "FinalBossAscentToVolcano":                "HerosPass To VaultOfTheWarrior",
    "FyrestoneToAsh":                          "AridNexusBoneyard To EridiumBlight",
    "RobotSlaughterToAsh":                     "RobotSlaughter To EridiumBlight",
    "VolcanoToFinalBossAscent":                "VaultOfTheWarrior To HerosPass",
    "CavesToOasisTown":                        "HaytorsFolly To Oasis",
    "OasisTownToCaves":                        "Oasis To HaytorsFolly",
    "OasisTownToSaltFlats":                    "Oasis To Wurmwater",
    "OasisTownToSpire":                        "Oasis To MagnysLighthouse",
    "OasisTownToWormBelly":                    "Oasis To LeviathansLair",
    "RefineryToSaltFlats":                     "WashburnRefinery To Wurmwater",
    "SaltFlatsToOasisTown":                    "Wurmwater To Oasis",
    "SaltFlatsToRefinery":                     "Wurmwater To WashburnRefinery",
    "SaltFlatsToShipGraveyard":                "Wurmwater To Rustyards",
    "SaltFlatsToSpire":                        "Wurmwater To MagnysLighthouse",
    "SaltFlatsToWormBelly":                    "Wurmwater To LeviathansLair",
    "ShipGraveyardToSaltFlats":                "Rustyards To Wurmwater",
    "SpireToOasisTown":                        "MagnysLighthouse To Oasis",
    "SpireToSaltFlats":                        "MagnysLighthouse To Wurmwater",
    "WormBellyToOasisTown":                    "LeviathansLair To Oasis",
    "WormBellyToSaltFlats":                    "LeviathansLair To Wurmwater",
    "CliffsToUnderground":                     "CandlerakksCragg To HuntersGrotto",
    "PowerStationToUnderground":               "PowerStation To HuntersGrotto",
    "Sage_Travel_CliffsToShip":                "CandlerakksCragg To Terminus",
    "Sage_Travel_CliffsToUnderground":         "CandlerakksCragg To HuntersGrotto",
    "Sage_Travel_PowerStationToRockForest":    "PowerStation To ScyllasGrove",
    "Sage_Travel_PowerStationToUnderground":   "PowerStation To HuntersGrotto",
    "Sage_Travel_RockForestToPowerStation":    "ScyllasGrove To PowerStation",
    "Sage_Travel_RockForestToUnderground":     "ScyllasGrove To HuntersGrotto",
    "Sage_Travel_RockForestToVillage":         "ScyllasGrove To Village",
    "Sage_Travel_ShipToCliffs":                "Terminus To CandlerakksCragg",
    "Sage_Travel_UndergroundToCliffs":         "HuntersGrotto To CandlerakksCragg",
    "Sage_Travel_UndergroundToPowerStation":   "HuntersGrotto To PowerStation",
    "Sage_Travel_UndergroundToRockForest":     "HuntersGrotto To ScyllasGrove",
}

fast_travel_name_to_region = {
    # FastTravelStationDefinition
    "Hunger":                        "Glutton Gulch",
    "Xmas":                          "Marcus's Mercenary Shop",
    "BackburnerIntro":               "The Backburner",
    "BackBurner":                    "The Backburner",
    "Helios":                        "Helios Fallen",
    "OldDust":                       "Dahl Abandon",
    "ResearchCenter":                "Mt. Scarab Research Center",
    "Helios_OneWay":                 "Helios Fallen",
    "ResearchCenter_OneWay":         "Mt. Scarab Research Center",
    "SanctuaryIntro":                "FFS Intro Sanctuary",
    "Sandworm_OneWay":               "The Burrows",
    "CastleExterior":                "Hatred's Shadow",
    "CastleKeep":                    "Dragon Keep",
    "DarkForest":                    "The Forest",
    "DeadForest":                    "Immortal Woods",
    "Docks":                         "Unassuming Docks",
    "Dungeons":                      "Lair of Infinite Agony",
    "Mines":                         "Mines of Avarice",
    "Village":                       "Flamerock Refuge",
    "FyrestoneOneWay":               "Arid Nexus Badlands",
    "Interlude":                     "The Dust",
    "Lynchwood":                     "Lynchwood",
    "Outwash":                       "Highlands Outwash",
    "Sanctuary":                     "Sanctuary",
    "Wilhelm":                       "End of the Line",
    "Caverns":                       "Caustic Caverns",
    "DamTop":                        "Bloodshot Ramparts",
    "Glacial":                       "Windshear Waste",
    "GlacialIgloo":                  "Windshear Waste",
    "GoshDam":                       "Bloodshot Stronghold",
    "IceCanyon":                     "Frostburn Canyon",
    "IceEast":                       "Three Horns Divide",
    "IceWest":                       "Three Horns Divide",
    "SouthernShelfTown":             "Southern Shelf",
    "SouthpawFactory":               "Southpaw Steam & Power",
    "TundraExpress":                 "Tundra Express",
    "TundraExpressSecret":           "Tundra Express",
    "TundraTrain":                   "End of the Line",
    "Cliffs":                        "Thousand Cuts",
    "Cliffs_Boss":                   "The Bunker",
    "Grass_A":                       "Highlands",
    "Grass_B":                       "Highlands",
    "Grass_C":                       "Highlands",
    "HyperionCity":                  "Opportunity",
    "PandoraPark":                   "Wildlife Exploitation Preserve",
    "TheFridge":                     "The Fridge",
    "Ash":                           "Eridium Blight",
    "CraterLake":                    "Sawtooth Cauldron",
    "FinalBossAscent":               "Hero's Pass",
    "OnFireStone":                   "Arid Nexus Boneyard", # ???
    "Volcano_Boss_A":                "Vault of the Warrior",
    "Volcano_Boss_B":                "Vault of the Warrior",
    "PumpkinPatch":                  "Hallowed Hollow",
    "BadassBar":                     "Baddass Crater Bar",
    "Beatdown":                      "The Beatdown",
    "Forge":                         "The Forge",
    "IrisCrater":                    "Badass Crater",
    "SouthernRaceway":               "Southern Raceway",
    "TestingZone":                   "Digistruct Peak",
    "EasterTravel":                  "Wam Bam Island",
    "Vday":                          "Rotgut Distillery",
    "Caves":                         "Haytor's Folly",
    "OasisTown":                     "Oasis",
    "Refinary":                      "Washburn Refinery",
    "SaltFlats":                     "Wurmwater",
    "ShipGraveyard":                 "The Rustyards",
    "Spire":                         "Magnys Lighthouse",
    "TopOfSpire":                    "Magnys Lighthouse",
    "HyperionShip":                  "Terminus",
    "PowerStation":                  "Adorton Station",
    "RockForest":                    "Scylla's Grove",
    "SageCliffs":                    "Candlerakk's Cragg",
    "Underground":                   "Hunter's Grotto",
    "Underground_Lodge":             "Hunter's Grotto",
    # "Cliffs":                      "Candlerakk's Cragg", # wtf
}