
gear_kind_to_item_pool = {
    "Common Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_01_Common',
    "Uncommon Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_02_Uncommon',
    "Rare Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_04_Rare',
    "VeryRare Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_05_VeryRare',
    "E-Tech Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_05_VeryRare_Alien',
    "Legendary Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_06_Legendary',

    "Common Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_01_Common',
    "Uncommon Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_02_Uncommon',
    "Rare Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_04_Rare',
    "VeryRare Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_05_VeryRare',
    "E-Tech Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_05_VeryRare_Alien',
    "Legendary Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_06_Legendary',

    "Common SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_01_Common',
    "Uncommon SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_02_Uncommon',
    "Rare SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_04_Rare',
    "VeryRare SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_05_VeryRare',
    "E-Tech SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_05_VeryRare_Alien',
    "Legendary SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_06_Legendary',

    "Common SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_01_Common',
    "Uncommon SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_02_Uncommon',
    "Rare SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_04_Rare',
    "VeryRare SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_05_VeryRare',
    "E-Tech SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_05_VeryRare_Alien',
    "Legendary SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_06_Legendary',

    "Common AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_01_Common',
    "Uncommon AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_02_Uncommon',
    "Rare AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_04_Rare',
    "VeryRare AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_05_VeryRare',
    "E-Tech AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_05_VeryRare_Alien',
    "Legendary AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_06_Legendary',

    "Common RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_01_Common',
    "Uncommon RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_02_Uncommon',
    "Rare RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_04_Rare',
    "VeryRare RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_05_VeryRare',
    "E-Tech RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_05_VeryRare_Alien',
    "Legendary RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_06_Legendary',
}

vault_symbol_id_to_name = {
    "WillowInteractiveObject'SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol Sanctuary 0",
    "WillowInteractiveObject'SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol Sanctuary 1",
    "WillowInteractiveObject'SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_2'": "Symbol Sanctuary 2",
    "WillowInteractiveObject'SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_263'": "Symbol Sanctuary 263",
    "WillowInteractiveObject'SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_98'": "Symbol Sanctuary 98",

    "WillowInteractiveObject'Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol Sanctuary 0",
    "WillowInteractiveObject'Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol Sanctuary 1",
    "WillowInteractiveObject'Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_2'": "Symbol Sanctuary 2",
    "WillowInteractiveObject'Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_263'": "Symbol Sanctuary 263",
    "WillowInteractiveObject'Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_98'": "Symbol Sanctuary 98",

    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol Ash 1",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_181'": "Symbol Ash 181",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_3'": "Symbol Ash 3",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_518'": "Symbol Ash 518",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_519'": "Symbol Ash 519",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_520'": "Symbol Ash 520",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_521'": "Symbol Ash 521",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_522'": "Symbol Ash 522",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_523'": "Symbol Ash 523",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_524'": "Symbol Ash 524",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_525'": "Symbol Ash 525",
    "WillowInteractiveObject'Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_526'": "Symbol Ash 526",

    "WillowInteractiveObject'BanditSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_29'": "Symbol BanditSlaughter 29",
    "WillowInteractiveObject'Boss_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol Boss_Cliffs 0",
    "WillowInteractiveObject'Boss_Volcano_P.TheWorld:PersistentLevel.WillowInteractiveObject_181'": "Symbol Boss_Volcano 181",
    "WillowInteractiveObject'Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_180'": "Symbol Cove 180",
    "WillowInteractiveObject'Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_235'": "Symbol Cove 235",
    "WillowInteractiveObject'CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_27'": "Symbol CraterLake 27",
    "WillowInteractiveObject'CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_7'": "Symbol CraterLake 7",
    "WillowInteractiveObject'CreatureSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol CreatureSlaughter 0",
    "WillowInteractiveObject'FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol FinalBossAscent 0",
    "WillowInteractiveObject'FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_6'": "Symbol FinalBossAscent 6",
    "WillowInteractiveObject'Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_89'": "Symbol Fridge 89",
    "WillowInteractiveObject'Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_90'": "Symbol Fridge 90",
    "WillowInteractiveObject'Frost_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5'": "Symbol Frost_Dynam 5",
    "WillowInteractiveObject'Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_31'": "Symbol Frost 31",
    "WillowInteractiveObject'Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_5'": "Symbol Frost 5",
    "WillowInteractiveObject'Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol Fyrestone 0",
    "WillowInteractiveObject'Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_3'": "Symbol Fyrestone 3",
    "WillowInteractiveObject'Glacial_P.TheWorld:PersistentLevel.WillowInteractiveObject_214'": "Symbol Glacial 214",
    "WillowInteractiveObject'Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_174'": "Symbol Grass_Cliffs 174",
    "WillowInteractiveObject'Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_302'": "Symbol Grass_Cliffs 302",
    "WillowInteractiveObject'Grass_Lynchwood_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_145'": "Symbol Grass_Lynchwood_Dynam 145",
    "WillowInteractiveObject'Grass_Lynchwood_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_146'": "Symbol Grass_Lynchwood_Dynam 146",
    "WillowInteractiveObject'Grass_Lynchwood_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_147'": "Symbol Grass_Lynchwood_Dynam 147",
    "WillowInteractiveObject'Grass_Lynchwood_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_148'": "Symbol Grass_Lynchwood_Dynam 148",
    "WillowInteractiveObject'Grass_Lynchwood_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_2'": "Symbol Grass_Lynchwood_Dynam 2",
    "WillowInteractiveObject'Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_298'": "Symbol Grass_Lynchwood 298",
    "WillowInteractiveObject'Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_601'": "Symbol Grass_Lynchwood 601",
    "WillowInteractiveObject'Grass_P.TheWorld:PersistentLevel.WillowInteractiveObject_346'": "Symbol Grass 346",
    "WillowInteractiveObject'HypInterlude_P.TheWorld:PersistentLevel.WillowInteractiveObject_12'": "Symbol HypInterlude 12",
    "WillowInteractiveObject'HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_180'": "Symbol HyperionCity 180",
    "WillowInteractiveObject'HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_181'": "Symbol HyperionCity 181",
    "WillowInteractiveObject'Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_238'": "Symbol Ice 238",
    "WillowInteractiveObject'Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_5'": "Symbol Ice 5",
    "WillowInteractiveObject'Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_79'": "Symbol Ice 79",
    "WillowInteractiveObject'Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_26'": "Symbol Interlude_Dynam 26",
    "WillowInteractiveObject'caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_641'": "Symbol caverns 641",
    "WillowInteractiveObject'caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_89'": "Symbol caverns 89",
    "WillowInteractiveObject'dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_137'": "Symbol dam 137",
    "WillowInteractiveObject'dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_138'": "Symbol dam 138",
    "WillowInteractiveObject'damtop_p.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol damtop 0",
    "WillowInteractiveObject'icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_51'": "Symbol icecanyon 51",
    "WillowInteractiveObject'icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_53'": "Symbol icecanyon 53",
    "WillowInteractiveObject'Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_4'": "Symbol Interlude_Dynam 4",
    "WillowInteractiveObject'Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5'": "Symbol Interlude_Dynam 5",
    "WillowInteractiveObject'Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678'": "Symbol Iris_DL1_Dynam 678",
    "WillowInteractiveObject'Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_772'": "Symbol Iris_DL1_Dynam 772",
    "WillowInteractiveObject'Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425'": "Symbol Iris_DL2_Dynam 425",
    "WillowInteractiveObject'Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_79'": "Symbol Iris_DL2_Dynam 79",
    "WillowInteractiveObject'Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_214'": "Symbol Iris_DL3_Dynam 214",
    "WillowInteractiveObject'Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425'": "Symbol Iris_DL3_Dynam 425",
    "WillowInteractiveObject'Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_61'": "Symbol Iris_DL3_Dynam 61",
    "WillowInteractiveObject'Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_6'": "Symbol Iris_Hub2 6",
    "WillowInteractiveObject'Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_9'": "Symbol Iris_Hub2 9",
    "WillowInteractiveObject'Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_11'": "Symbol Iris_Hub_Dynam 11",
    "WillowInteractiveObject'Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_12'": "Symbol Iris_Hub_Dynam 12",
    "WillowInteractiveObject'Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678'": "Symbol Iris_Hub_Dynam 678",
    "WillowInteractiveObject'Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_78'": "Symbol Iris_Hub_Dynam 78",
    "WillowInteractiveObject'Luckys_P.TheWorld:PersistentLevel.WillowInteractiveObject_16'": "Symbol Luckys 16",
    "WillowInteractiveObject'ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_347'": "Symbol ORCHID_CAVES_DYNAM 347",
    "WillowInteractiveObject'ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_461'": "Symbol ORCHID_CAVES_DYNAM 461",
    "WillowInteractiveObject'Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347'": "Symbol Orchid_OasisTown_Dynam 347",
    "WillowInteractiveObject'Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_348'": "Symbol Orchid_OasisTown_Dynam 348",
    "WillowInteractiveObject'Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_349'": "Symbol Orchid_OasisTown_Dynam 349",
    "WillowInteractiveObject'Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_367'": "Symbol Orchid_OasisTown_Dynam 367",
    "WillowInteractiveObject'Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_496'": "Symbol Orchid_Refinery_Dynam 496",
    "WillowInteractiveObject'Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_497'": "Symbol Orchid_Refinery_Dynam 497",
    "WillowInteractiveObject'Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347'": "Symbol Orchid_SaltFlats_Dynam 347",
    "WillowInteractiveObject'Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_400'": "Symbol Orchid_SaltFlats_Dynam 400",
    "WillowInteractiveObject'Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_401'": "Symbol Orchid_SaltFlats_Dynam 401",
    "WillowInteractiveObject'Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_22'": "Symbol Orchid_ShipGraveyard 22",
    "WillowInteractiveObject'Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_23'": "Symbol Orchid_ShipGraveyard 23",
    "WillowInteractiveObject'Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10'": "Symbol Orchid_Spire_Dynam 10",
    "WillowInteractiveObject'Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_22'": "Symbol Orchid_Spire_Dynam 22",
    "WillowInteractiveObject'Orchid_WormBelly_P.TheWorld:PersistentLevel.WillowInteractiveObject_497'": "Symbol Orchid_WormBelly 497",
    "WillowInteractiveObject'PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_273'": "Symbol PandoraPark 273",
    "WillowInteractiveObject'PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_274'": "Symbol PandoraPark 274",
    "WillowInteractiveObject'RobotSlaughter_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_15'": "Symbol RobotSlaughter_Dynam 15",
    "WillowInteractiveObject'Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_129'": "Symbol Sage_Cliffs_Dynam 129",
    "WillowInteractiveObject'Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71'": "Symbol Sage_Cliffs_Dynam 71",
    "WillowInteractiveObject'Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_84'": "Symbol Sage_Cliffs_Dynam 84",
    "WillowInteractiveObject'Sage_HyperionShip_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol Sage_HyperionShip 0",
    "WillowInteractiveObject'Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_29'": "Symbol Sage_PowerStation 29",
    "WillowInteractiveObject'Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_5'": "Symbol Sage_PowerStation 5",
    "WillowInteractiveObject'Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_6'": "Symbol Sage_PowerStation 6",
    "WillowInteractiveObject'Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_7'": "Symbol Sage_PowerStation 7",
    "WillowInteractiveObject'Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10'": "Symbol Sage_RockForest_Dynam 10",
    "WillowInteractiveObject'Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_6'": "Symbol Sage_RockForest_Dynam 6",
    "WillowInteractiveObject'Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_8'": "Symbol Sage_RockForest_Dynam 8",
    "WillowInteractiveObject'Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_9'": "Symbol Sage_RockForest_Dynam 9",
    "WillowInteractiveObject'Sanctuary_Hole_P.TheWorld:PersistentLevel.WillowInteractiveObject_6'": "Symbol Sanctuary_Hole 6",
    "WillowInteractiveObject'SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_181'": "Symbol SouthernShelf 181",
    "WillowInteractiveObject'SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_397'": "Symbol SouthernShelf 397",
    "WillowInteractiveObject'SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_398'": "Symbol SouthpawFactory_Dynam 398",
    "WillowInteractiveObject'SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_399'": "Symbol SouthpawFactory_Dynam 399",
    "WillowInteractiveObject'SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_46'": "Symbol SouthpawFactory_Dynam 46",
    "WillowInteractiveObject'ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_116'": "Symbol ThresherRaid 116",
    "WillowInteractiveObject'ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_364'": "Symbol ThresherRaid 364",
    "WillowInteractiveObject'TundraTrain_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol TundraTrain 0",
    "WillowInteractiveObject'tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_206'": "Symbol tundraexpress 206",
    "WillowInteractiveObject'tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_207'": "Symbol tundraexpress 207",
    "WillowInteractiveObject'BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_2'": "Symbol BackBurnerInteracti 2",
    "WillowInteractiveObject'BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_3'": "Symbol BackBurnerInteracti 3",
    "WillowInteractiveObject'CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol CastleExterior 0",
    "WillowInteractiveObject'CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol CastleExterior 1",
    "WillowInteractiveObject'CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_4'": "Symbol CastleExterior 4",
    "WillowInteractiveObject'CastleKeep_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol CastleKeep_Dynam 0",
    "WillowInteractiveObject'Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol Dark_Forest_Dynam 0",
    "WillowInteractiveObject'Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol Dark_Forest_Dynam 1",
    "WillowInteractiveObject'Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol Dead_Forest_Dynam 1",
    "WillowInteractiveObject'Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_19'": "Symbol Dead_Forest_Dynam 19",
    "WillowInteractiveObject'Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_20'": "Symbol Dead_Forest_Dynam 20",
    "WillowInteractiveObject'Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol Docks 0",
    "WillowInteractiveObject'Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol Docks 1",
    "WillowInteractiveObject'Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_2'": "Symbol Docks 2",
    "WillowInteractiveObject'DungeonRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_0'": "Symbol DungeonRaid 0",
    "WillowInteractiveObject'Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_307'": "Symbol Dungeon 307",
    "WillowInteractiveObject'Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_308'": "Symbol Dungeon 308",
    "WillowInteractiveObject'Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_90'": "Symbol Dungeon 90",
    "WillowInteractiveObject'Helios_Floor1.TheWorld:PersistentLevel.WillowInteractiveObject_11'": "Symbol Helios_Floo 11",
    "WillowInteractiveObject'Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_388'": "Symbol Helios_Interacti 388",
    "WillowInteractiveObject'Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_446'": "Symbol Helios_Interacti 446",
    "WillowInteractiveObject'Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_447'": "Symbol Helios_Interacti 447",
    "WillowInteractiveObject'Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_859'": "Symbol Helios_Interacti 859",
    "WillowInteractiveObject'Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_892'": "Symbol Helios_Interacti 892",
    "WillowInteractiveObject'Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_894'": "Symbol Helios_Interacti 894",
    "WillowInteractiveObject'Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol Mines_Dynam 1",
    "WillowInteractiveObject'Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_16'": "Symbol Mines_Dynam 16",
    "WillowInteractiveObject'Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_47'": "Symbol Mines_Dynam 47",
    "WillowInteractiveObject'OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_187'": "Symbol OldDust_Interacti 187",
    "WillowInteractiveObject'OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_269'": "Symbol OldDust_Interacti 269",
    "WillowInteractiveObject'OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_36'": "Symbol OldDust_Interacti 36",
    "WillowInteractiveObject'OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_59'": "Symbol OldDust_Interacti 59",
    "WillowInteractiveObject'OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_84'": "Symbol OldDust_Interacti 84",
    "WillowInteractiveObject'ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_164'": "Symbol ResearchCenter_Interacti 164",
    "WillowInteractiveObject'ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_167'": "Symbol ResearchCenter_Interacti 167",
    "WillowInteractiveObject'ResearchCenter_Research.TheWorld:PersistentLevel.WillowInteractiveObject_737'": "Symbol ResearchCenter_Resear 737",
    "WillowInteractiveObject'Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_68'": "Symbol Sage_Underground_Dynam 68",
    "WillowInteractiveObject'Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_69'": "Symbol Sage_Underground_Dynam 69",
    "WillowInteractiveObject'Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_70'": "Symbol Sage_Underground_Dynam 70",
    "WillowInteractiveObject'Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71'": "Symbol Sage_Underground_Dynam 71",
    "WillowInteractiveObject'SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1161'": "Symbol SandwormLair_ 1161",
    "WillowInteractiveObject'SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1162'": "Symbol SandwormLair_ 1162",
    "WillowInteractiveObject'SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1163'": "Symbol SandwormLair_ 1163",
    "WillowInteractiveObject'Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_46'": "Symbol Sandworm_Interacti 46",
    "WillowInteractiveObject'Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_60'": "Symbol Sandworm_Interacti 60",
    "WillowInteractiveObject'TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_1'": "Symbol TempleSlaughter_Comb 1",
    "WillowInteractiveObject'TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_3'": "Symbol TempleSlaughter_Comb 3",
    "WillowInteractiveObject'Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_206'": "Symbol Village_Dynam 206",
    "WillowInteractiveObject'Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_383'": "Symbol Village_Dynam 383",
}