
gear_kind_to_item_pool = {
    "Common Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_01_Common",
    "Uncommon Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_02_Uncommon",
    "Rare Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_04_Rare",
    "VeryRare Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_05_VeryRare",
    "Legendary Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_06_Legendary", # doesn't always spawn a legendary shield. see Roguelands/Looties.py

    "Common GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_01_Common",
    "Uncommon GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_02_Uncommon",
    "Rare GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_04_Rare",
    "VeryRare GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_05_VeryRare",
    "Legendary GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_06_Legendary",

    "Common ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_01_Common",
    "Uncommon ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_02_Uncommon",
    "Rare ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_04_Rare",
    "VeryRare ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_05_VeryRare",
    "Legendary ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_06_Legendary",
    
    "Common Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_01_Common",
    # "Uncommon Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_02_Uncommon", # this is actually just white relics
    "Rare Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_03_Rare", 
    # "VeryRare Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_04_VeryRare", # this is actually just blue relics
    # "Legendary Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_05_Legendary", # this is also actually just blue relics

    "Common Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_01_Common',
    "Uncommon Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_02_Uncommon',
    "Rare Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_04_Rare',
    "VeryRare Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_05_VeryRare',
    "E-Tech Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_05_VeryRare_Alien',
    "Legendary Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_06_Legendary',

    "Common Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_01_Common',
    "Uncommon Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_02_Uncommon',
    "Rare Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_04_Rare',
    "VeryRare Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_05_VeryRare',
    "E-Tech Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_05_VeryRare_Alien',
    "Legendary Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_06_Legendary',

    "Common SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_01_Common',
    "Uncommon SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_02_Uncommon',
    "Rare SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_04_Rare',
    "VeryRare SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_05_VeryRare',
    "E-Tech SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_05_VeryRare_Alien',
    "Legendary SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_06_Legendary',

    "Common SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_01_Common',
    "Uncommon SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_02_Uncommon',
    "Rare SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_04_Rare',
    "VeryRare SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_05_VeryRare',
    "E-Tech SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_05_VeryRare_Alien',
    "Legendary SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_06_Legendary',

    "Common AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_01_Common',
    "Uncommon AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_02_Uncommon',
    "Rare AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_04_Rare',
    "VeryRare AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_05_VeryRare',
    "E-Tech AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_05_VeryRare_Alien',
    "Legendary AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_06_Legendary',

    "Common RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_01_Common',
    "Uncommon RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_02_Uncommon',
    "Rare RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_04_Rare',
    "VeryRare RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_05_VeryRare',
    "E-Tech RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_05_VeryRare_Alien',
    "Legendary RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_06_Legendary',
}

vault_symbol_pathname_to_name = {
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":               "Symbol Sanctuary: Rooftop",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":               "Symbol Sanctuary: Moxxi's Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":               "Symbol Sanctuary: Trash Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_263":             "Symbol Sanctuary: Tire Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_98":              "Symbol Sanctuary: Parkour Door",

    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                  "Symbol Sanctuary: Rooftop",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                  "Symbol Sanctuary: Moxxi's Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":                  "Symbol Sanctuary: Trash Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_263":                "Symbol Sanctuary: Tire Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_98":                 "Symbol Sanctuary: Parkour Door",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                        "Symbol EridiumBlight: Hellsfont Crate",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_3":                        "Symbol EridiumBlight: Stairs Door",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_518":                      "Symbol EridiumBlight: Refund Building",
    "BanditSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_29":           "Symbol Fink's: Column",
    "Boss_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol Bunker: Backside",
    "Boss_Volcano_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":             "Symbol WarriorVault: Elevator Bottom",
    "Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_180":                     "Symbol SouthernShelfBay: Blackburn Cove Corner",
    "Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_235":                     "Symbol SouthernShelfBay: Ice Flows Shipwreck",
    "CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_27":                "Symbol Sawtooth: Refinery Container",
    "CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_7":                 "Symbol Sawtooth: Elevator",
    "CreatureSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol CreatureSlaughter: Crate Ceiling",
    "FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":            "Symbol HerosPass: Strut",
    "FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":            "Symbol HerosPass: Spawn",
    "Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_89":                    "Symbol Fridge: Secret Stash",
    "Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_90":                    "Symbol Fridge: Sheetmetal Roof",
    "Frost_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5":                "Symbol ThreeHornsValley: Slums Wall",
    "Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_31":                     "Symbol ThreeHornsValley: Frostsprings Wall",
    "Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":                      "Symbol ThreeHornsValley: Frostsprings Shack",
    "Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                  "Symbol AridNexusBoneyard: Pipe",
    "Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_3":                  "Symbol AridNexusBoneyard: Safety",
    "Glacial_P.TheWorld:PersistentLevel.WillowInteractiveObject_214":                  "Symbol WindshearWaste: Claptrap's Closet",
    "Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_174":             "Symbol ThousandCuts: Buzzard Factory",
    "Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_302":             "Symbol ThousandCuts: No Man's Land Shack",
    "Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_298":          "Symbol Lynchwood: Gunslinger Roof",
    "Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_601":          "Symbol Lynchwood: Main Street",
    "Grass_P.TheWorld:PersistentLevel.WillowInteractiveObject_346":                    "Symbol Highlands: Highlands Tower",
    "HypInterlude_P.TheWorld:PersistentLevel.WillowInteractiveObject_12":              "Symbol FriendshipGulag: Gulag Container",
    "HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_180":             "Symbol Opportunity: Construction Site",
    "HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":             "Symbol Opportunity: Office Bridge",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_238":                      "Symbol ThreeHornsDivide Drydocks Corner",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":                        "Symbol ThreeHornsDivide Billboard",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_79":                       "Symbol ThreeHornsDivide Windbreak Wall",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_26":           "Symbol Dust: 26",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_4":            "Symbol Dust: 4",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5":            "Symbol Dust: 5",
    "caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_641":                  "Symbol CausticCaverns: Gravestone Feature",
    "caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_89":                   "Symbol CausticCaverns: Bloody Ladder",
    "dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_137":                      "Symbol Blodshot: Pizza Intercom",
    "dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_138":                      "Symbol Blodshot: Switch Room",
    "damtop_p.TheWorld:PersistentLevel.WillowInteractiveObject_0":                     "Symbol BlodshotRamparts: Ramp",
    "icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_51":                 "Symbol Frostburn: Blisterpus Cave",
    "icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_53":                 "Symbol Frostburn: Ashmouth Pit",
    "Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678":           "Symbol TorgueArenaRing: 678",
    "Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_772":           "Symbol TorgueArenaRing: 772",
    "Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425":           "Symbol Beatdown: 425",
    "Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_79":            "Symbol Beatdown: 79",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_214":           "Symbol Forge: 214",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425":           "Symbol Forge: 425",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_61":            "Symbol Forge: 61",
    "Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":                  "Symbol SouthernRaceway: 6",
    "Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_9":                  "Symbol SouthernRaceway: 9",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_11":            "Symbol BadassCrater: 11",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_12":            "Symbol BadassCrater: 12",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678":           "Symbol BadassCrater: 678",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_78":            "Symbol BadassCrater: 78",
    "Luckys_P.TheWorld:PersistentLevel.WillowInteractiveObject_16":                    "Symbol HolySpirits: Bathroom",
    "ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_347":       "Symbol HaytorsFolly: 347",
    "ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_461":       "Symbol HaytorsFolly: 461",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347":   "Symbol Oasis: 347",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_348":   "Symbol Oasis: 348",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_349":   "Symbol Oasis: 349",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_367":   "Symbol Oasis: 367",
    "Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_496":    "Symbol WashburnRefinery: 496",
    "Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_497":    "Symbol WashburnRefinery: 497",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347":   "Symbol Wurmwater: 347",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_400":   "Symbol Wurmwater: 400",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_401":   "Symbol Wurmwater: 401",
    "Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_22":      "Symbol Rustyards: 22",
    "Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_23":      "Symbol Rustyards: 23",
    "Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10":        "Symbol MagnysLighthouse: 10",
    "Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_22":        "Symbol MagnysLighthouse: 22",
    "Orchid_WormBelly_P.TheWorld:PersistentLevel.WillowInteractiveObject_497":         "Symbol LeviathansLair: 497",
    "PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_273":              "Symbol WildlifePreserve: 273",
    "PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_274":              "Symbol WildlifePreserve: 274",
    "RobotSlaughter_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_15":      "Symbol OreChasm: Elevator",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_129":        "Symbol CandlerakksCragg: 129",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71":         "Symbol CandlerakksCragg: 71",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_84":         "Symbol CandlerakksCragg: 84",
    "Sage_HyperionShip_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol Terminus: 0",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_29":         "Symbol AdortonStation: 29",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":          "Symbol AdortonStation: 5",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":          "Symbol AdortonStation: 6",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_7":          "Symbol AdortonStation: 7",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10":     "Symbol ScyllasGrove: 10",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_6":      "Symbol ScyllasGrove: 6",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_8":      "Symbol ScyllasGrove: 8",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_9":      "Symbol ScyllasGrove: 9",
    "Sanctuary_Hole_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":             "Symbol SanctuaryHole: Staircase Wall",
    "SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":            "Symbol SouthernShelf: Flynt's Ship",
    "SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_397":            "Symbol SouthernShelf: Safehouse",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_398":    "Symbol Southpaw: 398",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_399":    "Symbol Southpaw: 399",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_46":     "Symbol Southpaw: 46",
    "ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_116":             "Symbol TerramorphousPeak: Dropdown",
    "ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_364":             "Symbol TerramorphousPeak: Elevator",
    "TundraTrain_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol EndOfTheLine: Wilhelm Wall",
    "tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_206":            "Symbol TundraExpress: Fork Shack",
    "tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_207":            "Symbol TundraExpress: Facility Roof",
    "BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_2":        "Symbol Backburner: 2",
    "BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_3":        "Symbol Backburner: 3",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":             "Symbol HatredsShadow: 0",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":             "Symbol HatredsShadow: 1",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_4":             "Symbol HatredsShadow: 4",
    "CastleKeep_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0":           "Symbol DragonKeep: 0",
    "Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol TheForest: 0",
    "Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":          "Symbol TheForest: 1",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":          "Symbol ImmortalWoods: 1",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_19":         "Symbol ImmortalWoods: 19",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_20":         "Symbol ImmortalWoods: 20",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                      "Symbol UnassumingDocks: 0",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                      "Symbol UnassumingDocks: 1",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":                      "Symbol UnassumingDocks: 2",
    "DungeonRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol WingedStorm: 0",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_307":                  "Symbol LairOfInfiniteAgony: 307",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_308":                  "Symbol LairOfInfiniteAgony: 308",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_90":                   "Symbol LairOfInfiniteAgony: 90",
    "Helios_Floor1.TheWorld:PersistentLevel.WillowInteractiveObject_11":               "Symbol HeliosFallen: 11",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_388":         "Symbol HeliosFallen: 388",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_446":         "Symbol HeliosFallen: 446",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_447":         "Symbol HeliosFallen: 447",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_859":         "Symbol HeliosFallen: 859",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_892":         "Symbol HeliosFallen: 892",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_894":         "Symbol HeliosFallen: 894",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":                "Symbol MinesOfAvarice: 1",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_16":               "Symbol MinesOfAvarice: 16",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_47":               "Symbol MinesOfAvarice: 47",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_187":        "Symbol DahlAbandon: 187",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_269":        "Symbol DahlAbandon: 269",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_36":         "Symbol DahlAbandon: 36",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_59":         "Symbol DahlAbandon: 59",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_84":         "Symbol DahlAbandon: 84",
    "ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_164": "Symbol MtScarab: 164",
    "ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_167": "Symbol MtScarab: 167",
    "ResearchCenter_Research.TheWorld:PersistentLevel.WillowInteractiveObject_737":    "Symbol MtScarab: 737",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_68":    "Symbol HuntersGrotto: 68",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_69":    "Symbol HuntersGrotto: 69",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_70":    "Symbol HuntersGrotto: 70",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71":    "Symbol HuntersGrotto: 71",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1161":           "Symbol WrithingDeep: 1161",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1162":           "Symbol WrithingDeep: 1162",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1163":           "Symbol WrithingDeep: 1163",
    "Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_46":        "Symbol TheBurrows: 46",
    "Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_60":        "Symbol TheBurrows: 60",
    "TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_1":       "Symbol MurderlinsTemple: 1",
    "TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_3":       "Symbol MurderlinsTemple: 3",
    "Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_206":            "Symbol FlamerockRefuge: 206",
    "Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_383":            "Symbol FlamerockRefuge: 383",
}

vending_machine_position_to_name = {
    "Level'Sanctuary_P.TheWorld:PersistentLevel'~11617.849609375,1242.7235107421875":   "Vending Sanctuary Crimson Base: Guns",
    "Level'Sanctuary_P.TheWorld:PersistentLevel'~11584.849609375,1403.7235107421875":   "Vending Sanctuary Crimson Base: Ammo Dump",
    "Level'Sanctuary_P.TheWorld:PersistentLevel'~8434.1513671875,-3526.410888671875":   "Vending Sanctuary Zed's: Ammo Dump",
    "Level'Sanctuary_P.TheWorld:PersistentLevel'~8387.515625,-4248.31298828125":        "Vending Sanctuary Zed's: Zed's Meds 1",
    "Level'Sanctuary_P.TheWorld:PersistentLevel'~9265.2314453125,-4415.875":            "Vending Sanctuary Zed's: Zed's Meds 2",
    "Level'Sanctuary_P.TheWorld:PersistentLevel'~10569.51171875,6224.16650390625":      "Vending Sanctuary Marcus's: Zed's Meds",
    "Level'Sanctuary_P.TheWorld:PersistentLevel'~11207.767578125,8562.2412109375":      "Vending Sanctuary Marcus's: Ammo Dump",
    "Level'Sanctuary_P.TheWorld:PersistentLevel'~11430.767578125,8505.240234375":       "Vending Sanctuary Marcus's: Marcus",

    "Level'SanctuaryAir_P.TheWorld:PersistentLevel'~11624.849609375,1267.7235107421875":   "Vending Sanctuary Crimson Base: Guns",
    "Level'SanctuaryAir_P.TheWorld:PersistentLevel'~11599.849609375,1407.7235107421875":   "Vending Sanctuary Crimson Base: Ammo Dump",
    "Level'SanctuaryAir_P.TheWorld:PersistentLevel'~8434.1513671875,-3526.410888671875":   "Vending Sanctuary Zed's: Ammo Dump",
    "Level'SanctuaryAir_P.TheWorld:PersistentLevel'~8387.515625,-4248.31298828125":        "Vending Sanctuary Zed's: Zed's Meds 1",
    "Level'SanctuaryAir_P.TheWorld:PersistentLevel'~9265.2314453125,-4415.875":            "Vending Sanctuary Zed's: Zed's Meds 2",
    "Level'SanctuaryAir_P.TheWorld:PersistentLevel'~10569.51171875,6224.16650390625":      "Vending Sanctuary Marcus's: Zed's Meds",
    "Level'SanctuaryAir_P.TheWorld:PersistentLevel'~11207.767578125,8546.2412109375":      "Vending Sanctuary Marcus's: Ammo Dump",
    "Level'SanctuaryAir_P.TheWorld:PersistentLevel'~11382.767578125,8937.240234375":       "Vending Sanctuary Marcus's: Marcus",
    "Level'HypInterlude_P.TheWorld:PersistentLevel'~30186.212890625,33162.26953125":       "Vending FriendshipGulag: Zed's Meds",
    "Level'HypInterlude_P.TheWorld:PersistentLevel'~30186.212890625,33347.77734375":       "Vending FriendshipGulag: Ammo Dump",
    "Level'Interlude_P.TheWorld:PersistentLevel'~-26727.54296875,32659.150390625":         "Vending Dust: Zed's Meds",
    "Level'Interlude_P.TheWorld:PersistentLevel'~-26727.833984375,32512.521484375":        "Vending Dust: Ammo Dump",
}