
gear_kind_to_item_pool = {
    "Common Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_01_Common",
    "Uncommon Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_02_Uncommon",
    "Rare Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_04_Rare",
    "VeryRare Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_05_VeryRare",
    "Legendary Shield": "GD_Itempools.ShieldPools.Pool_Shields_All_06_Legendary", # doesn't always spawn a legendary shield. see Roguelands/Looties.py

    "Common GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_01_Common",
    "Uncommon GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_02_Uncommon",
    "Rare GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_04_Rare",
    "VeryRare GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_05_VeryRare",
    "Legendary GrenadeMod": "GD_Itempools.GrenadeModPools.Pool_GrenadeMods_06_Legendary",

    "Common ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_01_Common",
    "Uncommon ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_02_Uncommon",
    "Rare ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_04_Rare",
    "VeryRare ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_05_VeryRare",
    "Legendary ClassMod": "GD_Itempools.ClassModPools.Pool_ClassMod_06_Legendary",
    
    "Common Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_01_Common",
    # "Uncommon Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_02_Uncommon", # this is actually just white relics
    "Rare Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_03_Rare", 
    # "VeryRare Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_04_VeryRare", # this is actually just blue relics
    # "Legendary Relic": "GD_Itempools.ArtifactPools.Pool_Artifacts_05_Legendary", # this is also actually just blue relics

    "Common Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_01_Common',
    "Uncommon Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_02_Uncommon',
    "Rare Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_04_Rare',
    "VeryRare Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_05_VeryRare',
    "E-Tech Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_05_VeryRare_Alien',
    "Legendary Pistol": 'GD_Itempools.WeaponPools.Pool_Weapons_Pistols_06_Legendary',

    "Common Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_01_Common',
    "Uncommon Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_02_Uncommon',
    "Rare Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_04_Rare',
    "VeryRare Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_05_VeryRare',
    "E-Tech Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_05_VeryRare_Alien',
    "Legendary Shotgun": 'GD_Itempools.WeaponPools.Pool_Weapons_Shotguns_06_Legendary',

    "Common SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_01_Common',
    "Uncommon SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_02_Uncommon',
    "Rare SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_04_Rare',
    "VeryRare SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_05_VeryRare',
    "E-Tech SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_05_VeryRare_Alien',
    "Legendary SMG": 'GD_Itempools.WeaponPools.Pool_Weapons_SMG_06_Legendary',

    "Common SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_01_Common',
    "Uncommon SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_02_Uncommon',
    "Rare SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_04_Rare',
    "VeryRare SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_05_VeryRare',
    "E-Tech SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_05_VeryRare_Alien',
    "Legendary SniperRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_SniperRifles_06_Legendary',

    "Common AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_01_Common',
    "Uncommon AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_02_Uncommon',
    "Rare AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_04_Rare',
    "VeryRare AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_05_VeryRare',
    "E-Tech AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_05_VeryRare_Alien',
    "Legendary AssaultRifle": 'GD_Itempools.WeaponPools.Pool_Weapons_AssaultRifles_06_Legendary',

    "Common RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_01_Common',
    "Uncommon RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_02_Uncommon',
    "Rare RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_04_Rare',
    "VeryRare RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_05_VeryRare',
    "E-Tech RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_05_VeryRare_Alien',
    "Legendary RocketLauncher": 'GD_Itempools.WeaponPools.Pool_Weapons_Launchers_06_Legendary',
}

vault_symbol_pathname_to_name = {
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":               "Symbol Sanctuary: Rooftop",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":               "Symbol Sanctuary: Moxxi's Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":               "Symbol Sanctuary: Trash Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_263":             "Symbol Sanctuary: Tire Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_98":              "Symbol Sanctuary: Parkour Door",

    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                  "Symbol Sanctuary: Rooftop",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                  "Symbol Sanctuary: Moxxi's Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":                  "Symbol Sanctuary: Trash Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_263":                "Symbol Sanctuary: Tire Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_98":                 "Symbol Sanctuary: Parkour Door",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                        "Symbol EridiumBlight: Hellsfont Crate",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_3":                        "Symbol EridiumBlight: Stairs Door",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_518":                      "Symbol EridiumBlight: Refund Building",
    "BanditSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_29":           "Symbol Fink's: Column",
    "Boss_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol Bunker: Backside",
    "Boss_Volcano_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":             "Symbol WarriorVault: Elevator Bottom",
    "Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_180":                     "Symbol SouthernShelfBay: Blackburn Cove Corner",
    "Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_235":                     "Symbol SouthernShelfBay: Ice Flows Shipwreck",
    "CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_27":                "Symbol Sawtooth: Refinery Container",
    "CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_7":                 "Symbol Sawtooth: Elevator",
    "CreatureSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol CreatureSlaughter: Crate Ceiling",
    "FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":            "Symbol HerosPass: Strut",
    "FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":            "Symbol HerosPass: Spawn",
    "Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_89":                    "Symbol Fridge: Secret Stash",
    "Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_90":                    "Symbol Fridge: Sheetmetal Roof",
    "Frost_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5":                "Symbol ThreeHornsValley: Slums Wall",
    "Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_31":                     "Symbol ThreeHornsValley: Frostsprings Wall",
    "Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":                      "Symbol ThreeHornsValley: Frostsprings Shack",
    "Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                  "Symbol AridNexusBoneyard: Pipe",
    "Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_3":                  "Symbol AridNexusBoneyard: Safety",
    "Glacial_P.TheWorld:PersistentLevel.WillowInteractiveObject_214":                  "Symbol WindshearWaste: Claptrap's Closet",
    "Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_174":             "Symbol ThousandCuts: Buzzard Factory",
    "Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_302":             "Symbol ThousandCuts: No Man's Land Shack",
    "Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_298":          "Symbol Lynchwood: Gunslinger Roof",
    "Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_601":          "Symbol Lynchwood: Main Street",
    "Grass_P.TheWorld:PersistentLevel.WillowInteractiveObject_346":                    "Symbol Highlands: Highlands Tower",
    "HypInterlude_P.TheWorld:PersistentLevel.WillowInteractiveObject_12":              "Symbol FriendshipGulag: Gulag Container",
    "HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_180":             "Symbol Opportunity: Construction Site",
    "HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":             "Symbol Opportunity: Office Bridge",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_238":                      "Symbol ThreeHornsDivide Drydocks Corner",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":                        "Symbol ThreeHornsDivide Billboard",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_79":                       "Symbol ThreeHornsDivide Windbreak Wall",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_26":           "Symbol Dust: 26",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_4":            "Symbol Dust: 4",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5":            "Symbol Dust: 5",
    "caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_641":                  "Symbol CausticCaverns: Gravestone Feature",
    "caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_89":                   "Symbol CausticCaverns: Bloody Ladder",
    "dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_137":                      "Symbol Blodshot: Pizza Intercom",
    "dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_138":                      "Symbol Blodshot: Switch Room",
    "damtop_p.TheWorld:PersistentLevel.WillowInteractiveObject_0":                     "Symbol BlodshotRamparts: Ramp",
    "icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_51":                 "Symbol Frostburn: Blisterpus Cave",
    "icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_53":                 "Symbol Frostburn: Ashmouth Pit",
    "Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678":           "Symbol TorgueArenaRing: 678",
    "Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_772":           "Symbol TorgueArenaRing: 772",
    "Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425":           "Symbol Beatdown: 425",
    "Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_79":            "Symbol Beatdown: 79",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_214":           "Symbol Forge: 214",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425":           "Symbol Forge: 425",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_61":            "Symbol Forge: 61",
    "Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":                  "Symbol SouthernRaceway: 6",
    "Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_9":                  "Symbol SouthernRaceway: 9",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_11":            "Symbol BadassCrater: 11",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_12":            "Symbol BadassCrater: 12",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678":           "Symbol BadassCrater: 678",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_78":            "Symbol BadassCrater: 78",
    "Luckys_P.TheWorld:PersistentLevel.WillowInteractiveObject_16":                    "Symbol HolySpirits: Bathroom",
    "ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_347":       "Symbol HaytorsFolly: 347",
    "ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_461":       "Symbol HaytorsFolly: 461",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347":   "Symbol Oasis: 347",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_348":   "Symbol Oasis: 348",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_349":   "Symbol Oasis: 349",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_367":   "Symbol Oasis: 367",
    "Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_496":    "Symbol WashburnRefinery: 496",
    "Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_497":    "Symbol WashburnRefinery: 497",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347":   "Symbol Wurmwater: 347",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_400":   "Symbol Wurmwater: 400",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_401":   "Symbol Wurmwater: 401",
    "Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_22":      "Symbol Rustyards: 22",
    "Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_23":      "Symbol Rustyards: 23",
    "Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10":        "Symbol MagnysLighthouse: 10",
    "Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_22":        "Symbol MagnysLighthouse: 22",
    "Orchid_WormBelly_P.TheWorld:PersistentLevel.WillowInteractiveObject_497":         "Symbol LeviathansLair: 497",
    "PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_273":              "Symbol WildlifePreserve: 273",
    "PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_274":              "Symbol WildlifePreserve: 274",
    "RobotSlaughter_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_15":      "Symbol OreChasm: Elevator",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_129":        "Symbol CandlerakksCragg: 129",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71":         "Symbol CandlerakksCragg: 71",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_84":         "Symbol CandlerakksCragg: 84",
    "Sage_HyperionShip_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol Terminus: 0",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_29":         "Symbol AdortonStation: 29",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":          "Symbol AdortonStation: 5",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":          "Symbol AdortonStation: 6",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_7":          "Symbol AdortonStation: 7",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10":     "Symbol ScyllasGrove: 10",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_6":      "Symbol ScyllasGrove: 6",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_8":      "Symbol ScyllasGrove: 8",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_9":      "Symbol ScyllasGrove: 9",
    "Sanctuary_Hole_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":             "Symbol SanctuaryHole: Staircase Wall",
    "SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":            "Symbol SouthernShelf: Flynt's Ship",
    "SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_397":            "Symbol SouthernShelf: Safehouse",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_398":    "Symbol Southpaw: 398",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_399":    "Symbol Southpaw: 399",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_46":     "Symbol Southpaw: 46",
    "ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_116":             "Symbol TerramorphousPeak: Dropdown",
    "ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_364":             "Symbol TerramorphousPeak: Elevator",
    "TundraTrain_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol EndOfTheLine: Wilhelm Wall",
    "tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_206":            "Symbol TundraExpress: Fork Shack",
    "tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_207":            "Symbol TundraExpress: Facility Roof",
    "BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_2":        "Symbol Backburner: 2",
    "BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_3":        "Symbol Backburner: 3",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":             "Symbol HatredsShadow: 0",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":             "Symbol HatredsShadow: 1",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_4":             "Symbol HatredsShadow: 4",
    "CastleKeep_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0":           "Symbol DragonKeep: 0",
    "Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol TheForest: 0",
    "Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":          "Symbol TheForest: 1",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":          "Symbol ImmortalWoods: 1",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_19":         "Symbol ImmortalWoods: 19",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_20":         "Symbol ImmortalWoods: 20",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                      "Symbol UnassumingDocks: 0",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                      "Symbol UnassumingDocks: 1",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":                      "Symbol UnassumingDocks: 2",
    "DungeonRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol WingedStorm: 0",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_307":                  "Symbol LairOfInfiniteAgony: 307",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_308":                  "Symbol LairOfInfiniteAgony: 308",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_90":                   "Symbol LairOfInfiniteAgony: 90",
    "Helios_Floor1.TheWorld:PersistentLevel.WillowInteractiveObject_11":               "Symbol HeliosFallen: 11",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_388":         "Symbol HeliosFallen: 388",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_446":         "Symbol HeliosFallen: 446",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_447":         "Symbol HeliosFallen: 447",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_859":         "Symbol HeliosFallen: 859",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_892":         "Symbol HeliosFallen: 892",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_894":         "Symbol HeliosFallen: 894",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":                "Symbol MinesOfAvarice: 1",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_16":               "Symbol MinesOfAvarice: 16",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_47":               "Symbol MinesOfAvarice: 47",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_187":        "Symbol DahlAbandon: 187",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_269":        "Symbol DahlAbandon: 269",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_36":         "Symbol DahlAbandon: 36",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_59":         "Symbol DahlAbandon: 59",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_84":         "Symbol DahlAbandon: 84",
    "ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_164": "Symbol MtScarab: 164",
    "ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_167": "Symbol MtScarab: 167",
    "ResearchCenter_Research.TheWorld:PersistentLevel.WillowInteractiveObject_737":    "Symbol MtScarab: 737",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_68":    "Symbol HuntersGrotto: 68",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_69":    "Symbol HuntersGrotto: 69",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_70":    "Symbol HuntersGrotto: 70",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71":    "Symbol HuntersGrotto: 71",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1161":           "Symbol WrithingDeep: 1161",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1162":           "Symbol WrithingDeep: 1162",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1163":           "Symbol WrithingDeep: 1163",
    "Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_46":        "Symbol TheBurrows: 46",
    "Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_60":        "Symbol TheBurrows: 60",
    "TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_1":       "Symbol MurderlinsTemple: 1",
    "TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_3":       "Symbol MurderlinsTemple: 3",
    "Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_206":            "Symbol FlamerockRefuge: 206",
    "Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_383":            "Symbol FlamerockRefuge: 383",
}

vending_machine_position_to_name = {
    "11617,1242":           "Vending Sanctuary Crimson Base: Guns",
    "11624,1267":           "Vending Sanctuary Crimson Base: Guns",
    "11584,1403":           "Vending Sanctuary Crimson Base: Ammo Dump",
    "11599,1407":           "Vending Sanctuary Crimson Base: Ammo Dump",
    "8434,-3526":           "Vending Sanctuary Zed's: Ammo Dump",
    "8387,-4248":           "Vending Sanctuary Zed's: Zed's Meds 1",
    "9265,-4415":           "Vending Sanctuary Zed's: Zed's Meds 2",
    "11207,8562":           "Vending Sanctuary Marcus's: Ammo Dump",
    "11430,8505":           "Vending Sanctuary Marcus's: Marcus",
    "10569,6224":           "Vending Sanctuary Marcus's: Zed's Meds",
    "11207,8546":           "Vending Sanctuary Marcus's: Ammo Dump",
    "11382,8937":           "Vending Sanctuary Marcus's: Marcus",
    "30186,33162":          "Vending FriendshipGulag: Zed's Meds",
    "30186,33347":          "Vending FriendshipGulag: Ammo Dump",
    "-26727,32659":         "Vending Dust Ellie's: Zed's Meds",
    "-26727,32512":         "Vending Dust Ellie's: Ammo Dump",
    "27889,-17657":         "Vending Shelf Hammerlock's: Guns",
    "29743,-13024":         "Vending Shelf Liar's: Ammo Dump",
    "27325,-12299":         "Vending Shelf Liar's: Zed's Meds",
    "25657,-28009":         "Vending Shelf Safehouse: Zed's Meds",
    "80436,-43687":         "Vending Shelf Dragon: Zed's Meds",
    "70136,-42976":         "Vending Shelf Dragon: Ammo Dump",
    "19286,-29147":         "Vending Bay Spawn: Ammo Dump",
    "19291,-29039":         "Vending Bay Spawn: Zed's Meds",
    "1460,-8267":           "Vending Bay Cove: Guns",
    "1314,-7353":           "Vending Bay Cove: Ammo Dump",
    "1166,-7430":           "Vending Bay Cove: Zed's Meds",
    "-40344,38442":         "Vending Divide Jump: Ammo Dump",
    "-40361,38650":         "Vending Divide Jump: Zed's Meds",
    "22261,38591":          "Vending Divide Crossroads: Guns",
    "22101,38575":          "Vending Divide Crossroads: Ammo Dump",
    "21781,38848":          "Vending Divide Crossroads: Zed's Meds",
    "17576,-8728":          "Vending Valley Motel: Guns",
    "17493,-8598":          "Vending Valley Motel: Ammo Dump",
    "17040,-10311":         "Vending Valley Motel: Zed's Meds",
    "-4700,19685":          "Vending Southpaw: Ammo Dump",
    "-4706,19520":          "Vending Southpaw: Zed's Meds",
    "3829,-2432":           "Vending Frostburn Spawn: Ammo Dump",
    "3656,-2410":           "Vending Frostburn Spawn: Zed's Meds",
    "16417,-20419":         "Vending Frostburn Firehawk: Ammo Dump",
    "16466,-20227":         "Vending Frostburn Firehawk: Zed's Meds",
    "-27706,5562":          "Vending Stronghold: Ammo Dump",
    "-27547,5571":          "Vending Stronghold: Zed's Meds",
    "-58424,20912":         "Vending Ramparts: Ammo Dump",
    "-58602,20955":         "Vending Ramparts: Zed's Meds",
    "-41219,13428":         "Vending Tundra Spawn: Ammo Dump",
    "-41076,13467":         "Vending Tundra Spawn: Zed's Meds",
    "1854,79":              "Vending Tundra Farm: Guns",
    "-13285,18100":         "Vending Tundra Tina: Ammo Dump",
    "-20192,34880":         "Vending End of the Line: Ammo Dump",
    "-20210,35067":         "Vending End of the Line: Zed's Meds",
    "1597,20937":           "Vending Fridge Spawn: Ammo Dump",
    "1688,21050":           "Vending Fridge Spawn: Zed's Meds",
    "8315,-6885":           "Vending Fridge Elevator: Ammo Dump",
    "8316,-7089":           "Vending Fridge Elevator: Zed's Meds",
    "22535,9903":           "Vending Fink's: Guns",
    "22342,9748":           "Vending Fink's: Ammo Dump",
    "22171,9605":           "Vending Fink's: Zed's Meds",
    "53791,73317":          "Vending Outwash: Ammo Dump",
    "53627,73348":          "Vending Outwash: Zed's Meds",
    "16764,-6564":          "Vending Highlands Bridge: Ammo Dump",
    "16733,-6406":          "Vending Highlands Bridge: Zed's Meds",
    "66989,4112":           "Vending Highlands Overlook: Guns",
    "66849,4450":           "Vending Highlands Overlook: Ammo Dump",
    "66917,1491":           "Vending Highlands Overlook: Zed's Meds",
    "57752,45408":          "Vending Extraction Plant: Zed's Meds",
    "-3426,-15360":         "Vending Hyperion Bridge: Zed's Meds",
    "472,2348":             "Vending Holy Spirits: Guns",
    "1182,970":             "Vending Holy Spirits: Ammo Dump",
    "1118,432":             "Vending Holy Spirits: Zed's Meds",
    "-23928,-5742":         "Vending Dust Speedway: Ammo Dump",
    "-24094,-5698":         "Vending Dust Speedway: Zed's Meds",
    "36756,-6778":          "Vending Dust Steve: Ammo Dump",
    "36826,-6644":          "Vending Dust Steve: Zed's Meds",
    "2730,-6726":           "Vending Sanctuary Hole: Ammo Dump",
    "2621,-6804":           "Vending Sanctuary Hole: Zed's Meds",
    "-14800,2393":          "Vending Caverns Spawn: Ammo Dump",
    "-14795,2550":          "Vending Caverns Spawn: Zed's Meds",
    "8817,8694":            "Vending Caverns Shortcut: Guns",
    "-31556,66487":         "Vending Preserve Spawn: Ammo Dump",
    "-31671,66271":         "Vending Preserve Spawn: Zed's Meds",
    "-25675,9895":          "Vending Preserve Halfway: Ammo Dump",
    "-25797,10014":         "Vending Preserve Halfway: Zed's Meds",
    "-10416,-1355":         "Vending Creature: Ammo Dump",
    "-10426,-1500":         "Vending Creature: Zed's Meds",
    "-17302,-9530":         "Vending Thousand: Ammo Dump",
    "-17474,-9552":         "Vending Thousand: Zed's Meds",
    "11266,-22845":         "Vending Lynchwood Spawn: Ammo Dump",
    "11433,-22844":         "Vending Lynchwood Spawn: Zed's Meds",
    "30956,-25556":         "Vending Lynchwood Gunslinger: Guns",
    "24548,-5676":          "Vending Opportunity Spawn: Guns",
    "24532,-3513":          "Vending Opportunity Spawn: Ammo Dump",
    "24065,-3513":          "Vending Opportunity Spawn: Zed's Meds",
    "13057,-8347":          "Vending Opportunity Office: Ammo Dump",
    "12579,-8351":          "Vending Opportunity Office: Zed's Meds",
    "14975,-3411":          "Vending Opportunity Square: Ammo Dump",
    "15301,-3746":          "Vending Opportunity Square: Zed's Meds",
    "79,2455":              "Vending Opportunity Residential: Guns",
    "65,1975":              "Vending Opportunity Residential: Ammo Dump",
    "13548,15976":          "Vending Bunker: Ammo Dump",
    "13495,15851":          "Vending Bunker: Zed's Meds",
    "-893,-47713":          "Vending Blight Spawn: Ammo Dump",
    "-719,-47729":          "Vending Blight Spawn: Zed's Meds",
    "-9755,-6528":          "Vending Blight Extraction: Ammo Dump",
    "-9739,-6359":          "Vending Blight Extraction: Zed's Meds",
    "27558,-40893":         "Vending Blight Refinery: Guns",
    "27422,-41023":         "Vending Blight Refinery: Ammo Dump",
    "27760,-40695":         "Vending Blight Refinery: Zed's Meds",
    "-52976,-61745":        "Vending Ore Chasm: Guns",
    "-52649,-61758":        "Vending Ore Chasm: Ammo Dump",
    "-52811,-61737":        "Vending Ore Chasm: Zed's Meds",
    "26036,40591":          "Vending Sawtooth Spawn: Ammo Dump",
    "26162,40656":          "Vending Sawtooth Spawn: Zed's Meds",
    "22406,25541":          "Vending Sawtooth Elevator: Ammo Dump",
    "-61941,12209":         "Vending Boneyard Spawn: Ammo Dump",
    "-62395,12297":         "Vending Boneyard Spawn: Zed's Meds",
    "-13311,31034":         "Vending Badlands Fyrestone: Ammo Dump",
    "-12519,33977":         "Vending Badlands Fyrestone: Zed's Meds",
    "-27127,27497":         "Vending Badlands Baha: Guns",
    "21912,-13934":         "Vending HerosPass Spawn: Ammo Dump",
    "22046,-14042":         "Vending HerosPass Spawn: Zed's Meds",
    "-13842,-3463":         "Vending Warrior: Ammo Dump",
    "-13973,-3522":         "Vending Warrior: Zed's Meds",
    "-26342,-382":          "Vending Terramorphous: Guns",
    "-26640,-559":          "Vending Terramorphous: Ammo Dump",
    "-26599,-746":          "Vending Terramorphous: Zed's Meds",
    "-27293,-3670":         "Vending Oasis Town: Guns",
    "-18475,-2363":         "Vending Oasis Town: Ammo Dump",
    "-18622,-2346":         "Vending Oasis Town: Zed's Meds",
    "46025,-60993":         "Vending Wurmwater Oasis Door: Ammo Dump",
    "46142,-61099":         "Vending Wurmwater Oasis Door: Zed's Meds",
    "54921,5163":           "Vending Wurmwater Canyon: Guns",
    "54822,5046":           "Vending Wurmwater Canyon: Ammo Dump",
    "-46810,32312":         "Vending Wurmwater Fen: Ammo Dump",
    "-2262,272":            "Vending Wurmwater Ship: Guns",
    "-2267,75":             "Vending Wurmwater Ship: Ammo Dump",
    "-2273,1189":           "Vending Wurmwater Ship: Zed's Meds",
    "10983,48962":          "Vending Wurmwater Rustyard: Guns",
    "-13165,22042":         "Vending Hayters Spawn: Guns",
    "-12622,21830":         "Vending Hayters Spawn: Ammo Dump",
    "-13780,20634":         "Vending Hayters Spawn: Zed's Meds",
    "-5408,-3514":          "Vending Hayters Gee: Ammo Dump",
    "-4899,-2502":          "Vending Hayters Gee: Zed's Meds",
    "-25931,25124":         "Vending Rustyards Spawn: Ammo Dump",
    "-26089,25248":         "Vending Rustyards Spawn: Zed's Meds",
    "27029,-20095":         "Vending Washburne Spawn: Ammo Dump",
    "27002,-19922":         "Vending Washburne Spawn: Zed's Meds",
    "41794,495":            "Vending Washburne Hyperius: Ammo Dump",
    "41622,474":            "Vending Washburne Hyperius: Zed's Meds",
    "-22807,-10281":        "Vending Magnys Spawn: Ammo Dump",
    "-22937,-10486":        "Vending Magnys Spawn: Zed's Meds",
    "-2900,25942":          "Vending Leviathan Body: Ammo Dump",
    "-2483,25214":          "Vending Leviathan Body: Zed's Meds",
    "-9856,-77793":         "Vending Leviathan Lair: Ammo Dump",
    "-9951,-77667":         "Vending Leviathan Lair: Zed's Meds",
    "-9145,33092":          "Vending Crater Spawn: Ammo Dump",
    "-9200,32936":          "Vending Crater Spawn: Zed's Meds",
    "25873,12851":          "Vending Crater Town: Ammo Dump",
    "25964,12667":          "Vending Crater Town: Zed's Meds",
    "2144,-13193":          "Vending Crater Forge: Torgue Vendor",
    "1436,-13206":          "Vending Crater Forge: Ammo Dump",
    "1675,-13230":          "Vending Crater Forge: Zed's Meds",
    "1167,-11409":          "Vending Arena Inner: Torgue Vendor",
    "-471,-11441":          "Vending Arena Inner: Ammo Dump",
    "-508,-11645":          "Vending Arena Inner: Zed's Meds",
    "14192,-25105":         "Vending Beatdown Spawn: Torgue Vendor",
    "13843,-25266":         "Vending Beatdown Spawn: Ammo Dump",
    "13683,-25434":         "Vending Beatdown Spawn: Zed's Meds",
    "-8393,-33132":         "Vending Beatdown Underpass: Torgue Vendor",
    "-8390,-33315":         "Vending Beatdown Underpass: Ammo Dump",
    "-8399,-33499":         "Vending Beatdown Underpass: Zed's Meds",
    "-979,-14889":          "Vending Pete's: Torgue Vendor",
    "-542,-16377":          "Vending Pete's: Ammo Dump",
    "-537,-16166":          "Vending Pete's: Zed's Meds",
    "32660,3715":           "Vending Badass Bar: Torgue Vendor",
    "32666,3895":           "Vending Badass Bar: Ammo Dump",
    "32670,4066":           "Vending Badass Bar: Zed's Meds",
    "-44247,42252":         "Vending Raceway: Torgue Vendor",
    "-44108,42363":         "Vending Raceway: Ammo Dump",
    "-43982,42463":         "Vending Raceway: Zed's Meds",
    "37097,5507":           "Vending Forge Spawn: Torgue Vendor",
    "37221,5735":           "Vending Forge Spawn: Ammo Dump",
    "37300,5922":           "Vending Forge Spawn: Zed's Meds",
    "40913,27674":          "Vending Forge Flyboy: Ammo Dump",
    "40989,27801":          "Vending Forge Flyboy: Zed's Meds",
    "1055,-5886":           "Vending Grotto Lodge: Guns",
    "1208,-5891":           "Vending Grotto Lodge: Ammo Dump",
    "900,-5890":            "Vending Grotto Lodge: Zed's Meds",
    "1981,-5757":           "Vending Grotto Lodge: Seraph Vendor",
    "8763,-5548":           "Vending Scylla's Entrance: Guns",
    "7780,-4930":           "Vending Scylla's Entrance: Ammo Dump",
    "7819,-5218":           "Vending Scylla's Entrance: Zed's Meds",
    "-29476,19838":         "Vending Scylla's Pukey: Zed's Meds",
    "-22360,-43387":        "Vending Ardorton Entrance: Ammo Dump",
    "-22498,-43332":        "Vending Ardorton Entrance: Zed's Meds",
    "-34414,4587":          "Vending Ardorton Exit: Ammo Dump",
    "-34078,4605":          "Vending Ardorton Exit: Zed's Meds",
    "101267,-61847":        "Vending Crag Spawn: Ammo Dump",
    "101275,-61691":        "Vending Crag Spawn: Zed's Meds",
    "60600,2505":           "Vending Crag Voracidous: Ammo Dump",
    "60733,2425":           "Vending Crag Voracidous: Zed's Meds",
    "9896,28808":           "Vending Terminus Entrance: Ammo Dump",
    "9790,28861":           "Vending Terminus Entrance: Zed's Meds",
    "-2715,4303":           "Vending Flamerock Refuge: Zed's Apothecary",
    "-5144,-8269":          "Vending Flamerock Refuge: Guns/Cannons",
    "-4723,-8339":          "Vending Flamerock Refuge: Ammo Dump/Miisiles",
    "-3704,-61590":         "Vending Forest Spawn: Ammo Dump/Missiles",
    "-3839,-61428":         "Vending Forest Spawn: Zed's Apothecary",
    "-20493,-34858":        "Vending Immortal Spawn: Ammo Dump/Missiles",
    "-20329,-34691":        "Vending Immortal Spawn: Zed's Apothecary",
    "823,-16453":           "Vending Immortal Vitality Grove: Ammo Dump/Missiles",
    "1035,-16468":          "Vending Immortal Vitality Grove: Zed's Apothecary",
    "4760,-1236":           "Vending Avarice Spawn: Ammo Dump/Missiles",
    "4650,-1373":           "Vending Avarice Spawn: Zed's Apothecary",
    "-13743,19706":         "Vending Avarice Greedtooth: Ammo Dump/Missiles",
    "-13742,19530":         "Vending Avarice Greedtooth: Zed's Apothecary",
    "19400,25669":          "Vending Shadow Spawn: Ammo Dump/Missiles",
    "19618,25615":          "Vending Shadow Spawn: Zed's Apothecary",
    "3963,-1982":           "Vending Handsome Bridge: Guns/Cannons",
    "3847,-1984":           "Vending Handsome Bridge: Ammo Dump/Missiles",
    "3906,-2088":           "Vending Handsome Bridge: Zed's Apothecary",
    "-2902,3361":           "Vending Agony Spawn: Ammo Dump/Missiles",
    "-2382,2132":           "Vending Agony Spawn: Zed's Apothecary",
    "156,-14330":           "Vending Agony Daughter: Ammo Dump/Missiles",
    "-111,-14330":          "Vending Agony Daughter: Zed's Apothecary",
    "8864,-6240":           "Vending Agony Hall of the Dead: Mr. Miz",
    "127351,-18203":        "Vending Dragon Keep: Ammo Dump/Missiles",
    "127553,-18221":        "Vending Dragon Keep: Zed's Apothecary",
    "11866,2102":           "Vending Winged Storm: Guns/Cannons",
    "12039,2104":           "Vending Winged Storm: Ammo Dump/Missiles",
    "11703,2101":           "Vending Winged Storm: Zed's Apothecary",
    "-702,8170":            "Vending Murderlin's Temple: Guns/Cannons",
    "-688,8382":            "Vending Murderlin's Temple: Ammo Dump/Missiles",
    "-526,8541":            "Vending Murderlin's Temple: Zed's Apothecary",
    "-4411,27888":          "Vending Hallowed Hollow Entrance: Ammo Dump",
    "-4321,27720":          "Vending Hallowed Hollow Entrance: Zed's Meds",
    "-4463,11658":          "Vending Hallowed Hollow Kingpin Approach: Zed's Meds",
    "-4521,11446":          "Vending Hallowed Hollow Kingpin Approach: Ammo Dump",
    "11987,-10601":         "Vending Glut Gulch Entrance: Guns",
    "11802,-10599":         "Vending Glut Gulch Entrance: Ammo Dump",
    "12170,-10603":         "Vending Glut Gulch Entrance: Zed's Meds",
    "2730,-9019":           "Vending Glut Gulch Kitchen: Ammo Dump",
    "5264,-21272":          "Vending Glut Gulch Stabber Jabber: Guns",
    "-643,-5104":           "Vending Glut Gulch Tribute Station: Guns",
    "-493,-5106":           "Vending Glut Gulch Tribute Station: Zed's Meds",
    "-346,-5116":           "Vending Glut Gulch Tribute Station: Ammo Dump",
    "-22508,-6510":         "Vending Merc Shop Entrance: Guns",
    "-22473,-6286":         "Vending Merc Shop Entrance: Ammo Dump",
    "-22290,-6099":         "Vending Merc Shop Entrance: Zed's Meds",
    "579,-5489":            "Vending Merc Shop Tinder Arena: Zed's Meds",
    "695,-5690":            "Vending Merc Shop Tinder Arena: Ammo Dump",
    "-28648,-18108":        "Vending Distillery Entrance: Zed's Meds",
    "-28810,-17913":        "Vending Distillery Entrance: Ammo Dump",
    "3470,-7297":           "Vending Distillery Pot of Gold: Ammo Dump",
    "-26015,-8933":         "Vending Distillery Wedding Venue: Zed's Meds",
    "-26327,-9001":         "Vending Distillery Wedding Venue: Ammo Dump",
    "14366,10131":          "Vending Wam Bam Entrance: Ammo Dump",
    "14206,10007":          "Vending Wam Bam Entrance: Zed's Meds",
    "7701,2177":            "Vending Wam Bam Water Wheel: Zed's Meds",
    "7576,2254":            "Vending Wam Bam Water Wheel: Ammo Dump",
    "33637,15119":          "Vending Wam Bam Son's Arena: Ammo Dump",
    "33858,15043":          "Vending Wam Bam Son's Arena: Zed's Meds",
    "-16947,66470":         "Vending The Backburner Entrance: Ammo Dump",
    "-16989,66902":         "Vending The Backburner Entrance: Zed's Meds",
    "-26515,43992":         "Vending The Backburner Vaughn's HQ: Guns",
    "-26266,44088":         "Vending The Backburner Vaughn's HQ: Ammo Dump",
    "-26389,44036":         "Vending The Backburner Vaughn's HQ: Zed's Meds",
    "-21122,38254":         "Vending The Backburner Marcus: Guns",
    "-21251,38221":         "Vending The Backburner Marcus: Ammo Dump",
    "-30491,37965":         "Vending Dahl Abandon Entrance: Ammo dump",
    "-30584,37776":         "Vending Dahl Abandon Entrance: Zed's Meds",
    "27315,27218":          "Vending Dahl Abandon Mine Door: Ammo Dump",
    "27224,27321":          "Vending Dahl Abandon Mine Door: Zed's Meds",
    "40207,-3635":          "Vending The Burrows Entrance: Ammo Dump",
    "40076,-3749":          "Vending The Burrows Entrance: Zed's Meds",
    "38103,-113737":        "Vending Helios Fallen Entrance: Ammo Dump",
    "37976,-113661":        "Vending Helios Fallen Entrance: Zed's Meds",
    "32427,-100308":        "Vending Helios Fallen Munitions Loading: Ammo Dump",
    "32293,-100304":        "Vending Helios Fallen Munitions Loading: Zed's Meds",
    "34348,-104837":        "Vending Helios Fallen The Arsenal: Ammo Dump",
    "34172,-104726":        "Vending Helios Fallen The Arsenal: Zed's Meds",
}
